- solr/solrj/src/test/org/apache/solr/client/solrj/io/graph/GraphExpressionTest.java
The `params` variable is unused, duplicating the `fq` that is inside the expression already.
Removed the unused variable.
This is a test :)
> Remove unused variable

- solr/CHANGES.txt
- solr/contrib/prometheus-exporter/src/test-files/solr/collection1/conf/solrconfig.xml
- solr/core/src/test-files/solr/collection1/conf/solrconfig-implicitproperties.xml
- solr/server/solr/configsets/sample_techproducts_configs/conf/solrconfig.xml
- solr/solr-ref-guide/src/response-writers.adoc
Browsers now care if you are doing a JSONP call and they expect application/json, and block any text/plain mime type response.
In Quepid we communicate the API command to update your JSONResponseWriter during your setup process, but it's still very confusing. It was a "cool hack" back when we first used it, but 10 years later, it's causing issues.
This is a copy of https://github.com/apache/lucene-solr/pull/2436
Remove hack, and add warning in the docs if you choose to do it.
Reran tests.
- [ X] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [ X] I have created a Jira issue and added the issue ID to …
> SOLR-15161: Remove documentation about bad practices for json responses and mime types

- gradle/maven/defaults-maven.gradle
- solr/packaging/build.gradle
Solr-core has a dependency, org.apache.solr:server, which fails to download.
For testing I created a test project here: https://github.com/bszabo97/solr_master_dep_test
If I run the command gradle -q dependencies --configuration solrCore the dependency org.apache.solr:server shows up and fails, though if I run gradle -q dependencies --configuration solrCore8 it doesn't show up at all.
Adding the missing artifact.
Unit tests
> SOLR-15178 Non-existent dependency listed in solr-core

- solr/webapp/web/partials/login.html
Remove login autocomplete, which currently allows you to see who had previously logged in. 
Add `autocomplete=off` 
Go to the login page and confirm that clicking in the username box doesn't show other users.
> SOLR-15248 Disable login autocomplete

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/ClusterAPI.java
- solr/solr-ref-guide/src/major-changes-in-solr-9.adoc
Pass the requestid param as the `{id}` in the url, same as in the DELETE verb
Simple change to mapper
run tests
- [ X] I have developed this patch against the `main` branch.
- [ X] I have run `./gradlew check`.
- [X ] I have added documentation for the [Reference …
> SOLR-15276: Use same pattern on GET as on DELETE and be more RESTful.

- gradle/documentation/changes-to-html/changes2html.pl
- solr/CHANGES.txt
Original lucene-solr pull request: apache/lucene-solr#1060
changes2html.pl generates invalid html
Fix it to generate a valid html.
Created the html and tested it using https://validator.w3.org/
> SOLR-14024 Invalid html generated by changes2html.pl

- README.md
Trivial README change - It would be better to point jdk.java.net to download JDK instead of OracleJDK page (because it now requires commercial license for production use) ?
> Point jdk.java.net instead of OracleJDK page from README

- solr/CHANGES.txt
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/CloudHttp2SolrClient.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/CloudHttp2SolrClientBuilderTest.java
This allows configuring the internal client with things like timeouts, credentials, etc
Moved from https://github.com/apache/lucene-solr/pull/2450
> SOLR-15155: Let CloudHttp2SolrClient accept an external Http2SolrClient Builder

- solr/CHANGES.txt
Noticed whilst resolving merge conflict during solr/main to lucene-solr/branch_8x backport.
> SOLR-15249: move solr/CHANGES.txt entry from 9.0.0 to 8.9.0 section

- solr/solr-ref-guide/src/morelikethis.adoc
- solr/solr-ref-guide/src/other-parsers.adoc
This PR makes major revisions to `morelikethis.adoc`:
* examples of how to configure each option
* examples/explanation of the output of each MLT approach
* default values for all parameters are provided (using a new approach I first introduced in `solr-tracing.adoc` change 2f45a31fbd0c5f46b9fa1431bb374cc24d43076a) - *this needs validation from someone who knows the code*
* reorganization of sections
* moved MLTQParser docs to `morelikethis.adoc` leaving a link to new location in `other-parsers.adoc`
> SOLR-15243: Update MoreLikeThis docs 

- solr/solr-ref-guide/src/audit-logging.adoc
Since it's an invalid JSON, it hurts my OCD 😄
> Fix typo in audit example JSON

- solr/core/src/java/org/apache/solr/core/backup/repository/BackupRepositoryFactory.java
BackupRepositoryFactory has a special case in its 'newInstance' method.
For 'TrackingBackupRepository' instances, BRF will modify a NamedList
representing the TBF config - adding references to the
SolrResourceLoader and to BRF itself.
In isolation this is innocuous, but becomes a problem when
BRF.newInstance is called concurrently from different threads.  Threads
can race to set these NamedList keys, corrupting the NamedList in the
process.  (i.e. NamedList values ended up in 'key' indices, and vice
versa)
This commit adds synchronization to this NL initialization, to ensure
that the NL values are only set by a single thread.
This PR itself is a fix for LocalFSCloudIncrementalBackupTest.  It can be validated by beasting that test class to ensure the flakiness has been resolved.
Please …
> SOLR-13608: Sync on TrackingBackupRepo NL changes

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/component/RealTimeGetComponent.java
- solr/core/src/java/org/apache/solr/handler/component/SearchHandler.java
- solr/core/src/java/org/apache/solr/handler/component/StatsField.java
- solr/core/src/java/org/apache/solr/schema/FieldType.java
- solr/core/src/java/org/apache/solr/schema/TextField.java
- solr/core/src/test-files/solr/collection1/conf/schema-pseudo-fields.xml
- solr/core/src/test-files/solr/collection1/conf/schema-trie.xml
- solr/core/src/test-files/solr/collection1/conf/schema11.xml
- solr/core/src/test-files/solr/collection1/conf/schema12.xml
- solr/core/src/test-files/solr/collection1/conf/schema_latest.xml
- solr/core/src/test/org/apache/solr/cloud/TestCloudPseudoReturnFields.java
- solr/core/src/test/org/apache/solr/cloud/TestRandomFlRTGCloud.java
- solr/core/src/test/org/apache/solr/search/TestExtendedDismaxParser.java
- solr/core/src/test/org/apache/solr/search/TestPseudoReturnFields.java
- solr/core/src/test/org/apache/solr/search/facet/TestCloudJSONFacetJoinDomain.java
- solr/core/src/test/org/apache/solr/search/facet/TestCloudJSONFacetSKGEquiv.java
- solr/server/solr/configsets/sample_techproducts_configs/conf/managed-schema
- solr/solr-ref-guide/src/documents-fields-and-schema-design.adoc
- solr/solr-ref-guide/src/indexing-nested-documents.adoc
- solr/solr-ref-guide/src/searching-nested-documents.adoc
- solr/solr-ref-guide/src/transforming-result-documents.adoc
- solr/solr-ref-guide/src/updating-parts-of-documents.adoc
- solr/solr-ref-guide/tools/BuildNavDataFiles.java
- solr/solr-ref-guide/tools/CheckLinksAndAnchors.java
- solr/solrj/src/java/org/apache/solr/client/solrj/io/stream/RandomStream.java
- solr/solrj/src/test/org/apache/solr/client/ref_guide_examples/IndexingNestedDocuments.java
- solr/solrj/src/test/org/apache/solr/client/solrj/SolrExampleTests.java
- solr/test-framework/src/java/org/apache/solr/util/SSLTestConfig.java
Fix a couple typos spread in the code base. Specially 'psuedo' instead of 'pseudo' and 'Requsted' instead of 'Requested'.
It required some IDE find and replace and a file name change. 
There's no need to write new tests for this change. Solr test suite should be enough.
> SOLR-15327: Fix typos spread in code base

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/core/CoreContainer.java
- solr/core/src/test/org/apache/solr/core/TestCoreContainer.java
Original lucene-solr pull request: https://github.com/apache/lucene-solr/pull/2406
In the SolrPaths.assertPathAllowed the normalize() method is only called for pathToAssert and not for the allowPaths elements
Calling it for allowPaths elements
> SOLR-15169 SolrPaths.assertPathAllowed normalization problem

- solr/core/src/java/org/apache/solr/core/CancellableQueryTracker.java
- solr/core/src/java/org/apache/solr/core/SolrCore.java
- solr/core/src/java/org/apache/solr/handler/component/ActiveTasksListComponent.java
- solr/core/src/java/org/apache/solr/handler/component/ActiveTasksListHandler.java
- solr/core/src/java/org/apache/solr/handler/component/QueryCancellationComponent.java
- solr/core/src/java/org/apache/solr/handler/component/QueryCancellationHandler.java
- solr/core/src/java/org/apache/solr/handler/component/QueryComponent.java
- solr/core/src/java/org/apache/solr/handler/component/ResponseBuilder.java
- solr/core/src/java/org/apache/solr/handler/component/SearchHandler.java
- solr/core/src/java/org/apache/solr/handler/component/TaskManagementHandler.java
- solr/core/src/java/org/apache/solr/search/CancellableCollector.java
- solr/core/src/java/org/apache/solr/search/QueryCommand.java
- solr/core/src/java/org/apache/solr/search/SolrIndexSearcher.java
- solr/core/src/resources/ImplicitPlugins.json
- solr/core/src/test/org/apache/solr/MinimalSchemaTest.java
- solr/core/src/test/org/apache/solr/core/SolrCoreTest.java
- solr/core/src/test/org/apache/solr/search/TestCancellableCollector.java
- solr/core/src/test/org/apache/solr/search/TestTaskManagement.java
- solr/solr-ref-guide/src/common-query-parameters.adoc
- solr/solr-ref-guide/src/index.adoc
- solr/solr-ref-guide/src/task-management.adoc
- solr/solrj/src/java/org/apache/solr/client/solrj/response/QueryResponse.java
- solr/solrj/src/java/org/apache/solr/common/params/CommonParams.java
- solr/solrj/src/java/org/apache/solr/common/params/ShardParams.java
- solr/solrj/src/resources/apispec/core.tasks.cancel.json
- solr/solrj/src/resources/apispec/core.tasks.list.json
This commit introduces the concept of task management in Solr.
Tasks can be marked as cancellable (thus, trackable) and can then be listed (ps -all), cancelled and specific task's status be
queried.
This commit also implements SOLR-15165.
Please refer to the JIRA for more information.
> SOLR-15164: Implement Task Management Interface

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/security/PKIAuthenticationPlugin.java
- solr/core/src/test/org/apache/solr/security/TestPKIAuthenticationPlugin.java
https://issues.apache.org/jira/browse/SOLR-15334
I made some conservative changes here, but the main effort was replacing all of the pass throughs with throwing Exceptions. We could probably remove more code if this is the right way to go instead of hiding behind `assert` statements.
Am I misunderstanding something about the intent here?
> SOLR-15334 Throw exception on failure in PKIAuthPlugin

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/response/transform/ChildDocTransformerFactory.java
Change-Id: I6cc22a9e13aeaef37a1e005b111a59bb7412023d
The ChildDocTransformerFactory creates a QueryBitSetProducer every time.  These are heavy to compute; they should be cached.  BlockJoinParentQParserPlugin does this correctly, using the "perSegFilter" named Solr cache.
The solution for this was to copy the implementation of the cache usage from BlockJoinParentQParser. We decided not to create a new class for this since the solution was quite simple
Unit tests.
> SOLR-15067 Child doc transformer should use the perSegFilter cache

- gradle/validation/validate-source-patterns.gradle
- solr/solr-ref-guide/src/analytics-expression-sources.adoc
- solr/solr-ref-guide/src/analytics-mapping-functions.adoc
- solr/solr-ref-guide/src/analytics-reduction-functions.adoc
- solr/solr-ref-guide/src/command-line-utilities.adoc
- solr/solr-ref-guide/src/faceting.adoc
- solr/solr-ref-guide/src/field-type-definitions-and-properties.adoc
- solr/solr-ref-guide/src/filter-descriptions.adoc
- solr/solr-ref-guide/src/language-analysis.adoc
- solr/solr-ref-guide/src/solr-control-script-reference.adoc
- solr/solr-ref-guide/src/solr-jdbc-apache-zeppelin.adoc
https://issues.apache.org/jira/browse/SOLR-15382
Included:
- Removed the Gradle check for unescaped `=>` and `->`.
- Went through and un-escaped all arrows, which did not mean to explicitly be the ascii-character arrows.
- Plenty were actually meant to be escaped, e.g. the entries in charFilters.
> SOLR-15382: Remove PDF Checks from gradle ref-guide generation.

- solr/solr-ref-guide/src/faceting.adoc
`json.nl` is important when faceting.
link in ref guide.
- [ x] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [ x] I have created a Jira issue and added the issue ID to my pull request title.
- [ x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [ x] I have developed this patch against the `main` branch.
- [x ] I have added …
> SOLR-15398: Faceting page in ref guide doesn't mention the json.nl parameter

- solr/CHANGES.txt
- solr/core/src/test/org/apache/solr/cloud/TestPullReplica.java
- solr/core/src/test/org/apache/solr/cloud/TestPullReplicaWithAuth.java
Pull replica tests are still flaky on Jenkins, see: https://jenkins.thetaphi.de/job/Solr-main-Linux/537/
and https://jenkins.thetaphi.de/job/Solr-main-Linux/536/
This PR marks those tests as BadApples, to be fixed by SOLR-15399
> SOLR-11904: Mark flaky tests as BadApples

- solr/core/src/test/org/apache/solr/handler/V2ApiIntegrationTest.java
- solr/solrj/src/java/org/apache/solr/client/solrj/request/V2Request.java
Not noticed yet because SolrJ doesn't look at it for V2.
I didn't create a JIRA issue because this appears to impact nobody because SolrJ doesn't call it.
Why does the regular expression have a negative lookahead on "/shards" at the end of the URL?  What does it matter?
Original code was introduced here: https://issues.apache.org/jira/browse/SOLR-11130 9f73bcf11d89f6ee7b2de8bea25be9018f4554cb
> Bug in V2Request.getCollection

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cloud/ReplicateFromLeader.java
- solr/core/src/test/org/apache/solr/cloud/TestPullReplica.java
- solr/core/src/test/org/apache/solr/cloud/TestPullReplicaWithAuth.java
When doing the work for https://github.com/apache/solr/commit/ae1ac22eb70d44f80e5c89241bdd0d3e4144e62a, I discovered that the `TestPullReplica` class was disabled via an AwaitsFix. I enabled it and it passed fairly consistently, but then saw flaky failures on Jenkins. This PR fixes those flaky tests ...
`IndexFetcher` was triggering a local commit for a PULL replica core (see snippet below) which caused a race condition where the PULL replica would think its index generation / version were the same as the leader (see log I posted in JIRA). 
From IndexFetcher, line 479:
```
if (skipCommitOnLeaderVersionZero) {
openNewSearcherAndUpdateCommitPoint();
} else {
SolrQueryRequest req = new LocalSolrQueryRequest(solrCore, new ModifiableSolrParams());
solrCore.getUpdateHandler().commit(new …
```
> SOLR-15399: IndexFetcher should not issue a local commit for PULL replicas

- .github/PULL_REQUEST_TEMPLATE.md
I wish our PRs *always* started with a convenient link to the JIRA issue.  Here, I am modifying the PR template to put it up front.
> GitHub PR Template: Add JIRA issue URL

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cloud/ConfigSetCmds.java
- solr/core/src/java/org/apache/solr/cloud/ZkConfigSetService.java
- solr/core/src/java/org/apache/solr/core/FileSystemConfigSetService.java
- solr/core/src/test/org/apache/solr/cloud/OverseerCollectionConfigSetProcessorTest.java
- solr/core/src/test/org/apache/solr/cloud/TestConfigSetsAPI.java
Both FileSystemConfigSetService and ZkConfigSetService only checks the existence of the directory only in checkConfigExists.
Create a new method to also check for solrconfig.xml checkConfigExistsWithSolrConfigXml
> SOLR-15421 ConfigSetService.checkConfigExists accepts empty configs

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/loader/JsonLoader.java
- solr/core/src/test/org/apache/solr/handler/JsonLoaderTest.java
When indexing nested docs via JSON, it is no longer necessary to provide child doc IDs.
This was already working for XML & "javabin"/SolrJ.
Previously, omitting the ID would be confused for a partial/atomic update.
https://issues.apache.org/jira/browse/SOLR-15044
> SOLR-15044: JSON Loading: nested docs don't need ID

- solr/contrib/blob-directory/src/java/org/apache/solr/blob/BlobDirectory.java
- solr/contrib/blob-directory/src/java/org/apache/solr/blob/BlobRepository.java
- solr/contrib/blob-directory/src/test/org/apache/solr/blob/BlobDirectoryTest.java
BlobPusher now is able to pull files, so I needed to rename it. I didn't find a nice name that satisfies me, at the moment it is named BlobStoreConnection. Would you have a better name?
> SOLR-15051: Pull files from the repository when BlobDirectory is created.

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/sql/SolrSchema.java
- solr/core/src/java/org/apache/solr/request/SolrRequestInfo.java
- solr/core/src/java/org/apache/solr/security/PKIAuthenticationPlugin.java
- solr/core/src/test/org/apache/solr/handler/sql/SQLWithAuthzEnabledTest.java
- solr/solr-ref-guide/src/parallel-sql-interface.adoc
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/LBSolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/io/stream/SolrStream.java
https://issues.apache.org/jira/browse/SOLR-15451
When executing a SQL statement, Solr needs to hit the `/admin/luke` endpoint (for a specific collection). This PR changes the `SolrSchema` class to mark the current thread as a server thread and sets a new `useServerToken` flag in `SolrRequestInfo` that forces the PKI plugin to use the server token instead of the principal associated with the request. The flag is needed because the `generateToken` method will always use the user's `Principal` from the request info if available. The flag says to not use the Principal and instead set the server token header. This alleviates the need to run the request in a background thread. I added a static `withServerIdentity` utility method to `PKIAuthenticationPlugin` to mark the thread as a server thread …
> SOLR-15451: SolrSchema (for SQL) should use PKI principal for request to /admin/luke

- solr/CHANGES.txt
- solr/solr-ref-guide/src/distributed-requests.adoc
- solr/solrj/src/java/org/apache/solr/client/solrj/routing/NodePreferenceRulesComparator.java
- solr/solrj/src/java/org/apache/solr/common/params/ShardParams.java
- solr/solrj/src/test/org/apache/solr/client/solrj/routing/NodePreferenceRulesComparatorTest.java
- solr/solrj/src/test/org/apache/solr/client/solrj/routing/RequestReplicaListTransformerGeneratorTest.java
https://issues.apache.org/jira/browse/SOLR-15472
Add a new `shards.preference` option to prefer replicas based on leader status. 
Unit tests provided to exercise this new feature. I also ran a quick query load test to verify the routing works, see screenshot.
> SOLR-15472: New shards.preference option for preferring replicas based on their leader status

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/component/ExpandComponent.java
- solr/core/src/java/org/apache/solr/handler/component/TermVectorComponent.java
https://issues.apache.org/jira/browse/SOLR-15517
> SOLR-15517: Remove unnecessary no-op implementation of SolrCoreAware in ExpandComponent and TermVectorComponent.

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/search/SignificantTermsQParserPlugin.java
- solr/core/src/test/org/apache/solr/search/SignificantTermsQParserPluginTest.java
https://issues.apache.org/jira/browse/SOLR-15531
The `SignificantTermsQParserPlugin` uses the class `SparseFixedBitSet` internall that requires a length parameter >= 1. In order to fill the parameter, the result of `searcher.indexReader().maxDoc()` which is 0 for shards without any document.
Before the Plugin creates the analytics collector, the proposed solution checks `maxDocs` and decides if it should return the `SignifcantTermsCollector` or a no op collector.
1. A test to check the existing behavior for collections with at least one document
2. A test to verify the error against a collection with 0 documents.
> SOLR-15531: significantTerms streaming function should not fail on empty collections

- solr/CHANGES.txt
- solr/core/src/test/org/apache/solr/cloud/VMParamsZkACLAndCredentialsProvidersTest.java
- solr/solr-ref-guide/src/zookeeper-access-control.adoc
- solr/solrj/src/java/org/apache/solr/common/cloud/VMParamsAllAndReadonlyDigestZkACLProvider.java
- solr/solrj/src/java/org/apache/solr/common/cloud/VMParamsSingleSetCredentialsDigestZkCredentialsProvider.java
https://issues.apache.org/jira/browse/SOLR-15525
Added new Java system property `zkDigestCredentialsFile` to allow loading of zk creds from a file instead of from system properties.
Added to existing unit test `VMParamsZkACLAndCredentialsProvidersTest` to use the new `zkDigestCredentialsFile` feature.
> SOLR-15525: Read ZK credentials from a file specified using a system property instead of exposing plain-text credentials

- solr/CHANGES.txt
- solr/contrib/ltr/src/java/org/apache/solr/ltr/LTRRescorer.java
- solr/contrib/ltr/src/java/org/apache/solr/ltr/interleaving/LTRInterleavingRescorer.java
…objects
https://issues.apache.org/jira/browse/SOLR-15496
A static instance of the comparator(s) could be created and reused.
I just created two static comparators instead of creating both each call
> SOLR-15496 LTRRescorer unnecessarily (re)creates Comparator

- .gitignore
- solr/CHANGES.txt
https://issues.apache.org/jira/browse/SOLR-15309
Add missing entries to .gitignore file for IntelliJ IDEA.
Manually verified that the IntelliJ files no longer show up in `git status`
> SOLR-15309: Update .gitignore files for IntelliJ IDEA

- solr/core/src/java/org/apache/solr/handler/designer/SchemaDesignerAPI.java
- solr/webapp/web/index.html
- solr/webapp/web/js/angular/app.js
- solr/webapp/web/js/angular/controllers/collections.js
- solr/webapp/web/js/angular/controllers/schema-designer.js
- solr/webapp/web/partials/schema-designer.html
https://issues.apache.org/jira/browse/SOLR-15568
Minor updates to handle 403 error if user is not authorized. Also includes fix that was listing un-published schemas as candidates to be copied from when creating a new schema.
> SOLR-15568: Don't render the Schema Designer screen if user is not authorized

- solr/CHANGES.txt
- solr/core/src/test/org/apache/solr/handler/TestSQLHandler.java
- solr/solr-ref-guide/src/parallel-sql-interface.adoc
https://issues.apache.org/jira/browse/SOLR-15566
Improved the docs around `select *` in the ref guide
Added a simple unit test for coverage of `select *`
> SOLR-15566: Clarify ref guide documentation about SQL queries with SELECT * requiring a LIMIT clause

- solr/core/src/java/org/apache/solr/handler/sql/SolrSchema.java
- solr/core/src/test-files/solr/configsets/sql/conf/schema.xml
- solr/core/src/test/org/apache/solr/handler/TestSQLHandler.java
https://issues.apache.org/jira/browse/SOLR-15570
Adding to previous commit: https://github.com/apache/solr/commit/6056b6814de1a93cfbf14858bfa5e6026e86d16d
Need to check if a field is either stored or has docValues enabled.
> SOLR-15570: Check stored or docValues when merging fields from the Luke schema response

- solr/CHANGES.txt
- solr/core/src/test/org/apache/solr/cloud/TestPullReplicaWithAuth.java
- solr/solrj/src/java/org/apache/solr/client/solrj/request/CollectionAdminRequest.java
https://issues.apache.org/jira/browse/SOLR-15575
See trivial code changes
Updated an existing unit test that already has the security wired into test cluster setup to verify this fix.
> SOLR-15575: Propagate request level basic auth creds from the top-level request to internally used async requests

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/sql/SolrFilter.java
- solr/core/src/test/org/apache/solr/handler/TestSQLHandler.java
- solr/solrj/src/java/org/apache/solr/client/solrj/io/stream/JDBCStream.java
https://issues.apache.org/jira/browse/SOLR-15576
Minor improvement for robustness of the SQL backend to allow filtering with ISO-8601 timestamp formatted literals.
Just needed to fix the proper handling of RexNode types in the translateBinary call. Also found a bug where the left and right operands were being swapped but that's only valid for equals operator. I mean we could also adapt the operator to the swap but that seems awkward, so leaving that as an open issue for now.
Added new unit test
> SOLR-15576: Allow filtering on ISO-8601 formatted timestamp literals in SQL WHERE clause

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/sql/SolrEnumerator.java
- solr/core/src/java/org/apache/solr/handler/sql/SolrSchema.java
- solr/core/src/test-files/solr/configsets/sql/conf/schema.xml
- solr/core/src/test/org/apache/solr/handler/TestSQLHandler.java
- solr/solr-ref-guide/src/parallel-sql-interface.adoc
- solr/solrj/src/java/org/apache/solr/client/solrj/io/stream/JDBCStream.java
- solr/solrj/src/test/org/apache/solr/client/solrj/io/sql/JdbcTest.java
https://issues.apache.org/jira/browse/SOLR-9853
There's a paradigm mismatch between Solr multi-valued fields and SQL:
1. Currently, the Table schema returned from `SolrSchema` does not indicate a field is multi-valued
2. Before the recent Calcite upgrade, projected multi-valued fields would be returned as a list of string values, regardless of type.
3. After the recent Calcite upgrade, projecting non-string multi-valued fields results in cast exceptions. There were no unit tests in the suite that should have caught this.
Although Calcite supports `ARRAY` types, you can't use them in a `WHERE` clause (such as `IN`) without creating UDFs like `array_contains`. Moreover, you can't do a `GROUP BY` on an `ARRAY` field w/o cumbersome un-nesting with sub-selects. Consequently, the best way to …
> SOLR-9853: Ability to project multi-valued fields in SQL query results

- solr/solr-ref-guide/src/filters.adoc
- solr/solr-ref-guide/src/other-parsers.adoc
https://issues.apache.org/jira/browse/SOLR-14655
This *finally* adds the MinHash docs that have been waiting for a few years. I kept them mostly the way they were in the issue, with some changes to match the current way we do things for params, examples, etc.
I tried out the filter, but not the query parser.
> SOLR-14655: Add MinHash docs

- solr/core/src/java/org/apache/solr/search/similarities/BM25SimilarityFactory.java
- solr/core/src/java/org/apache/solr/search/similarities/LegacyBM25SimilarityFactory.java
- solr/solr-ref-guide/src/schema-elements.adoc
As per https://github.com/apache/lucene/pull/247 `LegacyBM25Similarity` will be removed from Lucene 9.0 onwards.
Do we wish to formally mark `LegacyBM25SimilarityFactory` deprecated from Solr 8.10 onwards (assuming Solr 9.0 would remove it) or does the "Legacy" part of the name perhaps sort of imply deprecation enough already?
https://issues.apache.org/jira/browse/SOLR-13138
> SOLR-13138: deprecate LegacyBM25SimilarityFactory

- dev-tools/scripts/releaseWizard.py
Old URL to check the apache id gpg key is no longer available.
> Fix gpg key download in release wizard.

- solr/solr-ref-guide/src/caches-warming.adoc
- solr/solr-ref-guide/src/filters.adoc
- solr/solr-ref-guide/src/language-analysis.adoc
https://issues.apache.org/jira/browse/SOLR-12255
Adds documentation on the Nori tokenizer finally. It's mostly copied from the related Javadocs.
Also fixes SOLR-12996 to add the `fillerToken` param for the ShingleFilterFactory, since that was a quick fix.
And I caught a random typo in a completely unrelated page so tossed that in too.
> SOLR-12255: Add docs for Nori Korean tokenizer

- solr/core/src/java/org/apache/solr/search/SolrIndexSearcher.java
https://issues.apache.org/jira/browse/SOLR-13138
The method was deprecated in https://github.com/apache/solr/commit/1e63b32731bedf108aaeeb5d0a04d671f5663102 for https://issues.apache.org/jira/browse/SOLR-12366 i.e. Solr 7.4 version.
> SOLR-13138: remove deprecated SolrIndexSearcher.getLiveDocs() method

- solr/CHANGES.txt
- solr/webapp/web/js/angular/controllers/schema-designer.js
https://issues.apache.org/jira/browse/SOLR-15620
When basic auth is enabled, we need to make the request to download the zip using XMLHttpRequest so we can pass the Authorization header.
Testing is manual in FF, Chrome, and Safari
> SOLR-15620: Download Config button in Schema Designer screen should not require user to re-login when already authenticated

- solr/core/src/java/org/apache/solr/search/CaffeineCache.java
- solr/solr-ref-guide/src/caches-warming.adoc
- solr/test-framework/src/java/org/apache/solr/SolrTestCaseJ4.java
https://issues.apache.org/jira/browse/SOLR-15555
Addresses an issue with parent/child join queries by making async caches the default.
> SOLR-15555 Make Async Cache the default

- dev-tools/scripts/releaseWizard.py
- dev-tools/scripts/releaseWizard.yaml
- dev-tools/scripts/scriptutil.py
https://issues.apache.org/jira/browse/SOLR-15173
https://github.com/apache/lucene/pull/305 is for `lucene/main` branch equivalent, i tried having one `lucene-solr/branch_8x` commit and cherry-picking back to `lucene/main` and `solr/main` but there were conflicts, so separate pull requests seems easier.
> SOLR-15173: replace 'master' with 'main' in release wizard

- solr/CHANGES.txt
- solr/webapp/web/partials/query.html
https://issues.apache.org/jira/browse/SOLR-15650
Make picking a defType in the Solr Admin an explicit choice, otherwise you use the default.
Make the defType selection box follow the pattern of other selection boxes.
Manually, and paired on this work with @paul-blanchaert
- [ x] I have created a Jira issue and added the issue ID to my pull request title.
- [ X] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but …
> SOLR-15650: make not picking a defType more explicit in UI

- solr/solr-ref-guide/src/kerberos-authentication-plugin.adoc
https://issues.apache.org/jira/browse/SOLR-14321
replace `HttpClientUtil.setConfigurer(...)` with `HttpClientUtil.setHttpClientBuilder(new Krb5HttpClientBuilder().getBuilder());`
> SOLR-14321: SolrJ with Kerberos docs update invalid HttpClientUtil.setConfigurer

- dev-tools/scripts/poll-mirrors.py
https://issues.apache.org/jira/browse/SOLR-15665
Fix was actually borrowed from @HoustonPutman 's change for the Solr operator:
https://github.com/apache/solr-operator/commit/7ef0d8cebb3eb0af297d32c2a5f4dae3bf966c57#diff-cea0c736ffb3ab0d91013274d57de1fddc2539c7941134a887430cfb642374dd
Tested manually:
```
Run this script to check the number and percentage of mirrors (and Maven Central) that have the release
cd ~/.lucene-releases/8.10.0/lucene-solr
python3 -u dev-tools/scripts/poll-mirrors.py -version 8.10.0 -o
Q: Do you want me to run these commands now? (y/n): y
Output will be shown live byte by byte
2021-09-29 09:47:47
Polling 104 Apache Mirrors and Maven Central...
........................................................................................................
8.10.0 is …
```
> SOLR-15665: Move polling logic under main

- solr/solr-ref-guide/src/indexing-with-tika.adoc
According to [this jira ticket](https://issues.apache.org/jira/browse/SOLR-15763) documentation should be updated.
https://issues.apache.org/jira/browse/SOLR-15763
In [this page](https://solr.apache.org/guide/8_10/uploading-data-with-solr-cell-using-apache-tika.html#configuring-the-extractingrequesthandler-in-solrconfig-xml) there is the procedure to configure the ExtractingRequestHandler but, probably a typo, in the section of schema defining with URPs there's an error.
```java
<requestHandler name="/update/extract"
startup="lazy"
class="solr.extraction.ExtractingRequestHandler" >
<lst name="defaults">
<str name="lowernames">true</str>
<str name="fmap.content">_text_</str>
<str name="processor">uuid,remove-blank,field-name-mutating,parse-boolean,parse-long,parse-double,parse-date</process …
```
> SOLR-15763 : Fix documentation in indexing with tika

- solr/benchmark/src/resources/configs/cloud-minimal/conf/solrconfig.xml
[SOLR-15663 JsonFaceting benchmark should flush by doc count for better reproducible behavior.](https://app.gitkraken.com/glo/view/card/560bf6f8fc4043328abe0c351a6c6a2e)
> SOLR-15663: JsonFaceting benchmark should flush by doc count for better reproducible behavior.

- solr/CHANGES.txt
- solr/solr-ref-guide/build.gradle
- solr/solrj/src/test/org/apache/solr/client/solrj/SolrExampleXMLTest.java
https://issues.apache.org/jira/browse/SOLR-15793
pin http_parser.rb gem dependency to an older version that compiles.
pin an older version!    I tested in branch_8x and it didn't seem to have the same issue.
ran the build
- [ X] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [ X] I have developed this patch against the …
> SOLR-15793: ref-guide jrubyPrepare fails due to gems trying to compile native code

- solr/CHANGES.txt
- solr/contrib/extraction/src/test-files/extraction/solr/collection1/conf/solrconfig.xml
- solr/contrib/gcs-repository/src/java/org/apache/solr/gcs/GCSBackupRepository.java
- solr/core/src/test-files/solr/collection1/conf/solrconfig-analytics-query.xml
- solr/core/src/test-files/solr/collection1/conf/solrconfig-collapseqparser.xml
- solr/core/src/test-files/solr/collection1/conf/solrconfig-components-name.xml
- solr/core/src/test-files/solr/collection1/conf/solrconfig-doctransformers.xml
- solr/core/src/test-files/solr/collection1/conf/solrconfig-elevate.xml
- solr/core/src/test-files/solr/collection1/conf/solrconfig-hash.xml
- solr/core/src/test-files/solr/collection1/conf/solrconfig-minhash.xml
- solr/core/src/test-files/solr/collection1/conf/solrconfig-plugcollector.xml
- solr/core/src/test-files/solr/collection1/conf/solrconfig-sql.xml
- solr/core/src/test-files/solr/collection1/conf/solrconfig-test-misc.xml
- solr/core/src/test-files/solr/collection1/conf/solrconfig.xml
- solr/core/src/test-files/solr/crazy-path-to-config.xml
- solr/core/src/test/org/apache/solr/core/TestConfig.java
- solr/solrj/src/test-files/solrj/solr/collection1/conf/solrconfig-sql.xml
- solr/solrj/src/test-files/solrj/solr/collection1/conf/solrconfig.xml
- solr/solrj/src/test-files/solrj/solr/configsets/ml/conf/solrconfig.xml
- solr/solrj/src/test-files/solrj/solr/configsets/shared/conf/solrconfig.xml
- solr/solrj/src/test-files/solrj/solr/configsets/streaming/conf/solrconfig.xml
- solr/solrj/src/test-files/solrj/solr/multicore/core0/conf/solrconfig.xml
- solr/solrj/src/test-files/solrj/solr/multicore/core1/conf/solrconfig.xml
- solr/solrj/src/test/org/apache/solr/client/solrj/SolrExampleXMLTest.java
https://issues.apache.org/jira/browse/SOLR-15791
Removing old `<admin/>` xml stanza from solrconfigs that no longer is used.  Clean up!
Removed the xml, ran the tests.  I found one unit test, TestConfig.testAutomaticDeprecationSupport() that didn't seem to add any value anymore.
Ran existing tests.
- [x ] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [x ] I have created a Jira issue and added the issue ID to my pull request title.
- [x ] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR …
> SOLR-15791: Remove remaining <admin> clauses from solrconfigs

- solr/CHANGES.txt
- solr/docker/templates/Dockerfile.body.template
https://issues.apache.org/jira/browse/SOLR-15808
Just yet another simplification of Dockerfile, shaved off 4 lines :)
> SOLR-15808: The jattach tool for Docker image is now installed with apt

- solr/CHANGES.txt
- solr/bin/solr
https://issues.apache.org/jira/browse/SOLR-15700
In the `bin/solr` bash script, the header comment specifies which paths are searched for the environment file `solr.in.sh`, however this does not match the logic that actually finds and includes the file. This results in unexpected behavior if the user is packaging Solr to run under `/var/solr`, and the fairly common `/etc/default` path is undocumented. Both of these paths are already used in the reference guide, namely [Taking Solr to Production](https://github.com/apache/solr/blob/main/solr/solr-ref-guide/src/taking-solr-to-production.adoc) and [Upgrading a Solr Cluster](https://github.com/apache/solr/blob/main/solr/solr-ref-guide/src/upgrading-a-solr-cluster.adoc).
Added `/etc/default` to the script's header comment (was only in logic) …
> SOLR-15700: Make include paths in bin/solr consistent

- solr/core/src/java/org/apache/solr/handler/component/SpellCheckComponent.java
At INFO not DEBUG level a long message which includes the JSON of the response, including the words the user search for. 
Not sure if I should file an issue in the Jira for this kind of trivial change? @dsmiley
> SpellCheckComponent shouldn't log at info level

- solr/docker/build.gradle
- solr/docker/gradle-help.txt
- solr/docker/templates/Dockerfile.body.template
https://issues.apache.org/jira/browse/SOLR-15808
Cleaning up the GITHUB_URL option after updating the dockerfiles to download jattach from `apt-get` instead of github.
> SOLR-15808: Remove the GITHUB_URL arg from the docker build

- solr/core/src/java/org/apache/solr/core/SolrResourceLoader.java
- solr/core/src/test/org/apache/solr/schema/PrimitiveFieldTypeTest.java
https://issues.apache.org/jira/browse/SOLR-15826
This is round 2 with further improvement
* `allowUnsafeResourceloading` is now final
* Remove unnecessary use of `solr.allow.unsafe.resourceloading` in `PrimitiveFieldTypeTest.java`
* Simplify some code in ResourceLoader for Java8, use empty `<>`, shorter lambda functions and remove implicit null's
* Swap order of or'ed clauses in if test for tiny efficiency gain
> SOLR-15826 Simplify some code in SolrResourceLoader after review

- solr/core/src/java/org/apache/solr/client/solrj/embedded/JettySolrRunner.java
- solr/core/src/java/org/apache/solr/servlet/SolrDispatchFilter.java
- solr/server/etc/jetty-ssl.xml
Moves init into jetty-ssl.xml to ensure ssl is ready before any of our https request related code needs it, and remove such concerns form request and servlet related classes.
> SOLR-15590 Fix SSL, init order misplaced by prior commit for this ticket.

- solr/core/src/test/org/apache/solr/handler/component/MockSortSpecBuilder.java
See https://issues.apache.org/jira/browse/SOLR-15839
> SOLR-15839: Don't mock oal.search.Sort class (why the hell was this needed?)

- solr/core/src/java/org/apache/solr/handler/admin/ShowFileRequestHandler.java
https://issues.apache.org/jira/browse/SOLR-15804
I tested Velociry Response Writer in 8.11.1, and it appears that it uses ShowFile handler to get its css and js files from within the configset folder. But the VM templates uses `file=/velocity/foo.css`, i.e. absolute paths, which are now disallowed. So the simple fix is to strip leading slash and interpret that to mean start of config folder. We also add back support for `text/javascript`, as that is also used by Velocity.
Tested to work well with Admin UI files view. This is mainly done in main branch so that the 3rd party velocity package will still work in 9.0.
> SOLR-15804 Support leading slash for "file" parameter and text/javascript

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/admin/ZookeeperStatusHandler.java
https://issues.apache.org/jira/browse/SOLR-15849
Zookeeper only accepts 4LW, but solr socket sends 4LW with \n.
Remove \n.
You can use the Wireshark to view network data and close the connection.
> SOLR-15849 Incorrect use Zookeeper 4LW

- solr/core/src/test/org/apache/solr/cloud/CollectionPropsTest.java
There is no associated JIRA.
This is a simple test code cleanup.
Current code will not wait if log level is not at INFO
> ensures that test code does not depend on log level

- solr/solr-ref-guide/src/partial-document-updates.adoc
https://issues.apache.org/jira/browse/SOLR-15789
Explicitly state that the "inc" amounts in atomic updates can be negative or fractional. As written now, a reader may think that fields can only be incremented, as in Redis's INCRBY command.
> SOLR-15789: Explain that atomic update "inc" can take negative and fractional values

- solr/bin/post
- solr/docker/templates/Dockerfile.body.template
Inspired by https://github.com/docker-solr/docker-solr/pull/405
Make sure the rm statement works, and also delete redundant `solr-core-*.jar` from dist folder.
> Simplify rm statement, make sure deletion works, remove redundant solr-core jar

- solr/core/src/java/org/apache/solr/util/SolrVersion.java
- solr/core/src/test/org/apache/solr/util/TestSolrVersion.java
https://issues.apache.org/jira/browse/SOLR-15896
Simple workaround. Also verifies that build-version component is supported.
> SOLR-15896 Fix the toString method of SolrVersion

- solr/core/src/test-files/solr/question-answer-repository/repository.json
- solr/core/src/test/org/apache/solr/cloud/PackageManagerCLITest.java
https://issues.apache.org/jira/browse/SOLR-15902
This fixes the bug where newer versions of Solr (10.0.0) cause the `PackageManagerCLITest.testPackageManager` test to fail.
We can deal with the random jar issue separately.
> SOLR-15902: Do not set maximum Solr version on test package

- solr/CHANGES.txt
- solr/contrib/prometheus-exporter/bin/solr-exporter
- solr/docker/build.gradle
- solr/docker/templates/Dockerfile.body.template
- solr/docker/tests/cases/prometheus-exporter/test.sh
- solr/docker/tests/shared.sh
https://issues.apache.org/jira/browse/SOLR-14858
This finally adds docker testing for the prometheus-exporter contrib.
I also had to remove the jar-removing from the Dockerfile, because the prometheus-exporter relies on `solrj-lib` as well as `solr-solrj-*.jar`. Will see what I can do in the `solr-exporter` script, to use the other locations of these jars.
> SOLR-14858: Add docker test for the prometheus exporter

- solr/core/src/java/org/apache/solr/servlet/QueryRateLimiter.java
- solr/core/src/java/org/apache/solr/servlet/RateLimitManager.java
Discovered this while viewing the output of `MiniSolrCloudClusterTest.testErrorsInStartup`
> QueryRateLimiter should not error on empty input

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cloud/api/collections/Assign.java
- solr/core/src/java/org/apache/solr/cluster/placement/PlacementPluginFactory.java
- solr/core/src/java/org/apache/solr/cluster/placement/plugins/DefaultPlacementFactory.java
- solr/core/src/java/org/apache/solr/cluster/placement/plugins/LegacyPlacementFactory.java
- solr/core/src/java/org/apache/solr/cluster/placement/plugins/MinimizeCoresPlacementFactory.java
- solr/core/src/java/org/apache/solr/cluster/placement/plugins/RandomPlacementFactory.java
- solr/core/src/test/org/apache/solr/cloud/OverseerCollectionConfigSetProcessorTest.java
- solr/core/src/test/org/apache/solr/servlet/HttpSolrCallGetCoreTest.java
- solr/solr-ref-guide/src/replica-placement-plugins.adoc
https://issues.apache.org/jira/browse/SOLR-15209
There are some issues with each of the placementPlugins, but will follow up separately.
> SOLR-15209: Make the LegacyAssignStrategy the DefaultPlacementPlugin

- dev-tools/scripts/README.md
- dev-tools/scripts/addContrib.py
- dev-tools/scripts/scaffoldNewModule.py
Adding a new contrib required wiring contrib-name into several gradle files, and they all need a README and a `build.gradle`. So here is a py script to scaffold a new contrib and wire it into the build. See usage in README.
Perhaps such a tool can propell the effort to lift stuff out from core into contribs. A nice detail is that solr-operator has 1st class support for adding contribs by name. I wonder if we could add such shortcut to `bin/solr` as well, e.g. `bin/solr start -c -Dcontribs=analysis-extras,langid,clustering` and the script will automatically add them to global path.
> Script to scaffold a new contrib module

- solr/core/src/test/org/apache/solr/cloud/api/collections/CollectionsAPIDistributedZkTest.java
https://issues.apache.org/jira/browse/SOLR-15935
> SOLR-15935: Fix CollectionsAPIDistributedZkTest.testCreateShouldFailOnExistingCore

- dev-docs/plugins-modules-packages.adoc
Did a write-up for developers about plugins, modules and packages. Far from complete, as it needs more detail and guidance, but perhaps a good starting point.
I also propose a new naming convention for modules and packages that makes it more obvious from the name what kind of a module/package it is.
PS: See https://github.com/apache/solr/blob/1c52f8133378c149fd1e31a279fedb9b4f2f3e94/dev-docs/plugins-modules-packages.adoc for a redered version of the adoc
> Developer docs for modules and packages

- solr/CHANGES.txt
- solr/bin/solr
- solr/bin/solr.cmd
- solr/bin/solr.in.cmd
- solr/bin/solr.in.sh
- solr/server/etc/jetty-requestlog.xml
- solr/server/resources/log4j2.xml
- solr/solr-ref-guide/src/configuring-logging.adoc
- solr/solr-ref-guide/src/major-changes-in-solr-9.adoc
- solr/solr-ref-guide/src/securing-solr.adoc
(SOLR_REQUESTLOG_ENABLED defaults to true)
https://issues.apache.org/jira/browse/SOLR-14142
Picking up this old jira, hoping to get it into 9.0. This PR is the exact same as Rob's latest patch in JIRA. I have not tested it but let's do another review. 
There were some concerns about the requestlog not being rotated, and filling up disks. If it is a quick fix with some sys prop then let's add a default of 1Gb or something. There should perhaps be a RefGuide mention as well?
> SOLR-14142 Enable jetty's request log by default

- dev-tools/scripts/releaseWizard.yaml
Just discovered that the releaseWizard, after branching `branch_9_0`, adds version 9.1 to `branch_9x` (including CHANGES.txt), but it does not add v 9.1 to main branch. This is wrong, as there should be a 9.1 changes section also on main branch now.
I added it manually and committed. But this is the change I believe is ncessary to the wizard to automate this in the future. I find it strage that this has not been discovered before, so I'm starting to question whether I am overlooking something obvious here? Please review.
> Add the new minor version (e.g. 9.1) also to main branch

- solr/contrib/prometheus-exporter/src/test/org/apache/solr/prometheus/exporter/SolrExporterTestBase.java
- solr/contrib/prometheus-exporter/src/test/org/apache/solr/prometheus/utils/Helpers.java
https://issues.apache.org/jira/browse/SOLR-15922
> SOLR-15922 SolrExporterIntegrationTest fails on Java 17

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/store/blockcache/CustomBufferedIndexInput.java
- solr/core/src/test/org/apache/solr/cloud/hdfs/HDFSCollectionsAPITest.java
- solr/core/src/test/org/apache/solr/index/hdfs/CheckHdfsIndexTest.java
- solr/core/src/test/org/apache/solr/search/TestRecoveryHdfs.java
- solr/core/src/test/org/apache/solr/update/TestHdfsUpdateLog.java
https://issues.apache.org/jira/browse/SOLR-15405
Uses Lucene `ByteArrayDataInput` and `ByteBuffersDataInput` as inspiration.
* https://github.com/apache/lucene/blob/releases/lucene%2F9.0.0/lucene/core/src/java/org/apache/lucene/store/ByteArrayDataInput.java
* https://github.com/apache/lucene/blob/releases/lucene%2F9.0.0/lucene/core/src/java/org/apache/lucene/store/ByteBuffersDataInput.java#L212
`CustomBufferedIndexInput` needs to ensure that
it handles LUCNE-9047 changes for little
endianess. This replaces the existing methods
with little endian implementations.
Ran all HDFS repeatedly - details in comments below for some failures that are unrelated to this change.
> SOLR-15405: Make HDFS handle little endian LUCENE-9047

- solr/CHANGES.txt
- solr/modules/ltr/src/java/org/apache/solr/ltr/LTRThreadModule.java
https://issues.apache.org/jira/browse/SOLR-15953
> SOLR-15953: remove unused LTRThreadModule.preClose CloseHook logic

- solr/modules/prometheus-exporter/build.gradle
https://issues.apache.org/jira/browse/SOLR-15605
The duplicate jars existed because the `lib` generating logic was duplicated in `solr/modules/prometheus-exporter/build.gradle` and `gradle/solr/packaging.gradle`. The `gradle/solr/packaging.gradle` logic was correct, however the `solr/modules/prometheus-exporter/build.gradle` logic did not remove jars from solrj/solr-core, so there were duplicates left.
There's no reason to duplicate this logic in the first place, so removing the section fixes the build.
> SOLR-15605: Fix duplicate jars in prometheus-exporter

- dev-tools/scripts/cherrypick.sh
Running cherrypick.sh with `-p` but without `-r` caused a local failure for me. Running it without `-r` previously had always worked even for the pulls because I have upstream tracking branches set up.
> Attempt to detect remote if not specified

- solr/CHANGES.txt
- solr/prometheus-exporter/src/java/org/apache/solr/prometheus/exporter/SolrExporter.java
- solr/prometheus-exporter/src/java/org/apache/solr/prometheus/exporter/SolrScrapeConfiguration.java
https://issues.apache.org/jira/browse/SOLR-15957
New startup logs look like:
```
INFO  - 2022-01-27 15:55:39.177; org.apache.solr.prometheus.exporter.SolrExporter; Starting Solr Prometheus Exporting on port 8989
INFO  - 2022-01-27 15:55:39.197; org.apache.solr.prometheus.collector.SchedulerMetricsCollector; Beginning metrics collection
INFO  - 2022-01-27 15:55:39.289; org.apache.solr.prometheus.exporter.SolrExporter; Solr Prometheus Exporter is running. Collecting metrics for Solr Node: http://solr-host:8983/solr
```
> SOLR-15957: Add information to Prometheus Exporter startup logging

- README.md
- solr/README.md
- solr/docker/README.md
- solr/docker/build.gradle
- solr/docker/templates/Dockerfile.body.template
- solr/prometheus-exporter/README.md
- solr/solr-ref-guide/src/installing-solr.adoc
- solr/solr-ref-guide/src/solr-in-docker.adoc
https://issues.apache.org/jira/browse/SOLR-15956
Note I have also renamed `solr-<version>/docker/Dockerfile.local` to `solr-<version>/docker/Dockerfile` in the distribution, as I don't think there would be any confusion there and it is just cleaner. It's completely compatible with the official Docker image, just uses the binary distribution instead of downloading official releases.
As a last non-doc change, I added back in the logic to remove the Dockerfile from the Docker image. This is because without this logic, the official docker image would contain the _local_ Dockerfile, which doesn't particularly make sense. Easier to just remove it as it doesn't provide value.
Will mention both above changes in the JIRA.
> SOLR-15956: Docs for building a Docker image from the TGZ

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/core/SolrXmlConfig.java
- solr/core/src/java/org/apache/solr/metrics/reporters/SolrJmxReporter.java
- solr/server/resources/log4j2-console.xml
- solr/server/resources/log4j2.xml
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/Http2SolrClient.java
https://issues.apache.org/jira/browse/SOLR-15936
See JIRA issue for what log lines will be muted. Some Jetty packages are raised to WARN level. I kept the jetty logging related to Server startup.
@CaoManhDat: Check the `Http2SolrClient` changes. I detect ssl without instantiating `SslContextFactory`, and also removed dead code related to java8, which is not required as we now have minimum java 11 requirement.
> SOLR-15936 Reduce unnecessary startup logging, such as SSL warnings when SSL not in use 

- solr/core/src/java/org/apache/solr/core/SolrCore.java
https://issues.apache.org/jira/browse/SOLR-14686
Fixing my mistake.  Ensure MDC is cleared right before this method returns.
> SOLR-14686: fix MDC log clear in SolrCore.close

- solr/docker/templates/Dockerfile.body.template
I got this idea, that adding a symlink from `modules` to `contrib` in 9.x images, we'd get some degree of back-compat for free. If someone expects `/opt/solr/contrib/extracting/lib/*.jar` then that would actually work with the 9.x image. Not sure about solr-operator @HoustonPutman, perhaps this is enough for v0.5 to handle 9.x? Just a quick thought, have not tested, may be that other changes precludes this from being useful at all :)
> Symlink contrib to modules for 9.x

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/sql/SolrTableScan.java
- solr/core/src/test/org/apache/solr/handler/TestSQLHandler.java
https://issues.apache.org/jira/browse/SOLR-15974
Disable the `EnumerableRules.ENUMERABLE_AGGREGATE_RULE` optimization so that Solr only deals with LogicalAggregate. I looked into adding another rule for EnumerableAggregate but it seemed like we don't need this optimization from Calcite since we're pushing down into Solr's agg engine anyway, we don't need a bunch of optimizations in the Calcite layer.
> SOLR-15974: Remove Calcite's ENUMERABLE_AGGREGATE_RULE as Solr only supports push-down for LogicalAggregate

- solr/core/src/java/org/apache/solr/update/UpdateLog.java
https://issues.apache.org/jira/browse/SOLR-15983
The errors counter can be incremented from multiple threads (though in practice hopefully that is unlikely!) and so use of an `AtomicInteger` instead of an `int` would communicate that more clearly, without impact of performance in the non-error code paths.
Noticed as part of the https://issues.apache.org/jira/browse/SOLR-15983 investigation, but it's not the root cause of the exception seen there.
Also fixing `s/IOException/SolrException` copy/paste in two warning log messages.
> SOLR-15983: change UpdateLog.RecoveryInfo.errors to AtomicInteger

- solr/core/src/test/org/apache/solr/update/processor/AbstractAtomicUpdatesMultivalueTestBase.java
https://issues.apache.org/jira/browse/SOLR-16011
> SOLR-16011: AbstractAtomicUpdatesMultivalueTestBase should not use Guava lists from Curator

- solr/solr-ref-guide/modules/upgrade-notes/pages/major-changes-in-solr-9.adoc
https://issues.apache.org/jira/browse/SOLR-15965
> SOLR-15965 Clarify Upgrade Instructions

- solr/core/src/java/org/apache/solr/query/FilterQuery.java
- solr/core/src/java/org/apache/solr/search/DocSet.java
- solr/core/src/java/org/apache/solr/search/DocSetQuery.java
- solr/core/src/java/org/apache/solr/search/SolrIndexSearcher.java
- solr/solr-ref-guide/modules/upgrade-notes/pages/major-changes-in-solr-9.adoc
... and some misc adjustments
https://issues.apache.org/jira/browse/SOLR-12336
Mostly; instead of making DocSetQuery score as 0, make FilteredQuery do that.  Since FilteredQuery wraps DocSetQuery, there's no difference for FilteredQuery.  DocSetQuery is more internal.  It's users don't see to care about the score any way.
> SOLR-12336: DocSetQuery can have 1 score

- solr/modules/ltr/src/test/org/apache/solr/ltr/TestRerankBase.java
- solr/modules/ltr/src/test/org/apache/solr/ltr/feature/TestValueFeature.java
- solr/modules/ltr/src/test/org/apache/solr/ltr/response/transform/TestInterleavingTransformer.java
- solr/solrj/src/java/org/apache/solr/common/params/SolrParams.java
- solr/solrj/src/java/org/apache/solr/common/util/StrUtils.java
- solr/test-framework/src/java/org/apache/solr/JSONTestUtil.java
- solr/test-framework/src/java/org/apache/solr/util/RestTestBase.java
- solr/test-framework/src/java/org/apache/solr/util/RestTestHarness.java
Pull duplicate setup code into common methods
Narrow thrown exception type declarations
Fix a few spelling errors
Have test results lead to fail() instead of exception
I was motivated to make these changes while viewing the output of the proposed patch on SOLR-15333
Not sure if this is significant enough changes to warrant a JIRA issue or not.
> SOLR-16016 Refactoring RestTestBase and JSONTestUtil

- solr/core/src/java/org/apache/solr/api/V2HttpCall.java
- solr/core/src/test/org/apache/solr/servlet/HttpSolrCallCloudTest.java
https://issues.apache.org/jira/browse/SOLR-16019
* Addresses test failures due to randomized SSL in `org.apache.solr.servlet.HttpSolrCallCloudTest.testWrongUtf8InQ`
* Addresses test failures in `org.apache.solr.handler.V2ApiIntegrationTest`
> SOLR-16019 Supress SSL for the test, fix other test failures

- solr/CHANGES.txt
- solr/modules/hadoop-auth/src/test/org/apache/solr/security/hadoop/KerberosTestServices.java
- solr/modules/hadoop-auth/src/test/org/apache/solr/security/hadoop/KerberosUtils.java
- solr/modules/hadoop-auth/src/test/org/apache/solr/security/hadoop/LocaleTest.java
- solr/modules/hadoop-auth/src/test/org/apache/solr/security/hadoop/TestSolrCloudWithKerberosAlt.java
https://issues.apache.org/jira/browse/SOLR-16042
* Simplifies `TestSolrCloudWithKerberosAlt` to use `KerberosUtils#setupMiniKdc`
* Make sure `KerberosUtils#cleanupMiniKdc` actually clears all system properties it sets
* Adds assertion to `LocaleTest` to confirm that `KerberosTestServices#incompatibleLanguagesWithMiniKdc` has proper list of languages to ignore
* Adds missing languages to `KerberosTestServices#incompatibleLanguagesWithMiniKdc`
> SOLR-16042: Fix TestSolrCloudWithKerberosAlt.testBasics failure due to minikdc locale

- solr/core/src/java/org/apache/solr/core/ConfigOverlay.java
- solr/core/src/java/org/apache/solr/core/SolrCore.java
- solr/core/src/test/org/apache/solr/handler/TestSolrConfigHandlerConcurrent.java
- solr/solrj/src/java/org/apache/solr/common/util/Utils.java
Not a bug necessarily but is better because it's presumptuous to assume the classloader of Utils (SolrJ)
It's really only used internally.  While debugging something, I was suspicious this could have been a problem so I changed it.  It wasn't the problem I was hunting down but nonetheless I think this change makes sense.
> Utils.fromJSONResource should take a ClassLoader

- dev-tools/scripts/smokeTestRelease.py
https://issues.apache.org/jira/browse/SOLR-16048
* jakarta.annotation-api  - this should be allowed so exclusion in smokeTestRelease
* jakarta.activation - this should be allowed so exclusion in smokeTestRelease
* jakarta.xml.bind-api - this should be allowed so exclusion in smokeTestRelease
* unit-api - this should be allowed so exclusion in smokeTestRelease
* removed jersey and xml-api exclusion since they aren't dependencies
anymore
> SOLR-16048: Examine Tika dependencies that brought in javax classes

- build.gradle
- buildSrc/scriptDepVersions.gradle
- gradle/generation/regenerate.gradle
- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/designer/SampleDocumentsLoader.java
- solr/core/src/java/org/apache/solr/parser/ParseException.java
- solr/core/src/java/org/apache/solr/parser/QueryParser.java
- solr/core/src/java/org/apache/solr/parser/QueryParserTokenManager.java
- solr/core/src/test/org/apache/solr/cloud/DistribCursorPagingTest.java
- solr/core/src/test/org/apache/solr/handler/TestRequestId.java
- solr/core/src/test/org/apache/solr/search/TestBlockCollapse.java
- solr/core/src/test/org/apache/solr/update/TestInPlaceUpdatesStandalone.java
- solr/core/src/test/org/apache/solr/update/UpdateLogTest.java
https://issues.apache.org/jira/browse/SOLR-16053
Upgrades
* apache-rat 0.11 -> 0.13
* ecj 3.27.0 -> 3.28.0
* javacc 7.0.4 -> 7.0.10
* jgit 5.9.0.202009080501-r -> 5.13.0.202109080827-r
* flexmark 0.61.24 -> 0.64.0
Addresses
* LUCENE-10240: gradle regenerate fails on java 17
* ecj new findings
* regenerate based on new javacc
* Removes duplicate scriptDepVersions definition from build.gradle and uses buildSrc/scriptDepVersions.gradle
> SOLR-16053: Upgrade script dep versions

- solr/CHANGES.txt
- solr/modules/hdfs/src/test/org/apache/solr/hdfs/cloud/HdfsTestUtil.java
- solr/modules/hdfs/src/test/org/apache/solr/hdfs/util/BadHdfsThreadsFilter.java
https://issues.apache.org/jira/browse/SOLR-16043
Simplifies HDFS tests by:
* defaulting to 1 datanode instead of 2
* Calling only dfsCluster.shutdown(true);
* DataNode::shutdown should only be called from the offerService thread, otherwise deadlock might occur
This passes - but I couldn't readily reproduce the failure from SOLR-16043 on demand.
```
./gradlew test --tests "*hdfs*" --tests "*Hdfs*" --tests "*HDFS*" --tests "*Hadoop*" -Ptests.jvms=4 -Ptests.jvmargs=-XX:TieredStopAtLevel=1 -Ptests.nightly=true -Ptests.awaitsfix=false -Ptests.badapples=false -Ptests.file.encoding=UTF-8
```
> SOLR-16043: Fix HDFS tests - "Command processor" thread leak

- solr/core/src/java/org/apache/solr/request/DocValuesFacets.java
- solr/core/src/test/org/apache/solr/TestRandomDVFaceting.java
https://issues.apache.org/jira/browse/SOLR-15856
This is a fix until we can upgrade to Lucene 9.1. Though there is really no need to remove it down the line.
Some example seeds to test this out: (Useful to make sure the lucene upgrade solves this, when that happens)
```
gradlew test --tests TestRandomDVFaceting.testRandomFaceting -Dtests.seed=BEA0B40F548BF849 -Dtests.multiplier=2 -Dtests.slow=true -Dtests.locale=fr-MC -Dtests.timezone=Brazil/Acre -Dtests.asserts=true -Dtests.file.encoding=UTF-8
gradlew test --tests TestRandomDVFaceting.testRandomFaceting -Dtests.seed=93F6DBA02159A430 -Dtests.multiplier=2 -Dtests.slow=true -Dtests.locale=os-RU -Dtests.timezone=Pacific/Kwajalein -Dtests.asserts=true -Dtests.file.encoding=UTF-8
gradlew test --tests TestRandomDVFaceting.testRandomFaceting …
```
> SOLR-15856: Fix Lucene bug in facet prefix

- solr/CHANGES.txt
- solr/modules/sql/src/java/org/apache/solr/handler/sql/CalciteSolrDriver.java
- solr/modules/sql/src/java/org/apache/solr/handler/sql/SolrFilter.java
- solr/modules/sql/src/java/org/apache/solr/handler/sql/SolrTableScan.java
- solr/modules/sql/src/java/org/apache/solr/handler/sql/functions/ArrayContains.java
- solr/modules/sql/src/java/org/apache/solr/handler/sql/functions/ArrayContainsAll.java
- solr/modules/sql/src/java/org/apache/solr/handler/sql/functions/ArrayContainsAny.java
- solr/modules/sql/src/java/org/apache/solr/handler/sql/functions/package-info.java
- solr/modules/sql/src/test/org/apache/solr/handler/sql/TestSQLHandler.java
https://issues.apache.org/jira/browse/SOLR-16009
Force Calcite's `simplify` flag to false to avoid Calcite erasing query constructs that are meaningful for matching multi-valued fields, see test case from JIRA.
Disabling the simplify action in Calcite (via `Hook.REL_BUILDER_SIMPLIFY`), allows WHERE clauses that match multi-valued fields. However, changing this property to `false` resulted in changes to the Logical query plan passed to `SolrFilter`, especially around `NOT BETWEEN` clauses (which required some refactoring in `SolrFilter`). However, we also got a nice fix to a previous problem that we worked around in a hacky way, see change here:
https://github.com/apache/solr/pull/715/files#diff-5b2c3025d1fe325fee5dd09fbf0d271e28dac1740c886621490e4dc23fa16e9bR2486
> SOLR-16009: Disable Calcite simplify config setting

- solr/solr-ref-guide/modules/query-guide/pages/highlighting.adoc
This one is hard to catch because there's no error if you set `hl=on` and there's no `uniqueKey`. You just don't see a `highlighting` element in the response.
I didn't think a Jira is required for this small change. I did test my changes with `./gradlew buildLocalSite` so the link to the schema page works.
> Mention uniqueKey requirement for highlighting

- solr/CHANGES.txt
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/Http2SolrClient.java
- solr/solrj/src/java/org/apache/solr/common/EmptyEntityResolver.java
- solr/solrj/src/java/org/apache/solr/common/util/ContentStreamBase.java
https://issues.apache.org/jira/browse/SOLR-16088
A baby step towards getting rid of Apache Http client in solrj, removing it from three classes where it is not needed.
I was hoping that we could perhaps make the "default" solr-solr-core NOT suck in Apache Http client, only the Jetty-client, so that to use the old `HttpSolrClient` classes you'd have to add e.g. `org.apache.solr:solr-solrj-apache-http`.
> SOLR-16088 De-couple Http2SolrClient from org.apache.http

- solr/CHANGES.txt
- solr/webapp/web/js/angular/controllers/security.js
https://issues.apache.org/jira/browse/SOLR-SOLR-16022
One liner (well actually 2 but who's counting)! No regex enforcement for passwords with length >= 15
Manually tested in browser, created user with password 123456789012345 (passes) and 12345678901234 (fails)
> SOLR-16022: Enforce special character requirements on passwords with length less than 15

- solr/core/src/test/org/apache/solr/cloud/MultiThreadedOCPTest.java
https://issues.apache.org/jira/browse/SOLR-16092
> SOLR-16092 Do not fail test on slow CI servers

- solr/core/src/test/org/apache/solr/filestore/TestDistribPackageStore.java
- solr/core/src/test/org/apache/solr/handler/TestContainerPlugin.java
https://issues.apache.org/jira/browse/SOLR-16091
I don't think this will actually fix the issue seen by the test, but it will make the logging a little bit easier to follow and hopefully make future failures easier to diagnose.
> SOLR-16091 Improve logging for TestContainerPlugin

- solr/core/src/java/org/apache/solr/api/ContainerPluginsRegistry.java
- solr/core/src/java/org/apache/solr/api/V2HttpCall.java
- solr/core/src/test/org/apache/solr/handler/TestContainerPlugin.java
https://issues.apache.org/jira/browse/SOLR-16091
Tests were still failing after previous set of changes, but we can make the test wait for all nodes to trigger the onChange phaser, rather than a single overseer.
@sigram I can't add you as a reviewer, but would appreciate you looking as well.
> SOLR-16091 Wait for all nodes to register plugins in test

- solr/CHANGES.txt
This contains changes from https://github.com/apache/solr/pull/643 and https://github.com/apache/solr/pull/647
I'll be moving things around a bit more and consolidating this. I have some draft changes but should be ready to go tomorrow.
Changes from Jan's PR:
* Long lines split
* Moved [SOLR-15405](https://issues.apache.org/jira/browse/SOLR-15405) from 8.11.2 section to 9.0 section
* Removed 8.11.2 section from branch_9_0 (will re-add after 8.11.2 release)
* New "Docker" sub-heading since we have so many docker related changes
* New "Deprecation removals" sub-heading. Moved (most) removal JIRAs there
* Fixed some typos
* Remove [SOLR-15631](https://issues.apache.org/jira/browse/SOLR-15631) from 9.0 since it was in 8.11.0
* Removed [SOLR-15222 …
> Update branch_9_0 changelog

- solr/CHANGES.txt
Copied over the 9.0 section from `branch_9_0` after merging the CHANGELOG consolidation PR for that branch.
I confirmed that none of the JIRAs listed in the `9.1` section were duplicated in 9.0, however there are duplicates in 8x (8.11.2) as expected.
Other than this CHANGELOG update, we shouldn't have any commits that only made it into 9.0 and didn't make it into 9x so I think this reflects the current state.
> Update 9.0 changelog, copy from branch_9_0 after consolidation

- gradle/java/jar-manifest.gradle
https://issues.apache.org/jira/browse/SOLR-16118
I don't know why these were explicitly excluded in the first place, but the smoke tester explicitly checks for these in all jar files, and all our historic maven source and javadoc artifacts have had them.
Have not had time to dig up whether it is an absolute ASF policy, but doing this change to keep it as have been.
> SOLR-16118 Bring back NOTICE and LICENSE files in source-jar and javadoc-jar files

- dev-tools/scripts/smokeTestRelease.py
https://issues.apache.org/jira/browse/SOLR-15852
Smoketester fixes for 9.0 RC1
* Test of source tarball is now done on the `gradlew dev` output folder instead of inside source unpack where jars are missing
* Unique log-file names for java17 testing
* Do not require `solr-test-framework-x.x.x.jar` to be in binary release even if it a maven artifact
* Do not run `@Nighlty` tests in the smoketester, instead print a message to check recent Jenkins runs
> SOLR-15852: Smoketester fixes for maven artifact comparison

- dev-tools/scripts/smokeTestRelease.py
The bug was that `testSolrExample()` changed directory, and then the next test with JDK17 assumed that it was still in the source checkout. Fix it by changing back to where it was before exiting that function.
> Fix smoketester so it works with JDK17 - cwd bug

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/highlight/SolrHighlighter.java
https://issues.apache.org/jira/browse/SOLR-16120
> SOLR-16120: optimise hl.fl expansion

- solr/docker/templates/Dockerfile.official.header.template
https://issues.apache.org/jira/browse/SOLR-15891
This was likely just an oversight when migrating the official image to the new system.
> SOLR-15891: Delete tgz from the official image after untarring

- dev-tools/scripts/releaseWizard.yaml
This is the first test done before building the release artifacts from release branch, so it should make sure the local branch is up to date with remote.
Discovered during 9.0 release. Tested locally.
> ReleaseWizard: Add git pull for the 'gradlew documentation' todo

- solr/core/src/java/org/apache/solr/util/OrderedExecutor.java
- solr/core/src/test/org/apache/solr/util/OrderedExecutorTest.java
https://issues.apache.org/jira/browse/SOLR-16127
I'm not sure if the changes in #776 will fix this or not, but this is a test that fails with the current code.
> SOLR-16127 Ordered Executor orphans locks

- solr/bin/solr
- solr/packaging/build.gradle
- solr/packaging/test/README.md
- solr/packaging/test/bats_helper.bash
- solr/packaging/test/test_bats.bats
- solr/packaging/test/test_create_collection.bats
- solr/packaging/test/test_delete_collection.bats
- solr/packaging/test/test_start_solr.bats
https://issues.apache.org/jira/browse/SOLR-16134
Shutting down the cluster via bats's `run` command would hide failed exit status, so we should not do that.
> SOLR-16134: Failing integration tests should fail the build

- solr/solr-ref-guide/modules/deployment-guide/pages/system-requirements.adoc
Updates system requirements, Java versions and Solr version lines table.
There are tons of "Lucene/Solr" mentions elsewhere in the guide, I was a bit surprised to find that at this point, but that can be handled in another PR, unless someone already have a patch/PR lying uncommitted to fix that?
> Update ref-guide system requirements page

- dev-tools/scripts/releaseWizard.yaml
Cherry-picked from Lucene https://github.com/apache/lucene/pull/789
@jtibshirani I don't know if you are aware of the http://fucit.org/solr-jenkins-reports/ site, I added it to the Solr wizard since it is a nice tool to quickly spot failed tests. It also covers Lucene Jenkins, but I'm not sure if it is as useful for Lucene as for Solr, since Solr has a bigger problem with unstable tests.
> New release wizard build failures step

- solr/solr-ref-guide/modules/query-guide/pages/learning-to-rank.adoc
Once we tag the 9.0.0 release I **believe** that this will be the correct link (won't work right yet)
> [RefGuide] Fix github link on learning-to-rank.adoc page

- solr/solr-ref-guide/modules/configuration-guide/pages/configuring-solr-xml.adoc
- solr/solr-ref-guide/modules/configuration-guide/pages/index-segments-merging.adoc
- solr/solr-ref-guide/modules/deployment-guide/pages/indexupgrader-tool.adoc
- solr/solr-ref-guide/modules/deployment-guide/pages/jvm-settings.adoc
- solr/solr-ref-guide/modules/deployment-guide/pages/taking-solr-to-production.adoc
- solr/solr-ref-guide/modules/getting-started/pages/about-this-guide.adoc
- solr/solr-ref-guide/modules/getting-started/pages/tutorial-aws.adoc
- solr/solr-ref-guide/modules/indexing-guide/pages/currencies-exchange-rates.adoc
- solr/solr-ref-guide/modules/indexing-guide/pages/indexing-with-tika.adoc
- solr/solr-ref-guide/modules/indexing-guide/pages/luke-request-handler.adoc
- solr/solr-ref-guide/modules/indexing-guide/pages/phonetic-matching.adoc
- solr/solr-ref-guide/modules/query-guide/pages/dismax-query-parser.adoc
- solr/solr-ref-guide/modules/query-guide/pages/loading.adoc
- solr/solr-ref-guide/modules/query-guide/pages/machine-learning.adoc
- solr/solr-ref-guide/modules/query-guide/pages/standard-query-parser.adoc
- solr/solr-ref-guide/modules/query-guide/pages/stream-evaluator-reference.adoc
- solr/solr-ref-guide/modules/query-guide/pages/term-vectors.adoc
- solr/solr-ref-guide/modules/upgrade-notes/pages/solr-upgrade-notes.adoc
I know that the big Lucene/Solr -> Solr cleanup was done some time ago.
However, I did another search and came across some github links to `lucene-solr` repo (#798, #797). And in this PR I made some other (subjective) changes, mainly using "Solr" over "Lucene/Solr". The exception is when explicitly talking about Analyzers, where I left "Lucene/Solr" as-is.
Please have a look. I suspect that @ctargett left quite a few on these "Lucene/Solr" brands on purpose, so I don't want to overrule those judgements, and will happily change back wher eyou guys feel I was too trigger happy. My thinking is that Solr users in the future will be less aware of Lucene, and saying `Lucene/Solr makes extensive use of MMapDirectory` does not really bring more value than `Solr makes extensive use of …
> [RefGuide] Various Lucene/Solr, Solr/Lucene cleanups

- solr/core/src/java/org/apache/solr/handler/IndexFetcher.java
Fixing a bug in previous PR for this issue as pointed out by @magibney https://github.com/apache/solr/pull/794#issuecomment-1105477466
It'd be nice if RefCounted was Autocloseable
> SOLR-13044: fix searcher/core close sequence

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/component/SpellCheckComponent.java
- solr/core/src/test/org/apache/solr/handler/component/SpellCheckComponentTest.java
https://issues.apache.org/jira/browse/SOLR-16168
If a user provides `spellcheck.q` and an invalid `spellcheck.dictionary` there is an NPE.
This throws an exception with a helpful error message instead of the NPE. It moves the spellcheck null check up in the processing.
Added tests for both when `spellcheck.q` is specified and when `spellcheck.q` isn't specified with an invalid `spellcheck.dictionary` value.
> SOLR-16168: Spellcheck NPE if invalid dictionary name is provided

- gradle/documentation/changes-to-html/changes2html.pl
- solr/CHANGES.txt
When we convert CHANGES.txt to Changes.html, we support adding href links to text like "Pull Request #123". I counted and we only use it like 2 times, and both of those were incorrect, so I removed them.
NB: Perhaps we should allow a pattern like this as well, so you can add PRs to CHANGES without a JIRA:
```
* #794 Fix a bug
```
I.e. in addition to the pattern `((?:(?:(?:github|gh)\s+)?pull\s+request\s*(?:\#?\s*)?|gh-)(\d+))` also support `^\*\s+\#\d{1..4}`.
> Update github PR link to use the new solr repo

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/spelling/AbstractLuceneSpellChecker.java
- solr/core/src/java/org/apache/solr/spelling/DirectSolrSpellChecker.java
- solr/core/src/test/org/apache/solr/spelling/DirectSolrSpellCheckerTest.java
- solr/core/src/test/org/apache/solr/spelling/FileBasedSpellCheckerTest.java
- solr/core/src/test/org/apache/solr/spelling/IndexBasedSpellCheckerTest.java
https://issues.apache.org/jira/browse/SOLR-16169
An empty `spellcheck.q` parameter results in `NegativeArraySizeException` from Lucene. 
https://issues.apache.org/jira/browse/LUCENE-10533 is fixing the root cause, but we can add protection in Solr as well. This skips doing a spell check if the token is empty.
Adds tests to explicitly check if spellcheck tokens are empty and short circuits if it is.
> SOLR-16169: IndexBasedSpellChecker with empty spellcheck.q results in NegativeArraySizeException

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cloud/ZkConfigSetService.java
- solr/core/src/java/org/apache/solr/core/ConfigSetProperties.java
- solr/core/src/java/org/apache/solr/core/RequestParams.java
- solr/core/src/java/org/apache/solr/core/SolrConfig.java
- solr/core/src/java/org/apache/solr/rest/RestManager.java
- solr/core/src/test/org/apache/solr/cloud/TestConfigSetsAPI.java
- solr/solrj/src/java/org/apache/solr/common/cloud/Aliases.java
- solr/solrj/src/java/org/apache/solr/common/cloud/ZkStateReader.java
- solr/solrj/src/java/org/apache/solr/common/util/Utils.java
https://issues.apache.org/jira/browse/SOLR-16164
A draft fix for a NPE that happens when there is no metadata on a node.
Update Utils.fromJSON to handle the null case. 
Test added to `TestConfigSetsAPI` to check for base configset create case without authentication.
> SOLR-16164: ConfigSet API returns error if untrusted user creates from _default configset

- solr/core/src/java/org/apache/solr/search/facet/Constants.java
- solr/core/src/java/org/apache/solr/search/facet/FacetFieldProcessorByArray.java
- solr/core/src/java/org/apache/solr/search/facet/SlotAcc.java
copied from https://github.com/fullstorydev/lucene-solr/pull/140
> SOLR-16165: Rare deadlock in SlotAcc initialization

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cloud/ZkController.java
[SOLR-16154](https://issues.apache.org/jira/browse/SOLR-16154)
Partially based on some ideas from @markrmiller 's reference branch as well.
> SOLR-16154 Event listener thread leak

- dev-tools/scripts/releaseWizard.py
Error msg from wizard:
```
Running 'svn -m "Remove cancelled Solr 9.0.0 RC4" rm https://dist.apache.org/repos/dist/dev/solr/solr-9.0.0-RC4-revd6e36d590896755ca962c6d2ddedf78ca4f463cc' in folder '/Users/janhoy/.solr-releases/9.0.0/solr'
Output of command will be printed (logfile=/Users/janhoy/.solr-releases/9.0.0/RC4/logs/_svn_rm.log)
svn: E160013: URL 'https://dist.apache.org/repos/dist/dev/solr/solr-9.0.0-RC4-revd6e36d590896755ca962c6d2ddedf78ca4f463cc' does not exist
```
> The SVN URL lacks a '-' when deleting previous RC from staging svn

- solr/core/src/java/org/apache/solr/security/AuditLoggerPlugin.java
https://issues.apache.org/jira/browse/SOLR-16186
https://lists.apache.org/list?builds@solr.apache.org:lte=1Y:thread%20leaked%20from%20SUITE%20scope%20at%20org.apache.solr.security.AuditLoggerPluginTest
Doesn't happen very often, but looks like it might not be awaiting the termination even though it is interrupted?
> SOLR-16186: AuditLoggerPluginTest leaks threads

- solr/core/src/test/org/apache/solr/search/TestCancellableCollector.java
https://issues.apache.org/jira/browse/SOLR-16189
> SOLR-16189: TestCancellableCollector thread leak

- solr/solr-ref-guide/playbook.template.yml
By default all versions of the guide are indexed in Lunr. This gets confusing when 9.1, 9.2, 9.3 etc are in, so this PR enables a config option to only include latest version in the index.
I have not tested this yet, so don't know what will happen when e.g. the 9.1 guide is in beta version, if it all search results will then link to the beta guide. That would perhaps not be what we want, though it would be for a short period only..
> Index only latest version to avoid confusing search results

- solr/solr-ref-guide/ui-src/partials/nav-explore.hbs
Add a link to PDF guides in the "old guides" section for completeness.
> Link to PDF-guides in dropdown

- solr/CHANGES.txt
- solr/solr-ref-guide/modules/configuration-guide/pages/v2-api.adoc
The community decided recently that the v2 API should be treated as
"experimental", and exempt from strict adherence to
backwards-compatibility requirements.  But there's no mention of this
designation in our ref-guide or other docs.
This commit updates the v2-api.adoc page in the ref guide to include
a caveat/warning about this, along with a corresponding note in
CHANGES.txt.
N/A
> SOLR-15780: Document v2 API as "experimental"

- solr/solr-ref-guide/playbook.template.yml
Spinoff from #77 - do not rewrite `latest` to `9_0`, but opposite, so that people are encouraged to sharing `latest` links.
Note that it will still be possible to share an explicit link to 9.0 version, that will be sure to route to the 9.0 guide. Just that the 'default' will be `latest` when working with the latest version.
This may perhaps also help in boosting the PageRank of `latest` links in search engines?
> Make 'latest' remain in URL instead of `9_0`

- dev-tools/scripts/releaseWizard.yaml
New location in gradle build versus ant build
> ReleaseWizard: Update documentation path to correct location

- solr/core/src/java/org/apache/solr/cloud/ElectionContext.java
- solr/core/src/java/org/apache/solr/cloud/LeaderElector.java
- solr/core/src/java/org/apache/solr/cloud/ShardLeaderElectionContext.java
- solr/core/src/java/org/apache/solr/cloud/ShardLeaderElectionContextBase.java
- solr/core/src/java/org/apache/solr/cloud/ZkController.java
- solr/core/src/test/org/apache/solr/cloud/LeaderElectionTest.java
Minor change - no JIRA issue
Removes declared IOException from method signatures where it could never be thrown.
> (core) Leader election declares unused IOExceptions

- solr/docker/templates/Dockerfile.body.template
- solr/docker/templates/Dockerfile.official.header.template
Also address other issues required by official images team for the 9.0.0 image.
https://issues.apache.org/jira/browse/SOLR-16196
Mirroring the changes made in: https://github.com/apache/solr-docker/pull/4
These changes are in response to feedback on: https://github.com/docker-library/official-images/pull/12406
Will wait to merge until the 9.0.0 image has been released, to capture any other changes.
> SOLR-16196: Use Solr KEYS in official Dockerfile

- dev-tools/scripts/README.md
- dev-tools/scripts/buildAndPushRelease.py
- dev-tools/scripts/releaseWizard.py
- dev-tools/scripts/releaseWizard.yaml
Also fixing a small issue in the release wizard (the `gpg_key` needed to be prepended by `gpg.` although it's the `gpg_fingerprint` now)
> Use full gpg fingerprint when building official dockerfile

- solr/CHANGES.txt
- solr/modules/sql/src/java/org/apache/solr/handler/sql/SolrFilter.java
- solr/modules/sql/src/test/org/apache/solr/handler/sql/TestSQLHandler.java
https://issues.apache.org/jira/browse/SOLR-16199
Adding some more unit tests for LIKE clauses against text analyzed fields
only invoke the {!complexphrase} parser if the LIKE clause contains multiple terms and wildcards
also correctly handle escaped wildcard characters %, _ and '
add tests for LIKE clauses against text analyzed fields vs. just strings
new tests added in this PR
> SOLR-16199: Improve handling of LIKE queries with wildcard

- solr/core/src/java/org/apache/solr/api/V2HttpCall.java
- solr/core/src/test/org/apache/solr/util/tracing/TestDistributedTracing.java
Prior to this commit, V2HttpCall populated the "operationName" of
tracing spans differently depending on whether the API was implemented
as an AnnotatedApi or not.  A special code path for AnnotatedApi's had
the operationName come primarily from the path value specified on the
@Endpoint annotation.
This works well for AnnotatedApis registered at the CoreContainer level,
but actually produces the wrong path for AnnotatedApis registered on
individual cores.
This commit removes this optimized code path, so that
per-core AnnotatedApis produce spans consistent with everything else.
Relying primarily on existing tests in TestDistributedTracing.
> SOLR-16205: Simplify v2 API span-population logic

- solr/solr-ref-guide/build.gradle
- solr/solr-ref-guide/playbook.template.yml
https://issues.apache.org/jira/browse/SOLR-16214
Remove the use of supplemental-ui, as it's no longer necessary with the lunr-extension.
For more information, see: https://gitlab.com/antora/antora-lunr-extension/-/issues/15
> SOLR-16214: Fix refGuide usage of lunr

- .lift.toml
https://issues.apache.org/jira/browse/SOLR-16210
The antora site task is failing when trying to compile solr to prepare for lift static analysis. This prevents some tools from being able to produce results.
This will skip the antora task which was failing during the lift
build process by adding a line of configuration to the .lift.toml file
There should be no noticeable changes to the behavior of solr its self, but more lift results should be available and, under the tool results panel you should see that Infer ran successfully
*Note: As a result lift may claim this pr introduces new issues :-)*
> SOLR-16210: skip Antora task for lift builds

- solr/CHANGES.txt
- solr/modules/sql/src/java/org/apache/solr/handler/sql/SolrFilter.java
- solr/modules/sql/src/test/org/apache/solr/handler/sql/TestSQLHandler.java
https://issues.apache.org/jira/browse/SOLR-16215
* Query characters are currently not escaped inside values in array udf functions 
* Escape the query characters in translation
* Unit tests added
> SOLR-16215 Escape query characters in Solr SQL Array UDF functions

- dev-docs/plugins-modules-packages.adoc
- gradle/validation/jar-checks.gradle
- solr/server/solr/configsets/_default/conf/solrconfig.xml
- solr/server/solr/configsets/sample_techproducts_configs/conf/solrconfig.xml
- solr/solr-ref-guide/modules/configuration-guide/pages/configuring-solr-xml.adoc
- solr/solr-ref-guide/modules/configuration-guide/pages/libs.adoc
- solr/solr-ref-guide/modules/configuration-guide/pages/script-update-processor.adoc
- solr/solr-ref-guide/modules/configuration-guide/pages/solr-modules.adoc
- solr/solr-ref-guide/modules/configuration-guide/pages/solr-plugins.adoc
- solr/solr-ref-guide/modules/deployment-guide/pages/backup-restore.adoc
- solr/solr-ref-guide/modules/deployment-guide/pages/distributed-tracing.adoc
- solr/solr-ref-guide/modules/deployment-guide/pages/installing-solr.adoc
- solr/solr-ref-guide/modules/deployment-guide/pages/jwt-authentication-plugin.adoc
- solr/solr-ref-guide/modules/deployment-guide/pages/solr-on-hdfs.adoc
- solr/solr-ref-guide/modules/indexing-guide/pages/indexing-with-tika.adoc
- solr/solr-ref-guide/modules/indexing-guide/pages/indexing-with-update-handlers.adoc
- solr/solr-ref-guide/modules/indexing-guide/pages/language-analysis.adoc
- solr/solr-ref-guide/modules/indexing-guide/pages/language-detection.adoc
- solr/solr-ref-guide/modules/query-guide/pages/analytics.adoc
- solr/solr-ref-guide/modules/query-guide/pages/dense-vector-search.adoc
- solr/solr-ref-guide/modules/query-guide/pages/json-facet-api.adoc
- solr/solr-ref-guide/modules/query-guide/pages/learning-to-rank.adoc
- solr/solr-ref-guide/modules/query-guide/pages/result-clustering.adoc
- solr/solr-ref-guide/modules/query-guide/pages/sql-query.adoc
- solr/solr-ref-guide/modules/upgrade-notes/pages/major-changes-in-solr-7.adoc
- solr/solr-ref-guide/modules/upgrade-notes/pages/major-changes-in-solr-9.adoc
- solr/solrj/src/java/org/apache/solr/client/solrj/io/stream/JDBCStream.java
https://issues.apache.org/jira/browse/SOLR-16228
Our docs reflect years of evolution of how we add things to solr, and don't put Solr Modules front and center.
* Be consistent about referring to Solr Modules, remove use of the word for non Solr Modules where possible.
* Make sure EVERY Module in the Ref Guide lists the name of the module using the same terminology.
* Sets us up for better documentation around where just enabling a Solr Module isn't enough, and you have to do werid stuff.
- [ X] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to …
> SOLR-16228: Audit how we refer to Solr Modules

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/update/processor/DistributedUpdateProcessor.java
- solr/core/src/test/org/apache/solr/update/TestInPlaceUpdatesStandalone.java
https://issues.apache.org/jira/browse/SOLR-16218
Fix a bug in in-place update when _failOnVersionConflicts_=false.
When sending in-place/atomic updates for a non-existent doc with __version_=1_ Solr throws 409 error even if _failOnVersionConflicts_ is set to _false_.
- Send an update request (single or batch) that includes Update in-place/atomic command of a non-existent doc.
- Set _Version_=1
- Solr will throw 409 exception with  "_Document not found for update_" message error.
Set failOnVersionConflicts=false
- Solr still throws the same error.
if _failOnVersionConflicts=false_ Solr should ignore the error silently and continue processing the rest of the commands.
Solr throws 409 exception with  "_Document not found for update_" message error.
Check in _getUpdatedDocument_ if …
> Fix bug in in-place update when failOnVersionConflicts=false

- solr/solr-ref-guide/modules/configuration-guide/pages/replica-placement-plugins.adoc
https://issues.apache.org/jira/browse/SOLR-16256
The documentation for the [AffinityPlacementFactory](https://solr.apache.org/guide/solr/latest/configuration-guide/replica-placement-plugins.html#configuration) states that the `nodeType` configuration key limits the nodes eligible for placement to only those that match one or more of the specified node types.
The code for the [AffinityPlacementConfig](https://github.com/apache/solr/blob/main/solr/core/src/java/org/apache/solr/cluster/placement/plugins/AffinityPlacementConfig.java#L97) defines the key as `collectionNodeType` instead.
Updated the documentation.
Alternatively, I could've changed the code to match the docs. I can update the PR if asked.
N/A
> SOLR-16256: Fix documented key name for AffinityPlacementConfig.collectionNodeType

- dev-tools/scripts/refguide/gen-refguide-redirects.py
https://issues.apache.org/jira/browse/SOLR-16262
If you go to an old ref guide page (e.g. https://solr.apache.org/guide/8_10/libs.html) you will not currently see a response header with `X-Robots-Tag "noindex,nofollow,noarchive"`, which tells search engines to ignore this page.
This is because (while supported) for some reason httpd doesn't like nested if statements. Oh well, we can put it into one.
This has been tested locally via docker and the solr-site.
> SOLR-16262: Fix htaccess rules for ref-guide robots tag

- solr/core/src/test/org/apache/solr/cloud/DeleteReplicaTest.java
- solr/core/src/test/org/apache/solr/cloud/TestTolerantUpdateProcessorRandomCloud.java
- solr/core/src/test/org/apache/solr/core/MockEventListener.java
- solr/core/src/test/org/apache/solr/core/TestLazyCores.java
- solr/core/src/test/org/apache/solr/search/TestBlockCollapse.java
- solr/core/src/test/org/apache/solr/search/facet/RangeFacetCloudTest.java
- solr/core/src/test/org/apache/solr/search/facet/TestJsonFacets.java
- solr/core/src/test/org/apache/solr/search/function/TestMinMaxOnMultiValuedField.java
- solr/core/src/test/org/apache/solr/update/TestInPlaceUpdatesStandalone.java
https://issues.apache.org/jira/browse/SOLR-16269
IntelliJ flagged that some methods had extra keywords on them.
Apply fixes suggested by IntelliJ
- [X …
> SOLR-16269 clean up use of final keyword

- solr/core/src/test/org/apache/solr/CursorPagingTest.java
- solr/core/src/test/org/apache/solr/DisMaxRequestHandlerTest.java
- solr/core/src/test/org/apache/solr/TestGroupingSearch.java
- solr/core/src/test/org/apache/solr/TestRandomDVFaceting.java
- solr/core/src/test/org/apache/solr/TestRandomFaceting.java
- solr/core/src/test/org/apache/solr/cloud/DistribCursorPagingTest.java
- solr/core/src/test/org/apache/solr/cloud/RestartWhileUpdatingTest.java
- solr/core/src/test/org/apache/solr/cloud/TestQueryingOnDownCollection.java
- solr/core/src/test/org/apache/solr/cloud/TestRandomFlRTGCloud.java
- solr/core/src/test/org/apache/solr/cluster/events/ClusterEventProducerTest.java
- solr/core/src/test/org/apache/solr/handler/admin/ThreadDumpHandlerTest.java
- solr/core/src/test/org/apache/solr/handler/component/TermsComponentTest.java
- solr/core/src/test/org/apache/solr/search/TestComplexPhraseQParserPlugin.java
- solr/core/src/test/org/apache/solr/search/join/TestScoreJoinQPNoScore.java
- solr/core/src/test/org/apache/solr/update/TestInPlaceUpdatesStandalone.java
- solr/core/src/test/org/apache/solr/update/UpdateLogTest.java
https://issues.apache.org/jira/browse/SOLR-16270
intellij is warning of "dangling javadocs" and "invalid @returns" tags.
Fix them!  Make some javadocs actuall inline comments and block comments.  fix the `@returns` tags.
manual
- [ X] I have developed this patch …
> SOLR-16270: address dangling javadocs

- solr/core/src/java/org/apache/solr/search/stats/StatsUtil.java
- solr/core/src/java/org/apache/solr/servlet/SolrRequestParsers.java
- solr/core/src/java/org/apache/solr/update/UpdateLog.java
- solr/core/src/test/org/apache/solr/cloud/DistributedQueueTest.java
- solr/core/src/test/org/apache/solr/cloud/OutOfBoxZkACLAndCredentialsProvidersTest.java
- solr/core/src/test/org/apache/solr/cloud/OverriddenZkACLAndCredentialsProvidersTest.java
- solr/core/src/test/org/apache/solr/cloud/SolrCLIZkUtilsTest.java
- solr/core/src/test/org/apache/solr/cloud/TestConfigSetsAPI.java
- solr/core/src/test/org/apache/solr/core/BlobRepositoryMockingTest.java
- solr/core/src/test/org/apache/solr/handler/component/ResourceSharingTestComponent.java
- solr/core/src/test/org/apache/solr/security/BasicAuthStandaloneTest.java
- solr/modules/hadoop-auth/src/test/org/apache/solr/security/hadoop/HttpParamDelegationTokenPlugin.java
- solr/test-framework/src/java/org/apache/solr/SolrTestCaseJ4.java
https://issues.apache.org/jira/browse/SOLR-16275
Use a class defined constant instead of a forName()
Fixed in tests.  Should it be done globally???
ran tests
> SOLR-16275 use standard charset instead of string forName version

- solr/CHANGES.txt
- solr/solrj/src/java/org/apache/solr/client/solrj/io/Lang.java
- solr/solrj/src/test/org/apache/solr/client/solrj/io/TestLang.java
https://issues.apache.org/jira/browse/SOLR-9661
Fixed the `withField` and `withValue` usage problem while executing the stream enabled expression.
Defined the functions for `withField` and `withValue` 
expression (withField and withValue) is tested manually.
screenshot about improvement:
> SOLR-9661 added missing operations[withField,withValue] for expression on stream operations

- solr/core/src/test/org/apache/solr/security/AuditLoggerIntegrationTest.java
```
2> SEVERE: 1 thread leaked from SUITE scope at org.apache.solr.security.AuditLoggerIntegrationTest:
2>    1) Thread[id=1232, name=auditTestCallback-918-thread-1, state=RUNNABLE, group=TGRP-AuditLoggerIntegrationTest]
2>         at java.base@17.0.3/sun.nio.ch.Net.available(Native Method)
2>         at java.base@17.0.3/sun.nio.ch.NioSocketImpl.available(NioSocketImpl.java:842)
2>         at java.base@17.0.3/sun.nio.ch.NioSocketImpl$1.available(NioSocketImpl.java:807)
2>         at java.base@17.0.3/java.net.Socket$SocketInputStream.available(Socket.java:970)
2>         at java.base@17.0.3/sun.nio.cs.StreamDecoder.inReady(StreamDecoder.java:351)
2>         at java.base@17.0.3/sun.nio.cs.StreamDecoder.implReady(StreamDecoder.java:359)
2>         at …
```
> AuditLoggerIT should wait to join thread

- solr/CHANGES.txt
- solr/webapp/web/partials/query.html
https://issues.apache.org/jira/browse/SOLR-16316
DebugQuery should display the debug.explain.structured option, which can be checked to generate debug.explain.structured=true for query parameters.
> SOLR-16316: Fix debug query clicking on the query UI does not show the debug.explain.structured option

- solr/CHANGES.txt
- solr/webapp/web/css/angular/collections.css
- solr/webapp/web/js/angular/controllers/collections.js
- solr/webapp/web/partials/collections.html
https://issues.apache.org/jira/browse/SOLR-14319
This PR is based on a patch from early 2022 by  Richard Goodman.   
Add ability to specify replica types in UI, and check if only PULL are specified.
n/a, we don't believe in testing JavaScript code ;-(.
> SOLR-14319: specify replica types in UI when creating a collection

- solr/core/src/test/org/apache/solr/handler/TestContainerPlugin.java
Seen on a local Jenkins, but not reproducible on my machine. I think this fixes it, but would like some extra eyes.
```
org.junit.ComparisonFailure: Failed on path [result, packages, mypkg[0], files[0]] of {
"responseHeader":{
"status":0,
"QTime":0},
"result":{
"znodeVersion":-1,
"packages":{}}}after attempt #1 expected:<[/myplugin/v1.jar]> but was:<[]>
at __randomizedtesting.SeedInfo.seed([93A5391677407B93:7EFBC167450AAC1A]:0)
at org.junit.Assert.assertEquals(Assert.java:117)
at org.apache.solr.filestore.TestDistribPackageStore.assertResponseValues(TestDistribPackageStore.java:296)
at org.apache.solr.handler.TestContainerPlugin.waitForAllNodesToSync(TestContainerPlugin.java:455)
at org.apache.solr.handler.TestContainerPlugin.testApiFromPackage(TestContainerPlugin.java:255)
```
> TestContainerPlugin race condition

- solr/CHANGES.txt
- solr/docker/templates/Dockerfile.body.template
https://issues.apache.org/jira/browse/SOLR-16323
This makes it easier to use with software that checks for non-root users in Docker images.
> SOLR-16323: Use the Solr User ID for the Dockerfile

- solr/modules/analysis-extras/src/test-files/log4j2.xml
- solr/modules/analytics/src/test-files/log4j2.xml
- solr/modules/extraction/src/test-files/log4j2.xml
- solr/modules/hdfs/src/test-files/log4j2.xml
- solr/modules/jaegertracer-configurator/src/test-files/log4j2.xml
- solr/modules/jwt-auth/src/test-files/log4j2.xml
- solr/modules/langid/src/test-files/log4j2.xml
- solr/modules/ltr/src/test-files/log4j2.xml
- solr/modules/scripting/src/test-files/log4j2.xml
- solr/prometheus-exporter/src/test-files/log4j2.xml
When running tests in most of the modules, we don't get any log output because there was no logging configuration. I wonder if we could have some kind of gradle rule to validate that we have a log4j2.xml in every test-files folder?
> Add missing test log4j2.xml files

- solr/core/src/test/org/apache/solr/cloud/overseer/ZkStateReaderTest.java
https://issues.apache.org/jira/browse/SOLR-16257
Test failures due to NPE: https://lists.apache.org/list?builds@solr.apache.org:lte=1M:FAILED:%20%20org.apache.solr.cloud.overseer.ZkStateReaderTest.testNodeVersion
This was introduced in https://github.com/apache/solr/pull/909
> SOLR-16257: Fix ZkStateReaderTest NPE when checking node version

- solr/core/src/java/org/apache/solr/core/CorePropertiesLocator.java
https://issues.apache.org/jira/browse/SOLR-16349
I'm not sure if a real production scenario would prefer a logged exception here, but the behavior is unchanged.
> SOLR-16349 check for properties file before attempt to open

- gradle/globals.gradle
- gradle/validation/git-status.gradle
- gradle/validation/rat-sources.gradle
- gradle/validation/validate-source-patterns.gradle
I'd like to be able to still run these checks and report on them, but also be able to prevent them from failing the build. Useful in CI environment where I will have the output and also want to make sure other checks get run instead of failing fast here.
This pattern was modeled on the `validation.git.failOnModified` option.
> Allow skipping failure for RAT and Source Patterns

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/update/DocumentBuilder.java
https://issues.apache.org/jira/browse/SOLR-16362
> SOLR-16362: Logs: Truncate field values in logs if a doc fails to index

- solr/core/src/test/org/apache/solr/cloud/TestLeaderElectionZkExpiry.java
https://issues.apache.org/jira/browse/SOLR-16046
* Move `Thread killer` to an executor just to make sure it gets cleaned up
* Ensure `SolrZkClient zc = new SolrZkClient(server.getZkAddress(), LeaderElectionTest.TIMEOUT))` is closed with try w/ resources
* reorganize some of the try/finally to ensure things are closed in the reverse order of when they were opened
> SOLR-16046: Thread leak in TestLeaderElectionZkExpiry

- .gitignore
This file has recently started popping up as changed. I think it should be ignored, as it causes e.g. `gradlew check -x tests` to fail with "not clean checkout"
> Add the .gradletasknamecache file to .gitignore

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/MoreLikeThisHandler.java
- solr/core/src/test/org/apache/solr/handler/MoreLikeThisHandlerTest.java
* SOLR-7883: /mlt handler to support facets
Cherrypick.
> SOLR-7883: /mlt handler to support facets (#1010)

- solr/solrj/build.gradle
**On 9.x,** Solrj-Zookeeper should be "opt-out", thus a user needs to opt-out if they don't want it.  Don't change main (opt-in).
I looked at the upgrade docs for 9.1 in `solr-upgrade-notes.adoc` and I thought maybe just leave it be.  What it says isn't wrong -- yes you will need this JAR if you use this functionality.  It's unspecified wether this happens automatically or not based on Maven POM (for those that use it which is most folks for sure).  In some sense it's a detail.
In main, I can add a note for the 10.x upgrade to mention this, where it's more impactful / noticeable.
> SOLR-15342 Solrj-Zookeeper: opt-out on 9x

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/component/FacetComponent.java
- solr/core/src/java/org/apache/solr/response/SolrQueryResponse.java
https://issues.apache.org/jira/browse/SOLR-16417
* Extracts method from already implemented logic to apply error checking for refine facets and distrib intervals. 
* Use constants instead of strings in common cases.
I didn't add a test for this since I couldn't get it to reproduce easily. I know its a condition of timeAllowed for what I saw this error happen. The issue is that timeAllowed isn't easy to insert into the running query at a predetermined interval. Most of the time this just ends up breaking out at some random time in the query.
> SOLR-16417: NPE if facet query hits timeout or exception

- solr/core/src/java/org/apache/solr/search/ExtendedDismaxQParser.java
Whilst `sed` doing the #1016 changes for SOLR-16318 some comments in `IndexSchema` cropped up and a similar approach can be used in `ExtendedDismaxQParser.UserFields` also.
No JIRA ticket and `solr/CHANGES.txt` entry required in my opinion.
https://github.com/apache/solr/blob/releases/solr/9.0.0/solr/core/src/java/org/apache/solr/schema/IndexSchema.java#L765-L767
```
// Avoid creating the array twice by converting to an array first and using Arrays.sort(),
// rather than Collections.sort() then converting to an array, since Collections.sort()
// copies to an array first, then sets each collection member from the array.
```
> NO JIRA: reduce array allocation in ExtendedDismaxQParser.UserFields

- solr/core/src/java/org/apache/solr/handler/component/RealTimeGetComponent.java
- solr/core/src/java/org/apache/solr/update/processor/DocBasedVersionConstraintsProcessor.java
Remove methods that were deprecated in Solr 8.8 as per https://issues.apache.org/jira/browse/SOLR-14923 tags.
No JIRA ticket or `solr/CHANGES.txt` entry required for this I think.
> NO JIRA: remove deprecated RealTimeGetComponent methods

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/component/DebugComponent.java
- solr/core/src/java/org/apache/solr/handler/component/ExpandComponent.java
- solr/core/src/java/org/apache/solr/handler/component/FacetComponent.java
- solr/core/src/java/org/apache/solr/handler/component/HighlightComponent.java
- solr/core/src/java/org/apache/solr/handler/component/QueryComponent.java
- solr/core/src/java/org/apache/solr/handler/component/SpellCheckComponent.java
- solr/core/src/java/org/apache/solr/handler/component/StatsComponent.java
- solr/core/src/java/org/apache/solr/handler/component/SuggestComponent.java
- solr/core/src/java/org/apache/solr/handler/component/TermVectorComponent.java
- solr/core/src/java/org/apache/solr/handler/component/TermsComponent.java
- solr/core/src/java/org/apache/solr/search/grouping/distributed/responseprocessor/SearchGroupShardResponseProcessor.java
- solr/core/src/java/org/apache/solr/search/grouping/distributed/responseprocessor/StoredFieldsShardResponseProcessor.java
- solr/core/src/java/org/apache/solr/search/grouping/distributed/responseprocessor/TopGroupsShardResponseProcessor.java
- solr/core/src/java/org/apache/solr/util/SolrResponseUtil.java
- solr/core/src/test/org/apache/solr/search/RankQueryTestPlugin.java
https://issues.apache.org/jira/browse/SOLR-16418
During a query exception or timeout, there can be an NPE getting the firstPhase results. This extracts a method to deal with it. The commit also does some minor cleanup at the same time to avoid unnecessary casts.
I didn't add a test for this since I couldn't get it to reproduce easily. I know its a condition of timeAllowed for what I saw this error happen. The issue is that timeAllowed isn't easy to insert into the running query at a predetermined interval. Most of the time this just ends up breaking out at some random time in the query.
> SOLR-16418: Introduce SolrResponseUtil to handle NPE during query timeout or exception when parsing SolrResponse

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cloud/ZkController.java
- solr/solr-ref-guide/modules/upgrade-notes/pages/major-changes-in-solr-10.adoc
- solr/solr-ref-guide/modules/upgrade-notes/pages/major-changes-in-solr-9.adoc
- solr/solr-ref-guide/modules/upgrade-notes/pages/solr-upgrade-notes.adoc
See https://issues.apache.org/jira/browse/SOLR-15730?focusedCommentId=17603208&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17603208
Added "Major changes in Solr 10".
Moved the "Upgrading 9.1" section to the page it should be on.
Someone please do a sanity check on the pages by rendering them locally.  I believe this is via `gradlew buildLocalSite`.  I can't get major-changes-in-solr-10.adoc to show up in the navigation; it's an orphaned page.
> SOLR-15730: Document SolrJ opt-in for 10x

- solr/CHANGES.txt
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/Http2SolrClient.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/Http2SolrClientTest.java
Adding the option to Http2SolrClient. For the Cloud client, users need to use `withInternalClientBuilder` and provide a builder, similar to how they use for setting the other timeouts, authentication, etc.
Will update CHANGES once this gets reviewed, but my plan is to merge into 9.x
> SOLR-16435: Add Request timeout to Http2SolrClient

- solr/CHANGES.txt
- solr/modules/ltr/src/java/org/apache/solr/ltr/feature/FieldLengthFeature.java
- solr/modules/ltr/src/test-files/solr/collection1/conf/schema.xml
- solr/modules/ltr/src/test/org/apache/solr/ltr/feature/TestFeatureLogging.java
- solr/modules/ltr/src/test/org/apache/solr/ltr/feature/TestFieldLengthFeature.java
This commit removes unnecessary check for `omitNorms` from `FieldLengthFeatureScorer` that otherwise causes `NullPointerException` in `FieldLengthFeature` for non-stored or missing fields.
https://issues.apache.org/jira/browse/SOLR-13219
I recently encountered a problem with using `FieldLengthFeature` with non-stored fields where feature extraction/LTR reranking would result in `NullPointerException`. I checked the `FieldLengthFeature` docs and briefly inspected the implementation to check if using this feature really requires storing fields. According to my expectations it turned out to not be required - the only required information are norms, that my field has enabled.
I searched Solr Jira and found [SOLR-13219](https://issues.apache.org/jira/browse/SOLR-13219) that seemed very similar …
> SOLR-13219: Fix NPE in FieldLengthFeature with non-stored/missing fields

- solr/core/src/java/org/apache/solr/handler/admin/CollectionsHandler.java
https://issues.apache.org/jira/browse/SOLR-16392
CollectionsHandler.handleRequestBody had an unnecessary switch-case statement that cluttered thing up, instead of leaning on the CollectionsOperation enum already present for this purpose.
This PR removes the switch-case in favor of using CollectionOperation as was done previously.  Credit for Bruno R for the suggestion.
No new tests added for this minor refactor.  Existing tests continue to pass.
> SOLR-16392: Minor CollectionsHandler cleanup

- solr/CHANGES.txt
- solr/bin/solr
- solr/docker/templates/Dockerfile.body.template
- solr/server/etc/security.policy
https://issues.apache.org/jira/browse/SOLR-16457
solr.cmd does NOT have the same issue since it explicitly checks the case of empty SOLR_DATA_HOME before adding it. https://github.com/apache/solr/blob/main/solr/bin/solr.cmd#L1342
This was found while looking at https://github.com/apache/solr/pull/1044
> SOLR-16457: solr.data.home should not be set to empty string

- .lift.toml
See https://github.com/apache/solr/pull/1068#issuecomment-1279338815 and other recent PRs where Lift is repeatedly saying:
```
314 God Classes were detected by Lift in this project. [Visit the Lift web console](https://lift.sonatype.com/results/github.com/apache/solr/01GF5VM3TQ2XTE65VJSF5B3J4S?tab=technical-debt&utm_source=github.com&utm_campaign=lift-comment&utm_content=apache%20solr) for more details.
```
Disabled using .lift.toml based on https://help.sonatype.com/lift/prioritizing-technical-debt#PrioritizingTechnicalDebt-CanItweakthistool?
> Disable lift god classes

- solr/core/src/test/org/apache/solr/util/TestSolrVersion.java
https://issues.apache.org/jira/browse/SOLR-16467
Short term workaround in tests until https://github.com/semver4j/semver4j/pull/85 is merged and can upgrade semver4j version.
> SOLR-16467: Add check for working locale in TestSolrVersion

- build.gradle
- gradle/validation/precommit.gradle
- gradle/validation/solr.ref-guide-files.gradle
- solr/solr-ref-guide/antora.yml
Also _9.1-->9.3 for lucene-javadocs in solr-ref-guide/antora.yml_ to match `branch_9x` and `branch_9_1` commits.
> NO JIRA: start validateRefGuideFiles gradle task

- solr/CHANGES.txt
- solr/bin/solr
- solr/bin/solr.cmd
https://issues.apache.org/jira/browse/SOLR-16463
Hardcode the JVM flag in `bin/solr[.cmd]` from Solr 9.1, to workaround [https://bugs.openjdk.org/browse/JDK-8285835](https://bugs.openjdk.org/browse/JDK-8285835)
> SOLR-16463: Workaround for serious crash on JDK17+

- solr/docker/templates/Dockerfile.body.template
- solr/docker/templates/Dockerfile.official.header.template
https://issues.apache.org/jira/browse/SOLR-16484
Small improvement to shave off some Mb
> SOLR-16484 Remove gpg from image, slimming it down some Mb

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/update/DirectUpdateHandler2.java
- solr/core/src/test/org/apache/solr/update/TestUpdate.java
https://issues.apache.org/jira/browse/SOLR-16363
Based on IntelliJ analysis, this is the only place in Solr code base where String.format has String concatenation. So this should be the only place this is a problem.
> SOLR-16363: DirectUpdateHandler2 should not throw UnknownFormatConversionException

- dev-docs/lucene-upgrade.md
https://issues.apache.org/jira/browse/SOLR-16442
as per https://github.com/apache/solr/pull/1056/files#r999187407
> SOLR-16442: simplify two lucene-upgrade.md steps

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/update/DocumentBuilder.java
- solr/core/src/test-files/solr/collection1/conf/schema.xml
- solr/core/src/test/org/apache/solr/update/DocumentBuilderTest.java
https://issues.apache.org/jira/browse/SOLR-16502
> SOLR-16502: Multiple CopyField should not limit to first maxChars

- solr/solr-ref-guide/modules/deployment-guide/pages/solrcloud-shards-indexing.adoc
A full URL is shown in the docs, instead of a clickable word.
Fix the Zookeeper docs URL link so that it will not get shown
> Fix the Zookeeper docs URL link so that it will not get shown

- buildSrc/src/main/java/org/apache/lucene/gradle/WrapperDownloader.java
- gradlew
- gradlew.bat
Gradle will give a very confusing error using the
wrong JDK, let's make it absolutely clear.
Port the following to Solr with minor adjustments (minimum JDK 11)
* https://github.com/apache/lucene/pull/819
* https://github.com/apache/lucene/pull/11889
Co-authored-by: Dawid Weiss <dawid.weiss@carrotsearch.com>
Co-authored-by: Robert Muir <rmuir@apache.org>
> Gradle should fail clearly on too-new JDK

- solr/core/src/java/org/apache/solr/core/CoreContainer.java
- solr/core/src/java/org/apache/solr/security/PKIAuthenticationPlugin.java
- solr/core/src/java/org/apache/solr/security/PublicKeyAPI.java
- solr/core/src/java/org/apache/solr/security/PublicKeyHandler.java
- solr/core/src/java/org/apache/solr/security/SolrNodeKeyPair.java
- solr/core/src/test/org/apache/solr/security/PublicKeyAPITest.java
https://issues.apache.org/jira/browse/SOLR-16491
The /admin/info/key API used to retrieve a node's public key has no v2 equivalent.
This PR adds a v2 equivalent using the JAX-RS framework, the new endpoint is `GET /api/node/key`.  In implementing this, some shared logic around key-creation was refactored into a separate class, `SolrNodeKeyPair`, which is created by CoreContainer and made injectable to the JAX-RS framework to that a single instance (i.e. same key) can be used by both the existing v1 RH, and the new v2 binding.
A new simple unit test in `PublicKeyAPITest`; existing tests for  pki-auth and the PublicKeyHandler continue to pass.
> SOLR-16491: Create v2 equivalent for /admin/info/key

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/index/SlowCompositeReaderWrapper.java
https://issues.apache.org/jira/browse/SOLR-16515
The `SlowCompositeReaderWrapper` uses synchronized read and write access to its internal `cachedOrdMaps`. By using a `ConcurrentHashMap` instead of a `LinkedHashMap` as the  underlying `cachedOrdMaps` implementation and the `ConcurrentHashMap#computeIfAbsent` method to compute cache values, we were able to reduce locking contention significantly.
Under heavy load we discovered that application halts inside of Solr are becoming a serious problem in high traffic environments. Using Java Flight Recordings we discovered high accumulated applications halts on the `cachedOrdMaps` in `SlowCompositeReaderWrapper`. Without this fix we were able to utilize our machines only up to 25% cpu usage. With the fix applied, a utilization up to 80% is …
> [SOLR-16515] Remove synchronized access to cachedOrdMaps in SlowCompositeReaderWrapper

- build.gradle
Was unintentionally added in c23ecd6.
A previous commit (c23ecd6) inadvertently added `sourceCompatibility` and `targetCompatibility` settings to build.gradle.  These aren't desired and need to be removed.
This PR deletes them from the file.
Manual testing of the build and IDE integration.
> Remove 'compatibility' settings from gradle

- solr/CHANGES.txt
- solr/bin/solr
- solr/docker/templates/Dockerfile.body.template
- solr/server/etc/security.policy
https://issues.apache.org/jira/browse/SOLR-16457
This reverts commit e9100b9383a1f7e85285b381f5ee3eefda7814b4.
> Revert "SOLR-16457: solr.data.home should not be set to empty string in bin/solr

- solr/core/src/java/org/apache/solr/update/processor/DistributedUpdateProcessor.java
https://issues.apache.org/jira/browse/SOLR-13684
failOnVersionConflicts is a parameter used to fail an entire batch of updates if there is a version conflict of one or more documents in the batch: https://solr.apache.org/guide/solr/latest/indexing-guide/partial-document-updates.html#optimistic-concurrency. This is a parameter that should be passed on to the leader in the case of a distributed update.
This allows this parameter to be included in the whitelist of params as part of the DistributedUpdateProcessor.
N/A
> failOnVersionConflicts param should be added to the DistributedUpdateProcessor whitelist params

- solr/core/build.gradle
- solr/server/build.gradle
- solr/webapp/build.gradle
https://issues.apache.org/jira/browse/SOLR-15955
This fixes a regression caused by the Jetty 10 upgrade.
Note: This does not make the server/lib/, server/lib/ext/ and WEB-INF/lib situation less confusing. I will introduce something separate to make that work out of the box going forward.
> SOLR-15955: Put slf4j-api jar in lib/ext/

- build.gradle
- gradle/generation/local-settings.gradle
- gradle/hacks/turbocharge-jvm-opts.gradle
- gradle/testing/defaults-tests.gradle
- help/localSettings.txt
Ports over https://github.com/apache/lucene/pull/11927 and https://github.com/apache/lucene/pull/11937 to Solr
* pass jvm args to javac  #11925
* Update net.ltgt.errorprone to the latest version so that jvm args are not overwritten, add -XX:+PrintFlagsFinal for debugging
* speed up the pure javac case too
It does not help to fork additional VMs (although error-prone will do this since it messes with bootstrap classpath), so we avoid forking.
Instead it is best to tune org.gradle.jvmargs.
* use the flags consistently everywhere (tests and doc)
Co-authored-by: Robert Muir <rmuir@apache.org>
> speed up javac and error-prone tasks by using less resources (#11927)

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/search/BitDocSet.java
- solr/core/src/java/org/apache/solr/search/MutableBitDocSet.java
- solr/core/src/java/org/apache/solr/search/SolrIndexSearcher.java
Backport to 9x of https://issues.apache.org/jira/browse/SOLR-16555
> SOLR-16555: SolrIndexSearcher - FilterCache intersections/andNot should not clone bitsets repeatedly (#1184)

- .github/workflows/gradle-precommit.yml
https://issues.apache.org/jira/browse/SOLR-16516
This change modifies the Github Actions to execute on any PR opened against any branch, including branches with a `/` in the branch name. This can be useful for organizations that have forked the Solr repo and want to run checks against additional branches.
This is a simple change to the pattern used to be `**` instead of `*` to include branches with slashes. More info here: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet.
N/A
> Modifying github actions to run on all branches including ones with slashes

- solr/benchmark/build.gradle
- solr/benchmark/log4j2-bench.xml
- solr/core/src/java/org/apache/solr/core/NodeConfig.java
- solr/core/src/test/org/apache/solr/core/TestCoreContainer.java
Contains two commits that are related to fixing the benchmark stuff.
* https://issues.apache.org/jira/browse/SOLR-16553
* https://issues.apache.org/jira/browse/SOLR-16559
> SOLR-16553 and SOLR-16559

- gradle/generation/local-settings.gradle
Ports https://github.com/apache/lucene/pull/11936 over to Solr. I've been testing this the past week or so and haven't seen any issues.
You need to clear `gradle.properties` in the Solr directory and regenerate with `./gradlew localSettings` (or let the build regenerate it for you next time.
> Lower gradle heap: 3GB is unnecessary (#11936)

- solr/modules/hadoop-auth/build.gradle
This dependency is not compileTimeOnly. I think this was only done because of the weird old way of handling jetty dependencies.
After https://issues.apache.org/jira/browse/SOLR-16158 this should no longer be an issue.
> SOLR-15955: Fix dependency in hadoop-auth

- solr/core/src/java/org/apache/solr/handler/component/ExpandComponent.java
- solr/core/src/java/org/apache/solr/search/Grouping.java
- solr/core/src/java/org/apache/solr/search/QueryCommand.java
- solr/core/src/java/org/apache/solr/search/SolrIndexSearcher.java
- solr/core/src/java/org/apache/solr/search/grouping/CommandHandler.java
- solr/core/src/java/org/apache/solr/util/SolrPluginUtils.java
- solr/core/src/test/org/apache/solr/highlight/HighlighterTest.java
- solr/core/src/test/org/apache/solr/search/SolrIndexSearcherTest.java
1. QueryCommand: remove unused "filter"
2. SolrIndexSearcher.getProcessedFilter: remove unused setFilter param
Background:
While looking at SolrIndexSearcher.getProcessedFilter (on multiple occassions), it seemed to me the setFilter param was needless because a caller could simply provide the DocSet as a Query via DocSet.makeQuery (new in Solr 9).  Then I realized that nobody actually passes setFilter any way so I simply removed it, leading me to remove QueryCommand.filter in-kind.  Maybe it was used a long time ago; this is old code.
Not sure this needs a JIRA; it's a refactoring.  I'm thinking of only doing this in Solr 10 for back-compat sake.
> Refactor: remove unused "filter" in QueryCommand & getProcessedFilter

- solr/solrj/src/java/org/apache/solr/client/solrj/impl/ConcurrentUpdateSolrClient.java
https://issues.apache.org/jira/browse/SOLR-8975
Followup to fix ConnectionReuseTest.testConnectionReuse
> SOLR-8975: Ensure poll time default of 250 is set on builder

- build.gradle
- gradle/validation/owasp-dependency-check.gradle
- gradle/validation/owasp-dependency-check/exclusions.xml
- solr/CHANGES.txt
https://issues.apache.org/jira/browse/SOLR-16581
Dependency Check 7.4.0 added a Jenkins format (https://github.com/jeremylong/DependencyCheck/releases/tag/v7.4.0) which makes it better than the regular HTML output for the ci jobs (ie: https://ci-builds.apache.org/job/Solr/job/OWASP-main/).
> SOLR-16581: Upgrade OWASP dependency check to 7.4.1

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/search/SolrDocumentFetcher.java
- solr/core/src/test/org/apache/solr/search/LargeFieldTest.java
https://issues.apache.org/jira/browse/SOLR-16589
> SOLR-16589: Large fields with large=true can be truncated when using unicode values

- solr/core/src/java/org/apache/solr/core/SolrCore.java
https://issues.apache.org/jira/browse/SOLR-16582
Logs can somethings be a bit too noisy on SolrCore#execute which prints info on each response.
In our usage, `/get` and `/replication` are too verbose that we want to skip logging those 2 while keeping response logging for rest of the requests.
It would be nice to add a "marker" with the path of the request so that user can tune logging behavior per request handler (path).
If the path is available in `SolrCore#execute`, then log the response with the path as marker.
Logging for such can then be configured such as
```
<Logger name="org.apache.solr.core.SolrCore.Request" level="info">
<Filters>
<MarkerFilter marker="/get" onMatch="DENY" onMismatch="NEUTRAL"/>
<MarkerFilter marker="/replication" onMatch="DENY" onMismatch="NEUTRAL"/>
</Filters> …
```
> SOLR-16582: Allow configuration of solrcore response logging by path

- solr/core/src/test/org/apache/solr/cloud/ReindexCollectionTest.java
- solr/core/src/test/org/apache/solr/cloud/SystemCollectionCompatTest.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/CloudHttp2SolrClientTest.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/CloudSolrClientCacheTest.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/CloudSolrClientTest.java
- solr/test-framework/src/java/org/apache/solr/SolrTestCaseJ4.java
Named similar to the RandomizingCloudHttp2SolrClientBuilder.
https://issues.apache.org/jira/browse/SOLR-16583
Seeing CloudSolrClientBuilder everywhere in tests is very confusing when you discover that it's actually a special subvariant that randomizies settings and it only used in tests.   
Rename CloudSolrClientBuilder in SolrTestCaseJ4 to RandomizingCloudSolrClientBuilder
> SOLR-16583: Rename CloudSolrClientBuilder in SolrTestCaseJ4 to RandomizingCloudSolrClientBuilder

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/update/UpdateShardHandler.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/ConcurrentUpdateSolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/DelegationTokenHttpSolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/Http2SolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/HttpSolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/LBHttp2SolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/LBHttpSolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/LBSolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/SolrClientBuilder.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/BasicHttpSolrClientTest.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/Http2SolrClientTest.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/LBHttp2SolrClientTest.java
https://issues.apache.org/jira/browse/SOLR-10452
setQueryParams should be deprecated in favor of SolrClientBuilder methods.
I moved the the setQueryParams over for the Http2SolrClient, it already had been done for HttpSolrClient.   I noticed we have a `addQueryParams` method, which I marked deprecated and we shouldn't use, as that goes against the idea of a Solr Client being immutable.   
One area I tried to fix and gave up on was the `DelegationTokenHttpSolrClient`, I couldn't quite figure out what to do there, would love a suggestion or a fix ;-)
> SOLR-10452: setQueryParams should be deprecated in favor of SolrClientBuilder methods

- solr/CHANGES.txt
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/CloudHttp2SolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/CloudSolrClient.java
https://issues.apache.org/jira/browse/SOLR-10470
setParallelCacheRefreshes should be deprecated in favor of SolrClientBuilder methods
> SOLR-10470: setParallelCacheRefreshes should be deprecated in favor of SolrClientBuilder methods

- solr/modules/hadoop-auth/src/test/org/apache/solr/security/hadoop/KerberosTestServices.java
https://issues.apache.org/jira/browse/SOLR-16607
> SOLR-16607: org.apache.solr.security.hadoop.LocaleTest.testWithKdc needs to handle locales raj, bho, bgc added in JDK 20

- solr/solr-ref-guide/modules/configuration-guide/pages/package-manager-internals.adoc
https://issues.apache.org/jira/browse/SOLR-16602
While trying to understand how PackageManager api works, I went through this page.
Fix some of the examples and make it easier to use the ref guide "copy" command.
manually built
> SOLR-16602: tweaks to package manager docs to make following along easier

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/MoreLikeThisHandler.java
- solr/core/src/java/org/apache/solr/handler/component/QueryComponent.java
- solr/core/src/java/org/apache/solr/handler/component/RealTimeGetComponent.java
- solr/core/src/java/org/apache/solr/search/QueryUtils.java
- solr/core/src/java/org/apache/solr/search/neural/KnnQParser.java
- solr/core/src/test/org/apache/solr/search/neural/KnnQParserTest.java
- solr/modules/analytics/src/java/org/apache/solr/handler/AnalyticsHandler.java
- solr/solr-ref-guide/modules/query-guide/pages/dense-vector-search.adoc
https://issues.apache.org/jira/browse/SOLR-16567
Frange and in general post filters were abandoned for KNN search in favour of pre-filters.
This PR brings back supports for post-filters when they have a cost>0 (in line with the rest of Solr)
tests have been added
- [ X] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [ …
> SOLR-16567: KnnQueryParser support for both pre-filters and post-filter

- solr/modules/hadoop-auth/src/test/org/apache/solr/security/hadoop/KerberosTestServices.java
- solr/modules/hdfs/src/test/org/apache/hadoop/util/PlatformName.java
- solr/solrj/src/java/org/apache/solr/client/solrj/util/Constants.java
https://issues.apache.org/jira/browse/SOLR-16612
I'm looking into the Hadoop integration test failures on openj9 that are related to https://lists.apache.org/thread/b3053cvc2jqw768jrrw8npxkow4k70r6
I know Hadoop had some IBM java checks that look to be not necessary anymore after SOME change in IBM. I made an initial check change here, but not sure its correct.
@uschindler is there a good way to determine old IBM java vs new IBM Java based on openjdk?
> SOLR-16612: fix-hadoop-openj9

- solr/core/src/java/org/apache/solr/cloud/api/collections/MigrateCmd.java
- solr/core/src/java/org/apache/solr/handler/admin/SplitOp.java
- solr/core/src/java/org/apache/solr/update/SolrIndexSplitter.java
- solr/core/src/java/org/apache/solr/update/processor/DistributedZkUpdateProcessor.java
- solr/core/src/test/org/apache/solr/handler/admin/SplitHandlerTest.java
- solr/solrj/src/java/org/apache/solr/common/cloud/CompositeIdRouter.java
- solr/solrj/src/java/org/apache/solr/common/cloud/DocRouter.java
DocRouter is an abstraction with 3 implementations; it isn't pluggable.  Years ago at work, I hacked a custom subclass of CompositeIdRouter.  In the process I found a number of spots, especially with splits, that were making assumptions of how CompositeIdRouter parsed IDs.  So here I'm strengthening the separation of concerns so that the split code can do its job, delegating to the DocRouter (specifically a CompositeIdRouter) on how to parse doc IDs.  It also makes CompositeIdRouter more extendable, but I am not truly making the DocRouter choice pluggable because perhaps it's too advanced and would take more work today to do that cleanly & tested.
This is an internal refactoring; not too big, so I was thinking no JIRA.
> DocRouter: strengthen abstraction

- solr/CHANGES.txt
- solr/modules/jwt-auth/src/java/org/apache/solr/security/jwt/JWTAuthPlugin.java
- solr/modules/jwt-auth/src/test/org/apache/solr/security/jwt/JWTAuthPluginTest.java
- solr/solr-ref-guide/modules/deployment-guide/pages/jwt-authentication-plugin.adoc
https://issues.apache.org/jira/browse/SOLR-16616
A concrete use case for this is in a Kubernetes environment where a configMap exists with two `.cer` files, one for the SSL certificate of KeyCloak, and another file with SSL cert for the private CA. Currently we have been copying and concatenating the string content of those files into the `trustedCerts` configuration key. But that is cumbersome when you have several k8s clusters with different certificates for each.
With this feature, we'll supply a both files as this
```json
"trustedCertsFile": ["/path/to/hostCertFile.pem", "/path/to/caCertFile.pem"]
```
I considered adding a new parameter `trustedCertsFiles`, but went for accepting list on the existing one.
> SOLR-16616: JWTAuthPlugin: Read trusted X509 certificates from multi files

- dev-tools/scripts/releaseWizard.py
The release wizard detection of gpg keys fails in the event that the main key is offline (which causes the script output for `gpg --list-secret-keys` to display slightly differently). This PR introduces a minor tweak to parsing only, to enable gpg key detection to work in such cases.
The relevant section (full flag description from `man gpg` below) is `A # after the initial tags sec or ssb means that the secret key or subkey is currently not usable.`
```
--list-secret-keys
-K     List the specified secret keys.  If no keys are specified, then
all known secret keys are listed.  A # after the initial tags
sec or ssb means that the secret key or subkey is currently not
usable.  We also say that this key has been taken offline (for
example, a primary key can be taken offline by exporting the …
```
> update `releaseWizard.py` to support offline gpg key

- dev-tools/scripts/buildAndPushRelease.py
- dev-tools/scripts/releaseWizard.yaml
- gradle/java/jar-manifest.gradle
The purpose of this PR is to pass the RM's apache id into the `assembleRelease` task, for a more consistent `Implementation-Version` property in MANIFEST.MF in built jars.
> releaseWizard: allow explicitly setting manifest.mf userid (e.g., to apache id)

- solr/solr-ref-guide/modules/configuration-guide/pages/replica-placement-plugins.adoc
Minor change: according to the code (and I remember testing it, too), the default is 20GB, not 10: https://github.com/apache/solr/blob/c99af207c761ec34812ef1cc3054eb2804b7448b/solr/core/src/java/org/apache/solr/cluster/placement/plugins/AffinityPlacementConfig.java#L28
> Correcting default minimalFreeDiskGB

- solr/CHANGES.txt
- solr/webapp/web/js/angular/controllers/index.js
- solr/webapp/web/partials/index.html
https://issues.apache.org/jira/browse/SOLR-14336
This impl will simply parse release date from solr-impl string, count number of days old, and warn in Admin UI dashboard if older than a year. No warning in logs.
> SOLR-14336 Warn users running old version of Solr

- solr/CHANGES.txt
- solr/webapp/web/js/angular/controllers/security.js
https://issues.apache.org/jira/browse/SOLR-16621
Always grant access to a permission that has has the wildcard `"*"` role, no matter what roles user has.
Note, this is not the same as not requiring authentication for the permission, `"roles": null`. It means that the permission needs an authenticated user, but any role will do.
Also, this is just UI stuff so will not modify actual permissions on the API level, but will align role checking logic so it matches that of the backend.
To test:
1. Start Solr and enable security
```bash
./gradlew dev
cd solr/packaging/build/dev/
bin/solr start -c
bin/solr auth enable -credentials solr:solr -blockUnknown true
```
2. Log in to Admin UI with 'solr' and 'solr': http://localhost:8983/solr/#/~security
3. Edit the permissions 'security-edit' and …
> SOLR-16621: Admin UI fails to grant user permissions with wildcard role

- solr/server/solr/configsets/_default/conf/solrconfig.xml
Fixing a small typo in one of the comments in solrconfig.xml
> fix typo in comment

- solr/CHANGES.txt
- solr/test-framework/src/java/org/apache/solr/SolrTestCaseJ4.java
- solr/test-framework/src/java/org/apache/solr/cloud/MiniSolrCloudCluster.java
By resolving the full path of the pre-generated crypto keys in `MiniSolrCloudCluster` we make sure it also works for third party projects testing using Solr test framework
> SOLR-16635: Resolve crypto keys file path in MiniSolrCloudCluster

- solr/webapp/web/js/angular/controllers/security.js
- solr/webapp/web/js/angular/permissions.js
https://issues.apache.org/jira/browse/SOLR-16621
Re-using this global function, we can simplify the js code of the dashboard. Note that the backend `/admin/info/system` already returns an array of user's permissions, not roles.
During testing I found that the app.js `isPermitted()` function did not support the `all` permission, so that's why I added that as well.
The `roleMatch()` function that I patched in #1294 is still in use one other place in `security.js`, in the `onPermFilterOptionChanged()` function. Not sure if we can get rid of that too here?
> SOLR-16621 Use $scope.isPermitted("my-permissiong") in security dash

- .github/workflows/tests-via-crave.yml
Tests running through crave were using dirty workspace causing frequent patching failures
Add --clean flag to crave tests. It will always use a clean workspace
> Make tests through crave always use clean workspace

- solr/solr-ref-guide/modules/deployment-guide/pages/backup-restore.adoc
Configuration keys were mixed up making it hard to find them in the documentation and even harder to debug timeouts on backup.
Fixed the documentation.
n/a
> Fix broken documentation for gcs-backups

- solr/core/src/java/org/apache/solr/jersey/JerseyApplications.java
https://issues.apache.org/jira/browse/SOLR-16531
Jersey has several optional features that we don't need or use.  Disabling these keeps our use of Jersey as lightweight as possible.
These features are disabled by setting particular configuration props in each Jersey 'application' that gets created.
Manually tested via log-message inspection.  Manual validation of the improved Jersey app-startup performance.  Existing tests continue to pass.
> SOLR-16531: Disable unused Jersey features

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/MoreLikeThisHandler.java
- solr/core/src/test/org/apache/solr/handler/MoreLikeThisHandlerTest.java
Co-authored-by: Renato Haeberli <>
Cherry-pick #1305
> SOLR-16648: NullPointerException when excluding facets in More Like This Handler

- solr/test-framework/src/java/org/apache/solr/util/SolrClientTestRule.java
https://issues.apache.org/jira/browse/SOLR-16573
Fixing an oversight of mine in the configSet reference that can be a path and thus might be platform specific.
Later I want to move this sort of logic to where the value is interpreted (FileSystemConfigSetService) instead of being in the test utility.
> SOLR-16573: Fix test Windows path separator

- solr/bin/solr
- solr/bin/solr.cmd
- solr/server/etc/security.policy
I.e. typically til will allow /opt/solr/... in addition to /opt/solr-X.Y.Z/...
I file this PR on https://issues.apache.org/jira/browse/SOLR-16457 since it is related and still un-released.
> SOLR-16457 Add symbolic link version of solr.install.dir to security.policy

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/component/HttpShardHandlerFactory.java
- solr/core/src/java/org/apache/solr/update/StreamingSolrClients.java
- solr/core/src/java/org/apache/solr/update/UpdateShardHandler.java
- solr/core/src/test/org/apache/solr/update/MockingHttp2SolrClient.java
- solr/prometheus-exporter/src/java/org/apache/solr/prometheus/exporter/SolrClientFactory.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/CloudHttp2SolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/CloudLegacySolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/CloudSolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/ConcurrentUpdateHttp2SolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/ConcurrentUpdateSolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/Http2SolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/HttpSolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/LBHttp2SolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/LBHttpSolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/LBSolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/SolrClientBuilder.java
- solr/solrj/src/test/org/apache/solr/client/solrj/SolrExampleBinaryHttp2Test.java
- solr/solrj/src/test/org/apache/solr/client/solrj/TestLBHttp2SolrClient.java
- solr/solrj/src/test/org/apache/solr/client/solrj/embedded/SolrExampleXMLHttp2Test.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/ConcurrentUpdateHttp2SolrClientTest.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/Http2SolrClientTest.java
This change is going to touch a lot of places ;-)
https://issues.apache.org/jira/browse/SOLR-16595
Introduce the `TimeUnit unit` parameter to our Builder, and then internally convert what is passed in to what we need.
Start converting builder methods.
Run the existing test suite.
> SOLR-16595: Standardize Solr Client Builders handling of times

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/admin/SystemInfoHandler.java
- solr/core/src/java/org/apache/solr/security/RuleBasedAuthorizationPluginBase.java
- solr/core/src/test/org/apache/solr/security/BaseTestRuleBasedAuthorizationPlugin.java
https://issues.apache.org/jira/browse/SOLR-16658
It's a trappy design to allow "null" keys in maps like this. And to define a "null" role in a permission in Admin UI security editor you need to actively de-select all roles, which took me a while to figure. Not trying to fix this here, but at least trying to resolve correct set of permissions for a given user, taking into account that permissions may have `*` or `null` roles.
I discovered this bug when working with a quite open-ended security.json for JWT, where some endpoints don't require authentication and all others do require auth, but we don't care what role the user has, e.g.
```json
"permissions":[
{
"name": "info",
"role": null,
"collection": null,
"path": "/admin/info/system"
},
{
"name": "health",
"role": null
},
{
"name": …
```
> SOLR-16658 List of permissions returned to Admin UI is not complete

- solr/core/src/test/org/apache/solr/core/TestCoreDiscovery.java
This has been flapping at ~2% for a long time: http://fucit.org/solr-jenkins-reports/failure-report.html
And it's because the CloserThread closes the core in another thread and perhaps takes a while on a busy CI or high parallelism situation.  So I gave it more time and logged info to help debug if it happens.
> SOLR-16104 Fix TestCoreDiscovery.testTooManyTransientCores

- solr/CHANGES.txt
- solr/webapp/web/css/angular/collections.css
- solr/webapp/web/js/angular/app.js
- solr/webapp/web/partials/collections.html
https://issues.apache.org/jira/browse/SOLR-15928
This is the first of several permission related edits to Admin UI. The "Add Collection" button was already disabled when user lacked `collection-admin-edit`, but it was not dimmed/greyed so hard to understand why you could not click.
> SOLR-15928 Dim add collection buttons in Admin UI when no permission

- solr/CHANGES.txt
- solr/modules/s3-repository/src/java/org/apache/solr/s3/S3StorageClient.java
- solr/modules/s3-repository/src/test/org/apache/solr/s3/S3PathsTest.java
https://issues.apache.org/jira/browse/SOLR-16670
> SOLR-16670: Fix 404 error in S3 directory check

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/core/NodeConfig.java
- solr/solr-ref-guide/modules/configuration-guide/pages/configuring-solr-xml.adoc
- solr/solr-ref-guide/modules/deployment-guide/pages/upgrading-a-solr-cluster.adoc
- solr/solr-ref-guide/modules/deployment-guide/pages/zookeeper-file-management.adoc
- solr/solr-ref-guide/modules/getting-started/pages/tutorial-solrcloud.adoc
- solr/solr-ref-guide/modules/upgrade-notes/pages/major-changes-in-solr-9.adoc
https://issues.apache.org/jira/browse/SOLR-15959
Deprecation warning in log, and WARNING in refguide.
Also fixed some other refguide mentions of the need for copying solr.xml to SOLR_HOME, which is no longer needed.
> SOLR-15959 Deprecate loading of solr.xml from ZK

- solr/core/src/java/org/apache/solr/servlet/ServletUtils.java
- solr/modules/opentelemetry/src/java/org/apache/solr/opentelemetry/OtelTracerConfigurator.java
- solr/modules/opentelemetry/src/test/org/apache/solr/opentelemetry/OtelTracerConfiguratorTest.java
- solr/solr-ref-guide/modules/deployment-guide/pages/distributed-tracing.adoc
https://issues.apache.org/jira/browse/SOLR-16650
https://issues.apache.org/jira/browse/SOLR-16532
Testing solr 9.2.0-SNAPSHOT at a client and missing hostname/port from traces. So this PR will add those by default, following the [otel semantic conventions](https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/), both local logical host name as seen on the request, and peer host/port. Not yet tested in the wild.
> SOLR-16650, SOLR-16532: OTEL tracer additional tags

- solr/CHANGES.txt
- solr/solr-ref-guide/modules/upgrade-notes/pages/major-changes-in-solr-9.adoc
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/Http2SolrClient.java
https://issues.apache.org/jira/browse/SOLR-16669
The primary issue is the `checkPeerNameStr == null` check. If the sysProp is not provided we want to default to `true`, not `false`.
Not back-compat, but actually follows the code and ref-guide documentation.
> SOLR-16669: Fix default checkPeerName in Http2SolrClient

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/util/SolrCLI.java
- solr/core/src/test/org/apache/solr/util/TestSolrCLIRunExample.java
https://issues.apache.org/jira/browse/SOLR-16672
found unused (I believe!) parameter...
> SOLR-16672: Remove use of setDefaultCollection in SolrCLI

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/MoreLikeThisHandler.java
- solr/core/src/java/org/apache/solr/handler/component/MoreLikeThisComponent.java
- solr/core/src/test/org/apache/solr/handler/component/DistributedMLTComponentTest.java
https://issues.apache.org/jira/browse/SOLR-788
I think this is a somewhat reliable solution for the problem with distributed mlt component. Reminder, now it naively relies on parsing `booleanQuery.toString()` that's unacceptable.
> SOLR-16682: transfer mlt query for component right

- solr/core/src/java/org/apache/solr/cloud/ZkCLI.java
- solr/core/src/test/org/apache/solr/cloud/ZkCLITest.java
- solr/server/scripts/cloud-scripts/zkcli.sh
https://issues.apache.org/jira/browse/SOLR-16608
This provides support for compressed state.json for the ZkCLI tool. This will allow for using the ZkCLI tool to get and put state.json files and ensure they are correctly compressed when put and uncompressed when retrieved. This will allow Solr administrators to retrieve and modify state.json while maintaining compression.
This uses the local solr home by default to get the configured settings from solr.xml for compressed state. If this tool is run without providing solr home, then you will not be able to rely on compression being configured.
Added new tests to the ZkCLITest to cover cases with compression as well.
> Adding support for compression within the ZkCLI tool

- solr/core/src/test/org/apache/solr/cloud/ZkCLITest.java
https://issues.apache.org/jira/browse/SOLR-16608
Fixing a test failure on Windows for a recent test addition.
Using System.lineSeparator() to work on any OS
- [] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
> SOLR-16608: Fixing replacement of line ending in test to be OS agnostic

- solr/benchmark/src/java/org/apache/solr/bench/lifecycle/SolrStartup.java
- solr/benchmark/src/java/org/apache/solr/bench/lifecycle/package-info.java
- solr/benchmark/src/resources/configs/minimal/conf/schema.xml
- solr/benchmark/src/resources/configs/minimal/conf/solrconfig.xml
- solr/benchmark/src/resources/solr.xml
https://issues.apache.org/jira/browse/SOLR-16680
Solr has a benchmarking module built around an integration with JMH.  But it doesn't have a ton of benchmarks to run quite yet.
This PR adds a JMH benchmark that attempts to measure Solr Startup, by using the JettySolrRunner test-framework class.
N/A
> SOLR-16680: Add JMH benchmark for Solr startup

- solr/modules/opentelemetry/src/test/org/apache/solr/opentelemetry/OtelTracerConfiguratorTest.java
https://issues.apache.org/jira/browse/SOLR-16683
The `@ThreadLeakLingering`  should be in millis, not seconds, so 10 means 10ms, but we should wait for 10s.
> SOLR-16683 Fix frequent failures of OtelTracerConfiguratorTest

- solr/core/src/java/org/apache/solr/cloud/overseer/ZkStateWriter.java
- solr/core/src/test/org/apache/solr/cloud/overseer/ZkStateReaderTest.java
- solr/solrj-zookeeper/src/java/org/apache/solr/common/cloud/PerReplicaStatesOps.java
when the state.json (and no PRS) is changed, PRS just creates and deletes dummy node to that child watches are triggered. In reality, it's not used anywhere
> Eliminate redundant operation in PRS

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/ClusterAPI.java
- solr/core/src/java/org/apache/solr/handler/admin/CollectionsHandler.java
- solr/core/src/java/org/apache/solr/handler/admin/api/ListAliasesAPI.java
- solr/core/src/test/org/apache/solr/handler/V2ClusterAPIMappingTest.java
- solr/core/src/test/org/apache/solr/handler/admin/api/ListAliasesAPITest.java
- solr/solr-ref-guide/modules/deployment-guide/pages/alias-management.adoc
- solr/solrj-zookeeper/src/java/org/apache/solr/common/cloud/ZkStateReader.java
- solr/solrj/src/test/org/apache/solr/client/solrj/request/TestV2Request.java
https://issues.apache.org/jira/browse/SOLR-16393
List Aliases apis only.
List Aliases api responses:
```
curl -X GET 'http://localhost:8983/solr/admin/collections?action=LISTALIASES' | jq
{
"responseHeader": {
"status": 0,
"QTime": 0
},
"aliases": {
"testalias1": "collection1",
"testalias2": "collection2,collection1"
},
"properties": {
"testalias2": {
"someKey": "someValue"
}
}
}
```
```
curl -X GET http://localhost:8983/api/aliases | jq
{
"responseHeader": {
"status": 0,
"QTime": 1
},
"aliases": {
"testalias1": "collection1",
"testalias2": "collection2,collection1"
},
"properties": {
"testalias2": {
"someKey": "someValue"
}
}
}
```
```
curl -X GET http://localhost:8983/api/aliases/testalias2 | jq
{
"responseHeader": {
"status": 0,
"QTime": 1
},
"name": "testalias2",
"properties": { …
```
> SOLR-16393 Cosmetic, REST-fulness improvements to v2 alias, alias-prop

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/search/ReRankOperator.java
- solr/core/src/java/org/apache/solr/search/ReRankQParserPlugin.java
- solr/core/src/test/org/apache/solr/search/TestReRankQParserPlugin.java
- solr/solr-ref-guide/modules/query-guide/pages/query-re-ranking.adoc
https://issues.apache.org/jira/browse/SOLR-16643
This PR supersedes https://github.com/apache/solr/pull/1324 - please see that PR for earlier comments.
Add `reRankOperator=multiply` and `replace` options to ReRank query parser
The new options can be used to replace or multiply (rather than add to) documents' original scores with the output of the ReRankQuery.
We've added tests that validates that scores have changed as expected.
> SOLR-16643: Add reRankOperator=multiply/replace options to ReRank query parser

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cloud/ReplicateFromLeader.java
- solr/core/src/test/org/apache/solr/cloud/ReplicateFromLeaderTest.java
https://issues.apache.org/jira/browse/SOLR-16487
The polling for replication is fairly simply, but can lead to polling too often. As an example if you had the following config for commits:
```
<autoCommit>
<maxTime>15000</maxTime>
<openSearcher>false</openSearcher>
</autoCommit>
<autoSoftCommit>
<maxTime>60000</maxTime>
</autoSoftCommit>
```
The current logic would setup polling to be half of the autoCommit time, so poll every 7.5 seconds. However since a new searcher isn't opened, there will only be changes reflected every 60 seconds on the leader. We can make this logic a bit smarter knowing that the replication handler won't reflect changes until a new searcher is opened.
Modified the code setting the polling interval for replication to only use the autoCommit time if openSearcher is …
> SOLR-16487: Improve Pull Replica Interval

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/CollectionsAPI.java
- solr/core/src/java/org/apache/solr/handler/admin/CollectionsHandler.java
- solr/core/src/java/org/apache/solr/handler/admin/api/DeleteAliasAPI.java
- solr/core/src/java/org/apache/solr/jersey/AsyncJerseyResponse.java
- solr/core/src/java/org/apache/solr/jersey/SubResponseAccumulatingJerseyResponse.java
- solr/core/src/test/org/apache/solr/handler/admin/TestCollectionAPIs.java
- solr/core/src/test/org/apache/solr/handler/admin/V2CollectionsAPIMappingTest.java
- solr/core/src/test/org/apache/solr/handler/admin/api/DeleteAliasAPITest.java
- solr/solr-ref-guide/modules/deployment-guide/pages/alias-management.adoc
https://issues.apache.org/jira/browse/SOLR-16393
Solr is in the process of migrating its v2 APIs over to a JAX-RS framework. This gives us a more feature-rich framework for expressing APIs, makes it easier for the APIs themselves to be more REST-ful and standardized, and also makes it easier for Solr to integrate with tooling such as OpenAPI, which can be used to autogenerate client bindings for a variety of different languages.
But many non-JAX-RS APIs remain.
This commit migrates the "delete alias" API to the JAX-RS framework.
It also makes a few cosmetic changes to the v2 API to bring it closer into line with the more REST-ful design we're targeting for v2.  Alias deletion now uses the API:
```
DELETE /api/aliases/aliasName
```
Existing alias tests continue to pass.
Please review the …
> SOLR-16393: Migrate alias-deletion to JAX-RS

- solr/CHANGES.txt
- solr/benchmark/src/java/org/apache/solr/bench/MiniClusterState.java
- solr/benchmark/src/java/org/apache/solr/bench/search/SimpleSearch.java
The test is very simple, and it's goal (so far at least) is to test the client library more than the server
> SOLR-16704: Add simple search benchmark to benchmark module

- dev-tools/scripts/releaseWizard.yaml
- dev-tools/scripts/smokeTestRelease.py
The Jars were introduced by JAX-RS. All Jakarta jars have javax classes, so I just made all of them accepted.
The release wizard has a small typo in the command line of buildAndPushRelease.
> Fix smoke test jar checks & release wizard

- solr/solr-ref-guide/modules/upgrade-notes/pages/major-changes-in-solr-9.adoc
- solr/solr-ref-guide/modules/upgrade-notes/pages/solr-upgrade-notes.adoc
https://issues.apache.org/jira/browse/SOLR-16708
Re-arranging some upgrade notes
While reviewing the 9.2 release, I started reading release notes and found that two of my own deprecations notes were listed under a Jetty heading. Thus I added a new `Deprecations` heading and moved things around.
> SOLR-16708: Update major-changes-in-solr-9.adoc

- gradle/validation/error-prone.gradle
- solr/core/src/java/org/apache/solr/parser/QueryParserConstants.java
- solr/core/src/java/org/apache/solr/request/SimpleFacets.java
- solr/core/src/java/org/apache/solr/schema/BoolField.java
- solr/core/src/java/org/apache/solr/util/ExportTool.java
- solr/core/src/java/org/apache/solr/util/PackageTool.java
- solr/core/src/java/org/apache/solr/util/SolrCLI.java
- solr/core/src/test/org/apache/solr/CursorPagingTest.java
- solr/core/src/test/org/apache/solr/handler/CSVRequestHandlerTest.java
- solr/core/src/test/org/apache/solr/legacy/TestLegacyNumericUtils.java
- solr/core/src/test/org/apache/solr/legacy/TestNumericRangeQuery32.java
- solr/core/src/test/org/apache/solr/legacy/TestNumericRangeQuery64.java
- solr/core/src/test/org/apache/solr/search/CursorMarkTest.java
- solr/core/src/test/org/apache/solr/spelling/ConjunctionSolrSpellCheckerTest.java
- solr/modules/analytics/src/java/org/apache/solr/analytics/facet/SortableFacet.java
- solr/modules/analytics/src/test/org/apache/solr/analytics/legacy/facet/LegacyAbstractAnalyticsFacetTest.java
- solr/solrj/src/java/org/apache/solr/common/util/JsonTextWriter.java
- solr/solrj/src/java/org/apache/solr/common/util/StrUtils.java
- solr/solrj/src/java/org/noggit/JSONUtil.java
- solr/solrj/src/test/org/apache/solr/client/solrj/embedded/SolrExampleStreamingHttp2Test.java
- solr/solrj/src/test/org/apache/solr/client/solrj/embedded/SolrExampleStreamingTest.java
https://issues.apache.org/jira/browse/SOLR-16427
builds on https://github.com/apache/solr/pull/1128
Updates comments on a few rules since we do use them. Enables the following rules
* `MutablePublicArray` - most of these were in SolrCLI and switched to list vs array
* `NonCanonicalType` - fixed a few type references
The changes are in separate commits to help make reviews easier.
> SOLR-16427: Evaluate and fix errorprone rules - part 5

- solr/core/src/java/org/apache/solr/cloud/ZkCLI.java
- solr/core/src/java/org/apache/solr/cloud/overseer/ZkStateWriter.java
- solr/core/src/test/org/apache/solr/cloud/ZkCLITest.java
- solr/solrj/src/java/org/apache/solr/common/util/Compressor.java
- solr/solrj/src/java/org/apache/solr/common/util/ZLibCompressor.java
- solr/solrj/src/test/org/apache/solr/common/util/ZLibCompressorTest.java
Currently ZLibCompressor.compress() works with a compression buffer initialized with a capacity equal to the source data (to compress) length.
Since we expect a good compression ratio, specially for state.json, we propose a small adjustment to have the initial capacity of the buffer configurable. That way, when the caller knows it is compressing a state.json data, it can set the initial buffer capacity to sourceData.length / 10.
This PR adds ZLibCompressor.compressBytes(byte[] data, int initialBufferCapacity)
> SOLR-16706: Reduce the ZLibCompressor compression buffer size.

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cloud/api/collections/SplitShardCmd.java
use metric API instead of NodeStateProvider in SplitShardCmd.
> SOLR-16507: Remove NodeStateProvider & Snitch

- solr/CHANGES.txt
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/Http2SolrClient.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/Http2SolrClientTest.java
https://issues.apache.org/jira/browse/SOLR-16649
Converted patch into PR, added CHANGES
> SOLR-16649 Http2SolrClient.processErrorsAndResponse uses wrong instance of ResponseParser

- gradle/validation/forbidden-apis/com.google.guava.guava.all.txt
- gradle/validation/forbidden-apis/commons-io.commons-io.all.txt
- solr/core/src/java/org/apache/solr/cloud/api/collections/CollApiCmds.java
- solr/core/src/java/org/apache/solr/cluster/placement/plugins/AffinityPlacementFactory.java
- solr/core/src/java/org/apache/solr/cluster/placement/plugins/MinimizeCoresPlacementFactory.java
- solr/core/src/java/org/apache/solr/core/SolrCore.java
- solr/core/src/java/org/apache/solr/handler/DumpRequestHandler.java
- solr/core/src/java/org/apache/solr/handler/FieldAnalysisRequestHandler.java
- solr/core/src/java/org/apache/solr/handler/admin/SolrInfoMBeanHandler.java
- solr/core/src/java/org/apache/solr/handler/loader/JsonLoader.java
- solr/core/src/java/org/apache/solr/handler/tagger/TaggerRequestHandler.java
- solr/core/src/java/org/apache/solr/logging/jul/JulWatcher.java
- solr/core/src/java/org/apache/solr/logging/log4j2/Log4j2Watcher.java
- solr/core/src/java/org/apache/solr/request/json/RequestUtil.java
- solr/core/src/java/org/apache/solr/response/transform/ChildDocTransformer.java
- solr/core/src/java/org/apache/solr/schema/AbstractSpatialPrefixTreeFieldType.java
- solr/core/src/java/org/apache/solr/search/ExtendedDismaxQParser.java
- solr/core/src/java/org/apache/solr/servlet/SolrRequestParsers.java
- solr/core/src/java/org/apache/solr/util/MapListener.java
- solr/core/src/test/org/apache/solr/core/TestCoreContainer.java
- solr/core/src/test/org/apache/solr/servlet/SolrRequestParserTest.java
- solr/modules/langid/src/java/org/apache/solr/update/processor/SolrInputDocumentReader.java
- solr/solrj-zookeeper/build.gradle
- solr/solrj-zookeeper/src/test/org/apache/solr/common/cloud/TestZkConfigSetService.java
- solr/solrj/src/java/org/apache/solr/common/util/StrUtils.java
- solr/solrj/src/test/org/apache/solr/common/util/ContentStreamTest.java
- solr/test-framework/build.gradle
- solr/test-framework/src/java/org/apache/solr/cloud/ZkTestServer.java
https://issues.apache.org/jira/browse/SOLR-16713
Cleans up the following by adding forbiddenapis rules:
* com.google.common.base.Throwables
* com.google.common.collect.ImmutableMap
* com.google.common.collect.**
* com.google.common.io.** (and consequently org.apache.commons.io.IOUtils#toString(java.io.Reader) since its the same usage)
> SOLR-16713: Replace Guava usages with pure Java (part 2)

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/admin/SystemInfoHandler.java
Note that this only changes what's displayed by `SystemInfoHandler`
> SOLR-16731: Use the right cluster property for determining if TLS is enabled

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/admin/SystemInfoHandler.java
- solr/core/src/java/org/apache/solr/security/PKIAuthenticationPlugin.java
This PR addresses `SOLR-16730` by completely skipping including the username, roles and permissions when the request is an inter-node request to `SystemInfoHandler`. 
Having this part alone:
```
if (roles == null) {
info.add("permissions", Set.of());
}
```
should be enough to handle the NPE described in the Jira issue, but I think it may be better to just skip this section for internal requests, since the data displayed is unrelated to the user that issues the request.
> SOLR-16730: Exclude username, roles and permissions for inter-node requests to SystemInfoHandler

- gradle/validation/versions-props-sorted.gradle
- versions.props
This will not fail the build even if `versions.props` contains lines starting with `#`.
> Tolerate comments in versions.props

- build.gradle
Maintaining the Jenkins Smoketest jobs at https://builds.apache.org/job/Solr/ are a pain currently.
Anytime a version changes on the branch, the job requires the version to be manually changed twice in the job (and one location is pretty hard to find).
This makes it possible to just use to build a release without `-SNAPSHOT` at the end, which the smoketester requires.
```
gradle assembleRelease -Pversion.suffix=""
```
> Make it easy to build a non-snapshot version

- dev-tools/scripts/addDepsToChanges.py
- dev-tools/scripts/releaseWizard.yaml
https://issues.apache.org/jira/browse/SOLR-16714
Here is a python script that runs `git log` to find all `solrbot` commits since last release.
NOTE: The wizard change is not yet tested, only the python script.
To test the python script yourself, check out this branch and run e.g. `dev-tools/scripts/addDepsToChanges.py --version 10.0.0`
> SOLR-16714 ReleaseWizard to add solrbot dependency upgrades to CHANGES

- dev-tools/scripts/addDepsToChanges.py
https://issues.apache.org/jira/browse/SOLR-16714
After committing, I did a test on branch_9_2 and discovered a bug when list of solrbot changes was empty. This will detect not changes and exit script.
Also added a check to remove `(No changes)` line if it exists
> SOLR-16714: addDepsToChanges.py handle empty gitlog

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/core/CoreContainer.java
- solr/modules/hadoop-auth/src/java/org/apache/solr/security/hadoop/KerberosPlugin.java
- solr/packaging/test/test_modules.bats
- solr/packaging/test/test_placement_plugin.bats
https://issues.apache.org/jira/browse/SOLR-16240
The easy way out vs waiting on a hadoop fix and a hadoop release.
> SOLR-16240: Fix kerberosPlugin module classloading

- dev-docs/running-in-docker.adoc
- dev-docs/solr-source-code.adoc
- dev-tools/scripts/releaseWizard.yaml
- dev-tools/scripts/smokeTestRelease.py
- solr/CHANGES.txt
- solr/distribution/build.gradle
- solr/docker/README.md
- solr/docker/build.gradle
- solr/docker/gradle-help.txt
- solr/docker/templates/Dockerfile.body.template
- solr/docker/templates/Dockerfile.local.header.template
- solr/docker/templates/Dockerfile.official.header.template
- solr/packaging/README.txt
- solr/packaging/build.gradle
- solr/solr-ref-guide/modules/configuration-guide/pages/solr-modules.adoc
- solr/solr-ref-guide/modules/deployment-guide/pages/installing-solr.adoc
- solr/solr-ref-guide/modules/deployment-guide/pages/monitoring-with-prometheus-and-grafana.adoc
- solr/solr-ref-guide/modules/deployment-guide/pages/solr-in-docker.adoc
- solr/solr-ref-guide/modules/getting-started/pages/solr-tutorial.adoc
- solr/solr-ref-guide/modules/upgrade-notes/pages/major-changes-in-solr-9.adoc
https://issues.apache.org/jira/browse/SOLR-16742
Things to do:
All packaging commands should work with `slim` and `full`, and operate on both when neither is selected.
> SOLR-16742: Make a slim and full Solr release

- solr/CHANGES.txt
- solr/solr-ref-guide/build.gradle
https://issues.apache.org/jira/browse/SOLR-16747
Basically if the root directory is not a git repository, then don't include ref-guide tasks in the build by default.
The ref guide tasks require that the root directory is a git repository, otherwise they will not work. So we can only remove them. No way to "fix" these tasks.
> SOLR-16747: Fix source-release gradle build

- solr/CHANGES.txt
- solr/bin/solr
- solr/packaging/test/test_example_noprompt.bats
https://issues.apache.org/jira/browse/SOLR-16755
The new test fails with `# ERROR: No line found` without this patch.
> SOLR-16755: bin/solr's '-noprompt' option no longer works for examples

- solr/CHANGES.txt
- solr/modules/ltr/src/java/org/apache/solr/ltr/response/transform/LTRFeatureLoggerTransformerFactory.java
- solr/modules/ltr/src/java/org/apache/solr/ltr/store/rest/ManagedFeatureStore.java
- solr/modules/ltr/src/test/org/apache/solr/ltr/feature/TestFeatureLogging.java
- solr/modules/ltr/src/test/org/apache/solr/ltr/store/rest/TestManagedFeatureStore.java
- solr/modules/ltr/src/test/org/apache/solr/ltr/store/rest/TestModelManagerPersistence.java
https://issues.apache.org/jira/browse/SOLR-15493
https://issues.apache.org/jira/browse/SOLR-15494
When a wrong/non-existent feature store name is passed to the query for feature extraction, an empty list is returned;
it also happens when inspecting the contents of a non-existent feature store. It would be helpful if a message was returned indicating that the feature store I am calling is not present.
Also, this non-existent (and empty) feature store is inappropriately added to the feature store list and only disappears after the collection is reloaded.
This contribution wants to add the ability to throw an exception when a non-existent feature store name is passed and thus wants to prevent it from being inappropriately added to the feature store list.
A check for a non-existent feature …
> SOLR-15493: Throw an error message if the feature store doesn't exist

- solr/solr-ref-guide/modules/deployment-guide/pages/solr-control-script-reference.adoc
- solr/solr-ref-guide/modules/upgrade-notes/pages/major-changes-in-solr-9.adoc
https://issues.apache.org/jira/browse/SOLR-16761
I didn't know it existed..
Bit o' docs.
> SOLR-16761: Document the bin/solr api command

- solr/bin/solr
- solr/bin/solr.cmd
- solr/core/src/java/org/apache/solr/cli/StatusTool.java
- solr/packaging/test/test_status.bats
https://issues.apache.org/jira/browse/SOLR-16754
The magic `bin/solr -i` or `bin/solr -info` isn't documented anywhere, and duplicates `bin/solr status`, which is documented!
Remove the magic `-i` and `-info` parameters, and restore the `-h` and `-help` parameters so that `bin/solr status` looks like all the other commands!
added a .bats test and manually.
> SOLR-16754: Change the bin/solr -info logic to work like other tools.

- solr/solr-ref-guide/modules/deployment-guide/pages/authentication-and-authorization-plugins.adoc
Improve the section of the authentication page to make it easier for users to find their solr home, so they know where to place the security.json file.
This is a simple documentation text change, not a code change or a change to the ref guide structure.  Aside from having another committer review it, there's really no need to exhaustively test it.
> Ref Guide: Clearer instructions for placing security.json.

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cluster/placement/plugins/AffinityPlacementConfig.java
- solr/core/src/java/org/apache/solr/cluster/placement/plugins/AffinityPlacementFactory.java
- solr/core/src/test/org/apache/solr/cluster/placement/plugins/AffinityPlacementFactoryTest.java
This PR adds the option to require anti-affinity within an AZ (essentially giving another level of anti-affinity). 
The usecase is, to support something like rack diversity between an AZ, or host diversity, when multiple Solr instances are running on the same physical host.
I plan to add a CHANGES entry before merging
> SOLR-16719: Let AffinityPlacementFactory have a spread_domain label

- solr/solr-ref-guide/modules/getting-started/pages/tutorial-aws.adoc
The link in current form does not work. It needs "apache-" in front as visible below:  This works:
https://archive.apache.org/dist/zookeeper/zookeeper-3.8.1/  https://archive.apache.org/dist/zookeeper/zookeeper-3.8.1/apache-zookeeper-3.8.1.tar.gz This does not work:
https://archive.apache.org/dist/zookeeper/zookeeper-3.8.1/zookeeper-3.8.1.tar.gz
Link fix
Link fix
No code changes, so no tests.
> tutorial-aws.adoc link fix

- solr/core/src/test/org/apache/solr/cloud/api/collections/CollectionReloadTest.java
https://issues.apache.org/jira/browse/SOLR-13880
Migrate test from https://github.com/apache/lucene-solr/pull/986 to current repo.
Additional testing.
> SOLR-13880: Add test that creates/reloads/deletes collections

- solr/CHANGES.txt
- solr/webapp/web/js/angular/controllers/cloud.js
https://issues.apache.org/jira/browse/SOLR-16773
> SOLR-16773: UI: Cloud>Nodes screen fix display of cores with non-standard shard names

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cli/ExportTool.java
- solr/core/src/test/org/apache/solr/cli/TestExportTool.java
- solr/packaging/test/test_export.bats
- solr/solr-ref-guide/modules/deployment-guide/pages/solr-control-script-reference.adoc
https://issues.apache.org/jira/browse/SOLR-16764
bin/solr export by default actually uses the JSON with Lines format, not JSON.  
add Bats based integration tests, refactor some of the logic, make things more explicit it what is happening.
Oh, and now you can spedifyc a directory to create files in if you want...
BATS
> SOLR-16764: Be clearer that bin/solr export uses JSONL, not JSON format. Fix up how files are named and output and add tests.

- solr/core/src/test/org/apache/solr/cloud/api/collections/CollectionReloadTest.java
https://issues.apache.org/jira/browse/SOLR-16784
> SOLR-16784 Badapple CollectionReloadTest

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cloud/ZkController.java
- solr/core/src/test/org/apache/solr/cloud/ZkControllerTest.java
This PR addresses a race condition when deleting the clusterstate.json from multiple instances concurrently.
> SOLR-16783: Ignore NoNodeException when deleting clusterstate.json on startup

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cli/ExportTool.java
- solr/core/src/test/org/apache/solr/cli/TestExportTool.java
- solr/packaging/test/test_export.bats
- solr/solr-ref-guide/modules/deployment-guide/pages/solr-control-script-reference.adoc
https://issues.apache.org/jira/browse/SOLR-16782
Export tool only supports Javabin and JSONL, not JSON...   We would like to have that to be able to import docs directly!
Add JSON format...  Make it the default format as JSONL is somewhat special purpose...
extended existing tests.
> SOLR-16782: Export tool should export in JSON that matches Solr Import Format

- solr/CHANGES.txt
- solr/modules/ltr/src/java/org/apache/solr/ltr/CSVFeatureLogger.java
- solr/modules/ltr/src/java/org/apache/solr/ltr/FeatureLogger.java
- solr/modules/ltr/src/java/org/apache/solr/ltr/LTRScoringQuery.java
- solr/modules/ltr/src/java/org/apache/solr/ltr/SolrQueryRequestContextUtils.java
- solr/modules/ltr/src/java/org/apache/solr/ltr/interleaving/LTRInterleavingScoringQuery.java
- solr/modules/ltr/src/java/org/apache/solr/ltr/response/transform/LTRFeatureLoggerTransformerFactory.java
- solr/modules/ltr/src/java/org/apache/solr/ltr/search/LTRQParserPlugin.java
- solr/modules/ltr/src/test/org/apache/solr/ltr/TestLTRScoringQuery.java
- solr/modules/ltr/src/test/org/apache/solr/ltr/TestSelectiveWeightCreation.java
- solr/modules/ltr/src/test/org/apache/solr/ltr/feature/TestExternalFeatures.java
- solr/modules/ltr/src/test/org/apache/solr/ltr/feature/TestFeatureLogging.java
- solr/modules/ltr/src/test/org/apache/solr/ltr/feature/TestNoMatchSolrFeature.java
- solr/modules/ltr/src/test/org/apache/solr/ltr/feature/TestOriginalScoreFeature.java
- solr/modules/ltr/src/test/org/apache/solr/ltr/response/transform/TestFeatureLoggerTransformer.java
- solr/modules/ltr/src/test/org/apache/solr/ltr/response/transform/TestInterleavingTransformer.java
- solr/solr-ref-guide/modules/query-guide/pages/learning-to-rank.adoc
https://issues.apache.org/jira/browse/SOLR-16759
Currently,  there is no possibility of deciding how many features to log.
It would be useful to give the user the ability to decide if to print all the features of the store or only the features used by the model.
Suppose to execute a query with both logging and reranking, where the logging store is the same as the model store. 
Suppose the model store contains 200 features while the model uses just half of them.
The logging will always consider all the 200 features of the store. 
There is no possibility of printing only the 100 features used by the model.
An external parameter _logAll_ has been added to the features transformer in order to give the user the possibility to choose how many features to log.
The new parameter has been added …
> SOLR-16759: Introducing logAll parameter in the feature logger

- solr/core/src/java/org/apache/solr/core/SolrConfig.java
- solr/core/src/java/org/apache/solr/update/DirectUpdateHandler2.java
Just like we have node level aggregation for RequestHandler, We should have similar config for updatehandler as well
how to configure
`<updateHandler class="solr.DirectUpdateHandler2" aggregateNodeLevelMetricsEnabled="true">`
> add aggregateNodeLevelMetricsEnabled for updatehandler metrics

- solr/packaging/build.gradle
- solr/packaging/test/test_bats.bats
- solr/packaging/test/test_create.bats
- solr/packaging/test/test_example_noprompt.bats
- solr/packaging/test/test_placement_plugin.bats
- solr/packaging/test/test_start_solr.bats
- Fix some of the test names
- Add timing information to test output
- Fix `test_bats.bats` so that it waits for the server to start before trying to stop it. This should probably be fixed somewhere else, but I tried a lot of things and none helped.
- `test_create.bats` is faster by removing an unnecessary `delete_all_collections`
> Make small improvements to integration tests

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/core/CoreContainer.java
https://issues.apache.org/jira/browse/SOLR-16801
Due to [SOLR-16240](https://issues.apache.org/jira/browse/SOLR-16240) context class loader was set before loading CoreContainer.
As the context class loader is not unset when loading is finished it is currently impossible to use 
EmbeddedSolrServer within Tomcat and JSF, as it the whole class loading during servlet init process.
Set context class loader to original context class loader after plugin loading.
Plugin loading tests are already provided.
> SOLR-16801: Set previous context class loader after loading plugin

- solr/core/src/java/org/apache/solr/update/DocumentBuilder.java
- solr/core/src/test-files/solr/collection1/conf/schema-densevector.xml
- solr/core/src/test-files/solr/collection1/conf/schema-vector-catchall.xml
- solr/core/src/test/org/apache/solr/update/DocumentBuilderVectorCatchAllCopyTest.java
https://issues.apache.org/jira/browse/SOLR-16807
Currently if you setup a copy field with a * source and a DenseVectorField is present in the schema indexing will fail unless the destination is a DenseVectorField. I think the better behavior is to skip the DenseVectorField during the copy. If we don't do this the * copyfield is simply broken with a DenseVectorField in the index.
This PR resolves the issue while preserving the exception in the cases where the copyField source is not *. The PR skips adding the DenseVectorField to a destination field of a different type if the source for the copyField is *.
A * source copyField was added to an existing DenseVectorField test schema, which passes. An existing test (org.apache.solr.update.DocumentBuilderTest.denseVector_incorrectCopyFieldDestina …
> SOLR-16807: DenseVectorField breaks '*' copyFields

- solr/core/src/test/org/apache/solr/cloud/TestPullReplica.java
- solr/core/src/test/org/apache/solr/cloud/api/collections/CollectionReloadTest.java
https://issues.apache.org/jira/browse/SOLR-16784
Test was failing with 404 due to incorrect api calls every time the random picker chose '2'. I updated the urls and payload to the correct version and now it works.
I'm also taking the opportunity to fix one minor accidental change in TestPullReplica test class.
> SOLR-16784 Frequent failing CollectionReloadTest

- solr/core/src/test-files/solr/configsets/cloud-minimal-userproperties/conf/schema.xml
- solr/core/src/test-files/solr/configsets/cloud-minimal-userproperties/conf/solrconfig.xml
- solr/core/src/test/org/apache/solr/cloud/api/collections/TestCollectionsAPIViaSolrCloudCluster.java
https://issues.apache.org/jira/browse/SOLR-16678
SOLR-16678 is not a bug, it's using outdated syntax. Adding a test to showcase this, because I could not find an already exiting one.
> SOLR-16678 Collection API v2 CREATE does not handle user-defined properties

- solr/bin/solr
https://issues.apache.org/jira/browse/SOLR-16823
echo out to users that -upconfig should be upconfig for the various zk commands.
I will commit and backport to 9x, and remove the support from main.
> SOLR-16823: mark as deprecated the bin/solr zk -upconfig equivalents of bin/solr zk upconfig

- solr/core/src/java/org/apache/solr/cluster/placement/plugins/AffinityPlacementFactory.java
- solr/core/src/test/org/apache/solr/cluster/placement/plugins/AffinityPlacementFactoryTest.java
This commit fixes a bug where AffinityPlacementFactory would fail to compute placements for shards where one or more replicas are located in down nodes.
The feature hasn't been released yet, so this isn't affecting any official version
> SOLR-16839: Fix spread-domain bug in AffinityPlacementFactory

- solr/core/src/java/org/apache/solr/cli/AuthTool.java
- solr/core/src/java/org/apache/solr/cli/ConfigTool.java
- solr/core/src/java/org/apache/solr/cli/SolrCLI.java
- solr/solr-ref-guide/modules/configuration-guide/pages/package-manager.adoc
- solr/solr-ref-guide/modules/deployment-guide/pages/solr-control-script-reference.adoc
https://issues.apache.org/jira/browse/SOLR-16797
Make sure any -h output that we have is also capture in the Ref Guide.   This way, when we remove the extra help content that is in the shell and command scripts, we don't actuall lose the content!
Go through each tool, review it's -h output, and compare against whats in the Ref guide
> SOLR-16797: Migrate detailed help/examples/tips from Solr CLI -h output to Ref Guide

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/schema/DenseVectorField.java
- solr/core/src/test-files/solr/collection1/conf/schema-densevector-high-dimensionality.xml
- solr/core/src/test-files/solr/collection1/conf/schema-densevector.xml
- solr/core/src/test/org/apache/solr/schema/DenseVectorFieldTest.java
- solr/core/src/test/org/apache/solr/search/neural/KnnQParserTest.java
- solr/solr-ref-guide/modules/query-guide/pages/dense-vector-search.adoc
https://issues.apache.org/jira/browse/SOLR-16836
Very simple draft implementation to support high dimensional vector in Apache Solr.
It's a small change but quite useful as we enable our users with any vector size.
A warning is logged if the default Lucene MAX_DIMENSION is exceeded.
This warning is up for discussion as I am conflicted with this, given 1024 doesn't really mean anything nor it's a limit backed by any current data structure or algorithm optimisation).
Given that if it makes the community happier, we can leave the wanring, not going to put much resistance there.
N.B. as any other Solr configuration (number of fields, length of content in the fields, values per fields, etc), no performance is guaranteed.
It's your responsibility to carefully test and benchmark your solution if …
> SOLR-16836: introduce support for high dimensional vectors

- solr/CHANGES.txt
- solr/bin/solr
- solr/bin/solr.cmd
https://issues.apache.org/jira/browse/SOLR-16823
Remove the bin/solr and bin/solr.cmd zk -upconfig and -downconfig special handling in favour of the standard bin/solr zk upconfig and bin/solr zk downconfig commands.
Remove special handling logic.  This is only meant to be committed to `main`.
> SOLR-16823: remove the old backcompat formats for bin/solr zk -upconfig and -downconfig

- solr/core/src/java/org/apache/solr/handler/loader/CborLoader.java
- solr/core/src/java/org/apache/solr/response/CborResponseWriter.java
- solr/core/src/test/org/apache/solr/util/TestCborDataFormat.java
- solr/solr-ref-guide/modules/query-guide/pages/response-writers.adoc
Support toggling STRREF feature. It's a relatively new feature and it may not be supported on all platforms
A new boolean parameter `string_ref` is introduced. The default is true. use `string_ref=false` to toggle it to false
> SOLR-16812: Support toggling STRREF feature. 

- solr/core/src/java/org/apache/solr/search/AbstractReRankQuery.java
- solr/core/src/java/org/apache/solr/search/ReRankCollector.java
- solr/core/src/java/org/apache/solr/search/ReRankQParserPlugin.java
- solr/core/src/java/org/apache/solr/search/ReRankScaler.java
- solr/core/src/java/org/apache/solr/search/ReRankWeight.java
- solr/core/src/test/org/apache/solr/search/TestReRankQParserPlugin.java
- solr/solr-ref-guide/modules/query-guide/pages/query-re-ranking.adoc
https://issues.apache.org/jira/browse/SOLR-16827 
> SOLR-16827: Add min/max scaling to the reranker (#1692)

- solr/core/src/java/org/apache/solr/servlet/CoordinatorHttpSolrCall.java
https://issues.apache.org/jira/browse/SOLR-16861
In Coordinator node, the `MDCLoggingContext` has the synthetic core info set while processing core requests, therefore log prints collection/shard/replica of the synthetic collection/core info.
It should instead have the collection it queries on set.
Set the collection name in the `MDCLoggingContext` when `SolrCore` is obtained via `CoordinatorHttpSolrCall#getCore`
Tested with log4j2.xml format on coordinator node to confirm the log has correct collection name tagged to it
> SOLR-16861: Correct(override) MDC info for `CoordinatorHttpSolrCall`

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/servlet/CoordinatorHttpSolrCall.java
- solr/core/src/test/org/apache/solr/search/TestCoordinatorRole.java
https://issues.apache.org/jira/browse/SOLR-16860
Similar to #1752 , the mapping of collection -> synthetic core should be removed from Coordinator Node upon collection deletion. Otherwise query to such deleted collection would not throw `SolrException` of `Collection not found`.
Remove the collection from `collectionVsCoreNameMapping` on zk notification on collection removal
Added extra test condition in `AddWatch`
> SOLR-16860: Remove collection -> synthetic core mapping in Coordinator Node upon collection deletion

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/schema/DenseVectorField.java
- solr/core/src/java/org/apache/solr/search/FunctionQParser.java
- solr/core/src/java/org/apache/solr/search/StrParser.java
- solr/core/src/java/org/apache/solr/search/ValueSourceParser.java
- solr/core/src/test/org/apache/solr/schema/DenseVectorFieldTest.java
- solr/core/src/test/org/apache/solr/search/QueryEqualityTest.java
- solr/core/src/test/org/apache/solr/search/function/TestDenseVectorFunctionQuery.java
- solr/core/src/test/org/apache/solr/search/function/TestDenseVectorValueSourceParser.java
- solr/core/src/test/org/apache/solr/search/function/TestFunctionQuery.java
- solr/solr-ref-guide/modules/query-guide/pages/function-queries.adoc
https://issues.apache.org/jira/browse/SOLR-16675
Add function queries for dense vector that can be used a rerank time.
Use the latest changes in LUCENE for https://github.com/apache/lucene/pull/12253 I added a parser in ValueSourceParser:
* vectorSimilarity(vectorEncoding, similarityFunction, valueSource1, valueSource2)
vectorEncoding: FLOAT32 or BYTE
similarityFunction: COSINE, DOT_PRODUCT, EUCLIDEAN
valueSources: here it is accepted or a const vector (e.g. [1,2,3...]) or a fieldName of a DenseVectorField.
Unit tests for the vector parsing in FunctionQParser:
Integration tests: 
> SOLR-16675: dense vector function queries

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cloud/api/collections/SplitShardCmd.java
Back-porting SOLR-16507 to 9x.  SplitShardCmd is then identical to main branch.  main CHANGES.txt already has this, including CHANGES.txt in the 9.3 section.
> SOLR-16507: SplitShardCmd shouldn't use NodeStateProvider

- solr/core/src/java/org/apache/solr/servlet/CoordinatorHttpSolrCall.java
- solr/core/src/test/org/apache/solr/search/TestCoordinatorRole.java
https://issues.apache.org/jira/browse/SOLR-16871
From a unit test case [that issue concurrent select queries to coordinator nodes](https://github.com/cowpaths/fullstory-solr/blob/e4226eb8fa2afb01d7615f7faea01f71b144cd58/solr/core/src/test/org/apache/solr/search/TestCoordinatorRole.java#L486), it’s found that there could be 3 race condition issues:
1. If multiple concurrent requests find the synthetic collection is not yet created, they might all attempt to create the synthetic collection. This could trigger SolrException on `collection already exists`
2. Similarly, if multiple concurrent requests find there’s no replica of the synthetic collection for current node (multiple coordinator node scenario), then CoordinatorHttpSolrCall#addReplica could be invoked multiple times. This should not …
> SOLR-16871: Race condition in `CoordinatorHttpSolrCall` synthetic collection/replica init

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/response/BinaryResponseWriter.java
- solr/core/src/test/org/apache/solr/response/TestBinaryResponseWriter.java
https://issues.apache.org/jira/browse/SOLR-16845
Removing the unneeded call to StoredField#getCharSequenceValue for every stored field in the query response.
> SOLR-16845 BinaryResponseWriter should not attempt cast to Utf8CharSequence

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cloud/overseer/ReplicaMutator.java
- solr/core/src/test/org/apache/solr/cloud/SplitShardWithNodeRoleTest.java
[SOLR-16753](https://issues.apache.org/jira/browse/SOLR-16753): Fix PRS state update for splitShard
> SOLR-16753: Fix PRS state update for splitShard

- solr/CHANGES.txt
- solr/modules/s3-repository/build.gradle
- solr/modules/s3-repository/src/java/org/apache/solr/s3/S3OutputStream.java
- solr/modules/s3-repository/src/test/org/apache/solr/s3/S3OutputStreamMockitoTest.java
The `complete()` method is currently being called from the `close()`, which is called from try-with-resources
> SOLR-16886: Don't commit multi-part uploads that have been aborted

- solr/test-framework/src/java/org/apache/solr/JSONTestUtil.java
https://issues.apache.org/jira/browse/SOLR-16898
It's found that a possibly debug statement https://github.com/apache/solr/commit/e5ca599f51f859834efde2e190ba1e3f17cbb4b1#diff-1098b7bd3712859836c1915cc5af5190782fb27183e5750d4bbf1d2d3e229c92R80 creates a large amount of log for our test case in https://github.com/cowpaths/fullstory-solr/actions/runs/5591120540/jobs/10221763319 and caused GC limit exception hence test failure
We should remove such println assuming that's leftover from debugging
No new tests
> SOLR-16898: Remove a println statement from JSONTestUtil

- solr/core/src/java/org/apache/solr/servlet/CoordinatorHttpSolrCall.java
https://issues.apache.org/jira/browse/SOLR-16871
PR https://github.com/apache/solr/pull/1762 fixes various race condition for coordinator node. One of the fixes restricts the name of the synthetic core to ensure at most 1 core is created per coordinator node.
Unfortunately unit test cases failed because it could still add 2 cores for the first coordinator node (1st from collection creation with default naming scheme, and then 2nd from addReplica call with a different name)
For example this is the list of replicas on a failed run of `TestCoordinatorRole#testConcurrentAccess` which is supposed to only create 4 cores, one of each for the 4 coordinator nodes:
```
core_node2:{
"core":".sys.COORDINATOR-COLL-conf_shard1_replica_n1",
"leader":"true",
"node_name":"127.0.0.1:49656_solr", …
```
> SOLR-16871: Fix for duplicated replica added from first coordinator node

- solr/core/src/java/org/apache/solr/cli/SolrCLI.java
A merge from master to branch_9x includes reference to `PostTool` which is not available in 9x
Details in https://github.com/apache/solr/pull/1784#issuecomment-1642461497
Removed the reference to `PostTool`. This branch is based on branch_9x
> SOLR-16842: Remove reference to PostTool for branch_9x

- solr/distribution/build.gradle
- solr/docker/build.gradle
[SOLR-16901](https://issues.apache.org/jira/browse/SOLR-16901)
Testing:
```
$ ./gradlew assembleRelease -Psign=false -x signJarsPublication
$ ./gradlew testBuildDockerfileOfficial -Psign=false
```
> SOLR-16901: Fix gradle workflow for non-signed official images

- solr/solr-ref-guide/modules/upgrade-notes/pages/major-changes-in-solr-9.adoc
https://issues.apache.org/jira/browse/SOLR-16693
I forgot the upgrade notes.  Even though 9.3 was released, this can be added retroactively.  I also augmented the release highlights: https://cwiki.apache.org/confluence/display/SOLR/ReleaseNote9_3_0
> SOLR-16693 upgrade notes

- solr/core/src/java/org/apache/solr/servlet/CoordinatorHttpSolrCall.java
https://issues.apache.org/jira/browse/SOLR-16871
While the previous fix #1762  does seem to avoid race condition, unfortunately, it was still happening on some test runs, for example https://github.com/cowpaths/fullstory-solr/actions/runs/5616774664/job/15219717699
The issue is that even we sync the `addReplica` block, we could still run into race condition if:
1. Request 1 in Thread 1 hits node 1 and attempt to create synthetic collection
2. Request 2 in Thread 2 also hits node 1, due to race condition it might attempt to create the synthetic collection too, but in this case it's fine as we ignore the creation exception if it's "already exists collection"
3. Request 2 in Thread 2 can proceed and claim the synchronize block, it scans for replica and it might not see any, since Thread 1 …
> SOLR-16871: Synchronize on a larger block to avoid race condition in CoordinatorHttpSolrCall init

- solr/solr-ref-guide/modules/deployment-guide/pages/replica-management.adoc
Fixed path in move-replica API (v2) documentation.
> Fix a typo in move-replica API documentation

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cli/HealthcheckTool.java
- solr/packaging/test/test_healthcheck.bats
https://issues.apache.org/jira/browse/SOLR-16850
Alert a user, since you can use -solrUrl to point healthcheck at a standalone mode solr node.   
No zkHost means not in SolrCloud mode!
Bats test.
> SOLR-16850: Notify a user if they run Healthcheck againsts a standalone mode Solr

- solr/CHANGES.txt
- solr/prometheus-exporter/conf/solr-exporter-config.xml
https://issues.apache.org/jira/browse/SOLR-16906
The Prometheus exporter config provided with Solr seems to unintentionally ignore replication-related metrics. This change lets the Prometheus exporter correctly collect/expose them.
Fix the regex that intends to match REPLICATION category metrics. REPLICATION metrics start with `REPLICATION./replication`, but the previous regex misses the `/` (slash) and fails to match them.
Start a `solr-exporter` process and make a request to `http://localhost:9983/metrics` and confirm metrics such as `solr_metrics_core_replication_leader` or `solr_metrics_core_requests_total{category="REPLICATION"}` show up.
```
$ cd solr/packaging/build/dev
$ ./bin/solr start -f
$ ./bin/solr create -c films -s 2 -rf 2
$ ./prometheus-exporter/bin/solr-exporter -f …
```
> SOLR-16906: Correctly capture REPLICATION metrics in Prometheus config

- gradle/testing/randomization/policies/solr-tests.policy
- solr/CHANGES.txt
- solr/packaging/test/test_security_manager.bats
- solr/server/etc/security.policy
* SOLR-16905: Java Security Manager rules don't inclue "solr.allowPaths" property
Since solr 9 java security policy is enabled by default. When you configure the allowPaths property, acces will be denied by java security policy.
To grant acces this creates a policy for that.
Additionally my IDE deletes Spaces of empty lines, thats why there are changes on multiple lines.
Unfortunately I don't know how to write tests for this
- [] I have added tests for my changes.
> SOLR-16905: fix(java security policy): allow access to configured value of allowPaths

- solr/solr-ref-guide/modules/indexing-guide/pages/partial-document-updates.adoc
There is no Jira issue, as this is a trivial ref guide update.
The Field Storage requirements for Atomic Updates needed a little extra clarity around docValues.
> Clarify Field Storage requirements for partial doc updates

- solr/CHANGES.txt
- solr/bin/solr
- solr/bin/solr.cmd
https://issues.apache.org/jira/browse/SOLR-16922
Set the max port to be `64535` (`1_000` less than the max port number `65535`, as embedded zookeeper is started on `SOLR_PORT + 1_000`, not `+ 10_000` (used by RMI which has a separate check)
> SOLR-16922: Scripts wrongly prohibit embedded zookeeper when solr port is between 55535 and 64535

- solr/core/src/test/org/apache/solr/util/RegexFileFilterTest.java
- solr/core/src/test/org/apache/solr/util/TestUtils.java
https://issues.apache.org/jira/browse/SOLR-16928
Adding some unit tests that cover the `RegexFileFilter` class and the `StrUtils.toLower` method
N/A
N/A
> SOLR-16928: Add missing unit tests for RegexFileFilter and StrUtils.toLower

- solr/CHANGES.txt
- solr/solrj/src/java/org/apache/solr/client/solrj/cloud/SocketProxy.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/Http2SolrClient.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/Http2SolrClientProxyTest.java
https://issues.apache.org/jira/browse/SOLR-16859
> SOLR-16859 Missing Proxy support for Http2SolrClient

- build.gradle
- gradle/testing/fail-on-unsupported-jdk.gradle
- gradle/testing/randomization.gradle
https://issues.apache.org/jira/browse/SOLR-16733
Many (> 700!) tests fail with this OS/JDK combination due to a JDK bug that crops up when the Security Manager is used.
Disabling the Security Manager in this case isn't ideal, but is really kindof necessary to test this OS/Java combination in any meaningful way.
~~This PR makes a change to randomization.gradle to skip enabling the SecurityManager if the known problem OS/Java combination is present.  A warning is logged as a breadcrumb to avoid misleading users who wanted to run tests with SecurityManager, including a pointer to SOLR-16733.~~
Rather than disabling the Security Manager in these cases, feedback below has suggested failing the test run entirely before it really kicks off.  If JDK20+Mac+SecurityManager is fundamentally broken, …
> SOLR-16733: Fail 'test' tasks using JDK20 on Mac

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/admin/api/NodeHealthAPI.java
https://issues.apache.org/jira/browse/SOLR-16944
> SOLR-16944 V2 API /api/node/health should be governed by "health" permission

- solr/solr-ref-guide/modules/configuration-guide/pages/v2-api.adoc
I haven't found this alias anywhere in code. When I checked 9.3 RC1 /api/c isn't handled either. Perhaps I miss something.
> Update v2-api.adoc: remove mention of /api/c

- solr/solrj/src/java/org/apache/solr/client/solrj/impl/Http2SolrClient.java
https://issues.apache.org/jira/browse/SOLR-16265
Fixing error seen below when passing a bad url to the client.
> ERROR: Cannot invoke "org.eclipse.jetty.client.api.Request.abort(java.lang.Throwable)" because "req" is null
> SOLR-16265: Fix NPE for req in Http2SolrClient

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/core/ClusterSingletons.java
- solr/core/src/test/org/apache/solr/handler/TestContainerPlugin.java
https://issues.apache.org/jira/browse/SOLR-16946
When a Cluster Singleton plugin config is updated via the /cluster/plugin API, the `ClusterSingletons.modified` method calls the `added` and `deleted` methods, in that order.
This effect of this is to leave no entry for the plugin in the `singletonMap` map, because the entries are keyed by the plugin name.
The `added` method will overwrite the entry for the existing plugin, and the `deleted` method will remove the new entry that was put by the `added` method.  
The solution is to reverse the order in which the `added` and `deleted` methods are called from the `modified` method. Removing the existing plugin from the map first, and then adding the new one means that the new one will remain in the map, and it will be found and stopped when the …
> SOLR-16946: Updated Cluster Singleton plugins are stopped correctly when the Overseer is closed

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cli/ApiTool.java
- solr/core/src/java/org/apache/solr/cli/CreateTool.java
- solr/core/src/java/org/apache/solr/cli/DeleteTool.java
- solr/core/src/test/org/apache/solr/cli/ApiToolTest.java
- solr/solrj-zookeeper/src/java/org/apache/solr/client/solrj/impl/NodeValueFetcher.java
- solr/solrj-zookeeper/src/java/org/apache/solr/client/solrj/impl/SolrClientNodeStateProvider.java
- solr/solrj/src/java/org/apache/solr/client/solrj/response/SimpleSolrResponse.java
- solr/solrj/src/java/org/apache/solr/common/IteratorWriter.java
- solr/solrj/src/java/org/apache/solr/common/SolrDocumentList.java
- solr/solrj/src/java/org/apache/solr/common/util/Utils.java
- solr/solrj/src/java/org/noggit/JSONWriter.java
https://issues.apache.org/jira/browse/SOLR-16933
So the initial issue here is that the SolrDocumentList serialization used to only be really handled by the `SolrRequestWriter` (solr core only), and if you tried to use a general JSON serializer (`JSONWriter`), it would try to serialize the `SolrDocumentList` as an ArrayList of SolrDocuments, because it extends `ArrayList<SolrDocument>`. This meant that the `numFound`, `numFoundExact`, `start`, etc. fields were lost.
Two solutions here:
1. `SolrDocumentList` now extends `MapWriter`, so that it will serialize correctly even when used with a "dumb" serializer.
2. The CLI tools that just print output from the APIs they call (`ApiTool`, `CreateTool`, `DeleteTool`), should use the `NoOpResponseParser("json")`, and just plainly echo the output of …
> SOLR-16933: Include full query response in API tool

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/core/SolrConfig.java
- solr/core/src/java/org/apache/solr/core/SolrCore.java
- solr/core/src/java/org/apache/solr/core/SolrResourceLoader.java
- solr/core/src/java/org/apache/solr/handler/component/SearchHandler.java
- solr/core/src/java/org/apache/solr/util/circuitbreaker/CPUCircuitBreaker.java
- solr/core/src/java/org/apache/solr/util/circuitbreaker/CircuitBreaker.java
- solr/core/src/java/org/apache/solr/util/circuitbreaker/CircuitBreakerManager.java
- solr/core/src/java/org/apache/solr/util/circuitbreaker/CircuitBreakerRegistry.java
- solr/core/src/java/org/apache/solr/util/circuitbreaker/MemoryCircuitBreaker.java
- solr/core/src/test-files/solr/collection1/conf/solrconfig-legacy-circuitbreaker.xml
- solr/core/src/test-files/solr/collection1/conf/solrconfig-pluggable-circuitbreaker.xml
- solr/core/src/test/org/apache/solr/util/BaseTestCircuitBreaker.java
- solr/core/src/test/org/apache/solr/util/TestLegacyCircuitBreaker.java
- solr/server/solr/configsets/_default/conf/solrconfig.xml
- solr/server/solr/configsets/sample_techproducts_configs/conf/solrconfig.xml
- solr/solr-ref-guide/modules/deployment-guide/pages/circuit-breakers.adoc
https://issues.apache.org/jira/browse/SOLR-15474
This is a continuation of the effort from PR #193 which had grown out of date by almost 2 years and no activity.
Thus I updated that branch to main and squashed as one commit to kickstart this PR. I intend to bring it to mergable state.
To do before committable
> SOLR-15474 Make Circuit breakers pluggable (take 2)

- solr/solr-ref-guide/modules/configuration-guide/pages/configuring-solr-xml.adoc
The Solr Reference Guide for Configuring solr.xml contains an invalid parameter in the example file.
I replaced the invalid parameter `compressor` with the correct parameter `stateCompressor`
No tests were performed.
> Fix configuration parameter stateCompressor in solr-xml reference doc

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/core/CoreContainer.java
- solr/core/src/java/org/apache/solr/core/NodeConfig.java
- solr/core/src/java/org/apache/solr/core/SolrConfig.java
- solr/core/src/java/org/apache/solr/core/SolrCore.java
- solr/core/src/java/org/apache/solr/core/SolrXmlConfig.java
- solr/core/src/java/org/apache/solr/search/CacheConfig.java
- solr/core/src/java/org/apache/solr/search/CaffeineCache.java
- solr/core/src/java/org/apache/solr/search/SolrCache.java
- solr/core/src/java/org/apache/solr/search/SolrIndexSearcher.java
- solr/core/src/test-files/solr/collection1/conf/solrconfig-nodelevelcaches.xml
- solr/core/src/test-files/solr/solr-nodelevelcaches.xml
- solr/core/src/test/org/apache/solr/core/TestSolrXml.java
- solr/core/src/test/org/apache/solr/search/TestThinCache.java
- solr/core/src/test/org/apache/solr/search/ThinCache.java
- solr/solr-ref-guide/modules/configuration-guide/pages/configuring-solr-xml.adoc
- solr/test-framework/src/java/org/apache/solr/util/TestHarness.java
> SOLR-16654: Add support for node-level caches

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/core/SolrConfig.java
https://issues.apache.org/jira/browse/SOLR-16958
Switch back to the use of `==` to check whether the supplied version is `LATEST` or the actual latest version (e.g. `9.7.0`).
> SOLR-16958: Fix spurious warning about LATEST luceneMatchVersion

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/servlet/LoadAdminUiServlet.java
- solr/core/src/test/org/apache/solr/servlet/LoadAdminUiServletTest.java
- solr/modules/jwt-auth/src/java/org/apache/solr/security/jwt/JWTAuthPlugin.java
- solr/modules/jwt-auth/src/java/org/apache/solr/security/jwt/JWTIssuerConfig.java
- solr/modules/jwt-auth/src/test-files/solr/security/jwt_plugin_jwk_security.json
- solr/modules/jwt-auth/src/test-files/solr/security/jwt_plugin_jwk_security_blockUnknownFalse.json
- solr/modules/jwt-auth/src/test/org/apache/solr/security/jwt/JWTAuthPluginIntegrationTest.java
- solr/modules/jwt-auth/src/test/org/apache/solr/security/jwt/JWTAuthPluginTest.java
- solr/modules/jwt-auth/src/test/org/apache/solr/security/jwt/JWTIssuerConfigTest.java
- solr/solr-ref-guide/modules/deployment-guide/pages/jwt-authentication-plugin.adoc
https://issues.apache.org/jira/browse/SOLR-16897
This is the "back-end" part of '[code with PKCE](https://github.com/apache/solr/pull/1791)' contribution. 
The back-end code is mainly for configuration. This is where the different options are configured.
This PR adds _tokenEndpoint_ and _authorizationFlow_ options.
> add support of OAuth 2.0/OIDC 'code with PKCE' flow (back-end)

- solr/bin/solr
- solr/packaging/test/test_start_solr.bats
https://issues.apache.org/jira/browse/SOLR-16956
In doing some other testing, I noticed that `bin/solr stop -p 7574` didn't work, I get back the error message:
```
Found 2 Solr nodes running! Must either specify a port using -p or -all to stop all Solr nodes on this host.
```
Set the PROVIDED_SOLR_PORT to the SOLR_PORT.
extended bats tests
> SOLR-16956: fix not being able to stop a solr by port number

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/ContentStreamHandlerBase.java
- solr/core/src/java/org/apache/solr/handler/component/SearchHandler.java
- solr/core/src/java/org/apache/solr/util/circuitbreaker/CircuitBreaker.java
- solr/core/src/java/org/apache/solr/util/circuitbreaker/CircuitBreakerRegistry.java
- solr/core/src/test-files/solr/collection1/conf/solrconfig-pluggable-circuitbreaker.xml
- solr/core/src/test/org/apache/solr/util/BaseTestCircuitBreaker.java
- solr/solr-ref-guide/modules/deployment-guide/pages/circuit-breakers.adoc
https://issues.apache.org/jira/browse/SOLR-16954
> SOLR-16954 Make Circuit Breakers available for Update Requests

- solr/api/src/java/org/apache/solr/client/api/endpoint/AddReplicaPropertyApi.java
- solr/api/src/java/org/apache/solr/client/api/endpoint/AliasPropertyApis.java
- solr/api/src/java/org/apache/solr/client/api/endpoint/DeleteAliasApi.java
- solr/api/src/java/org/apache/solr/client/api/endpoint/DeleteCollectionApi.java
- solr/api/src/java/org/apache/solr/client/api/endpoint/DeleteCollectionBackupApi.java
- solr/api/src/java/org/apache/solr/client/api/endpoint/DeleteCollectionSnapshotApi.java
- solr/api/src/java/org/apache/solr/client/api/endpoint/DeleteNodeApi.java
- solr/api/src/java/org/apache/solr/client/api/endpoint/DeleteReplicaApi.java
- solr/api/src/java/org/apache/solr/client/api/endpoint/DeleteReplicaPropertyApi.java
- solr/api/src/java/org/apache/solr/client/api/endpoint/ListAliasesApi.java
- solr/api/src/java/org/apache/solr/client/api/endpoint/ListCollectionBackupsApi.java
- solr/api/src/java/org/apache/solr/client/api/endpoint/ListCollectionsApi.java
- solr/api/src/java/org/apache/solr/client/api/endpoint/ListConfigsetsApi.java
- solr/api/src/java/org/apache/solr/client/api/endpoint/ReloadCollectionApi.java
- solr/core/src/test/org/apache/solr/handler/configsets/ListConfigSetsAPITest.java
https://issues.apache.org/jira/browse/SOLR-16825
Many of Solr's api definitions rely on `@Produces` annotation to explicitly declare the response content types that they support.
But it turns out that this wasn't ever really necessary - Jersey can match the API invocation up with an appropriate MessageBodyWriter without the help of this annotation.  Only those APIs that want to specifically restrict their response formats need by annotated.
Ultimately it's a minor problem, but in addition to cluttering up our API definitions these annotations also are the cause of some noisy messages in our build logs. 
All `@Produces` annotations have been removed from the `api` submodule.  We'll need this annotation for some APIs that are very selective about their response content-type (e.g. our …
> SOLR-16825: Remove unneeded @Produces annotations

- solr/core/src/java/org/apache/solr/api/Api.java
- solr/core/src/java/org/apache/solr/core/TracerConfigurator.java
- solr/core/src/java/org/apache/solr/handler/admin/api/RestoreCollectionAPI.java
- solr/core/src/java/org/apache/solr/util/tracing/SimplePropagator.java
- solr/core/src/java/org/apache/solr/util/tracing/TraceUtils.java
- solr/core/src/test/org/apache/solr/util/tracing/BasicAuthIntegrationTracingTest.java
- solr/core/src/test/org/apache/solr/util/tracing/TestDistributedTracing.java
- solr/core/src/test/org/apache/solr/util/tracing/TestSimplePropagatorDistributedTracing.java
- solr/modules/jaegertracer-configurator/src/test/org/apache/solr/jaeger/TestJaegerConfigurator.java
- solr/modules/opentelemetry/src/test/org/apache/solr/opentelemetry/OtelTracerConfiguratorTest.java
- solr/server/resources/log4j2.xml
- solr/test-framework/src/java/org/apache/solr/cloud/MiniSolrCloudCluster.java
https://issues.apache.org/jira/browse/SOLR-15367
**PR for 9.x branch**
This is a 9.x version of https://github.com/apache/solr/pull/1854 for evaluation.
Almost all changes relevant to OpenTracing are in SimplePropagator. I made an effort to minimize changes that are not on main branch. ideally we'd reach a state where this has working basic generation of traces and remains frozen on 9.x until 10.x starts releasing and everyone transitions automatically to the new OTEL-based impl.
Similar to main branch, this is enabled by default. this could be an issue for setups that already have tracing enabled, so I am ok with off by default if switching this off via system property is too much to handle in a minor upgrade.
Please provide a short description of the approach taken to implement your …
> SOLR-15367 [9.x] Convert "rid" functionality into a default Tracer

- solr/core/src/java/org/apache/solr/util/circuitbreaker/CPUCircuitBreaker.java
- solr/core/src/java/org/apache/solr/util/circuitbreaker/MemoryCircuitBreaker.java
- solr/core/src/test-files/solr/collection1/conf/solrconfig-pluggable-circuitbreaker.xml
https://issues.apache.org/jira/browse/SOLR-16954
The tests ran fine both on localhost and github actions, but on Jenkins this one tripped during indexing content in `indexDocs()`. Must be some difference in memory handling, perhaps how many tests are ran in parallel in Jeknins vs GitHub actions/Crave, or the `-Xmx` setting??
Output from [failing test](https://ci-builds.apache.org/job/Solr/job/Solr-Check-main/7905/testReport/org.apache.solr.util/TestCircuitBreaker/classMethod/):
> Seen JVM heap memory usage 383.848.016 and allocated threshold 383.778.816
383Mb threshold suggests that the VM is ran with 512Mb RAM, which makes sense.
> SOLR-16954: Fix test failure in UPDATE circuit breaker

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/core/SolrCore.java
- solr/core/src/java/org/apache/solr/jersey/PostRequestLoggingFilter.java
https://issues.apache.org/jira/browse/SOLR-16044
> SOLR-16044: SlowRequest logging disabled if SolrCore logger set to ERROR

- solr/core/src/test/org/apache/solr/util/BaseTestCircuitBreaker.java
https://issues.apache.org/jira/browse/SOLR-16954
There were still some test failures in Jenkins due to low memory on the runner, so it tripped on 99%
> SOLR-16954: Fix test failures from updates

- solr/CHANGES.txt
- solr/core/src/test/org/apache/solr/util/tracing/TestSimplePropagatorDistributedTracing.java
- solr/solrj/src/java/org/apache/solr/client/solrj/SolrRequest.java
- solr/solrj/src/java/org/apache/solr/client/solrj/request/UpdateRequest.java
https://issues.apache.org/jira/browse/SOLR-16950
Fix support for client side manual transaction ids on UpdateRequest.
Currently due to UpdateRequest getting recreated, the headers are lost so propagation is broken.
> SOLR-16950 SimpleTracer propagation for manual transaction ids

- solr/bin/solr
https://issues.apache.org/jira/browse/SOLR-16981
```
bin/solr stop -h
Usage: solr stop [-k key] [-p port] [-all] [-V]
-k <key>      Stop key; default is solrrocks
-p <port>     Specify the port the Solr HTTP listener is bound to
-all          Find and stop all running Solr servers on this host
-V/-verbose   Verbose messages from this script
NOTE: To see if any Solr servers are running, do: solr status
```
The behavior with only `solr stop` is not clearly documented, but it can be seen from [script comments](https://github.com/apache/solr/blob/main/solr/bin/solr#L1469-L1470) that the intent is that a pure `solr stop` will check PIDs, and if exactly one is found, it will stop it. If more are found, it will abort and ask user to pass `-all`.
However, if the `SOLR_HOME` env var is set (as it …
> SOLR-16981: bin/solr stop improvements

- solr/core/src/java/org/apache/solr/handler/component/RealTimeGetComponent.java
It's strange to be logging this (multiple lines per request) at info level. Seems like some leftover when testing/debugging
> Reduce logging level for slice -> shard mapping in RTG

- solr/CHANGES.txt
- solr/core/src/test/org/apache/solr/cloud/api/collections/TestCollectionAPI.java
- solr/core/src/test/org/apache/solr/core/TestSolrXml.java
- solr/core/src/test/org/apache/solr/util/TestUtils.java
- solr/solrj/src/java/org/apache/solr/common/util/StrUtils.java
- solr/solrj/src/test/org/apache/solr/common/util/StrUtilsTest.java
The translation between V1 parameters into the new code based in V2 APIs is using `StrUtils.getBool(String param)` to parse from string. This `StrUtils.getBool` is intended to be more flexible than `Boolean.parseBoolean()`, and accepts things like `yes`/`no`, `on`/`off`, but it's case sensitive.
This PR makes it case insensitive. Note that this code is often used for reading configuration files, so those will also now be case insensitive when this is merged. 
An alternative could be to have a new method to be case insensitive and use that one for the API parameters, but really, if this code is supposed to be more flexible than `Boolean.parseBoolean()`, I think make it case insensitive is the right way to go.
I was also a bit surprised that this code uses `startsWith`, for the most part, …
> SOLR-16978: Be case insensitive when parsing booleans from text

- solr/core/src/java/org/apache/solr/handler/component/QueryElevationComponent.java
Very minor change for extensibility.  IMO doesn't warrant a JIRA issue.
> QueryElevationComponent: declare some methods as protected

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/util/circuitbreaker/CPUCircuitBreaker.java
- solr/core/src/java/org/apache/solr/util/circuitbreaker/CircuitBreakerManager.java
- solr/core/src/java/org/apache/solr/util/circuitbreaker/LoadAverageCircuitBreaker.java
- solr/core/src/test-files/solr/collection1/conf/solrconfig-pluggable-circuitbreaker.xml
- solr/core/src/test/org/apache/solr/util/BaseTestCircuitBreaker.java
- solr/solr-ref-guide/modules/deployment-guide/pages/circuit-breakers.adoc
- solr/solr-ref-guide/modules/upgrade-notes/pages/major-changes-in-solr-9.adoc
SOLR-15056  add circuit breaker for CPU utilization, use accurate name for load average circuit breaker, update docs and tests
The current CPU load circuit breaker is based on load average instead of CPU utilization. Rename that to an accurate name and create a new circuit breaker based on CPU utilization. Improved documentation for all circuit breakers by linking to the JMX metric they are based on.
Use existing metrics framework to get a CPU utilization metric. Not all JVMs provide that. Add unit test and documentation.
Rename existing CPU circuit breaker to LoadAverageCircuitBreaker, rename unit test.
Unit tests based on existing test. I have not run a system test (run up system load during a load benchmark).
> SOLR-15056:  add circuit breaker for CPU, fix load circuit breaker

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/core/SolrCore.java
- solr/core/src/java/org/apache/solr/util/circuitbreaker/AveragingMetricProvider.java
- solr/core/src/java/org/apache/solr/util/circuitbreaker/CircuitBreaker.java
- solr/core/src/java/org/apache/solr/util/circuitbreaker/CircuitBreakerManager.java
- solr/core/src/java/org/apache/solr/util/circuitbreaker/CircuitBreakerRegistry.java
- solr/core/src/java/org/apache/solr/util/circuitbreaker/MemoryCircuitBreaker.java
- solr/core/src/test/org/apache/solr/util/BaseTestCircuitBreaker.java
https://issues.apache.org/jira/browse/SOLR-16968
Introduced a new utility class `AveragingMetricProvider` that will cache the average for a `double` value provided by the breaker. Uses a scheduled executor every 5 seconds, which is shared by all instances of this class. This same utility can be used by other CBs to achieve the same, but I started with `MemoryCircuitBreaker`.
As this requires some cleanup of executor threads, CircuitBreaker now implements `Closeable` and the registry will close all CBs on close, which is also called from `CoreContainer#doClose`. I also added some synchonization on the map, which isn't really necessary in normal runtime, but I figured useful for tests.
*NOTE* that this may conflict with other in-flight CB PRs...
> SOLR-16968: The MemoryCircuitBreaker now uses average heap usage

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/response/JacksonJsonWriter.java
https://issues.apache.org/jira/browse/SOLR-16925
`PrettyPrinter` is stateful, so we need a new instance every time.
> SOLR-16925: Fix indentation for JacksonJsonWriter

- solr/CHANGES.txt
- solr/core/src/test/org/apache/solr/cloud/overseer/ZkStateReaderTest.java
- solr/solrj-zookeeper/src/java/org/apache/solr/common/cloud/PerReplicaStatesOps.java
- solr/solrj-zookeeper/src/java/org/apache/solr/common/cloud/ZkStateReader.java
- solr/solrj/src/java/org/apache/solr/common/util/CommonTestInjection.java
https://issues.apache.org/jira/browse/SOLR-16701
This fixes a race condition on PRS enabled collection deletion, which triggers the exception:
```
org.apache.solr.common.SolrException: Error fetching per-replica states
at __randomizedtesting.SeedInfo.seed([C2BFFBF8FE49C1E1:F1C8D9E308D2745]:0)
at app//org.apache.solr.common.cloud.PerReplicaStatesFetcher.fetch(PerReplicaStatesFetcher.java:49)
at app//org.apache.solr.common.cloud.PerReplicaStatesFetcher$LazyPrsSupplier.lambda$new$0(PerReplicaStatesFetcher.java:62)
at app//org.apache.solr.common.cloud.DocCollection$PrsSupplier.get(DocCollection.java:515)
at app//org.apache.solr.common.cloud.Replica.isLeader(Replica.java:314)
at app//org.apache.solr.common.cloud.Slice.findLeader(Slice.java:242)
at …
```
> SOLR-16701: Race condition on PRS enabled collection deletion

- solr/CHANGES.txt
- solr/webapp/web/js/angular/app.js
- solr/webapp/web/js/angular/controllers/login.js
https://issues.apache.org/jira/browse/SOLR-16991
There's an intermittent failure in JWT authentication, with a roughly 20% failure rate (depends on the network latency). Upon investigating, I identified a race condition due to simultaneous HTTP requests within the authentication process. 
Here's the chain of events:
1.   The user initiates the OAuth/IdProvider authentication process. Once completed, they are redirected back to Solr.
2.   _LoginController_ is then activated to handle the response from the IdProvider.
3.   _LoginController_ calls "[resetMenu](https://github.com/apache/solr/blob/51c1a785c4611d0103f7b73c8adefa028d608bcd/solr/webapp/web/js/angular/controllers/login.js#L21)" method which triggers requests to the "admin/info/system" and "admin/cores" endpoints. These requests …
> SOLR-16991: Fix bug: Concurrent requests failing JWT Auth intermittently

- solr/modules/jwt-auth/build.gradle
- solr/modules/jwt-auth/src/java/org/apache/solr/security/jwt/JWTAuthPlugin.java
- solr/modules/jwt-auth/src/java/org/apache/solr/security/jwt/JWTVerificationkeyResolver.java
- solr/modules/jwt-auth/src/test/org/apache/solr/security/jwt/JWTAuthPluginIntegrationTest.java
- solr/modules/jwt-auth/src/test/org/apache/solr/security/jwt/JWTAuthPluginTest.java
- solr/modules/jwt-auth/src/test/org/apache/solr/security/jwt/JWTIssuerConfigTest.java
- solr/modules/jwt-auth/src/test/org/apache/solr/security/jwt/JWTVerificationkeyResolverTest.java
(Jo JIRA)
Basically followed recommendations from IDEA.
We still use Apache HTTPClient in some tests, did not cross that bridge now
> Clean up some deprecations and warnings in jwt-auth module

- solr/core/src/java/org/apache/solr/cloud/api/collections/CreateAliasCmd.java
- solr/core/src/java/org/apache/solr/servlet/HttpSolrCall.java
- solr/core/src/test/org/apache/solr/cloud/CreateRoutedAliasTest.java
- solr/solr-ref-guide/modules/deployment-guide/pages/alias-management.adoc
Don't overwrite list of collections in a Routed Alias when updating parameters. (#864)
(cherry picked from commit adeab2d88f5bbb5bf56d5d4fc5fda349b9c8ee10) 
https://issues.apache.org/jira/browse/SOLR-16194
> SOLR-16194: Don't overwrite list of collections in a Routed Alias

- solr/CHANGES.txt
- solr/solrj-streaming/src/java/org/apache/solr/client/solrj/io/SolrClientCache.java
- solr/solrj-streaming/src/java/org/apache/solr/client/solrj/io/stream/CloudSolrStream.java
- solr/solrj-streaming/src/java/org/apache/solr/client/solrj/io/stream/DeepRandomStream.java
- solr/solrj-streaming/src/java/org/apache/solr/client/solrj/io/stream/FeaturesSelectionStream.java
- solr/solrj-streaming/src/java/org/apache/solr/client/solrj/io/stream/ParallelListStream.java
- solr/solrj-streaming/src/java/org/apache/solr/client/solrj/io/stream/SignificantTermsStream.java
- solr/solrj-streaming/src/java/org/apache/solr/client/solrj/io/stream/StreamExecutorHelper.java
- solr/solrj-streaming/src/java/org/apache/solr/client/solrj/io/stream/TextLogitStream.java
- solr/solrj-streaming/src/java/org/apache/solr/client/solrj/io/stream/TopicStream.java
- solr/solrj-streaming/src/java/org/apache/solr/client/solrj/io/stream/TupleStream.java
- solr/solrj-streaming/src/test/org/apache/solr/client/solrj/io/stream/StreamExecutorHelperTest.java
- solr/solrj/src/java/org/apache/solr/common/util/ExecutorUtil.java
- solr/solrj/src/test/org/apache/solr/common/util/ExecutorUtilTest.java
-- suggests CloudSolrStream concurency race condition
https://issues.apache.org/jira/browse/SOLR-16992
Introduced a new method to deal with the executor task list work. it will wait for everything to complete and fully shut down. it will also attempt to throw the exception if one occurs, attaching all other exceptions to it.
refactored all previous uses to move to this common method.
Also, SolrClientCache is more strict about being closed
Open Questions
- where should the executor method live? it is now in a new class `StreamExecutorHelper` but it could easily move to ExecutorUtil, it is generic enough.
- I did not tackle adding 'closed' flags to all tuple stream impls. this might not strictly be needed to plug this gap. it could be a followup task given the amount of refactoring needed. …
> SOLR-16992 Non-reproducible StreamingTest failures

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/update/processor/DistributedZkUpdateProcessor.java
- solr/core/src/test/org/apache/solr/cloud/LeaderElectionIntegrationTest.java
- solr/solrj-zookeeper/src/java/org/apache/solr/common/cloud/ZkStateReader.java
https://issues.apache.org/jira/browse/SOLR-17004
Trying to get the leader with retry ends up using a lot of watches and locks on collection state watchers. This ends up being contentious and slows down processing. In most cases we can pull the leader right from the `clusterState` and fall back to the slower logic if the leader is not setup yet.
Update waitForState to check the predicate against the known clusterState before falling back to the retry logic.
> SOLR-17004: ZkStateReader waitForState should check clusterState before using watchers

- solr/CHANGES.txt
- solr/webapp/web/js/angular/controllers/cloud.js
The green bar should be 100% wide for the largest core, and the other should be as wide as their relative size compared to the largest core.
> Fix the admin UI green core-size graph on nodes screen

- build.gradle
- solr/CHANGES.txt
This is usual maintenance:
-  to support Java 21/22
-  Allow upgrading of commons-io to 2.14.0
> Update forbiddenapis to 3.6

- solr/CHANGES.txt
- solr/api/src/java/org/apache/solr/client/api/model/CollectionBackupDetails.java
- solr/core/src/java/org/apache/solr/cloud/api/collections/BackupCmd.java
- solr/core/src/java/org/apache/solr/core/backup/BackupProperties.java
- solr/core/src/java/org/apache/solr/handler/admin/api/CreateCollectionBackupAPI.java
- solr/core/src/test/org/apache/solr/cloud/api/collections/LocalFSCloudIncrementalBackupTest.java
- solr/core/src/test/org/apache/solr/cloud/api/collections/PurgeGraphTest.java
- solr/solr-ref-guide/modules/deployment-guide/pages/collection-management.adoc
- solr/solrj/src/java/org/apache/solr/client/solrj/request/CollectionAdminRequest.java
- solr/test-framework/src/java/org/apache/solr/cloud/api/collections/AbstractIncrementalBackupTest.java
Currently backups have some properties attached such as `configName`, `collectionAlias`, `indexVersion`, etc. It would be useful to allow custom properties/annotations to add some information coming from the process that triggers the backup. For example, say you have a process that consumes from a queue, adds documents to Solr and then triggers a backup command, the backup could include the queue offset at the time of triggering the backup so that the application could potentially continue processing from such offset upon restore.
> SOLR-16852: Let backups have custom key/values

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/response/JacksonJsonWriter.java
- solr/core/src/test/org/apache/solr/response/JSONWriterTest.java
https://issues.apache.org/jira/browse/SOLR-17009
> SOLR-17009 json.wrf parameter ignored in JacksonJsonWriter

- solr/modules/hadoop-auth/src/test-files/krb5-template.conf
- solr/modules/hadoop-auth/src/test/org/apache/solr/security/hadoop/SaslZkACLProviderTest.java
- solr/test-framework/src/java/org/apache/solr/cloud/ZkTestServer.java
https://issues.apache.org/jira/browse/SOLR-17013
> SOLR-17013: Always use 127.0.0.1 for ZK instead of localhost in tests

- solr/bin/solr
https://issues.apache.org/jira/browse/SOLR-16644
> SOLR-16644: Only warn entropy on Linux

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cloud/ZkCLI.java
- solr/solrj-zookeeper/src/java/org/apache/solr/common/cloud/ClusterProperties.java
https://issues.apache.org/jira/browse/SOLR-17019
> SOLR-17019: ZkCli should create subpaths when necessary

- solr/core/src/java/org/apache/solr/cloud/RecoveryStrategy.java
- solr/core/src/java/org/apache/solr/cloud/ShardLeaderElectionContext.java
- solr/core/src/java/org/apache/solr/cloud/ZkController.java
- solr/core/src/java/org/apache/solr/cloud/api/collections/DeleteNodeCmd.java
- solr/core/src/java/org/apache/solr/cloud/api/collections/LeaderRecoveryWatcher.java
- solr/solrj/src/java/org/apache/solr/common/cloud/Replica.java
- solr/solrj/src/java/org/apache/solr/common/cloud/Slice.java
https://issues.apache.org/jira/browse/SOLR-16995
A new `leaderEligible` property was introduced on the `Replica.Type` in Solr 9 (?), but it is currently not used much in the codebase. Most of the code still uses something like `replicaType == Type.NRT || replicaType == Type.TLOG`, which makes the intention behind the code more difficult to read.
This PR is a refactoring using the `leaderEligible` property wherever it makes sense, to make the code more readable.
No new tests, as this refactoring does not introducing any new classes or methods, and does not change the existing behaviour.
> SOLR-16995: Use leaderEligible property where it makes sense

- build.gradle
- buildSrc/scriptDepVersions.gradle
https://issues.apache.org/jira/browse/SOLR-17028
Builds on https://github.com/apache/solr/pull/1997 to get to latest Gradle build dependency versions.
Gradle Build Plugins:
* `org.owasp.dependencycheck` - 8.0.1 -> 8.4.0
* `ca.cutterslade.analyze` - 1.9.0 -> 1.9.1
* `de.undercouch.doownload` - 5.2.0 -> 5.5.0
* `net.ltgt.errorprone` - 3.0.1 -> 3.1.0
* `com.github.node-gradle.node` - 3.4.0 -> 7.0.1
`buildSrc` script dep versions:
* `apache-rat` - 0.14 -> 0.15
* `commons-codec` - 1.15 -> 1.16.0
* `ecj` - 3.30.0 -> 3.33.0 - Note: 3.34.0 or higher requires JDK 17+
* `jgit` - 5.13.1.202206130422-r -> 6.7.0.202309050840-r
* `flexmark` - 0.64.0 -> 0.64.8
> SOLR-17028: Upgrade build tool versions

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cloud/CloudDescriptor.java
- solr/core/src/java/org/apache/solr/cloud/api/collections/AddReplicaCmd.java
- solr/core/src/java/org/apache/solr/cloud/api/collections/Assign.java
- solr/core/src/java/org/apache/solr/cloud/api/collections/CreateCollectionCmd.java
- solr/core/src/java/org/apache/solr/cloud/api/collections/CreateShardCmd.java
- solr/core/src/java/org/apache/solr/cloud/api/collections/MigrateReplicasCmd.java
- solr/core/src/java/org/apache/solr/cloud/api/collections/ReplaceNodeCmd.java
- solr/core/src/java/org/apache/solr/cloud/api/collections/RestoreCmd.java
- solr/core/src/java/org/apache/solr/cloud/api/collections/SplitShardCmd.java
- solr/core/src/java/org/apache/solr/cluster/events/impl/CollectionsRepairEventListener.java
- solr/core/src/java/org/apache/solr/cluster/placement/impl/PlacementPluginAssignStrategy.java
- solr/core/src/java/org/apache/solr/cluster/placement/impl/PlacementRequestImpl.java
- solr/core/src/test/org/apache/solr/cluster/placement/plugins/AffinityPlacementFactoryTest.java
- solr/core/src/test/org/apache/solr/cluster/placement/plugins/MinimizeCoresPlacementFactoryTest.java
- solr/solrj/src/java/org/apache/solr/client/solrj/request/CollectionAdminRequest.java
- solr/solrj/src/java/org/apache/solr/common/cloud/DocCollection.java
- solr/solrj/src/java/org/apache/solr/common/cloud/Replica.java
- solr/solrj/src/java/org/apache/solr/common/cloud/ReplicaCount.java
- solr/solrj/src/java/org/apache/solr/common/cloud/Slice.java
- solr/solrj/src/test/org/apache/solr/common/cloud/ReplicaCountTest.java
https://issues.apache.org/jira/browse/SOLR-16995
Working with replica counts, i.e., the number of replicas per replica type, is currently a bit painful, as the number of replicas is tracked individually for every replica type via individual variables. Solving this issue is also a step towards making it easier to add new replica types.
This PR introduces a `ReplicaCount` class (there was one up to Solr 8.x in the autoscaling framework, but it was removed in Solr 9) that is fancy wrapper around a Map<Replica.Type, Integer>.
New tests for the `ReplicaCount` class. Existing tests ensure non-regression (there is no added feature).
> SOLR-16995 Add a ReplicaCount to keep track of replicas per type

- solr/CHANGES.txt
- solr/bin/solr
https://issues.apache.org/jira/browse/SOLR-17039
@chatman
> SOLR-17039: Entropy calculation fails in Docker due to missing 'bc' cmd

- solr/core/src/java/org/apache/solr/update/TransactionLog.java
- solr/core/src/java/org/apache/solr/update/UpdateLog.java
TransactionLog is already extended by HdfsTransactionLog. But the extension basically relies on an empty protected constructor, and HdfsTransactionLog re-implements everything.
We want to open more TransactionLog to extension so that an extending class could leverage the logic present in TransactionLog, and override mainly how output/input streams are opened. This extension will be used by an EncryptionTransactionLog in solr-sandbox.
No functional change, only some refactoring.
The change consists in introducing OutputStreamOpener and ChannelInputStreamOpener so that an extending class can replace the defaults by a custom implementation (e.g. stream openers supporting encryption).
Also fix the various flush() calls to ensure the delegate streams are also flushed.
> SOLR-17030: Open TransactionLog for extension.

- solr/solrj/build.gradle
https://issues.apache.org/jira/browse/SOLR-17048
Solr 9.4 introduced a new 'api' module consumed by various other parts of Solr.  The solrj module declared an 'implementation' dependency on this new module which worked for Solr's own build, but isn't actually sufficient to have the dependency picked up transitively in client apps, leading to a variety of ClassDefNotFound's.
This commit updates SolrJ's declaration of its 'api' dependency to list it as an "api" type dependency.  This should prevent any client-side ClassDefNotFound problems related to these jar contents.
(Users of 9.4 can workaround this problem by adding an explicit dependency on solr-api in their apps, as in:
```
<dependency>
<groupId>org.apache.solr</groupId>
<artifactId>solr-api</artifactId>
<version>9.4.0</version> …
```
> SOLR-17048: Update solrj dep on 'api' module

- solr/core/src/java/org/apache/solr/servlet/HttpSolrCall.java
https://issues.apache.org/jira/browse/SOLR-17034
> SOLR-17034: Hitting /solr// ends up with HttpSolrCall NPE

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cloud/api/collections/CollApiCmds.java
- solr/core/src/java/org/apache/solr/handler/IndexFetcher.java
- solr/core/src/java/org/apache/solr/update/UpdateShardHandler.java
- solr/core/src/java/org/apache/solr/util/tracing/TraceUtils.java
- solr/core/src/test/org/apache/solr/util/tracing/TestSimplePropagatorDistributedTracing.java
- solr/modules/opentelemetry/src/test/org/apache/solr/opentelemetry/TestDistributedTracing.java
https://issues.apache.org/jira/browse/SOLR-17011
Adding trace information for the internal operations by wrapping CollectionApiCommand
> SOLR-17011 Add tracing spans to internal collection commands

- solr/core/src/java/org/apache/solr/update/processor/DistributedZkUpdateProcessor.java
https://issues.apache.org/jira/browse/SOLR-17054
There is dead code and duplicate code in DistributedZkUpdateProcessor. It makes understanding this already complex class more difficult.
Dead code and duplicate code has been removed, using automated refactoring tools available in Intellij whenever possible, to reduce the risk of errors.
No new code.
> SOLR-17054: Remove unused and duplicate code in DistributedZkUpdateProcessor

- solr/docker/build.gradle
- solr/docker/gradle-help.txt
Small change, so I don't think there needs to be a JIRA.
Example:
```bash
$ gradle dockerTag -Psolr.docker.imageTagSuffix=-java21 -Psolr.docker.baseImage=eclipse-temurin:21-jre-jammy
...
Solr Docker Image Created
ID:     sha256:2fc272cd564635f1b60f75d216d8f3d794fa2f7f79ed432bbb5ff806ffe86c50
Base Image:     eclipse-temurin:21-jre-jammy
Solr Version:   10.0.0-SNAPSHOT
Solr Distribution:      Full
Solr Docker Image Tagged
ID:     sha256:2fc272cd564635f1b60f75d216d8f3d794fa2f7f79ed432bbb5ff806ffe86c50
Tag:    apache/solr:10.0.0-SNAPSHOT-java21
```
> Add option for specifying a imageTagSuffix in gradle

- dev-tools/scripts/buildAndPushRelease.py
- gradle/maven/defaults-maven.gradle
Tested this out a bit locally with and without signing. Love that we can get rid of the “-x signJarsPublication” requirement for non signed builds.
Need to make sure that the artifacts are still teated to make sure that the signatures exist in the full smoke tester.
> SOLR-17026: Fix releaseBuild without signing

- .github/workflows/bin-solr-test.yml
- .github/workflows/docker-test.yml
- .github/workflows/gradle-precommit.yml
- .github/workflows/solrj-test.yml
- gradle/ge.gradle
- settings.gradle
@dsmiley - This is the similar PR to https://github.com/apache/lucene/pull/12293
This PR publishes a build scan for every CI build on Jenkins and GitHub Actions and for every local build from an authenticated Apache committer. The build will not fail if publishing fails.
The build scans of the Apache Solr project are published to the Gradle Enterprise instance at [ge.apache.org](https://ge.apache.org/), hosted by the Apache Software Foundation and run in partnership between the ASF and Gradle. This Gradle Enterprise instance has all features and extensions enabled and is freely available for use by the Apache Solr project and all other Apache projects.
This pull request enhances the functionality of publishing build scans to the publicly available …
> Capture build scans on ge.apache.org to benefit from deep build insights

- solr/core/src/test/org/apache/solr/cloud/SplitShardTest.java
- solr/core/src/test/org/apache/solr/cloud/SplitShardWithNodeRoleTest.java
- solr/core/src/test/org/apache/solr/cloud/api/collections/SplitByPrefixTest.java
- solr/test-framework/src/java/org/apache/solr/cloud/SolrCloudTestCase.java
Given the low and test only impact of this change, absent any feedback I plan to merge in about 2 days from now.
> SOLR-17067 SolrCloudTestCase activeClusterShape() should only consider active shards

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/update/CommitTracker.java
- solr/core/src/java/org/apache/solr/update/DirectUpdateHandler2.java
https://issues.apache.org/jira/browse/SOLR-17041
Switching to lazy provider for the tlog size
> SOLR-17041 Make CommitTracker currentTlogSize lazy

- solr/bin/solr
- solr/core/src/java/org/apache/solr/core/SolrCore.java
- solr/core/src/java/org/apache/solr/core/SolrResourceLoader.java
- solr/core/src/java/org/apache/solr/util/circuitbreaker/CPUCircuitBreaker.java
- solr/core/src/java/org/apache/solr/util/circuitbreaker/CircuitBreakerRegistry.java
- solr/core/src/java/org/apache/solr/util/circuitbreaker/LoadAverageCircuitBreaker.java
- solr/core/src/java/org/apache/solr/util/circuitbreaker/MemoryCircuitBreaker.java
- solr/core/src/test/org/apache/solr/util/BaseTestCircuitBreaker.java
- solr/core/src/test/org/apache/solr/util/TestGlobalCircuitBreaker.java
https://issues.apache.org/jira/browse/SOLR-16974
Proof-of-concept with static map of global breakers.
> SOLR-16974: Global Circuit Breakers

- gradle/node.gradle
- solr/api/build.gradle
- solr/webapp/build.gradle
- solr/webapp/web/index.html
- solr/webapp/web/js/angular/app.js
- solr/webapp/web/js/angular/controllers/collections.js
- solr/webapp/web/js/angular/services.js
https://issues.apache.org/jira/browse/SOLR-17062
Currently, Solr only offers one "first-party" client, SolrJ, which can only be used within JVM environments. This is obviously limiting for our users.
Historically, keeping client bindings in multiple languages up to date has been too daunting for the project to undertake. But now that Solr produces an OpenAPI spec for its upcoming "v2" API, we have the ability to generate client bindings from that for a variety of languages with very little additional maintenance cost.
There's extra incentive for us to experiment with languages that we ourselves use internally, as that gives us the opportunity to vet/dogfood the generated clients in our own code.
This PR uses the 'openapi-generator' gradle plugin to create a Javascript client based on our …
> SOLR-17062: Create JS client for Admin UI use

- solr/test-framework/src/java/org/apache/solr/cloud/MiniSolrCloudCluster.java
https://issues.apache.org/jira/browse/SOLR-16911
SOLR-16911 removed almost all of the references to a variable called 'hostContext' used by Jetty to set a base path for v1 requests.  However, one reference remained.
This PR removes the last removable hostContext reference from 'main': an unused parameter to a MiniSolrCloudCluster method.
N/A - small refactor. Existing tests continue to pass.
> SOLR-16911: Purge last hostContext references

- solr/solr-ref-guide/modules/getting-started/pages/tutorial-techproducts.adoc
Fix a typo in the "Exercise 1: Index Tech Products" tutorial. 
> Fix typo in tutorial 

- solr/core/src/java/org/apache/solr/cluster/placement/plugins/OrderedNodePlacementPlugin.java
- solr/core/src/java/org/apache/solr/cluster/placement/plugins/SimplePlacementFactory.java
https://issues.apache.org/jira/browse/SOLR-17076
`OrderedNodePlacementPlugin#getAllReplicasOnNode` can be slow in a cluster with lot of replicas. The effect could compound with new collection creation with many shards. 
Introduced a new field `allReplicas` which keeps track of all the replicas added/removed in the Plugin. Return a copy of that set instead for `getAllReplicasOnNode`.
Also added a new convenient method `getAllReplicaCount` if only the count is needed
A minor change, rely on existing unit test case
> SOLR-17076: Optimize `OrderedNodePlacementPlugin#getAllReplicasOnNode`

- solr/core/src/test/org/apache/solr/core/BlobRepositoryMockingTest.java
* GH-2086: errorprone fix
* GH-2086: tidy
(cherry picked from commit f9c17ebd90180910a7d3d1a695c23c6686bf1191)
> GH-2086: errorprone build fix #2086 (#2090)

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/packagemanager/PackageManager.java
- solr/core/src/test/org/apache/solr/packagemanager/TestPackageManager.java
- solr/modules/extraction/src/test/org/apache/solr/handler/extraction/TestXLSXResponseWriter.java
https://issues.apache.org/jira/browse/SOLR-17072
for current repository.json it yields: 
```
com.jayway.jsonpath.InvalidPathException: Error in JSON Path:$[config].[requestHandler].[HANDLER-PATH].[_packageinfo_].[version]
at org.apache.solr.packagemanager.PackageManager.jsonPathResolve(PackageManager.java:866)
at org.apache.solr.packagemanager.PackageManager.verify(PackageManager.java:829)
at org.apache.solr.packagemanager.PackageManager.deployPackage(PackageManager.java:363)
at org.apache.solr.packagemanager.PackageManager.deploy(PackageManager.java:943)
at org.apache.solr.cli.PackageTool.runImpl(PackageTool.java:187)
at org.apache.solr.cli.ToolBase.runTool(ToolBase.java:52)
at org.apache.solr.cli.SolrCLI.main(SolrCLI.java:153)
Caused by: com.jayway.jsonpath.InvalidPathException: Could …
```
> SOLR-17072: CLI package to print problem JSON Path

- solr/core/src/java/org/apache/solr/util/circuitbreaker/LoadAverageCircuitBreaker.java
- solr/core/src/test/org/apache/solr/util/TestGlobalCircuitBreaker.java
- solr/solr-ref-guide/modules/deployment-guide/pages/circuit-breakers.adoc
(cherry picked from commit a96eca6c1d88aff1d5f0b617e8c7dd768e51434b)
https://issues.apache.org/jira/browse/SOLR-17082
> SOLR-17082 Disable TestGlobalCircuitBreaker on windows (9x)

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/schema/FieldType.java
- solr/core/src/java/org/apache/solr/schema/UUIDField.java
- solr/core/src/test/org/apache/solr/schema/UUIDFieldTest.java
- solr/core/src/test/org/apache/solr/update/UuidAtomicUpdateTest.java
Also FieldType.createField() propagates underneath SolrException, to avoid error code erasure.
(cherry picked from commit c1cfaec00d37cbca71b62b4c535c1eed5fa7c4f6)
> SOLR-10653: leader to replica update fail if there's a UUIDField in schema (#2078)

- solr/CHANGES.txt
- solr/modules/ltr/example/README.md
- solr/modules/ltr/example/train_and_upload_demo_model.py
https://issues.apache.org/jira/browse/SOLR-17078
Almost all Python scripts in our repo use Python3, but one ("train_and_upload_demo_model.py") still lingers on Python2 years after its EOL in 2020.  
This commit updates the script to use Python3, using the automated [2to3](https://docs.python.org/3/library/2to3.html) tool offered by the Python community.
Manually tested the Python script after the update.  The script, and the larger example/demo it's a part of, still work following the move the python3.
> SOLR-17078: Upgrade ltr script to use Python3

- solr/CHANGES.txt
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/LBSolrClient.java
https://issues.apache.org/jira/browse/SOLR-17084
Exceptions returned by LBSolrClient can become very large. Building and returning them can consume large amount of ressources.
Exceptions should not contain the full list of zombie replicas but only its count.
No tests added since the change is really simpl
> SOLR-17084: Don't return full list of zombie in Exception

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/admin/api/RestoreCollectionAPI.java
- solr/test-framework/src/java/org/apache/solr/cloud/api/collections/AbstractCloudBackupRestoreTestCase.java
Most APIs return a "requestid" field with the request id when executed asynchronously. [SolrJ even relies on this field to return](https://github.com/apache/solr/blob/7eceece76771bdcd71245bcdfd5c0ae99ec980ee/solr/solrj/src/java/org/apache/solr/client/solrj/request/CollectionAdminRequest.java#L218), but now this is returning null for the restore API.
This API adds this field to the response when present.
> SOLR-17093: Collection restore API returns requestid when executed asynchronously

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cloud/ElectionContext.java
- solr/core/src/java/org/apache/solr/cloud/LeaderElector.java
- solr/core/src/java/org/apache/solr/cloud/ShardLeaderElectionContext.java
- solr/core/src/java/org/apache/solr/cloud/ShardLeaderElectionContextBase.java
- solr/core/src/java/org/apache/solr/cloud/ZkController.java
- solr/core/src/java/org/apache/solr/cloud/api/collections/CollApiCmds.java
- solr/core/src/java/org/apache/solr/handler/admin/RebalanceLeaders.java
- solr/core/src/java/org/apache/solr/handler/admin/api/RejoinLeaderElectionAPI.java
- solr/core/src/test/org/apache/solr/handler/admin/api/V2NodeAPIMappingTest.java
- solr/solrj-zookeeper/src/java/org/apache/solr/common/cloud/ZkStateReader.java
- solr/solrj/src/java/org/apache/solr/client/solrj/request/beans/RejoinLeaderElectionPayload.java
https://issues.apache.org/jira/browse/SOLR-17077
When we invoke `REJOINELECTION` command on a replica, the replica must first leave its current election position by deleting the sequential ephemeral node in Zookeeper. This is done by invoking `cancelElection()` method on the election context.
This issue is `cancelElection()` method is invoked twice. Once in `ZkController` and once in `retryElection()` in the leader elector. Consequently we try to delete the Zookeeper leader election node twice. The second attempt always fails since the node was already removed by the first attempt.
Remove the call to `cancelElection()` from ZkController. Also remove the creation of a new election context here, since a new one will be created in `retryElection()`.
Second commit on the pull request is to …
> SOLR-17077: Don't cancel twice when rejoining shard leader election

- .github/workflows/tests-via-crave.yml
We now have self-hosted runners by Crave.io.  Only Crave based GHA actions should use it.  More improvements to come later.
> GitHub: tests-via-crave.yml should use self-hosted runner

- .github/workflows/tests-via-crave.yml
The crave tests need to be run from the location of the clone, not the default start directory.
Change the directory to the appropriate one.
Have not been able to test this locally, but the creation of this pull request should result in it being tested.
> Switch to the directory of the clone before beginning the test

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/rest/RestManager.java
- solr/core/src/test/org/apache/solr/rest/schema/analysis/TestManagedStopFilterFactory.java
- solr/core/src/test/org/apache/solr/rest/schema/analysis/TestManagedSynonymGraphFilterFactory.java
https://issues.apache.org/jira/browse/SOLR-6853
Backport to 9.4.1
> SOLR-6853: Allow '/' characters in the text managed by Managed Resources API (branch_9_4)

- solr/core/src/java/org/apache/solr/handler/component/SearchHandler.java
https://issues.apache.org/jira/browse/SOLR-17053
Address a ClassCastException issue in the event exception in shard response is not of type org.apache.solr.common.SolrException
Wrap the exception in shard response into org.apache.solr.common.SolrException and throw the same
Tests checked in as part of previous PR here: https://github.com/apache/solr/pull/2102. Did not introduce additional testing with this PR as it is a minor change
> SOLR-17053: Address ClassCastException issue

- .github/workflows/tests-via-crave.yml
PRs have remote refs.
That remote ref will not be automatically fetched when we fetch origin. 
So how do we fetch it?
1. first fetch the actual remote reference and map it to a "local ref". This is done using `git fetch origin <remote-ref>:<name for local ref>`
2. Then we switch to the ref: `git checkout <name for local ref>`
This sets the state of the local clone to what the PR expects it to be
I've run this on a private repository with Crave's internal self-hosted Actions.
Needs to run against the solr GHA to test
> tests-via-crave.yml - switch to the correct branch for the PR

- solr/server/solr/configsets/_default/conf/solrconfig.xml
Remove the "Use Filter For Sorted Query" section from solrconfig.xml, since this exact section already appears at lines 464-479 in the same file.
I also checked other solrconfig.xml in the repository for the presence of a similar duplicate section.
NA
> Remove duplicate section from solrconfig.xml

- solr/solr-ref-guide/modules/configuration-guide/pages/package-manager-internals.adoc
Update the Reference Guide to clarify the actual behavior of Package Manager, - specifically, how it processes the version strings of packages.
NA
> Clarify the docs about the Package Manager

- solr/webapp/build.gradle
Running "gradle clean" should no longer be necessary when changing branches.
> Improve jsClient building for gradle caching

- .github/PULL_REQUEST_TEMPLATE.md
The link in the pull request template was a soft redirect.
Update it to point to the right page.
NA
- NA I have created a Jira issue and added the issue ID to my pull request title.
- NA I have run `./gradlew check`.
- NA I have added tests for my changes.
- NA I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)
> Update outdated link in PULL_REQUEST_TEMPLATE.md

- solr/core/src/java/org/apache/solr/handler/export/ExportWriter.java
- solr/core/src/java/org/apache/solr/search/SolrReturnFields.java
- solr/core/src/test/org/apache/solr/handler/export/TestExportWriter.java
- solr/solr-ref-guide/modules/query-guide/pages/exporting-result-sets.adoc
- solr/solr-ref-guide/modules/query-guide/pages/stream-decorator-reference.adoc
- solr/solrj-streaming/build.gradle
- solr/solrj-streaming/src/java/org/apache/solr/client/solrj/io/stream/SelectStream.java
- solr/solrj-streaming/src/test/org/apache/solr/client/solrj/io/stream/StreamExpressionToExpessionTest.java
- solr/solrj/src/java/org/apache/solr/common/util/GlobPatternUtil.java
- solr/solrj/src/test/org/apache/solr/common/util/TestGlobPatternUtil.java
https://issues.apache.org/jira/browse/SOLR-17022
This PR provides support for using glob patterns for fields in Export handler, Stream handler and with the SelectStream streaming expression. This creates similar ease of use for these handlers as we already have for the Select handler. Given how Solr export handler works, the glob pattern will be applied to only match fields that support stream, which are fields with docvalues enabled.
This solution uses similar methods to the Select handler to part glob patterns into matching fields. We then create a FieldWriter for each matching field to return the necessary data.
Implemented tests to ensure that we create the correct set of fields as a results of glob pattern matching.
> SOLR-17022: Support for glob patterns for fields in Export handler, Stream handler and with SelectStream streaming expression

- solr/core/src/java/org/apache/solr/core/CoreContainer.java
https://issues.apache.org/jira/browse/SOLR-17094
In #2110 was introduced the capability for ObjectCache to close Closeable objects that were put in it. Unfortunately, despite itself implementing Closeable, the ObjectCache was never closed by CoreContainer when shutting down.
CoreContainer is now closing the ObjectCache when shutting down.
None
> SOLR-17094: Close ObjectCache when closing CoreContainer

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/schema/FieldTypePluginLoader.java
- solr/core/src/java/org/apache/solr/schema/IndexSchema.java
- solr/core/src/java/org/apache/solr/schema/ManagedIndexSchema.java
- solr/core/src/test/org/apache/solr/schema/ResolveAnalyzerByNameTest.java
https://issues.apache.org/jira/browse/SOLR-16203
> SOLR-16203: Initialize schema plugins loaded by SPI name

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/SolrConfigHandler.java
- solr/core/src/java/org/apache/solr/schema/ManagedIndexSchema.java
- solr/solrj/src/java/org/apache/solr/client/solrj/SolrRequest.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/CloudHttp2SolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/CloudLegacySolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/ConcurrentUpdateHttp2SolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/ConcurrentUpdateSolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/Http2SolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/HttpSolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/LBHttp2SolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/LBHttpSolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/LBSolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/SolrClientBuilder.java
- solr/solrj/src/java/org/apache/solr/client/solrj/request/AbstractUpdateRequest.java
- solr/solrj/src/java/org/apache/solr/client/solrj/request/DataStoreSolrRequest.java
- solr/solrj/src/java/org/apache/solr/client/solrj/request/DirectXmlRequest.java
- solr/solrj/src/java/org/apache/solr/client/solrj/request/DocumentAnalysisRequest.java
- solr/solrj/src/java/org/apache/solr/client/solrj/request/FieldAnalysisRequest.java
- solr/solrj/src/java/org/apache/solr/client/solrj/request/LukeRequest.java
- solr/solrj/src/java/org/apache/solr/client/solrj/request/QueryRequest.java
- solr/solrj/src/java/org/apache/solr/client/solrj/request/SolrPing.java
- solr/solrj/src/java/org/apache/solr/client/solrj/util/ClientUtils.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/ConcurrentUpdateSolrClientBuilderTest.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/HttpSolrClientBuilderTest.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/LBHttpSolrClientBuilderTest.java
- solr/solrj/src/test/org/apache/solr/client/solrj/util/ClientUtilsTest.java
- solr/test-framework/src/java/org/apache/solr/cloud/ConfigRequest.java
https://issues.apache.org/jira/browse/SOLR-17066
SOLR-17066 recently expanded the concept of a "default collection" to all SolrClient implementations, as a migration path for folks away from baking core or collection names into the baseURL provided to clients.
This (unreleased) change still has a drawback though: clients still have issues with making "admin" (i.e. core-agnostic) requests, since the SolrClient path-building logic always adds a collection to the path.  It doesn't have any way to differentiate between core-aware (e.g. `/select`, `/update`, `/config`) and core-agnostic (e.g. `/admin/info/health`) requests.
This PR fixes this by adding a boolean metadata method to SolrRequest, called `requiresDataStore()`, which allows SolrClients to only selectively use the defaultCollection …
> SOLR-17066: Only apply default collection to collection requests

- .github/labeler.yml
- .github/workflows/labeler.yml
The project has some PR labels defined, but we don't use them because it is boring to manually label things, see https://github.com/apache/solr/pulls
This PR implements https://github.com/actions/labeler github action. It will make it easier to quickly discern the PRs and filter on area of interest.
The configuration will assign labels based on what paths have modifications. See `.github/labeler.yml` for labels and rules.
I borrowed some label names from lucene, e.g. `tool:build` and `module:XXX`.
Other labels are not prefixed such as `bats-tests`, `example`, `admin-ui`, `solrj`. I feel those should be prefixed in some way too, ideas welcome.
See screenshot below for a test I did in a fork:
> Auto-label PRs with labeler action

- dev-tools/scripts/githubPRs.py
- dev-tools/scripts/requirements.txt
When listing PRs that lack JIRA in title, we must exclude "solrbot" user and also DRAFT PRs
> githubPRs script: Exclude solrbot and draft PRs

- .asf.yaml
I browsed the [asf.yaml docs](https://cwiki.apache.org/confluence/pages/viewpage.action?spaceKey=INFRA&title=git+-+.asf.yaml+features), and found several new capabilities related to GitHub that I believe we should add:
* `protected_branches` - our main branch should at least be protected from force-push
* `protected_tags` - prevent deletion of `release*` tags
* `autolink_jira` - make references to short-form SOLR JIRA issues in PRs clickable
* `collaborators` - list of github user names to allow full PR edit karma
> Various asf.yaml updates

- dev-tools/scripts/releaseWizard.yaml
As a new `branch_X_Y` branch is created, it should be added to list of protected branches.
These commands are not tested, so please do a thorough manual review.
> ReleaseWizard commands to protect new minor branch

- solr/solrj/src/java/org/apache/solr/common/util/EnvUtils.java
https://issues.apache.org/jira/browse/SOLR-15960
The test run in #2126 (and #2202, I think) has failed for some Collection creation tests. The stack trace is 
`Caused by: java.lang.NullPointerException: key can't be null
at java.base/java.lang.System.checkKey(System.java:956) 
at java.base/java.lang.System.getProperty(System.java:826) 
at org.apache.solr.common.util.EnvUtils.getPropWithCamelCaseFallback(EnvUtils.java:169) 
at org.apache.solr.common.util.EnvUtils.getProp(EnvUtils.java:153) 
at org.apache.solr.common.util.PropertiesUtil.substitute(PropertiesUtil.java:68) `
It seems that `getPropWithCamelCaseFallback` has returned a null value for a key name. I suspect this may be caused by a concurrency issue causing an inconsistent view of the map state between threads, as the tests that …
>  SOLR-15960: Use ConcurrentHashMap for EnvUtils.camelCaseToDotsMap

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/core/SchemaCodecFactory.java
- solr/core/src/test-files/solr/collection1/conf/schema_postingsformat.xml
- solr/core/src/test/org/apache/solr/schema/TestSchemaField.java
This fixes [SOLR-13968](https://issues.apache.org/jira/browse/SOLR-13968) and adds a test case.
Thanks @dsmiley for spotting this!
> SOLR-17121: Fix SchemaCodecFactory to get PostingsFormat and DocValues from field.

- gradle/node.gradle
- help/localSettings.txt
I also added some docs to the local Settings help.
> Give NPM registry option for downloading node tools

- solr/CHANGES.txt
- solr/bin/solr
https://issues.apache.org/jira/browse/SOLR-17074
fixed the script `solr/bin/solr` 
Added the missing quotes 
Tried to run the script locally, now the output is correct. 
> SOLR-17074 - Not correctly escaped quote in bin/solr script

- solr/solr-ref-guide/modules/query-guide/pages/result-clustering.adoc
> solr-ref-guide: fix typo in result-clustering.adoc

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/admin/ContainerPluginsApi.java
- solr/core/src/test/org/apache/solr/handler/TestContainerPlugin.java
https://issues.apache.org/jira/browse/SOLR-17119
When registering a [ConfigurablePlugin](https://github.com/apache/solr/blob/main/solr/core/src/java/org/apache/solr/api/ConfigurablePlugin.java) through the `/cluster/plugin` API using the [V2Request](https://github.com/apache/solr/blob/main/solr/solrj/src/java/org/apache/solr/client/solrj/request/V2Request.java) client, exceptions raised within the `void configure(T cfg)` method are swallowed in [ContainerPluginsApi](https://github.com/apache/solr/blob/b5db179164919df657845f5e71f9fe0f0a1c86d8/solr/core/src/java/org/apache/solr/handler/admin/ContainerPluginsApi.java#L153-L156).
This behavior can be troublesome as the exceptions raised in the `configure(...)` method are usually validation errors on the configuration to be applied, which are …
> SOLR-17119: Exception swallowing in ContainerPluginsApi causes some config validation errors to be ignored

- solr/CHANGES.txt
https://issues.apache.org/jira/browse/SOLR-17126
Targeting 9.6 for this since 9.5 release is already rolling. Therefore also using a separate JIRA number
> SOLR-17126 Changes entry for 9.6 and new JIRA number

- .github/workflows/stale.yml
Following Lucene's lead and adding a stale bot that will label open, non-draft PRs as `Stale` after 60 days of inactivity. It is almost identical fork of Lucene's config: https://github.com/apache/lucene/blob/main/.github/workflows/stale.yml
I re-wrote the stale-message text a bit. I don't think random contributors can tag developers as reviewer, so I encouraged instead tagging people in a comment or emailing the dev-list.
> Introduce stale bot

- dev-docs/apis.adoc
- dev-docs/v2-api-conventions.adoc
https://issues.apache.org/jira/browse/SOLR-15781
Currently, decisions around what our v2 API should look like are scattered across a large number of JIRA tickets, PR reviews, and spreadsheets.  There's no one place giving an overview of the desired syntax (beyond perhaps the general guidance in SIP-16 to move towards "REST" where possible).
This commit attempts to address this by introducing docs describing some of the conventions used in our v2 API.
Room for improvement remains: parameters conventions remain a big gap, as does sourcing to the original rationale behind many of these decisions.  But this PR provides a place to build off of moving forward.
N/A - doc change only.
> SOLR-15781: Document v2 API syntax conventions

- solr/core/src/java/org/apache/solr/handler/component/TermVectorComponent.java
* There's already a `termVectorsNL` name used elsewhere in the component: https://github.com/apache/solr/blob/releases/solr/9.4.1/solr/core/src/java/org/apache/solr/handler/component/TermVectorComponent.java#L419
* To make `termVectors` available for use as per the the https://github.com/apache/solr/pull/1557/files#r1192193725 comments.
> NO JIRA: termVectors[NL] local variable rename in TermVectorComponent.process

- .github/workflows/labeler.yml
Building upon  #2180.
Noticed that #2233 had retained the `dependencies` label even after the pull request had been updated.
references:
* https://github.com/actions/labeler?tab=readme-ov-file#create-workflow
* https://github.com/search?q=org%3Aapache%20sync-labels&type=code
> update labeler.yml to sync-labels=true

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/core/CoreContainer.java
- solr/core/src/java/org/apache/solr/handler/admin/CoreAdminHandler.java
- solr/core/src/test/org/apache/solr/cloud/api/collections/LocalFSCloudIncrementalBackupTest.java
- solr/modules/gcs-repository/src/test/org/apache/solr/gcs/GCSIncrementalBackupTest.java
- solr/modules/hdfs/src/test/org/apache/solr/hdfs/cloud/api/collections/HdfsCloudIncrementalBackupTest.java
- solr/modules/s3-repository/src/test/org/apache/solr/s3/S3IncrementalBackupTest.java
- solr/solrj/src/java/org/apache/solr/common/util/ExecutorUtil.java
- solr/test-framework/src/java/org/apache/solr/cloud/api/collections/AbstractIncrementalBackupTest.java
https://issues.apache.org/jira/browse/SOLR-17149
A regression was introduced with [SOLR-16879](https://issues.apache.org/jira/browse/SOLR-16879) that makes backup/restore failing when there are more than 5 shards per node.
Replace the bounded queue for async core admin tasks by an unbounded one.
No unit tests added.
Manually checked we don't have any tasks rejected by the executor.
> SOLR-17149: Fix backup/restore for large collections.

- solr/solr-ref-guide/modules/deployment-guide/pages/basic-authentication-plugin.adoc
The algorithm for the password hash in the basic auth plugin docs is incorrect:
```diff
- sha256(password+salt)
+ sha256(sha256(salt+password))
```
See:
https://github.com/apache/solr/blob/9d6306e061374a4dea0dd14c7397994e1ab0bebe/solr/core/src/java/org/apache/solr/security/Sha256AuthenticationProvider.java#L124-L132
Updated docs.
Didn't run a build due to missing setup.
> Update password hash documentation on basic authentication

- solr/core/src/java/org/apache/solr/search/SolrIndexSearcher.java
Subjective of course, but I think more `final` use would help with code reading/comprehension. Noticed whilst looking at #2248 changes to this method. No JIRA ticket or CHANGES.txt entry needed IMHO.
> SolrIndexSearcher.getDocList[AndSet]NC style: more final local variables

- solr/solr-ref-guide/modules/indexing-guide/pages/indexing-with-update-handlers.adoc
It's a minor change that we tested (if you just do `split=true` it seems to apply to all fields, which is rarely what you want).
> Clarify split parameter usage

- build.gradle
- gradle/validation/owasp-dependency-check/exclusions.xml
line is incorrectly matched
the kerby CVE is specific to a subcomponent that is not used in Solr
> Suppress two `gradle dependencyCheckAggregate` false positives

- solr/solr-ref-guide/modules/configuration-guide/pages/coreadmin-api.adoc
This is a trivial fix in doc. I did not fill a Jira for it.
Parameter `core` for `STATUS` admin request is (wrongly) required in the full description, but (correctly) optional just before.
> Update core param in STATUS doc

- solr/solr-ref-guide/modules/configuration-guide/pages/caches-warming.adoc
Add a note about documentCache not supporting maxRamMB setting properly.
Since Lucene's RamUsageEstimator doesn't understand the Document objects, it will default to 256 bytes. Depending on the real document size this can be wildly inaccurate and cause the cache to use several magnitudes more memory than expected.
> Update caches-warming.adoc with a note about maxRamMB

- solr/core/src/java/org/apache/solr/core/SolrXmlConfig.java
Plugins can be disabled via `enable="false"` but unfortunately it's up to the caller of creating a PluginInfo to remember to consult this flag.  This PR addresses plugin disablement in solr.xml stuff.  No test, I know... it's not like every possible other case is tested :-).  Nonetheless I will manually test one of these soon that I have an interest in disabling via config before merging the PR.  Seems so minor, maybe no CHANGES.txt.
> solr.xml: honor plugin enable=true|false

- .github/labeler.yml
Followup from #2180 
Add GH labels based on java packages, e.g. for a package `org.apache.solr.foo[.xxx]`, assign label `cat:foo`. There are 23 new cat labels defined in total.
Also added label `tests` when any test is touched.
Most PRs will get two more labels due to this. Large refactor PRs or e.g. changing `javax.` to `jakarta.` would touch large parts of the code base and may thus get a large number of labels assigned.
This is still just a proposal. I'm open to suggestions for how to group some packages together into larger topics to obtain fewer categories. I also contemplated using different naming than the package name, e.g. "requesthandler" instead of "handler", but then there is something simplistic about that 1:1 relation too... 
As long as we're using this tool, we are …
> GH Labeler action: Category labels

- solr/core/src/java/org/apache/solr/cloud/CloudDescriptor.java
- solr/core/src/java/org/apache/solr/cloud/RecoveryStrategy.java
- solr/core/src/java/org/apache/solr/cloud/ReplicateFromLeader.java
- solr/core/src/java/org/apache/solr/cloud/ShardLeaderElectionContext.java
- solr/core/src/java/org/apache/solr/cloud/ZkController.java
- solr/core/src/java/org/apache/solr/core/CoreContainer.java
- solr/core/src/java/org/apache/solr/handler/ReplicationHandler.java
- solr/core/src/java/org/apache/solr/update/UpdateHandler.java
- solr/solrj/src/java/org/apache/solr/common/cloud/Replica.java
https://issues.apache.org/jira/browse/SOLR-16995
I am resuming refactoring started earlier (#1928, #1981, #2039) with the goal of simplifying/centralising code related to replica types. The end goal would be to avoid having `if (replicaType == Replica.Type.*)` scattered across the codebase, and to make it easier to add new replica types.
This PR adds a new attribute to replica types that specify whether they should replicate from their leader.
Existing tests should pass, no change of behaviour.
> SOLR-16995: Configure replication behaviour for each replica type

- solr/core/src/test/org/apache/solr/cloud/SolrCloudExampleTest.java
Occasionally get a "PKIX" error in the test runs. 
Suppress SSL, like we do in many other unit tests.   For a while I thought bin/solr post didnt' support SSL, but I did a bats test as part of `test_ssl.bats` and it worked just fine.
Not user facing, so no JIRA.
n/a
> Prevent odd error from occasionally showing up.

- solr/core/src/java/org/apache/solr/search/SolrIndexSearcher.java
unusedness spotted by @chatman in #2248 -- splitting out removal here for clarity (though that's subjective of course).
> remove unused local variable in SolrIndexSearcher.sortDocSet

- solr/CHANGES.txt
- solr/solrj-streaming/src/java/org/apache/solr/client/solrj/io/stream/CloudSolrStream.java
- solr/solrj-streaming/src/test/org/apache/solr/client/solrj/io/stream/BadClusterTest.java
https://issues.apache.org/jira/browse/SOLR-16138
When reading from a `CloudSolrStream`, if all Solr cores are down, we receive an empty stream (EOF from the first `read()` operation).
Instead, an exception should be thrown to represent that the Solr cluster is unreachable, even if the ZooKeeper cluster itself is reachable.
Throw `IOException` in `CloudSolrStream.open()` when all shards or replicas are unavailable.
I added a set of three tests to validate behaviors on badly behaving clusters. These tests are in their own suite, for reasons explained in the comments: we progressively damage the cluster, so it can not be run along "normal" tests.
Tests 1 (empty collection) and 3 (cluster shutdown) were already working as expected, but I left them in for completeness.
Test 2 (all nodes down) …
> SOLR-16138: Throw when streaming and all cores are down

- solr/core/src/java/org/apache/solr/cli/PostTool.java
- solr/core/src/java/org/apache/solr/cli/RunExampleTool.java
- solr/core/src/test/org/apache/solr/cli/PostToolTest.java
https://issues.apache.org/jira/browse/SOLR-17163
Make sure not to load other non films.json files that are json formatted
Explicit path to the file, plus fix some informaiton message around recursion when you don't have directories to index.
Added a test for the detection of recursing into directories.   Also made two existing tests that run the PostTool actually run the full lifecycle.
> SOLR-17163: Only load the films.json file when running the bin/solr start -e films

- solr/bin/solr
- solr/bin/solr.cmd
- solr/packaging/test/test_zk.bats
https://issues.apache.org/jira/browse/SOLR-16780
bin/solr cp would run, but the params wouldn't be properly formatted and you get an error.
Trap the use of the zk subcommands and give user appropriate message.
Bats
> SOLR-16780: Prevent ZK subcommands from being run without the bin/solr zk prefix

- solr/solrj/build.gradle
- solr/solrj/src/java/org/apache/solr/common/util/GlobPatternUtil.java
https://issues.apache.org/jira/browse/SOLR-17181
This is intended to fix a bug raised where glob pattern matching suffered a performance degradation after https://github.com/apache/solr/pull/1996.
This reverts back to using the Apache Commons IO FilenameUtils.wildcardMatch method to do glob pattern matching. This is the original implementation used prior to 9.5 and thus should match performance. This does introduce commons-io as a new library for solrj since glob pattern matching is needed in solrj as well to be available for all use cases.
Using existing tests to validate functionality.
> SOLR-17181: Using apache commons implementation for wildcard matching for glob patterns

- solr/core/src/test/org/apache/solr/cloud/NestedShardedAtomicUpdateTest.java
- solr/core/src/test/org/apache/solr/handler/JsonLoaderTest.java
- solr/core/src/test/org/apache/solr/response/transform/TestChildDocTransformer.java
- solr/core/src/test/org/apache/solr/response/transform/TestChildDocTransformerHierarchy.java
- solr/core/src/test/org/apache/solr/search/facet/TestJsonFacetsWithNestedObjects.java
- solr/core/src/test/org/apache/solr/search/join/BJQParserTest.java
- solr/core/src/test/org/apache/solr/search/join/TestCloudNestedDocsSort.java
- solr/core/src/test/org/apache/solr/search/join/TestNestedDocsSort.java
- solr/core/src/test/org/apache/solr/search/join/another/BJQFilterAccessibleTest.java
- solr/core/src/test/org/apache/solr/update/AddBlockUpdateTest.java
- solr/core/src/test/org/apache/solr/update/RootFieldTest.java
- solr/core/src/test/org/apache/solr/update/TestNestedUpdateProcessor.java
- solr/core/src/test/org/apache/solr/update/processor/AtomicUpdatesTest.java
- solr/core/src/test/org/apache/solr/update/processor/NestedAtomicUpdateTest.java
- solr/test-framework/src/java/org/apache/solr/util/RandomMergePolicy.java
- solr/test-framework/src/java/org/apache/solr/util/RandomNoReverseMergePolicyFactory.java
- Defend other block join tests from reverse merge.
- introduce @ClassRule for no revers merge policy
> SOLR-17156: introducing RandomNoReverseMergePolicyFactory (#2289)

- solr/core/src/test/org/apache/solr/update/PeerSyncTest.java
https://issues.apache.org/jira/browse/SOLR-17184
This is a small fix for an issue with PeerSyncTest where it would randomly fail due to the order of documents returned.
Added a secondary sort on id for the queries to ensure consistent ordering.
Using existing tests.
> SOLR-17184: Fixing sorting order of documents for comparison in PeerSyncTest to avoid random failures

- solr/CHANGES.txt
- solr/solrj-streaming/src/java/org/apache/solr/client/solrj/io/stream/expr/StreamExpressionParser.java
- solr/solrj-streaming/src/test/org/apache/solr/client/solrj/io/stream/StreamExpressionTest.java
https://issues.apache.org/jira/browse/SOLR-17186
StreamExpressionParser today replaces ` with " indiscriminately which can break queries where the tokens themselves contain backtick. 
Allow for backticks to be escaped in the streaming query and only replace non-escaped backticks with "
- [+ ] I have reviewed the guidelines for [How to Contribute](https://github.com/apache/solr/blob/main/CONTRIBUTING.md) and my code conforms to the standards described there to the best of my ability.
- [ +] I have created a Jira issue and added the issue ID to my pull request title.
- [ +] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR …
> SOLR-17186: Streaming query breaks if token contains backtick

- solr/core/src/test/org/apache/solr/TestSolrCoreProperties.java
- solr/core/src/test/org/apache/solr/cli/TestSolrCLIRunExample.java
- solr/core/src/test/org/apache/solr/cloud/ConcurrentCreateRoutedAliasTest.java
- solr/core/src/test/org/apache/solr/cloud/TestConfigSetsAPIExclusivity.java
- solr/core/src/test/org/apache/solr/cloud/TestConfigSetsAPIZkFailure.java
- solr/core/src/test/org/apache/solr/cloud/TestRequestForwarding.java
- solr/core/src/test/org/apache/solr/cloud/TestWaitForStateWithJettyShutdowns.java
- solr/core/src/test/org/apache/solr/cloud/api/collections/ConcurrentDeleteAndCreateCollectionTest.java
- solr/core/src/test/org/apache/solr/handler/PingRequestHandlerTest.java
- solr/core/src/test/org/apache/solr/handler/ReplicationTestHelper.java
- solr/core/src/test/org/apache/solr/handler/TestReplicationHandlerBackup.java
- solr/core/src/test/org/apache/solr/handler/TestRestoreCore.java
- solr/core/src/test/org/apache/solr/handler/V2StandaloneTest.java
- solr/core/src/test/org/apache/solr/handler/admin/CoreAdminHandlerTest.java
- solr/core/src/test/org/apache/solr/handler/admin/DaemonStreamApiTest.java
- solr/core/src/test/org/apache/solr/handler/component/SearchHandlerTest.java
- solr/core/src/test/org/apache/solr/response/TestRawTransformer.java
- solr/core/src/test/org/apache/solr/search/stats/TestDistribIDF.java
- solr/core/src/test/org/apache/solr/security/BasicAuthStandaloneTest.java
- solr/modules/hadoop-auth/src/test/org/apache/solr/security/hadoop/TestSolrCloudWithDelegationTokens.java
- solr/modules/hadoop-auth/src/test/org/apache/solr/security/hadoop/TestSolrCloudWithSecureImpersonation.java
- solr/modules/ltr/src/test/org/apache/solr/ltr/TestLTROnSolrCloud.java
- solr/solrj/src/test/org/apache/solr/client/solrj/TestLBHttp2SolrClient.java
- solr/solrj/src/test/org/apache/solr/client/solrj/TestLBHttpSolrClient.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/TestCloudSolrClientConnections.java
- solr/test-framework/src/java/org/apache/solr/SolrTestCaseHS.java
- solr/test-framework/src/java/org/apache/solr/cloud/MiniSolrCloudCluster.java
- solr/test-framework/src/test/org/apache/solr/embedded/TestJettySolrRunner.java
Isn't needed because it's the default
Note this is on branch_9x.  Main already has this; was done some time ago I guess.
> Tests: JettyConfig.Builder.setContext("/solr")

- solr/core/src/java/org/apache/solr/handler/component/HttpShardHandlerFactory.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/CloudHttp2SolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/LBHttp2SolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/LBHttpSolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/LBSolrClient.java
https://issues.apache.org/jira/browse/SOLR-17066
In PR #2283, SOLR-17066 introduced the `LBSolrClient.Endpoint` class, and modified several "LB" client methods to use it on "main".  Users who take advantage of these methods in Solr 9 should be given proper notice that they'll be changing (or going away entirely) in Solr 10.
This commit adds the corresponding deprecation notices to branch_9x, so that users can be notified of these changes and start to upgrade their apps where appropriate/required.
N/A - doc change only.
> SOLR-17066: Add deprecation warnings to 9x methods

- solr/solr-ref-guide/modules/query-guide/pages/faceting.adoc
The parameters descriptions in the faceting docs begin inconsistently. Some re-state the parameter names, some start with "This parameter...", etc.
Make them begin consistently and concisely by starting directly with the description of what it does.
Did not run tests.
- NA: I have created a Jira issue and added the issue ID to my pull request title.
- NA I have run `./gradlew check`.
- NA I have added tests for my changes.
- NA I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)
> Make parameter descriptions consistent in faceting.adoc

- solr/solr-ref-guide/modules/query-guide/pages/common-query-parameters.adoc
Add optional/default table to Common Query Parameters to be consistent with other docs. Also make some small modification to some sections for clarity/conciseness.
Used the same table syntax from the other documentation pages.
- [NA] I have created a Jira issue and added the issue ID to my pull request title.
- [NA] I have run `./gradlew check`.
- [NA] I have added tests for my changes.
- [NA] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)
> Add default/optional tables to common-query-parameters.adoc

- solr/test-framework/src/java/org/apache/solr/embedded/JettySolrRunner.java
Very simple little check.  I saw in a failure here: https://github.com/apache/solr/actions/runs/8180447387/job/22376604762?pr=2335 for TestLBHttp2SolrClient.
> Tests: avoid NPE in JettySolrRunner lifeCycleStopped

- solr/core/src/test/org/apache/solr/cloud/DeleteShardTest.java
https://issues.apache.org/jira/browse/SOLR-16403
#1926 introduced unreliability into the DeleteShardTest by inadvertently removing the wait on observing the new Shard state. This could cause the test to fail depending on timings.
Correct the issue by using the class method to change the Shard state (as intended), instead of calling ShardTestUtil directly, restoring the wait on the state change being observed.
This is a test change. The test runs reliably once more.
> Fix unreliable DeleteShardTest

- solr/CHANGES.txt
- solr/solr-ref-guide/modules/deployment-guide/pages/solrj.adoc
- solr/solr-ref-guide/modules/upgrade-notes/pages/major-changes-in-solr-9.adoc
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/CloudHttp2SolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/ConcurrentUpdateHttp2SolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/Http2SolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/HttpClientBuilderFactory.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/Krb5HttpClientBuilder.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/LBHttp2SolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/PreemptiveBasicAuthClientBuilderFactory.java
https://issues.apache.org/jira/browse/SOLR-17201
Also, undeprecate `Krb5HttpClientBuilder` and `PreemptiveBasicAuthClientBuilderFactory`.
> SOLR-17201 Make Http2SolrClients not experimental

- solr/solrj/src/java/org/apache/solr/client/solrj/impl/HttpJdkSolrClient.java
By checking if the client implements AutoCloseable, we can properly close the underlying http client should the user have a Java 21+ jvm.
> HttpJdkSolrClient: Close the underlying http client, if it is supported (java 21+)

- solr/solr-ref-guide/modules/query-guide/pages/spatial-search.adoc
Due to API changes a JTS 1.17.x version is currently required.
The appropriate JTS version may be determined based on the JTS version used for tests in Lucene, referenced in https://github.com/apache/lucene/blob/main/versions.props
Strictly speaking, the appropriate JTS version for the version of spatial4j used by the Lucene version used in Solr should always be referenced - either this needs to be kept manually updated here (or somehow automatically in the build process?) or the process of finding the correct JTS version should be described here in a clear and concise way rather than just pointing to a specific version.
> Update required JTS version

- solr/core/src/java/org/apache/solr/response/transform/ValueAugmenterFactory.java
- solr/core/src/test/org/apache/solr/pkg/ValueAugmenterPublicTest.java
https://issues.apache.org/jira/browse/SOLR-17185
Opening up the class `ValueAugmenter` in the `ValueAugmenterFactory` to `public` access level eases the creation of custom document transformers.
Currently, we have to place our custom document transformers in the `org.apache.solr.response.transform` package to be able to access the package private `ValueAugmenter`. Changing the visibility to `public` enables building custom document transformers very slim and quick like the following one in any package:
```java
public class CollectionAugmenterFactory extends TransformerFactory {
@Override
public DocTransformer create(String field, SolrParams params, SolrQueryRequest req) { 
String v = ComponentUtils.getCollectionNameFrom(req.getCore()).orElse("[unknown]"); 
return new …
```
> [SOLR-17185] Open ValueAugmenter in ValueAugmenterFactory for extension

- solr/core/src/test/org/apache/solr/cloud/api/collections/TestLocalFSCloudBackupRestore.java
- solr/test-framework/src/java/org/apache/solr/cloud/SolrCloudTestCase.java
We suspect that the commits from PR  #2230 caused the tests to fail sporadically. This PR disables PRS for this specific test and if the test doesn't fail we can conclude that it is a PRS bug
> Disable PRS for this testcase to observe if PRS is causing the problem

- solr/solr-ref-guide/modules/query-guide/pages/common-query-parameters.adoc
Reorganize/reword the `sort` section on the Common Query Parameters documentation page.
* A lot of small tightening of the language.
* Reorganized to try to have the most useful information at the top. So lead with the examples, since the examples are pretty clear on their own. Then the nitty-gritty of the details appears after.
* Made it clearer that multi-valued fields _do_ support sorting.
Tested by previewing on https://asciidoclive.com/ , and it all looked good there.
- [NA] I have created a Jira issue and added the issue ID to my pull request title.
- Not sure if you all would prefer I create issues for some of the documentation changes ; can do if so.
- [NA] I have run `./gradlew check`.
- [NA] I have added tests for my changes. …
> Reorganize sort section in common-query-parameters.adoc

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/response/JacksonJsonWriter.java
- solr/core/src/test/org/apache/solr/response/JSONWriterTest.java
https://issues.apache.org/jira/browse/SOLR-17110
Fix JacksonJsonWriter to properly quote uuid values in json query response
Added a test to assert that different field types properly serialize their values with `wt=json`.
> SOLR-17110: Fix JacksonJsonWriter to properly quote uuid values in json query response

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/api/V2HttpCall.java
- solr/core/src/java/org/apache/solr/servlet/HttpSolrCall.java
- solr/solrj-zookeeper/src/java/org/apache/solr/client/solrj/impl/ZkClientClusterStateProvider.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/ClusterStateProvider.java
…ted cluster state
https://issues.apache.org/jira/browse/SOLR-17153
At present, when CloudSolrClient is instructed to send a request to a collection it deems non-existent due to its outdated local ClusterState view, it fails locally, which is undesired. This failure should be addressed. Moreover, many SolrCloud tests should remove their waitForState calls following collection creation. Matters concerning other stale states are not addressed here.
Similar changes will be required on the server side to handle "Collection Not Found" errors resulting from outdated cluster state.
If neither CloudSolrClient nor HttpSolrCall (server) can locate a collection, trigger a forced fetch of the collection from ZooKeeper and update the local cluster state accordingly.
Please describe the tests you've …
> SOLR-17153: CloudSolrClient should not throw "Collection not found" with an out-dated ClusterState

- solr/CHANGES.txt
- solr/solr-ref-guide/modules/deployment-guide/pages/solrj.adoc
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/Http2SolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/HttpJdkSolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/HttpSolrClientBase.java
- solr/solrj/src/java/org/apache/solr/client/solrj/util/AsyncListener.java
- solr/solrj/src/java/org/apache/solr/client/solrj/util/Cancellable.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/DebugAsyncListener.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/DebugServlet.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/Http2SolrClientTest.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/HttpJdkSolrClientTest.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/HttpSolrClientTestBase.java
This PR adds method  `asyncRequest` to abstract supertype `HttpSolrClientBase` and implements it on `HttpJdkSolrClient`.  Also adds unit tests for normal, exceptional and cancelled asynchronous requests, both for `HttpJdkSolrClient` and `Http2SolrClient`.  Also includes a few javadoc improvements.
> SOLR-17211:  HttpJdkSolrClient Support Async requests

- solr/solr-ref-guide/modules/deployment-guide/pages/enabling-ssl.adoc
Zookeeper client TLS works fine with Java, and all referred issues are either closed or refer to the above fact.
> Ref Guide: Remove note about Zookeeper client TLS support

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/search/IncompleteRerankingException.java
- solr/core/src/java/org/apache/solr/search/ReRankCollector.java
- solr/modules/ltr/src/java/org/apache/solr/ltr/LTRRescorer.java
- solr/modules/ltr/src/test-files/featureExamples/features-slow.json
- solr/modules/ltr/src/test-files/modelExamples/linear-slow-model.json
- solr/modules/ltr/src/test/org/apache/solr/ltr/TestLTRQParserPlugin.java
- solr/solr-ref-guide/modules/query-guide/pages/learning-to-rank.adoc
https://issues.apache.org/jira/browse/SOLR-17018
Learning To Rank was ignoring any queryLimit parameter (such as timeAllowed) during the reranking phase.
This means that a particularly expensive feature to extract may cause extremely slow responses and failures out of control.
The idea is to check the query limits after the rescore of each search result (Learning To Rank rescore topK results).
If the query limit is exhausted before the completion of the rescoring, the reranking is aborted and reverted (all or nothing approach).
The response is marked as a partialResult and the original score and ranking are returned.
A test has been added with a simple Learning To Rank model that uses just one single slow feature (implemented with a sleep function query).
This feature simulates a slow …
> SOLR-17018: add QueryLimits support to Learning To Rank rescoring

- .github/renovate.json
Ref discussion in https://lists.apache.org/thread/ovwytr47zv2y9xs7fxbgl6kbpfmbqc5v
Try to be explicit with schedule on the packages we want to update less frequently.
Also fix changelog location for some gitbox repos, where renovate was complaining, e.g.
```
INFO: Unknown platform, skipping changelog fetching. (repository=apache/solr, branch=renovate/org.apache.zookeeper)
"sourceUrl": "https://gitbox.apache.org/repos/asf/zookeeper.git",
"hostType": null
```
> Renovatebot config fixes

- .github/workflows/stale.yml
Annoying that this attempts to run on forks, where it typically will fail
> Disable stale bot for forks

- solr/benchmark/src/java/org/apache/solr/bench/BaseBenchState.java
- solr/benchmark/src/java/org/apache/solr/bench/generators/StringsDSL.java
- solr/benchmark/src/test/org/apache/solr/bench/DockMakerTest.java
https://issues.apache.org/jira/browse/SOLR-17189
-Dsolr.bench.seed=1392507964231541
----
WIP.  Didn't fix the problem yet but just tried to make the benchmark tests actually repeatable
> SOLR-17189 Fix DockMakerTest.testRealisticUnicode

- .github/renovate.json
We always close the renovate PRs for major eclipse upgrades since they need much more work. So let's skip these
> [SolrBot] Skip automated major version eclipse upgrades

- solr/solr-ref-guide/modules/deployment-guide/pages/zookeeper-ensemble.adoc
So they work for Java 9+, given that we require Java 11+. Existing ones are for Java 8.
Manually tested these options (which are stolen from Solr's own GC logging options) on a 9.5 installation with Java 17.
> Update GC logging options for Zookeeper

- solr/solrj/src/java/org/apache/solr/common/util/ExecutorUtil.java
This actually logs the correct stack trace for an exception caught in the ExecutorUtil.
It also provides the correct ordering of "causes" unlike the way it was previously implemented, where the "cause" was actually the thread that called the Executor. Now the "cause" is the error in the executor, and the base exception is the thread that called the ExecutorUtil.
It may look strange that we always use an `Exception` class, but this is ok since these exceptions that we are copying are only made a few lines up and are always of class `Exception`. (They aren't real exceptions, they are merely storing the stackTrace of how the original thread called the Executor, or the tree of executor calls). Therefore, no information is being lost here.
> Add correct exception logging in the ExecutorUtil

- solr/solrj/src/java/org/apache/solr/client/solrj/impl/LBSolrClient.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/LBHttp2SolrClientTest.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/LBSolrClientTest.java
This is to fix a regression bug in `main` only, in that LBHttp2SolrClient does not skip "zombie" Endpoints.  See JIRA for more details.
> SOLR-17234: LBHttp2SolrClient does not skip "zombie" endpoints

- solr/solr-ref-guide/modules/deployment-guide/pages/monitoring-with-prometheus-and-grafana.adoc
- solr/solr-ref-guide/modules/deployment-guide/pages/taking-solr-to-production.adoc
- solr/solr-ref-guide/modules/deployment-guide/pages/zookeeper-access-control.adoc
- solr/solr-ref-guide/modules/deployment-guide/pages/zookeeper-utilities.adoc
https://issues.apache.org/jira/browse/SOLR-14115
Update the Ref Guide to not refer to zkcli.sh
I did the lightest version of updating the Ref Guide to refer to the bin/solr equivalent of zkcli.sh.  
I didn't try to rethink the layout of the Ref Guide... However, if feels like the `solr-control-script-reference.adoc` page is getting overwhelmed....    We probably should break up that page into control script, zk commands, other features.    Therefore, instead of eliminating `zookeeper-utilities.adoc`, I left it, because in the future we could move more documentation specific to zk into this page FROM `solr-control-script-reference.adoc`.  
Also didn't want to think about how to handle deleting a ref guide page!
Manual testing.
> SOLR-14115: Update the docs to reference to the bin/solr equivalent of the zkcli.sh

- solr/core/src/test/org/apache/solr/uninverting/TestUninvertingReader.java
I got a test failure that reproduces:
./gradlew :solr:core:test --tests
"org.apache.solr.uninverting.TestUninvertingReader.testSortedSetFloat"
-Ptests.seed=5827A2FA13E7BE3C
Turns out this is a case of doc re-ordering that happens recently from Lucene's test infra.
> fixTestUninvertingReader

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/core/CoreContainer.java
- solr/solrj/src/java/org/apache/solr/common/util/ExecutorUtil.java
https://issues.apache.org/jira/browse/SOLR-17261
ExecutorUtil once again has the ability to wait for an ExecutorService to terminate without a timeout.
I looked through the other uses of `ExecutorUtil.shutdownAndAwaitTermination(coreLoadExecutor)`, however almost all the other usages are in a `shutdown()` or `close()` method, which should be time-boxed. I think these two usages are the only two currently that really shouldn't be timeboxed. However, I've added java docs to help developers chose the correct one in the future.
I will probably include this in a 9.6.1 release as well.
> SOLR-17261: Allow cores to load without a timeout

- solr/core/src/java/org/apache/solr/cloud/api/collections/CreateCollectionCmd.java
- solr/test-framework/src/java/org/apache/solr/cloud/AbstractBasicDistributedZk2TestBase.java
- solr/test-framework/src/java/org/apache/solr/cloud/SolrCloudTestCase.java
https://issues.apache.org/jira/browse/SOLR-17265
This fixes the test errors introduced by https://github.com/apache/solr/pull/2230
I'm not really certain what the previous logic was supposed to be doing, but `isPRS()` practically returned a random true or false every time it was called, since the `"use.per-replica"` sysProp was never set.
I've simplified the logic considerably. Before a class is run `"solr.prs.default"` is set to either `true` or `false` (either randomly, or determined by the Class annotation). Then ever call to `isPRS()` will read that sysProp to determine if the default is PRS or not.
> SOLR-17265: Fix randomized PRS testing

- dev-tools/scripts/releaseWizard.py
- dev-tools/scripts/releaseWizard.yaml
https://issues.apache.org/jira/browse/SOLR-17260
This PR implements the suggested policy of deleting version `N.M-2` from hub. This means that when we release 9.7, 9.5 will be marked as "unsupported" in docker hub. That is, it will still be available for pull but not advertised as "supported".
> SOLR-17260 ReleaseWizard should remove old minor versions from Docker Hub

- solr/test-framework/src/java/org/apache/solr/cloud/MiniSolrCloudCluster.java
https://issues.apache.org/jira/browse/SOLR-17088
> SOLR-17088: Fix custom solr.xml usage in tests with extra jettys

- solr/solr-ref-guide/modules/deployment-guide/pages/basic-authentication-plugin.adoc
https://issues.apache.org/jira/browse/SOLR-17282
for the pwd encode format, there missed a ')', and this confused me , so i added this: (Format: base64(sha256(sha256(salt+password))) base64(salt))
i added this: (Format: base64(sha256(sha256(salt+password))) base64(salt))
> SOLR-17282: Update basic-authentication-plugin.adoc

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/loader/JsonLoader.java
- solr/core/src/test-files/solr/collection1/conf/atomic-update-json-test.xml
- solr/core/src/test/org/apache/solr/update/processor/AtomicUpdateJsonTest.java
- solr/core/src/test/org/apache/solr/update/processor/AtomicUpdatesJsonTest.java
Fixes problems with the JsonLoader's parsing of atomic update values that use multiple modifiers in a single update or reference a field name that matches a modifier (like `set` or `add`).
https://issues.apache.org/jira/browse/SOLR-17274
Fixes two problems with JSON atomic updates where an atomic update value like `{"set": {"set": "foo"}}` (set a field named `set` to value `foo`) or `{"foo": {"add": "bar", "remove": "baz"}}` (add `bar` value to and remove `baz` values from field `foo`) would throw an exception due to `isChildDoc` thinking a nested doc was being updated. The exact exception message was:
`Unable to index docs with children: the schema must include definitions for both a uniqueKey field and the '_root_' field, using the exact same fieldType`
I modified the `isChildDoc` …
> SOLR-17274: allow JSON atomic updates to use multiple modifiers or a modifier like 'set' as a field name if child docs not enabled 

- solr/core/src/java/org/apache/solr/core/backup/repository/DelegatingBackupRepository.java
- solr/test-framework/src/java/org/apache/solr/cloud/api/collections/AbstractBackupRepositoryTest.java
One line PR to make DelegatingBackupRepository extend AbstractBackupRepository, so it has the config and the shouldVerifyChecksum field.
> DelegatingBackupRepository extends AbstractBackupRepository.

- solr/core/src/test/org/apache/solr/cloud/api/collections/ShardSplitTest.java
- solr/modules/hdfs/src/test/org/apache/solr/hdfs/cloud/StressHdfsTest.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/HttpSolrClient.java
- solr/test-framework/src/java/org/apache/solr/cloud/AbstractBasicDistributedZkTestBase.java
- solr/test-framework/src/java/org/apache/solr/cloud/AbstractFullDistribZkTestBase.java
- solr/test-framework/src/java/org/apache/solr/embedded/JettySolrRunner.java
SOLR-17066 broke some tests marked Nightly since the beginning of February; they didn't fail previously then they fail always.  It's so sad we don't have mechanisms to bring our attention to something that is so glaring.  I just happened to be looking at build failures, and I saw so many and I started looking at them.
http://fucit.org/solr-jenkins-reports/history-trend-of-recent-failures.html#series/org.apache.solr.cloud.api.collections.ShardSplitTest.test
https://ge.apache.org/scans/tests?search.rootProjectNames=*solr*&search.timeZoneId=America%2FNew_York&tests.container=org.apache.solr.cloud.api.collections.ShardSplitTest&tests.help=executedTest&tests.test=test
Even though SOLR-17066 shipped, I'm nonetheless doing a PR against the same issue because I _basically_ just fixed tests.
> SOLR-17066 Fix ShardSplitTest & StressHdfsTest

- solr/CHANGES.txt
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/HttpJdkSolrClient.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/Http2SolrClientTest.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/HttpJdkSolrClientTest.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/HttpSolrClientTestBase.java
https://issues.apache.org/jira/browse/SOLR-17263
HttpJdkSolrClient doesn't encode curly braces etc
NB see also https://github.com/apache/solr/pull/2454
Use SolrParams' toQueryString() method rather than implicitly using toString() which doesn't encode all chars.
I've updated tests to include a curly brace character which should be encoded to `%7B`, and a length check on the request body content length for PUT/POST requests. Each subsequent commit resolves some of the test failures.
> SOLR-17263: HttpJdkSolrClient doesn't encode curly braces etc

- solr/CHANGES.txt
- solr/solrj-zookeeper/src/java/org/apache/solr/client/solrj/impl/ZkClientClusterStateProvider.java
https://issues.apache.org/jira/browse/SOLR-17275
A recent change, as part of SOLR-17153 to ZkClusterStateProvider caused CloudSolrClient (zk based) to force update collection in local cluster state for aliases, which indeed caused a performance regression. Verified this using a test
Partially reverted the change from SOLR-17153 that caused the regression (behavior on the client side should be fully reverted)
Verified that all tests pass. Used a test locally to understand whether the regression specifically triggers a ZK getData - which did not happen before and after. 
- [] I have run `./gradlew check`.
> SOLR-17275: Major performance regression of CloudSolrClient in Solr 9.6.0 when using aliases

- solr/CHANGES.txt
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/HttpJdkSolrClient.java
This refactors the `preparePutOrPost` method in HttpJdkSolrClient to make the code clearer, and remove the previous unreachable `else` block.
All tests still pass.
> Refactor preparePutOrPost in HttpJdkSolrClient

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/IndexFetcher.java
- solr/core/src/test/org/apache/solr/cloud/RecoveryZkTestWithAuth.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/Http2SolrClient.java
https://issues.apache.org/jira/browse/SOLR-17300
Instead of #2462, this PR would copy the existing listeners to the new Http2SolrClient. This way re-creating client not requires to call explicitly `Builder#withListenerFactory` to copy existing listeners as `withHttpClient` method automatically  takes care of that. 
Added #2462 test case here.
> SOLR-17300: Copy existing listeners on re-creation of Http2SolrClient

- solr/solr-ref-guide/modules/configuration-guide/pages/caches-warming.adoc
Clarify that only the filter cache, and not any other caches, can be disabled by the `cache` local parameter.
> Clarify the cache behavior in the Ref Guide

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/core/CachingDirectoryFactory.java
- solr/core/src/test/org/apache/solr/core/CachingDirectoryFactoryTest.java
https://issues.apache.org/jira/browse/SOLR-17307
> SOLR-17307: Use file separator instead of '/' in CachingDirectoryFactory

- solr/solrj/src/java/org/apache/solr/client/solrj/impl/Http2SolrClient.java
Just a few small matters; no material changes.
> Minor: Http2SolrClient cleanups

- gradlew
- gradlew.bat
* Avoid running GradleWrapper.java if we already have the file
* Don't pass `--source 11` to either script; it's unnecessary and I found there to be an issue in a JDK config where this is (supposedly) incompatible with `--release`, which I don't see specified here (shrug).
> Build: gradlew avoid downloader

- solr/core/src/java/org/apache/solr/handler/component/SearchHandler.java
- solr/core/src/java/org/apache/solr/handler/component/ShardHandler.java
- solr/core/src/java/org/apache/solr/handler/component/TaskManagementHandler.java
- solr/core/src/test/org/apache/solr/core/TestShardHandlerFactory.java
- solr/solrj/src/java/org/apache/solr/common/params/ModifiableSolrParams.java
- solr/solrj/src/test/org/apache/solr/common/params/ModifiableSolrParamsTest.java
From ModifiableSolrParams to SearchHandler.  Too special-purpose to warrant any back-compat concern.  Was here since 2023-06
> Move setShardAttributesToParams

- gradle/testing/randomization/policies/solr-tests.policy
- solr/server/etc/security.policy
- solr/test-framework/src/java/org/apache/solr/SolrTestCaseJ4.java
The Java VM/host, doesn't always support IPv6, our tests shouldn't require it. security.policy: Removed 3 lines that were for tests.
https://issues.apache.org/jira/browse/SOLR-16093
In a fork of Solr that I use at work, these changes are what was needed to get the build passing finally.
I wasn't thinking of adding to CHANGES.txt over build/test matters like this.
> SOLR-16093: Tests: don't require IPv6

- gradle/testing/failed-tests-at-end.gradle
Put a convenient link to test history, powered by Gradle Enterprise.
Could be enhanced to also include fucit.org
Improve the corresponding build logic to be more "groovy", as it's said.
Example, with me forcing some failures to demo:
```
> Task :solr:core:test FAILED
ERROR: The following test(s) have failed:
- org.apache.solr.search.TestThinCache.testInitCore (:solr:core)
Test history: https://ge.apache.org/scans/tests?search.rootProjectNames=solr-root&tests.container=org.apache.solr.search.TestThinCache&tests.test=testInitCore
Test output: /Users/dsmiley/SFDCDev/solr_main/solr/core/build/test-results/test/outputs/OUTPUT-org.apache.solr.search.TestThinCache.txt
Reproduce with: gradlew :solr:core:test --tests "org.apache.solr.search.TestThinCache.testInitCore" -Ptests.jvms=8 …
```
> Build: report test history via GE

- solr/core/src/java/org/apache/solr/cloud/DistributedClusterStateUpdater.java
- solr/core/src/java/org/apache/solr/cloud/api/collections/CollectionHandlingUtils.java
- solr/core/src/java/org/apache/solr/cloud/api/collections/CreateCollectionCmd.java
- solr/core/src/java/org/apache/solr/cloud/api/collections/MoveReplicaCmd.java
- solr/core/src/java/org/apache/solr/cloud/api/collections/RestoreCmd.java
- solr/core/src/java/org/apache/solr/cloud/api/collections/SplitShardCmd.java
- solr/core/src/java/org/apache/solr/servlet/HttpSolrCall.java
Recently Utils.RANDOM came to exist.  Let's remove all the other occurrences of this pattern, replacing references to this one.
> Refactor: dedupe Utils.RANDOM from other spots

- solr/solrj/src/java/org/apache/solr/client/solrj/SolrRequest.java
- solr/solrj/src/java/org/apache/solr/client/solrj/request/RequestWriter.java
and RequestWriter.getPath
https://issues.apache.org/jira/browse/SOLR-17256
First commit is deprecation; maybe just take this PR now and then follow up in another PR with replacements and removal.  Not touching CHANGES.txt merely to mark some obscure methods deprecated but will eventually add to CHANGES.txt when there's something more interesting.
> SOLR-17256: Deprecate SolrRequest get/set BasePath

- solr/solr-ref-guide/modules/query-guide/pages/pagination-of-results.adoc
Cursormark can give some funky results if used across multiple replicas in a SolrCloud collection, if `score` is used as a sort field.  But there's not currently any warning of this in the ref-guide.
This PR documents the limitation for users in the ref-guide.
N/A
> Add 'score' field caveat to cursormark docs

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/api/V2ApiUtils.java
- solr/core/src/java/org/apache/solr/jersey/CatchAllExceptionMapper.java
- solr/core/src/java/org/apache/solr/jersey/MediaTypeOverridingFilter.java
- solr/core/src/test/org/apache/solr/handler/api/V2ApiUtilsTest.java
https://issues.apache.org/jira/browse/SOLR-17317
A mailing list user recently pointed out that certain JAX-RS v2 APIs return XML content when "wt=json" is specified.  The cause is an embarrassing little coding error: a missing switch-case clause for "wt=json" in `V2ApiUtils` 
This PR trivially corrects the error.
Tests added for various 'wt' cases in `V2ApiUtilsTest`.
> SOLR-17317: Correct 'wt' interpretation for v2 APIs

- solr/solrj/build.gradle
Before compiling SolrJ, the gradle build creates an OpenAPI Spec ("OAS") describing our JAX-RS v2 APIs and then uses that spec to generate SolrRequest ".java" files.  The responsible task (`solr:solrj:openApiGenerate`) adds newly generated code to `solrj/build/generated`, but it doesn't (by default) wipe the directory at the start of each invocation.
This can cause generated files to "leak" across branches - sticking around in `solrj/build/generated` even when the developer has changed to a branch that shouldn't contain the file.
These leaks can cause compilation issues, as pointed out by @dsmiley recently [on the dev list](https://lists.apache.org/thread/rth0hbo8y0gtcvrntyvg9khvfl8xh4x8).
The solution is to have the `solr:solrj:openApiGenerate` task clear its output directory each time …
> Clean openApiGenerate output dir before generating

- solr/packaging/test/test_assert.bats
- solr/packaging/test/test_auth.bats
- solr/packaging/test/test_create_collection.bats
- solr/packaging/test/test_example_noprompt.bats
- solr/packaging/test/test_placement_plugin.bats
- solr/packaging/test/test_prometheus.bats
- solr/packaging/test/test_ssl.bats
- solr/packaging/test/test_start_solr.bats
- solr/packaging/test/test_status.bats
https://issues.apache.org/jira/browse/SOLR-17327
bin/solr cli tools that end in /solr is an old approach, and we shouldn't model using it.
> SOLR-17327: remove trailing /solr unless we actually are actually testing it works in backwards compatible fashion.

- solr/modules/hdfs/src/test/org/apache/solr/hdfs/cloud/MoveReplicaHdfsFailoverTest.java
the changes made by SOLR-16962 to ZkController and MoveReplicaCmd resolve the conflation of ulog and tlog dir, and remove some related hacky compensations for this conflation. The nightly test MoveReplicaHdfsFailoverTest was still compensating for this issue when it no longer needs to, and was thus failing.
(no jira)
> fix MoveReplicaHdfsFailoverTest after SOLR-16962

- solr/solr-ref-guide/modules/indexing-guide/pages/field-types-included-with-solr.adoc
https://issues.apache.org/jira/browse/SOLR-16576
The existing documentation for the `StrField` field type makes some assumptions about the configuration and steers users toward not using it for large strings. Apparently it's the `indexed=true` aspect that effectively limits the size of StrField, not the type of the field itself.
It can be fine to use StrField for large strings as long as `indexed=false` and `docValues=false`. The documentation for `StrField` has been updated to reflect this.
N/A
> SOLR-16576: Add information about large StrField configuration to documentation

- solr/solr-ref-guide/modules/query-guide/pages/dense-vector-search.adoc
Minor change to dense vector search documentation (added a note) in relation to this [stackoverflow question](https://stackoverflow.com/questions/77522104/dense-vector-search-with-solr-9-4-incorrect-dot-product-and-cosine-values-retu)
Added a note to dense vector search to tell that cosine similarity scores returned by the knn search for dense vector are normalized.
> Add a note that tells cosine similarities are normalized

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/search/SolrDocumentFetcher.java
https://issues.apache.org/jira/browse/SOLR-17349
> SOLR-17349: SolrDocumentFetcher should always skip lazy field loading overhead if documentCache==null

- .github/workflows/bin-solr-test.yml
- .github/workflows/docker-test.yml
- .github/workflows/gradle-precommit.yml
- .github/workflows/solrj-test.yml
- .github/workflows/tests-via-crave.yml
Spinoff from #2540 
We should run all tests on PRs against `branch_9x`, to catch errors in larger backport efforts.
This should work fine at least until we bump main to some newer java version or make the branches incompatible, but then we can introduce separate workflows for stable and main branches..
> Run more workflows for branch_9x

- solr/solr-ref-guide/modules/query-guide/pages/standard-query-parser.adoc
https://issues.apache.org/jira/browse/SOLR-17358
Fix minor rendering issue to show + symbol again in documentation.
Note that escaping with double backticks doesn't seem to work in this scenario.
> SOLR-17358: Escape + symbol to render documentation correctly

- .github/workflows/stale.yml
Also re-word the stale-message text (with help from GPT).
Increasing operations budget will allow for more PRs to be tagged as stale per run - there is currently a backlog..
> Stalebot: increase to 100 operations per run

- solr/core/src/java/org/apache/solr/search/SolrDocumentFetcher.java
- solr/core/src/java/org/apache/solr/util/SolrPluginUtils.java
this also reverts the code change from 390c30ff56ad354a6ee55eaae54713dd8ec4cce3, which is obviated by directly making `enableLazyFieldLoading` conditional on presence of `documentCache`.
See: https://issues.apache.org/jira/browse/SOLR-17349
> SOLR-17349: (adjusted) SolrDocumentFetcher should always skip lazy field loading overhead if documentCache==null

- solr/solr-ref-guide/modules/deployment-guide/pages/collection-management.adoc
missing a + for `property.<propertyName> (V1), extraProperties (V2)`
what it looks like now https://solr.apache.org/guide/solr/latest/deployment-guide/collection-management.html#backup-parameters
> ref doc format fix on backup page

- solr/solrj-streaming/src/test/org/apache/solr/client/solrj/io/stream/CloudAuthStreamTest.java
- solr/solrj-streaming/src/test/org/apache/solr/client/solrj/io/stream/JDBCStreamTest.java
- solr/solrj-streaming/src/test/org/apache/solr/client/solrj/io/stream/ParallelFacetStreamOverAliasTest.java
- solr/solrj-streaming/src/test/org/apache/solr/client/solrj/io/stream/SelectWithEvaluatorsTest.java
- solr/solrj-streaming/src/test/org/apache/solr/client/solrj/io/stream/StreamDecoratorTest.java
- solr/solrj-streaming/src/test/org/apache/solr/client/solrj/io/stream/StreamExecutorHelperTest.java
- solr/solrj-streaming/src/test/org/apache/solr/client/solrj/io/stream/StreamExpressionTest.java
- solr/solrj-streaming/src/test/org/apache/solr/client/solrj/io/stream/StreamExpressionToExpressionTest.java
- solr/solrj-streaming/src/test/org/apache/solr/client/solrj/io/stream/StreamingTest.java
Typos, methods not used, return values not used, that sort of thing.   Flagged by IntelliJ.
Refactoring, so no CHANGES.txt or JIRA.
> Review org.apache.solr.client.solrj.io.stream and responding to some warnings.

- solr/core/src/java/org/apache/solr/cli/PostTool.java
- solr/core/src/test/org/apache/solr/cli/PostToolTest.java
PostTool did not compile after https://github.com/apache/solr/commit/a405b3b2245350c2dae7e6979f33827e4b979511 due to the backport not being tailored to branch_9x which does not care about testing with basic auth.
Patched PostTool so that the new test creates collection and does the query without auth credentials, also using `url` variable, which actually exists in the class, as opposed to `uri`.
> SOLR-17367 Unbreak the build caused by bad backport

- solr/packaging/test/test_help.bats
- solr/packaging/test/test_post.bats
[SOLR-17357](https://issues.apache.org/jira/browse/SOLR-17357): Improve SolrCLI tool --help printout introduced a new format for the usage description.   Some bats tests appear to not have been updated to match.
Introduce the `bin/solr` part to the usage command checks to match what ` SolrCLI.printToolHelp` does.
Manually rans BATS tests.
> SOLR-17357 Bug fix.  Update to match SolrCLI.printToolHelp formatting rules

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/util/stats/MetricUtils.java
https://issues.apache.org/jira/browse/SOLR-17340
Solr endpoint `/solr/admin/info/system` is slow because of time spent in Java beans introspection.
Add a simple cache on top of bean info introspection. For each bean class, the introspection will be run only once for the JVM lifespan.
Naive performance benchmark. See results in [Jira comment](https://issues.apache.org/jira/browse/SOLR-17340?focusedCommentId=17860407&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17860407)
> SOLR-17340: add cache on top of BeanInfo instrospector

- solr/core/src/java/org/apache/solr/cloud/SyncStrategy.java
No Jira.
This is just to clean-up a bad smell in the code.
We create a `java.lang.Thread` instance, but this thread is never started. It just acts as a target for another existing thread, from the executor pool. The call to `setDaemon()` has no effect.
This code was reported by errorprone because of the thread creation without a name (hence the removed `@SuppressForbidden`)
Replacing the thread by a Runnable makes the full thing cleaner.
> Don't create a Thread when there is no thread

- solr/core/src/java/org/apache/solr/core/CoreContainer.java
On a request level, `multiThreaded=false` is already possible but for full (node level) opt-out SolrIndexSearcher must pass a null executor to Lucene's IndexSearcher.
https://issues.apache.org/jira/browse/SOLR-13350
> SOLR-13350: multi-threaded search: (undocumented) opt-out ability

- solr/core/src/java/org/apache/solr/core/CoreContainer.java
- solr/core/src/java/org/apache/solr/handler/RequestHandlerBase.java
- solr/core/src/java/org/apache/solr/request/SolrRequestInfo.java
- solr/core/src/java/org/apache/solr/search/CpuAllowedLimit.java
- solr/core/src/java/org/apache/solr/search/MultiThreadedSearcher.java
- solr/core/src/java/org/apache/solr/search/QueryLimit.java
- solr/core/src/java/org/apache/solr/search/QueryLimits.java
- solr/core/src/java/org/apache/solr/search/SolrIndexSearcher.java
- solr/core/src/java/org/apache/solr/search/TimeAllowedLimit.java
- solr/core/src/java/org/apache/solr/util/TestInjection.java
- solr/core/src/java/org/apache/solr/util/ThreadCpuTimer.java
- solr/core/src/test/org/apache/solr/search/CallerSpecificQueryLimit.java
- solr/core/src/test/org/apache/solr/search/TestCpuAllowedLimit.java
- solr/solrj/src/java/org/apache/solr/common/util/ExecutorUtil.java
This introduces a version of ThreadCpuTimer class that does not need to depend on the request context or be instantiated to track timing. This approach turns ThreadCpuTimer into a "stopwatch" service that simply answers the question of how long has it been since the last time this thread asked for time... I added an override of beforeExecute() to MDCAwareThreadPoolExecutor and some related methods to ExecutorUtil to allow the "stopwatch" to be reset just before lucene asks the executor to execute a task. Every shouldExit() causes a read operation which returns the time since last read by that thread and resets the timer. An atomic long is used to accumulate the total and test the timeout.
Additionally the ThreadCpuTimer also can track …
> SOLR-17298 - ThreadCpuTimer safe for multi-threaded search

- solr/packaging/build.gradle
Although success and failures are written to stdout, `./gradlew integrationTest` doesn't produce any lasting artifact (i.e. a report) to indicate which tests succeeded and which failed.  BATS has built-in support for reporting, it's just not something that's on by default.
This commit tweaks our BATS invocation so that a JUnit-style XML report ('report.xml') is produced in the packaging module's 'build/test-output' directory.
N/A - this is a build-system-only change.  Though I've done manual testing to ensure that the test report is generated under various circumstances, as expected.
> Produce test report for integration tests

- solr/core/src/test/org/apache/solr/search/TestFiltering.java
It seems the change is no longer necessary now.
https://issues.apache.org/jira/browse/SOLR-13350
> SOLR-13350, SOLR-17298: multi-threaded search: revert TestFiltering.java change

- solr/core/src/java/org/apache/solr/core/CoreContainer.java
- solr/core/src/java/org/apache/solr/request/SolrRequestInfo.java
- solr/core/src/java/org/apache/solr/search/CpuAllowedLimit.java
- solr/core/src/java/org/apache/solr/search/MultiThreadedSearcher.java
- solr/core/src/java/org/apache/solr/search/QueryLimit.java
- solr/core/src/java/org/apache/solr/search/QueryLimits.java
- solr/core/src/java/org/apache/solr/search/SolrIndexSearcher.java
- solr/core/src/java/org/apache/solr/search/TimeAllowedLimit.java
- solr/core/src/java/org/apache/solr/util/TestInjection.java
- solr/core/src/java/org/apache/solr/util/ThreadCpuTimer.java
- solr/core/src/test/org/apache/solr/search/CallerSpecificQueryLimit.java
- solr/core/src/test/org/apache/solr/search/TestCpuAllowedLimit.java
- solr/solrj/src/java/org/apache/solr/common/util/ExecutorUtil.java
Simplify ThreadCpuTimer  by never instantiating it, and instead tracking any number of contexts per thread. This avoids thread safety issues previously caused by keeping state in a field. Also add TestInjection for cpu delay and use it in TestCpuAllowedLimit
Assuming no objections & main remains happy will merge in a couple days
Since https://issues.apache.org/jira/browse/SOLR-16986 (cpu logging) is not in 9x changes to SearchHandler that kept logging in sync with the timeout were omitted.
> SOLR-17298 backport from main.  ThreadCpuTimer for multi-threaded search

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/schema/BinaryField.java
- solr/core/src/java/org/apache/solr/schema/CollationField.java
- solr/core/src/java/org/apache/solr/schema/DenseVectorField.java
- solr/core/src/java/org/apache/solr/schema/FieldType.java
- solr/core/src/java/org/apache/solr/schema/LatLonPointSpatialField.java
- solr/core/src/java/org/apache/solr/schema/PointType.java
- solr/core/src/java/org/apache/solr/schema/PrimitiveFieldType.java
- solr/core/src/java/org/apache/solr/schema/SortableTextField.java
- solr/core/src/test-files/solr/collection1/conf/schema-binaryfield.xml
- solr/modules/analysis-extras/src/java/org/apache/solr/schema/ICUCollationField.java
- solr/solr-ref-guide/modules/indexing-guide/pages/docvalues.adoc
- solr/solr-ref-guide/modules/indexing-guide/pages/field-type-definitions-and-properties.adoc
- solr/solr-ref-guide/modules/query-guide/pages/spatial-search.adoc
- solr/solr-ref-guide/modules/upgrade-notes/pages/major-changes-in-solr-9.adoc
- solr/test-framework/src/java/org/apache/solr/schema/SortableBinaryField.java
https://issues.apache.org/jira/browse/SOLR-10808
This changes the functionality that https://github.com/apache/solr/pull/2017 introduced, by explicitly stating the list of fields that have docValues enabled.
I still need to go through and update the changelog and ref guide to list the affected fields.
Fields:
- PrimitiveField (Numbers/Dates/String/UUID/Enum/Bool) - Without DenseVectors
- SortableTextField
- ICUCollationField
- LatLonPointSpacialField
- SortableBinaryField
> SOLR-10808: Enable docValues by default on specific fields

- dev-tools/scripts/releaseWizard.py
Just a new URL https://downloads.apache.org/solr/KEYS
When we used mirrors, KEYS was not present on the mirrors, naturally. Now it is safe to pull it from CDN since it is under ASF control.
> SOLR-17245 Download KEYS from downloads server

- dev-tools/scripts/releaseWizard.yaml
This should do the trick for suggesting correct jira version
> SOLR-17253 Release wizard suggests wrong minor version for jira

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/core/CoreContainer.java
- solr/core/src/java/org/apache/solr/core/SolrCore.java
- solr/core/src/java/org/apache/solr/core/SyntheticSolrCore.java
- solr/core/src/test/org/apache/solr/search/TestCoordinatorRole.java
https://issues.apache.org/jira/browse/SOLR-17386
It was reported by user (with nice details!) that calling /admin/cores?action=RELOAD&core=<synthetic core on coordinator node> gives 500
This is caused by the change introduced in https://github.com/apache/solr/pull/2438, which core from coordinator node is now of class `SyntheticSolrCore`, which is a child class of `SolrCore`, (instead of being `SolrCore`) and the dummy coordinator collection no longer registers against the zk. 
There are 2 main issues arise because of this change:
1. On a `reload` call of the coordinator core, since the implementation class `SyntheticSolrCore` does not override `reload`, it will run the `SolrCore` implementation which create a new `SolrCore` (instead of `SyntheticSorlCore`) as a replacement.
2. In …
> SOLR-17386: Fixed SyntheticSolrCore reload issue

- solr/core/src/java/org/apache/solr/search/MultiThreadedSearcher.java
- solr/core/src/java/org/apache/solr/search/SolrIndexSearcher.java
(cherry picked from commit e5051e8bed85646f268cb93af9305c0842e02c71)
> SOLR-17298 (backport) verify that graph, join and rerank queries are unaffected by the use of multithreaded search and re-enable them. (#2625)

- solr/core/src/java/org/apache/solr/search/MultiThreadedSearcher.java
- solr/core/src/java/org/apache/solr/search/SolrIndexSearcher.java
(cherry picked from commit e5051e8bed85646f268cb93af9305c0842e02c71)
> SOLR-17298 (backport) verify that graph, join and rerank queries are unaffected by the use of multithreaded search and re-enable them. (#2625) (#2648)

- solr/core/src/test/org/apache/solr/handler/export/TestExportWriter.java
This test was asserting the docs from /export came in the same order as an equivalent from /select.  But that's too strong an expectation; only the sorted values should be equivalent.
It's remarkable to me how much code was written to test it as it was before... I wonder if I'm missing something by replacing it with something fairly trivial?
----
The following test was failing with this seed:
> ./gradlew :solr:core:test --tests "org.apache.solr.handler.export.TestExportWriter.testMultipleSorts"   -Ptests.seed=D7C851B5C905B099
I debugged it for a while; didn't fail due to any recent changes; isn't concurrency related.  Even optimizing to one segment still had the same test failure.
> TestExportWriter fix, loosen order constraint

- solr/core/src/java/org/apache/solr/handler/component/HttpShardHandler.java
HttpShardHandler.transformResponse is an extension hook for subclasses to transform the shard response.  Ever since 9.0 when the HTTP2 Async stuff landed, this hook became inoperable/dormant (method existed but hasn't been called anymore).  This brings it back.
It's sufficiently minor that I'm thinking no JIRA/CHANGES.txt
> HttpShardHandler: Fix extension hook transformResponse

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cli/PostTool.java
https://issues.apache.org/jira/browse/SOLR-3913
if you do a opitmize, don't do a commit, otherwise if you request commit do it.
Be smart about the logic.
Arguably you shouldn't be able to pass in the skip-commit AND the optimize options as the same time...?
> SOLR-3913: Optimize the commit/optimize cycle in the PostTool

- build.gradle
- gradle/testing/defaults-tests.gradle
- gradle/testing/retry-test.gradle
The test-retry mechanism allows failed test cases to be automatically re-run. It also includes functionality to mark the build as "successful" if the tests pass on re-run, though we’re not focusing on that feature at this time. Our primary goal in enabling this mechanism for Develocity is to classify tests as deterministic or non-deterministic. This classification will provide developers with better insights into failed test cases and help them make more informed decisions.
Additionally, it saves time by automating the re-running of failed test cases, so developers don’t have to manually retry them.
```
retry {
maxRetries = 3
maxFailures = 20
failOnPassedAfterRetry = false
}
```
I believe the retry-test functionality is already integrated into the Gradle Enterprise plugin, which our …
> Enabling test-retry-gradle-plugin

- gradle/validation/jar-checks.gradle
- solr/CHANGES.txt
see https://github.com/apache/lucene/issues/13695 for details what the problem was.
> SOLR-17142: Fix Gradle build sometimes gives spurious "unreferenced license file" warnings

- solr/core/src/java/org/apache/solr/cli/RunExampleTool.java
- solr/core/src/test/org/apache/solr/cli/TestSolrCLIRunExample.java
- solr/solr-ref-guide/modules/deployment-guide/pages/docker-faq.adoc
- solr/solr-ref-guide/modules/deployment-guide/pages/solr-control-script-reference.adoc
- solr/solr-ref-guide/modules/getting-started/pages/tutorial-aws.adoc
Couple of small code cleanups..
https://issues.apache.org/jira/browse/SOLR-17423
Deal with `-h` confusion.
Got lucky and found out RunExampleTool never uses `-h` option, so easy removal!
> SOLR-17423: Remove -h as short option for --host, and use --host.

- solr/core/src/java/org/apache/solr/cli/SolrCLI.java
Tools that parse the output of the Solr CLI will be broken with the new deprecation notices. Moving the deprecation notices to stderr instead of stdout will fix this.
Unfortunately we can't make the Deprecation Handler:
```java
o -> System.err.println(o.toDeprecatedString())
```
because `Option.toDeprecatedString()` is package protected for some reason. Because of this, I've basically copied the method until a release of CommonsCLI will make that method public. (or even make stderr the default, which it likely should be)
> SOLR-17429, SOLR-17338: Use stderr for SolrCLI deprecation logs

- solr/solr-ref-guide/modules/query-guide/pages/pagination-of-results.adoc
"You can repeat this process until you’ve fetched as many docs as you want, or until the nextCursorMark returned matches the cursorMark you’ve already specified — indicating that there are no more results."
The pseudo code misses the first part.
Add an extra if for checking whether the number of documents in the result is less than the specified rows. The extra if also prevents an unnecessary extra request.
It could also be shortened, by replacing the two ifs by:
`$done = count($results[response][docs]) < $r || $params[cursorMark] == $results[nextCursorMark]`
I don't know whether that's good for readability.
In addition this could be transformed into a `do while` statement.
None. This is a documentation change.
Not all of the above is …
> Add extra if in pseudocode fetch all docs

- solr/core/src/test/org/apache/solr/search/SolrIndexSearcherTest.java
- solr/core/src/test/org/apache/solr/search/TestFiltering.java
> remove use of deprecated SolrIndexSearcher.search variant

- README.md
- dev-tools/scripts/releaseWizard.yaml
- solr/docker/templates/Dockerfile.body.template
- solr/documentation/src/markdown/index.template.md
- solr/packaging/README.txt
https://issues.apache.org/jira/browse/SOLR-16295
Solr uses variations of the blurb below to describe itself on solr.apache.org, in the ref-guide, READMEs, etc:
> Solr is the popular, blazing-fast, open source enterprise search platform built on Apache Lucene [...]
This has served us well for years, but a few reasons call for a refresh:
1. Copies of this description have varied apart over time and need realigned
2. The description misses (or underplays) some of Solr's newer features (e.g. vector search)
3. Longer forms of the description emphasize features that aren't meaningful differentiators (e.g. XML-based APIs, scalability) in today's tech landscape.
This PR (along with accompanying changes to the operator and website) updates and unifies the language the project uses to describe …
> SOLR-16295: Modernize and standardize project description

- solr/solrj/src/java/org/apache/solr/client/solrj/impl/LBSolrClient.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/HttpSolrClientConPoolTest.java
https://issues.apache.org/jira/browse/SOLR-3696
I haven't found the bug for SOLR-3696 yet but this is at least a step towards hopefully doing so eventually.  At least ruling out a missing close().
(no CHANGES.txt for trivial matter)
> SOLR-3696: LBSolrClient use ObjectReleaseTracker

- solr/CHANGES.txt
- solr/core/src/test/org/apache/solr/cli/AssertToolTest.java
https://issues.apache.org/jira/browse/SOLR-11318
Introduce unit testing to assert tool
Use code already written by @gerlowskija that never made it to a commit!
yeah, thats what this is!
> SOLR-11318: Introduce unit testing for AssertTool

- solr/core/src/java/org/apache/solr/search/facet/FacetParser.java
- solr/core/src/test/org/apache/solr/search/TestMinHashQParser.java
- solr/solrj/src/java/org/apache/solr/common/params/SolrParams.java
Noticed whilst code reading. The methods appear to have been deprecated in Solr 7.4 -- https://issues.apache.org/jira/browse/SOLR-11914 -- and so the removal here can be both for `main` and `branch_9x` branches.
> remove deprecated SolrParams methods

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cli/AuthTool.java
- solr/core/src/java/org/apache/solr/cli/CreateTool.java
- solr/core/src/java/org/apache/solr/cli/DeleteTool.java
https://issues.apache.org/jira/browse/SOLR-16254
Extend help docs to clarify that if you create a core you need to run it on the server.
i couldn't find a good way to check this to prevent it from happening, which would have been nicer.  so tried to just add better help docs.
manual testing
> SOLR-16254: Clarify when a create needs to be run on the same server as Solr.

- solr/solr-ref-guide/modules/deployment-guide/pages/solr-in-docker.adoc
https://issues.apache.org/jira/browse/SOLR-17439
The documentation misses a section for finding out a non-default PID.
Added a `ps` command for finding the PID.
I successfully executed the command in a running Solr 9.6.1 and 9.7.0 container.
> SOLR-17439 Fix missing documentation for finding out non-standard PID for Solr in Docker

- solr/solr-ref-guide/modules/getting-started/pages/tutorial-diy.adoc
- solr/solr-ref-guide/modules/indexing-guide/pages/post-tool.adoc
Small changes from using the bin/solr post tool to index some PDF's!
> Ref Guide Doc fixes to match on bin/solr post works in 9.7

- solr/core/src/java/org/apache/solr/cli/StatusTool.java
https://issues.apache.org/jira/browse/SOLR-17457
On Windows the `bin/solr.cmd` uses the StatusTool with `--max-wait-secs`, but the flag is not supported in the new notation, only in the old format `-maxWaitSecs`.
This PR adds support for the new notation, so that the `bin/solr.cmd` does not fail anymore when running `bin/solr.cmd start`. 
Note that this change is not applicable to `main` because `maxWaitSecs` is already replaced in `StatusTool` with `max-wait-secs`.
I have manually tested the changes on a Windows system, since I am not sure if we have any Windows-specific test bats.
> SOLR-17457: Fix support for --max-wait-secs for bin/solr.cmd

- solr/core/src/java/org/apache/solr/cloud/CloudUtil.java
- solr/core/src/test/org/apache/solr/cloud/ReindexCollectionTest.java
- solr/core/src/test/org/apache/solr/search/TestCpuAllowedLimit.java
- solr/core/src/test/org/apache/solr/search/TestQueryLimits.java
https://issues.apache.org/jira/browse/SOLR-17453
_(this does not fully address the ticket)_
Method `CloudUtil.waitForState()` does use a Zookeeper watch, but it does active polling of the collection state. This change is in test code only.
Update tests so they use the standard `waitForState()`, relying on a Zookeeper watch, instead of actively polling the collection state.
I removed method `CloudUtil.waitForState()`.
Also removed `CloudUtil.clusterShape()` as it is unused. The correct one is in `SolrCloudTestCase` and already used everywhere. This makes test code a little less bloated.
This change is in only test code.
> SOLR-17453: Drop CloudUtil.waitForState() in favor of common waitForState()

- solr/core/src/java/org/apache/solr/cli/StatusTool.java
https://issues.apache.org/jira/browse/SOLR-17457
This PR backports the changes from https://github.com/apache/solr/pull/2717 to `branch_9_7`.
> SOLR-17457: Backport fix for max-wait-secs

- solr/bin/solr
- solr/bin/solr.cmd
- solr/solr-ref-guide/modules/deployment-guide/pages/solr-control-script-reference.adoc
https://issues.apache.org/jira/browse/SOLR-17459
This PR is a fix for the "unrecognized option: -scheme" exception thrown when using the `bin/solr config` tool.
The PR fully removes the support of `-s`, `-scheme` and `--scheme`, which was only used in `ConfigTool` before the migration (see #2540). Note that the argument could be set by the users before the migration. With the migration, the URL scheme can no longer be set via the scheme argument and is now set via the `--solr-url` argument or the environment variable `solr.url.scheme` (in case the fallback URL is used).
Note that this bug occurs only in `branch_9x` and `branch_9_7` and does not affect `main`.
_No tests were modified or added.__
> SOLR-17459: Fix unrecognized option -scheme

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/util/stats/MetricUtils.java
https://issues.apache.org/jira/browse/SOLR-17441
Enhance the property introspection logic by skipping unreadable properties early in the process. By checking if desc.getReadMethod() is null before attempting to access the property, we can avoid unnecessary attempts to access properties that do not have a read method. This will reduce the number of exceptions thrown and the overhead associated with handling those exceptions, improving overall performance and stability.
> SOLR-17441 MetricUtils: Skip Unreadable Properties

- solr/core/src/java/org/apache/solr/search/MultiThreadedSearcher.java
https://issues.apache.org/jira/browse/SOLR-17454
This PR removes an errant ERROR message in the Solr logs. 
This message is not an error, and since there are no other logging calls in this file, it was simply removed.
> SOLR-17454: Remove debugging error message

- solr/bin/solr
- solr/bin/solr.cmd
- solr/core/src/java/org/apache/solr/cli/CreateTool.java
- solr/core/src/java/org/apache/solr/cli/DeleteTool.java
- solr/core/src/java/org/apache/solr/cli/HealthcheckTool.java
- solr/core/src/java/org/apache/solr/cli/SolrCLI.java
- solr/core/src/java/org/apache/solr/cli/ToolBase.java
- solr/packaging/test/test_create.bats
- solr/packaging/test/test_delete_collection.bats
- solr/packaging/test/test_healthcheck.bats
- solr/packaging/test/test_zk.bats
Fixes some bugs that existing in branch_9_7.
* -p port numbers
* bin/solr healthcheck is broken
This has good stuff to port back to main and branch_9x...
New Bats tests added
> bin/solr in branch_9_7 has commands that fail

- solr/bin/solr
- solr/core/src/java/org/apache/solr/cli/SolrCLI.java
- solr/packaging/test/test_version.bats
This ensures the `bin/solr --version`, `bin/solr -version` and `bin/solr version` all work in branch_9x.
> Fix bin/solr handling of --version flag and version command to be backcompat compatible.

- solr/core/src/java/org/apache/solr/cli/AuthTool.java
- solr/core/src/java/org/apache/solr/cli/ConfigSetDownloadTool.java
- solr/core/src/java/org/apache/solr/cli/ConfigSetUploadTool.java
- solr/core/src/java/org/apache/solr/cli/ConfigTool.java
- solr/core/src/java/org/apache/solr/cli/CreateTool.java
- solr/core/src/java/org/apache/solr/cli/DeleteTool.java
- solr/core/src/java/org/apache/solr/cli/HealthcheckTool.java
- solr/core/src/java/org/apache/solr/cli/RunExampleTool.java
- solr/core/src/java/org/apache/solr/cli/SolrCLI.java
- solr/core/src/java/org/apache/solr/cli/ToolBase.java
- solr/core/src/java/org/apache/solr/cli/ZkCpTool.java
- solr/core/src/java/org/apache/solr/cli/ZkLsTool.java
- solr/core/src/java/org/apache/solr/cli/ZkMkrootTool.java
- solr/core/src/java/org/apache/solr/cli/ZkMvTool.java
- solr/core/src/java/org/apache/solr/cli/ZkRmTool.java
- solr/packaging/test/test_config.bats
> Forward port PR#2710

- solr/core/src/test/org/apache/solr/cli/PackageToolTest.java
Just fixing test, no user impact so skipping CHANGES.txt
> Fix failure in PackageToolTest caused by --params instead of --param CLI command

- .github/workflows/stale.yml
Ref mailing list consensus https://lists.apache.org/thread/2v4b0l4vlvzls1vgl5sx2y8mr0c4p6wj
These changes will auto close PRs after 60 days of continued inactivity after receiving the `stale` label, and assign the `closed-stale` label. Further, it will exempt PR with the label `exempt-stale` from ever being marked as stale or auto closed.
Please proof-read the modified messages and settings.
> Close stale PRs after 60 more days

- solr/solrj/src/java/org/apache/solr/client/solrj/util/ClientUtils.java
- solr/solrj/src/test/org/apache/solr/client/solrj/util/ClientUtilsTest.java
- solr/test-framework/src/java/org/apache/solr/SolrTestCaseJ4.java
The 'solr.v2RealPath' system property was used to control how SolrJ built v2 API paths, seemingly as a workaround to allow certain tests to work which didn't at the time use a full Jetty stack. (Jetty.xml is involved in supporting our v2 API currently by rewriting the v2 API root "/api" to "/solr/____v2")
This workaround though is unnecessary and needlessly complicates SolrJ's path-building logic.
Remove all references to 'solr.v2RealPath' in our codebase, and ensure that all tests still pass.
(This change targets 'main' only right now.  It may also be safe to backport to branch_9x, but more investigation is needed there to see whether the user-configurable context-root causes any complications.)
Existing tests continue to pass.  No new tests, as this PR only removes functionality.
Please …
> SOLR-17044: Remove 'solr.v2RealPath' sysprop

- solr/bin/solr
- solr/bin/solr.cmd
- solr/core/src/java/org/apache/solr/cli/DeleteTool.java
- solr/core/src/java/org/apache/solr/cli/PostTool.java
- solr/core/src/java/org/apache/solr/cli/RunExampleTool.java
- solr/solr-ref-guide/modules/deployment-guide/pages/solr-control-script-reference.adoc
- solr/solr-ref-guide/modules/indexing-guide/pages/post-tool.adoc
https://issues.apache.org/jira/browse/SOLR-17488
see jira
* Deprecate -d for server-dir in RunExmapleTool. 
*  Support --server-dir in bin/solr and  bin/solr.cmd 
* Deprecate -d for delay in PostTool to avoid any confusion with conf-dir.
bats and java tests
> SOLR-17488: CLI: Resolve -d conflicts

- solr/bin/solr
- solr/bin/solr.cmd
- solr/packaging/test/test_start_solr.bats
https://issues.apache.org/jira/browse/SOLR-17466
Let 9x users know about bin/solr start being cloud mode by default and that they need `--standalone` in 10.
Warnings
bats
> SOLR-17466: Inform 9x users about upcoming change to solrcloud default mode

- solr/solr-ref-guide/modules/deployment-guide/pages/client-apis.adoc
- solr/solr-ref-guide/modules/deployment-guide/pages/zookeeper-file-management.adoc
Searched for "xref" in ref guide using javascript search thing, and found TWO broken links.  Fixing them.
No changes.txt.
> Fix xref references in Ref Guide

- solr/core/src/java/org/apache/solr/cli/ExportTool.java
- solr/core/src/java/org/apache/solr/cli/PostLogsTool.java
- solr/core/src/java/org/apache/solr/cli/PostTool.java
- solr/core/src/java/org/apache/solr/cli/RunExampleTool.java
- solr/core/src/test/org/apache/solr/cli/PostToolTest.java
- solr/core/src/test/org/apache/solr/cli/TestExportTool.java
- solr/core/src/test/org/apache/solr/cloud/SolrCloudExampleTest.java
- solr/packaging/test/test_basic_auth.bats
- solr/packaging/test/test_export.bats
- solr/packaging/test/test_extraction.bats
- solr/packaging/test/test_post.bats
- solr/packaging/test/test_snapshots.bats
- solr/packaging/test/test_ssl.bats
- solr/prometheus-exporter/src/java/org/apache/solr/prometheus/exporter/SolrExporter.java
- solr/solr-ref-guide/modules/deployment-guide/pages/enabling-ssl.adoc
- solr/solr-ref-guide/modules/indexing-guide/pages/post-tool.adoc
- solr/solr-ref-guide/modules/query-guide/pages/spatial-search.adoc
https://issues.apache.org/jira/browse/SOLR-17489
See JIRA
Deprecate old options in favour of `--solr-url` and `--name`.   I am really liking how this looks after going through the code...
Debating if we should be using `--collection` instead of `--name`....   That can be a seperate ticket.
bats and java
> SOLR-17489: CLI: Deprecate variations on solr urls options

- solr/core/src/java/org/apache/solr/cli/AssertTool.java
- solr/core/src/java/org/apache/solr/cli/PostTool.java
- solr/core/src/java/org/apache/solr/cli/SolrCLI.java
- solr/packaging/test/test_assert.bats
- solr/packaging/test/test_placement_plugin.bats
- solr/packaging/test/test_start_solr.bats
Draft PR to get a green state in branch_9x
Tests used to pass on branch_9x a few days ago. Some of the many `SolrCLI` changes touched the urlNormalization stuff so that you needed to add `/solr` at the end of some URLs passed to Solr.
In particular this was true for `AssertTool`, which I fix here by getting the SolrClient from SolrCLI util method instead of constructing an `Http2HttpSolrClient` manually. The difference is that the former adds a /solr before constructing the client, and this is consistent with other client initializations in AssertTool.
The whole Solr Base Path and `/solr` suffix is a mess, and it is different in main than in branch_9x. So this will keep cropping up for as long as we backport stuff from 10 to 9 :(
> Fix assert tool url normalization

- solr/core/src/java/org/apache/solr/cli/RunExampleTool.java
- solr/packaging/test/test_example_noprompt.bats
https://issues.apache.org/jira/browse/SOLR-17467
Finishing migration towards --user-managed as a flag.
Missed a boolean flip! 
Added a cloud specific assert
> SOLR-17467: Finish migration to --user-managed mode

- solr/bin/solr.cmd
https://issues.apache.org/jira/browse/SOLR-17467
The current changes of this issue that were introduced in #2729  broke the start script on Windows. Executing `bin\solr.cmd start` failed with errors. See https://github.com/apache/solr/pull/2729#issuecomment-2424106562 for details.
Changing these two lines seems to solve the issue. The one change makes sense, the other one doesn't. I guess it's magic. 😕 
@epugh I added you as reviewer since you have made most of the work in the original PR and should better understand the logic of the changes.
_No tests were modified._
> SOLR-17467: Fix Windows start script for default / cloud mode

- gradle/template.gradle.properties
- gradle/testing/defaults-tests.gradle
This is a simple enhancement that makes it easy to enable the html test report that gradle would normally produce (but we disable to save a few seconds). I frequently have a NO_COMMIT change list containing this, and so I've finally got around to formalizing it into a gradle.properties option so others can use it if they like. 
I find it far faster to click on the link displayed at the end of a failed build. YMMV, but now you won't have to edit anything that's version controlled to try it.
> Add an option in the gradle.properties for html junit reports

- solr/core/src/java/org/apache/solr/cli/PostTool.java
- solr/core/src/java/org/apache/solr/cli/SimplePostTool.java
- solr/core/src/java/org/apache/solr/cli/SolrCLI.java
- solr/core/src/test/org/apache/solr/cli/PostToolTest.java
- solr/core/src/test/org/apache/solr/cli/SimplePostToolTest.java
This is the continuation of #2778, as it seems there are some special cases that cause URL parsing issues.
The changes leverage jakarta's `UriBuilder` to avoid custom logic for URL path concatenation, which seems to cause some issues for cases where path segments like the `hostContext` may be `/`. Additionally, the currently used `SolrCLI#normalizeSolrUrl`is updated to behave differently for the special case where `hostContext` is `/`.
Any usage of `PostTool#appendPath` is replaced to avoid custom concatenation.
Since the `appendPath` method is removed, the tests for that method are also removed.
> Resolve CLI tool issues for hostContext "/"

- solr/bin/solr
- solr/bin/solr.cmd
- solr/packaging/test/test_start_solr.bats
https://issues.apache.org/jira/browse/SOLR-17467
The Windows start script on 9x behaves differently than on main / 10.0, and fails with the message "mode. was unexpected at this time.". This mesage is coming from the deprecation warnings.
The fix moves the deprecation warnings to the dedicated mode setter functions and uses `echo` instead of `@echo`, which probably caused the execution error.
Additionally, this commit adds support for the `--user-managed` mode that allows the user to suppress the deprecation warning by being explicit about the current mode.
Existing tests were updated to reflect the updated messages and confirm the behavior for `--user-managed`, `--cloud` and no option (default fallback).
> SOLR-17467: Fix Windows start script on 9x and optimize deprecation messages

- gradle/testing/randomization/policies/solr-tests.policy
- solr/bin/solr
- solr/bin/solr.cmd
- solr/core/src/java/org/apache/solr/cli/SolrCLI.java
- solr/core/src/java/org/apache/solr/cli/SolrProcessManager.java
- solr/core/src/java/org/apache/solr/cli/StatusTool.java
- solr/core/src/test/org/apache/solr/cli/SolrProcessManagerTest.java
- solr/packaging/test/test_help.bats
- solr/packaging/test/test_status.bats
Co-authored-by: Christos Malliaridis <c.malliaridis@gmail.com>
(cherry picked from commit 2391f49b1e47b2cecee147332e57fef9d5ee7583)
https://issues.apache.org/jira/browse/SOLR-17450
> SOLR-17450 StatusTool with pure Java code (backport 9x)

- dev-tools/scripts/releaseWizard.yaml
We should just remove attempting to cleanup the Lucene space once we do the Solr 10.0 release. Right now the wizard fails when it tries to cleanup the Lucene space because the 9x Solr releases are not found there.
> Fix release wizard to remove from Solr space before attempting Lucene

- gradle/testing/randomization/policies/solr-tests.policy
- solr/core/src/test/org/apache/solr/cli/SolrProcessManagerTest.java
After #2712 the introduced changes were causing file permissions errors on Windows systems.
This PR extends the required permissions to all files for Windows, allowing it to run `wmic` without limitations to find and filter processes in the java tests. This permission is not needed when running the `StatusTool` through the CLI, as the Security Manager is not interfering there.
The error returned in test messages mentions:
> access denied ("java.io.FilePermission" "\<\<ALL FILES\>\>" "execute")
The PR fixes an issue in the `PATH` filtering logic for determining the classpath on Windows. Since on Windows an escaped backslash (`\\`) is used, path segments are checked individually instead.
Changes should be backported to `branch_9x`.
> Fix StatusTool related issues on Windows

- solr/CHANGES.txt
https://issues.apache.org/jira/browse/SOLR-17524
I started by listing individual JIRA's and it became a wall of text.  The underlying thing users care about is that stuff changed in the CLI, and you get deprecation warnings ;-).  We have called out (in a separate PR) the biggest changes in the major changes for 10x.
> SOLR-17524: Track changes for the whole slew of CLI commands under one umbrella JIRA

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cli/RunExampleTool.java
https://issues.apache.org/jira/browse/SOLR-17528
match how PackageTool works.
use `-y` to mean accept all the defaults.
> SOLR-17528: Match PackageTool use of -y

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cli/PostTool.java
https://issues.apache.org/jira/browse/SOLR-17529
Misleading error message in the 9x line of Solr.  Fine in 10x!
> SOLR-17529: Clean up error message for 9x.

- solr/core/src/java/org/apache/solr/cli/ExportTool.java
- solr/core/src/test/org/apache/solr/cli/TestExportTool.java
- solr/packaging/test/test_basic_auth.bats
- solr/packaging/test/test_export.bats
- solr/solr-ref-guide/modules/deployment-guide/pages/solr-control-script-reference.adoc
https://issues.apache.org/jira/browse/SOLR-17384
Resolve ExportTool option choices
Move to -- long opt, deprecate -out in favour of --output.
junit and bats
> SOLR-17384: Bring ExportTool options in line with the new CLI pattern

- solr/core/src/test/org/apache/solr/cloud/RecoveryZkTestWithAuth.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/Http2SolrClient.java
https://issues.apache.org/jira/browse/SOLR-17515
Prior to this commit, Http2SolrClient only initialized its 'authenticationStore' instance var when creating a fresh Jetty HttpClient.  This causes NPE's later on when client code (e.g. PreemptiveBasicAuthClientBuilderFactory) would attempt to access the object.
This commit fixes this by making sure that 'authenticationStore' is initialized when using an existing Jetty client (typically by reusing the AuthenticationStore already used by the client).
Strengthens an existing test, RecoveryZkTestWithAuth, by randomizing use of some sysprops helpful for reproducing.
> SOLR-17515: Always init Http2SolrClient authStore

- solr/core/src/java/org/apache/solr/cli/ConfigSetUploadTool.java
- solr/core/src/java/org/apache/solr/cli/CreateTool.java
- solr/core/src/java/org/apache/solr/cli/PackageTool.java
- solr/core/src/java/org/apache/solr/cli/RunExampleTool.java
- solr/core/src/java/org/apache/solr/cli/SolrCLI.java
https://issues.apache.org/jira/browse/SOLR-17383
During the migration of the CLI options some situations do not cover both (old and new) options and therefore compatibility is not granted.
This PR focuses on the options listed in `getOptions()` and adds missing checks and reads to places where they should be included.
Note that this PR focuses only on deprecated options and is not relevant for `main`. For `main` see https://github.com/apache/solr/pull/2725 and future PRs that remove deprecated options.
No tests modified.
> SOLR-17383: Fix support for deprecated options in 9x

- solr/core/src/java/org/apache/solr/update/TransactionLog.java
The TransactionLog constructor can't handle an existing file being present; it shouldn't be there.  Should throw an exception in this case, NOT log a warning, leaving the object in a partially constructed state.
https://issues.apache.org/jira/browse/SOLR-17456
BTW I experienced this on a fork of Solr and I don't know the root cause.  Since applying the fix in this PR, I have not seen it since (perhaps by chance).  It should never happen!
Not sure if needs CHANGES.txt
> SOLR-17456: TransactionLog ctor integrity

- README.md
- dev-docs/asf-jenkins.adoc
We've recently tweaked the Jenkins jobs that we run, in order to get as many 'test' runs as possible out of our hardware.  This involved changing some job names and details in Jenkins. Links and references to those jobs in our dev-docs and README files need updated accordingly.
> Update references to ASF Jenkins jobs

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cluster/events/impl/CollectionsRepairEventListener.java
- solr/core/src/test/org/apache/solr/cloud/ReindexCollectionTest.java
- solr/solrj-zookeeper/src/java/org/apache/solr/client/solrj/impl/SolrClientNodeStateProvider.java
- solr/solrj-zookeeper/src/java/org/apache/solr/common/LazySolrCluster.java
- solr/solrj/src/java/org/apache/solr/common/cloud/ClusterState.java
Use collectionStream() instead.  Redirect callers.  A simple refactoring.
https://issues.apache.org/jira/browse/SOLR-17535
> SOLR-17535: Deprecate ClusterState.forEachCollection

- solr/CHANGES.txt
- solr/solr-ref-guide/modules/deployment-guide/pages/solrj.adoc
- solr/solrj/src/java/org/apache/solr/client/solrj/SolrRequest.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/HttpSolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/HttpSolrClientBase.java
- solr/solrj/src/java/org/apache/solr/client/solrj/request/RequestWriter.java
- solr/solrj/src/java/org/apache/solr/client/solrj/util/ClientUtils.java
- solr/solrj/src/test/org/apache/solr/client/solrj/SolrExampleCborTest.java
- solr/solrj/src/test/org/apache/solr/client/solrj/util/ClientUtilsTest.java
https://issues.apache.org/jira/browse/SOLR-17256
Previous PRs removed all use of getBasePath/setBasePath, but didn't remove the methods themselves to facilitate easier backporting.
This commit removes these methods from 'main'.  It's NOT intended for backporting, as setBasePath/getBasePath are required to stick around on branch_9x through the remainder of the 9x release line.
N/A
> SOLR-17256: Nuke SolrRequest set/getBasePath in 10

- gradle/testing/alternative-jdk-support.gradle
https://issues.apache.org/jira/browse/SOLR-17545 / https://github.com/apache/solr/pull/2848 inadvertently broke alternative JDK support that some Jenkins jobs use to run different JDKs. One deprecated use was replaced this replaces the other one.
This now matches what Lucene has - https://github.com/apache/lucene/blob/main/gradle/testing/alternative-jdk-support.gradle#L53
> SOLR-17545: Fix alternative jdk testing support

- solr/core/src/java/org/apache/solr/cli/StreamTool.java
- solr/core/src/java/org/apache/solr/handler/CatStream.java
- solr/packaging/test/test_stream.bats
https://issues.apache.org/jira/browse/SOLR-17567
In https://github.com/apache/solr/pull/2479 an issue was introduced together with the stream tests that cause the bats tests to fail.
This PR applies a fix that is used in `test_basic_auth.bats` for enabling authentication. Bats tests are not starting with a clean state sometimes, and this is one situation that is affected by that.
A test for missing credentials was added. CLI output could be improved but is not task of this fix / PR.
> SOLR-17567: Fix auth issue in stream tests

- solr/core/src/java/org/apache/solr/core/SolrCore.java
Avoid NPE when SolrCore is closing.
If the snapshotMgr failed to initialize (e.g., because it didn't have write permission to create the snapshot metadata folder), SolrCore begins its `close` routine and may encounter a NPE because snapshotMgr is null.
```
11:07:29.001 [coreLoadExecutor-12-thread-1] ERROR org.apache.solr.core.SolrCore - Error while closing
java.lang.NullPointerException: null
at org.apache.solr.core.SolrCore.doClose(SolrCore.java:1879) ~[solr-core-9.4.0.jar:9.4.0 71e101bb37497f730078d9afe1991b60d10bfe96 - stillalex - 2023-10-10 19:10:39]
at org.apache.solr.core.SolrCore.close(SolrCore.java:1755) ~[solr-core-9.4.0.jar:9.4.0 71e101bb37497f730078d9afe1991b60d10bfe96 - stillalex - 2023-10-10 19:10:39]
at …
```
> Avoid NPE if snapshotMgr failed during init

- .github/labeler.yml
https://issues.apache.org/jira/browse/SOLR-17406
With the updates from https://github.com/apache/solr/pull/2706 the GitHub action does not take the new `gradle/libs.version.toml` into account when setting the `dependencies` label.
Add `gradle/libs.versions.toml` to the watched file list of the dependencies label.
Note that we still want to keep `versions.props` in the list to also label 9X PRs that make changes in the versions.props file.
- ~I have added tests for my changes.~
- ~I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)~
> SOLR-17406: Update labeler.yml to correctly set dependency label

- solr/solrj/src/java/org/apache/solr/client/solrj/impl/LBSolrClient.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/LBHttp2SolrClientIntegrationTest.java
- solr/test-framework/src/java/org/apache/solr/util/LogListener.java
1. Remove "testReliability" because it had no asserts.
2. For "testTwoServers" and "testSimple", wait for the alive check query to be logged after restarting the node.  Previously a blind "Thread.sleep" was in use.
> SOLR-17569: fix flaky test TestLBHttpSolrClient (9.x) / LBHttp2SolrClientIntegrationTest (main)

- solr/CHANGES.txt
- solr/modules/langid/src/java/org/apache/solr/update/processor/LanguageIdentifierUpdateProcessor.java
- solr/modules/langid/src/test/org/apache/solr/update/processor/LanguageIdentifierUpdateProcessorFactoryTestCase.java
https://issues.apache.org/jira/browse/SOLR-17575
Making sure that backwards compatibility with the legacy `"langid.whitelist"` config in Solr Langid works as expected. In other words, the language detection runtime behavior should be the same when the ISO 639-1 language codes specified in the legacy `"langid.whitelist"` OR the current (default) `"langid.allowlist"`.
Making sure that if the legacy `"langid.whitelist"` is configured, its value is used as the default value when reading the `LANG_ALLOWLIST` parameter.
- Added a sanity unit test to demonstrate that the behavior using the current (default) `"langid.allowlist"` is as expected.
- Added a unit test to demonstrate that the backwards compatibility with the legacy `"langid.whitelist"` works as expected.
Please review the following …
> SOLR-17575: Fixed broken backwards compatibility with the legacy "langid.whitelist" config in Solr Langid

- solr/bin/solr.cmd
https://issues.apache.org/jira/browse/SOLR-17352
This PR backports the changes from #2858.
Additionally to the changes from #2858 this also updates the outdated `--solr.home` param in the output of `bin/solr.cmd start --help`.
Manually tested the presence of the bug and the fix by running `bin/solr.cmd auth enable -s http://localhost:8983 --prompt true` on a running instance (cloud mode).
> SOLR-17352: Backport removal of deprecated options for auth command (#2858)

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/api/V2HttpCall.java
- solr/core/src/java/org/apache/solr/cli/ExportTool.java
- solr/core/src/java/org/apache/solr/servlet/HttpSolrCall.java
- solr/solr-ref-guide/modules/upgrade-notes/pages/major-changes-in-solr-10.adoc
- solr/test-framework/src/java/org/apache/solr/cloud/AbstractBasicDistributedZk2TestBase.java
https://issues.apache.org/jira/browse/SOLR-17568
> SOLR-17568: SolrCloud shouldn't proxy/route a core specific request

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/security/AllowListUrlChecker.java
- solr/core/src/test/org/apache/solr/handler/component/TestShardHandlerFactory.java
- solr/core/src/test/org/apache/solr/security/AllowListUrlCheckerTest.java
- solr/solrj/src/java/org/apache/solr/common/cloud/ClusterState.java
Remove the host allow list cache from ClusterState and move it to it's only caller AllowListUrlChecker. There it is cached based on live nodes.
> SOLR-17574: Move host allow list cache to AllowListUrlChecker.

- solr/core/src/java/org/apache/solr/cli/RunExampleTool.java
https://issues.apache.org/jira/browse/SOLR-16781
A specific change was missing in the PR https://github.com/apache/solr/pull/2875 but present in the backport https://github.com/apache/solr/pull/2894, which leads to job execution failure.
Add the missing change.
_none_
> SOLR-16781: Fix missing change in RunExampleTool

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cli/SolrCLI.java
- solr/core/src/java/org/apache/solr/cloud/ZkCLI.java
- solr/server/scripts/cloud-scripts/zkcli.sh
https://issues.apache.org/jira/browse/SOLR-17586
This is a partial fix for https://github.com/apache/solr-operator/issues/720 on the solr side.
> SOLR-17586 Print zkcli.sh deprecation msg to stderr (9x)

- solr/solrj/src/java/org/apache/solr/common/cloud/ClusterState.java
- solr/solrj/src/java/org/apache/solr/common/cloud/DocCollection.java
- solr/solrj/src/java/org/apache/solr/common/cloud/Replica.java
https://issues.apache.org/jira/browse/SOLR-17561
Just some deprecations to help users (and us) to switch off of some methods.
The JIRA issue, as originally written (now), is a bit specific to certain methods but it could be generalized to ClusterState / DocCollection / Slice / Replica stuff.
> SOLR-17561 Deprecations in ClusterState/DocCollection/Replica

- solr/core/src/test/org/apache/solr/handler/admin/api/ClusterPropsAPITest.java
https://issues.apache.org/jira/browse/SOLR-16390
(linking to the Jira that introduced the test)
The test fails when SSL is enabled, because of testing framework that set 'urlScheme' cluster property.
I was looking at the failure in another PR, and it seems this test fails quite often since #2788. I don't think it is tracked somewhere else.
This change updates the test to ignore existing cluster properties.
n/a
> SOLR-16390: fix flaky test ClusterPropsAPITest.testClusterPropertyOpsAllGood

- solr/solr-ref-guide/modules/query-guide/pages/streaming-expressions.adoc
https://issues.apache.org/jira/browse/SOLR-17583
The section for adding Custom Expressions was removed in Solr 8.8. This change brings it back.
I found the source for the Custom Expressions section in the 8.7 docs and copied It to the current streaming-expressions.adoc page. The Expressible interface has been moved into the solrj-streaming package since version 8.7 so I updated the link to this interface to point to the correct javadoc location.
I ran `./gradlew tidy updateLicenses check -x test` and then opened my local copy of the Reference Guide.  I verified that I see the new text and that the link to the Expressible javadoc is working.
- [x ] I have reviewed the guidelines for [How to …
> SOLR-17583: Bring back documentation for Adding Custom Expressions

- solr/CHANGES.txt
- solr/bin/solr.cmd
- solr/core/src/java/org/apache/solr/cli/RunExampleTool.java
https://issues.apache.org/jira/browse/SOLR-17595
This is the backport for the fixes from #2909.
I have manually tested this backport PR to make sure the examples are working fine. Tested `techproducts` and `cloud` with
```bash
>bin\solr.cmd start -e techproducts
>bin\solr.cmd start -e cloud
```
Both are executed successful and created the expected collections.
- X] I have reviewed the guidelines for [How to Contribute](https://github.com/apache/solr/blob/main/CONTRIBUTING.md) and my code conforms to the standards described there to the best of my ability.
> SOLR-17595: Backport "Fix Solr examples for Windows"

- solr/CHANGES.txt
- solr/solrj-zookeeper/src/java/org/apache/solr/common/cloud/ConnectionManager.java
- solr/solrj-zookeeper/src/java/org/apache/solr/common/cloud/SolrZkClient.java
https://issues.apache.org/jira/browse/SOLR-17405
`OnReconnect` can be invoked by several threads concurrently (see Jira for the explanation).
Same change as #2644, but against `9x` branch. This bug does not exist anymore in `main` since the move to Curator.
Always add the wrapper on the watch that handle the session expiration events. This makes sure the session is re-established in a dedicated thread, and this thread exists only once per server.
No new tests added. Unfortunately, this is super tricky to reproduce.
> SOLR-17405: allow a single thread to reestablish ZK session

- solr/core/src/java/org/apache/solr/search/CaffeineCache.java
- solr/core/src/test/org/apache/solr/search/TestCaffeineCache.java
https://issues.apache.org/jira/browse/SOLR-17597
> SOLR-17597: Fix `CaffeineCache.put()` ramBytes decrement

- solr/core/src/java/org/apache/solr/cloud/ZkController.java
- solr/core/src/test/org/apache/solr/cloud/OverseerTaskQueueTest.java
- solr/solrj/src/java/org/apache/solr/common/MapWriter.java
I don't really like MapWriter.append – undocumented and called in only 2 places.  Since MapWriter is implemented by a great many things, we should be conservative adding methods there.   append() is kind of clever but I think it's outside the scope of what MapWriter should be.
> Deprecate MapWriter.append

- .github/renovate.json
With the version catalogs the solrbot stopped working, and we considered switching to dependabot (see https://github.com/apache/solr/pull/2880). Since the switch to dependabot is not straight-forward and was proven difficult, we may update solrbot to work with version catalogs.
This solution updates the renovate.json file, adds the version catalog file to the includePaths and executes the writeLocks task before updating licenses, as this step was also changed during the migration to version catalogs.
> Fix renovate.json to work with version catalogs

- dev-tools/scripts/parseContributorsFromChanges.py
This script can be used to list contributors as indicated in CHANGES.txt so that we can easily thank them in our release notes.
I tested it on 9.6 and I'm happy with the results!  Added them to: https://cwiki.apache.org/confluence/display/SOLR/ReleaseNote9_6_0
Ideally we incorporate this into the Release Wizard.
> Parses CHANGES.txt to identify contributors

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/admin/MetricsHandler.java
- solr/core/src/java/org/apache/solr/metrics/prometheus/core/PrometheusCoreFormatterInfo.java
- solr/core/src/java/org/apache/solr/metrics/prometheus/core/SolrCoreCacheMetric.java
- solr/core/src/java/org/apache/solr/metrics/prometheus/core/SolrCoreHandlerMetric.java
- solr/core/src/java/org/apache/solr/metrics/prometheus/core/SolrCoreHighlighterMetric.java
- solr/core/src/java/org/apache/solr/metrics/prometheus/core/SolrCoreIndexMetric.java
- solr/core/src/java/org/apache/solr/metrics/prometheus/core/SolrCoreMetric.java
- solr/core/src/java/org/apache/solr/metrics/prometheus/core/SolrCoreSearcherMetric.java
- solr/core/src/java/org/apache/solr/metrics/prometheus/core/SolrCoreTlogMetric.java
- solr/core/src/java/org/apache/solr/metrics/prometheus/core/SolrPrometheusCoreFormatter.java
- solr/core/src/java/org/apache/solr/response/PrometheusResponseWriter.java
- solr/core/src/test/org/apache/solr/handler/admin/MetricsHandlerTest.java
- solr/core/src/test/org/apache/solr/metrics/SolrCoreMetricTest.java
- solr/core/src/test/org/apache/solr/metrics/SolrPrometheusFormatterTest.java
- solr/core/src/test/org/apache/solr/response/TestPrometheusResponseWriter.java
https://issues.apache.org/jira/browse/SOLR-17587
Solr's Prometheus writer duplicates `# TYPE <metric name> <prometheus metric type>` in it's exposition format for `core`registry metrics. 
This is an illegal format and depending on the technologies prometheus exposition verification for example `Telegraf`, this will fail. For Prometheus server itself, this still passes and collects the metrics just fine for some reason.
This is because the Prometheus Writer takes Dropwizard registries and exports them to Prometheus Registries to expose them in Prometheus format. Solr creates Dropwizard registry for every `core` and differentiates the metrics that way even though they have the same metric names.
For prometheus, this creates an issue in that metrics should be differentiated in it's …
> SOLR-17587: (9x backport) wt=prometheus fix duplicate TYPE information 

- solr/core/src/test/org/apache/solr/cloud/DeleteInactiveReplicaTest.java
The test was retrieving a replica from cluster state using core name instead of correct replica name.
The test is rarely failing because of this, it may happen.
Fix the test, just replace `getCoreName()` by `getName()`.
> Fix rarely flaky DeleteInactiveReplicaTest.

- solr/solr-ref-guide/modules/query-guide/pages/faceting.adoc
(small docs contribution, not in jira)
While experimenting with some different `facet.method`s in solr, I found the `requestedMethod` and `appliedMethod` fields in the debug output very helpful.  I did not see them mentioned in the ref guide yet, so wanted to make them easier to find.
Mention these debug fields in the ref guide as a note.
No tests provided, it's just a documentation commit.
> [ref guide] Note how to view the requested and applied facet.method

- solr/core/src/java/org/apache/solr/core/PluginInfo.java
- solr/core/src/java/org/apache/solr/core/SolrConfig.java
- solr/core/src/java/org/apache/solr/core/SolrXmlConfig.java
- solr/core/src/java/org/apache/solr/schema/FieldTypePluginLoader.java
- solr/core/src/java/org/apache/solr/schema/IndexSchema.java
- solr/core/src/java/org/apache/solr/util/DOMConfigNode.java
- solr/core/src/java/org/apache/solr/util/DataConfigNode.java
- solr/core/src/java/org/apache/solr/util/plugin/AbstractPluginLoader.java
- solr/core/src/java/org/apache/solr/util/plugin/MapPluginLoader.java
- solr/core/src/java/org/apache/solr/util/plugin/NamedListPluginLoader.java
- solr/core/src/test/org/apache/solr/core/TestCodecSupport.java
- solr/solrj/src/java/org/apache/solr/common/ConfigNode.java
- solr/solrj/src/java/org/apache/solr/common/util/DOMUtil.java
ConfigNode.requiredStrAttr -> attrRequired
ConfigNode.child (ex) -> childRequired
ConfigNode.getAll move name to first param; don't use empty set
PluginInfo: don't need the XML Node constructor anymore
A Solr 10-only change
> Move DOMUtil ConfigNode methods to ConfigNode, with some name changes.

- solr/modules/hadoop-auth/src/java/org/apache/solr/security/hadoop/HadoopAuthPlugin.java
- solr/solr-ref-guide/modules/deployment-guide/pages/hadoop-authentication-plugin.adoc
https://issues.apache.org/jira/browse/SOLR-17540
Communicate to 9x users that Hadoop Auth is removed in 10 when it comes out.
This goes with the already committed code in https://github.com/apache/solr/pull/2835 to `main` that removed Hadoop Auth.
> SOLR-17540: mark deprecation and removal of Hadoop Auth

- .github/workflows/bin-solr-test.yml
- .github/workflows/docker-test.yml
- .github/workflows/gradle-precommit.yml
- .github/workflows/solrj-test.yml
- dev-docs/FAQ.adoc
- gradle/develocity.gradle
- gradle/testing/failed-tests-at-end.gradle
- settings.gradle
This PR migrates the Solr project to publish Build Scans to the the new Develocity instance at develocity.apache.org.
N/A
N/A
> Publish build scans to develocity.apache.org

- solr/solr-ref-guide/modules/indexing-guide/pages/language-analysis.adoc
I am adding info about the undocumented Spanish Plural Stemmer (https://github.com/apache/lucene/issues/11284, https://lucene.apache.org/core/9_11_0/analysis/common/org/apache/lucene/analysis/es/SpanishPluralStemmer.html)
I reworked the initial paragraph in the "Spanish" section and added an example.
No tests, just integrating the reference docs :-)
> Add info about the Spanish Plural Stemmer

- solr/CHANGES.txt
- solr/modules/sql/src/java/org/apache/solr/handler/sql/SolrEnumerator.java
https://issues.apache.org/jira/browse/SOLR-17629
This unblocks #2764 (more use of Http2SolrClient / Jetty HttpClient) which has greater use of ObjectReleaseTracker than Apache HttpClient, thus detecting problems formerly unseen.
> SOLR-17629: SQLHandler: remember to close if open fails

- .github/renovate.json
Now that main branch uses gradle version catalogs (#2706), dependency upgrades cannot be easily back ported to branch_9x anymore, unless the version catalogs are back ported as well.
Also, many features are removed in main that still exist in branch_9x, so we will miss out on certain dep updates if we only rely on manual backports.
Therefore I propose, and will test with dryRun, that @solrbot files separate PRs for branch_9x, using the [baseBranches feature](https://docs.renovatebot.com/configuration-options/#basebranches). For that to work we define [`useBaseBranchConfig=merge`](https://docs.renovatebot.com/configuration-options/#usebasebranchconfig) so that we can use `renovate.json` on this branch as an overlay, specifying configs that differ from main and giving a PR title suffix etc. …
> Prepare for having Renovate add separate PRs for branch_9x

- solr/solrj-zookeeper/src/java/org/apache/solr/common/cloud/ZkStateReader.java
Remove broken and unused implementation of `getReplicaProps()` which is error prone.
> Remove broken and unused ZkStateReader.getReplicaProps()

- solr/core/src/test/org/apache/solr/handler/ReplicationTestHelper.java
- solr/core/src/test/org/apache/solr/handler/TestReplicationHandler.java
This actually stems from two commits on the same day, kind of eerie.
This uncommented out:
```java
System.setProperty("solr.directoryFactory", "solr.StandardDirectoryFactory");
```
Apparently when using the StandardDirectoryFactory, we see core snapshot directories when we don't see them using the default DirectoryFactory. The code already accounted for snapshot metadata, but not snapshots themselves. I updated the check to ignore any snapshot directory when counting index directories. @dsmiley, you wrote the snapshot metadata filtering, so can you check this for me?
In `ReplicationTestHelper`, this changed 
```java
FileUtils.copyFile(
new File(SolrTestCaseJ4.TEST_HOME(), "solr.xml"),
new File(instance.getHomeDir(), "solr.xml"));
```
to
```java
Files.copy( …
```
> Fix TestReplicationHandler

- solr/CHANGES.txt
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/LBHttp2SolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/LBSolrClient.java
https://issues.apache.org/jira/browse/SOLR-17637
> SOLR-17637: Fix LBHttpSolrClient & HttpShardHandler bug

- .github/workflows/tests-via-crave.yml
The Solr tests ran for over 2 days - and I forgot to check them over the weekend.    
Keeping a 96 core machine running for that long is expensive.
1. Limit the runtime to 90 minutes
2. At the end, always send a clear kill signal to the job running in Crave
None: This is a Github Actions change
> Limit Github Actions runtime and cleanup always

- gradle/testing/randomization.gradle
- solr/core/src/java/org/apache/solr/update/processor/ParseDateFieldUpdateProcessorFactory.java
- solr/core/src/test/org/apache/solr/security/BasicAuthIntegrationTest.java
- solr/core/src/test/org/apache/solr/update/processor/ParsingFieldUpdateProcessorsTest.java
https://issues.apache.org/jira/browse/SOLR-17379
> SOLR-17379: Fix date parsing in Java 23, remove Lucene TestSecurityManager

- solr/core/src/java/org/apache/solr/cli/StatusTool.java
- solr/core/src/java/org/apache/solr/handler/admin/ClusterStatus.java
- solr/core/src/java/org/apache/solr/handler/admin/CollectionsHandler.java
- solr/core/src/test/org/apache/solr/cloud/api/collections/TestCollectionAPI.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/BaseHttpClusterStateProvider.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/ClusterStateProviderTest.java
https://issues.apache.org/jira/browse/SOLR-17582
Check for SolrJ version from a cluster status request user agent header to stream the response for any SolrJ clients >= 9.9 allowing for backwards compatibility.
Removed old Javabin check that didn't allow streaming for SolrJ and use the requests Solr version as the check instead for >= 9.9 to either stream or collect whole response in a `SimpleOrderedMap`
Created `testClusterStateProviderBackwardCompatability` to test backwards compatability
> SOLR-17582: Stream CLUSTERSTATUS API for SolrJ version >= 9.9

- solr/core/src/java/org/apache/solr/filestore/DistribFileStore.java
https://issues.apache.org/jira/browse/SOLR-17654
Number of tests failing on windows due to beginning slash in a path not being stripped to become relative.
Revert to old logic but use more modern `FileSystems.getDefault().getSeparator()` instead.
> SOLR-17654: DistribFileStore._getRealPath() has issues on Windows

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/search/SolrIndexSearcher.java
from unlimited to 1000 max, after which the caller thread will execute.
Didn't need the RejectedExecutionException avoidance hack anymore; Lucene 9.12 has it.
https://issues.apache.org/jira/browse/SOLR-17648
> SOLR-17648: multiThreaded=true: changed queue implementation

- solr/core/src/test/org/apache/solr/cloud/SSLMigrationTest.java
- solr/core/src/test/org/apache/solr/cloud/TestMiniSolrCloudClusterSSL.java
- solr/test-framework/src/java/org/apache/solr/SolrTestCaseJ4.java
Only a test or two need to actually reset this.
AfterClass no longer calls:
* HttpClientUtil.resetHttpClientBuilder();
* Http2SolrClient.resetSslContextFactory();
----
The theme here is trimming away quirky one-off activities in STCJ4 AfterClass & BeforeClass
Planning to do main only.
> SolrTestCaseJ4: don't reset HttpClient SSL stuff

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/search/facet/FacetField.java
- solr/core/src/java/org/apache/solr/search/facet/FacetFieldProcessorByArrayDV.java
- solr/core/src/java/org/apache/solr/search/facet/FieldUtil.java
- solr/core/src/test-files/solr/collection1/conf/schema_latest.xml
- solr/core/src/test/org/apache/solr/response/TestRawTransformer.java
- solr/core/src/test/org/apache/solr/search/facet/TestJsonFacets.java
https://issues.apache.org/jira/browse/SOLR-17649
FacetFieldProcessorByArrayDV can not handle fields with DocValues of type DocValuesType.SORTED_NUMERIC.
If such a type is requested for faceting FacetFieldProcessorByHashDV must be used.
Use the correct FacetFiledProcessor
Create multi valued EnumFileds, which had DocValues enabled, to ensure the use of  DocValuesType.SORTED_NUMERIC, index a few multivalued docs and query the facets afterwards
> SOLR-17649: Fix Json faceting on  multivalue number types

- solr/core/src/test/org/apache/solr/cloud/BalanceReplicasTest.java
- solr/core/src/test/org/apache/solr/pkg/TestPackages.java
- solr/solrj-zookeeper/src/java/org/apache/solr/common/cloud/NodesSysPropsCacher.java
- solr/solrj/src/java/org/apache/solr/common/MapWriter.java
- solr/solrj/src/java/org/apache/solr/common/MapWriterMap.java
- solr/solrj/src/java/org/apache/solr/common/NavigableObject.java
- solr/solrj/src/java/org/apache/solr/common/util/Utils.java
- solr/solrj/src/test/org/apache/solr/common/cloud/PerReplicaStatesIntegrationTest.java
Introduce NavigableObject.wrap to coerce its arg to a NavigableObject.  Maybe call this method "of"?
Deprecate MapWriter.EMPTY; don't need it anymore (due to the above); was only used once.
Enhance Utils to not need MapWriterMap for its functions, and to slightly optimize for SimpleOrderedMap becoming a Map soon.
Deprecate MapWriterMap.  Ultimately may simply make package scope and maybe rename to orient itself around it's NavigableObject-ness, which is what it's only used for, after the changes here.
No JIRA: too internal; low impact.
> Add NavigableObject.wrap. Deprecate MapWriter.EMPTY and MapWriterMap.

- solr/core/src/java/org/apache/solr/util/TimeOut.java
- solr/core/src/test/org/apache/solr/util/TimeOutTest.java
https://issues.apache.org/jira/browse/SOLR-17663
TimeOut constructor is passed a long interval parameter. If this long is large enough, the timeoutAt field overflows, making all the methods incorrect, including hasTimedOut() which returns true immediately.
TimeUnit.convert() deals with the same problem by checking the value to convert ahead of time and by setting fixed Long.MAX_VALUE to prevent overflow. We should do the same for timeoutAt in TimeOut constructor.
> SOLR-17663: Protect TimeOut from overflow.

- solr/benchmark/src/java/org/apache/solr/bench/generators/StringsDSL.java
- solr/benchmark/src/test/org/apache/solr/bench/DockMakerTest.java
See this [thread](https://github.com/apache/solr/pull/254#discussion_r1917413526)
> I see a repeating failure running DockMakerTest.testBasicCardinalityAlpha with seed E0BBCB76FA600308 in which every field value is the letter 'k'. This DSL framework is extremely different from any other code most people encounter so it took some time to narrow down the problem to where I'm commenting. This code will choose consecutive seeds for subsequent processing. (Consecutiveness is not a problem I think). For a cardinality of 2 and based on the random test seed, this long seed will be either 635258717 or 635258718. But the next stage will always produce 'k' for either of those seeds; the next stage produces a random string of length from 1 to 6.
I think the fundamental fix is in the test; to …
> Fix DockMakerTest maxCardinality

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/core/NodeConfig.java
- solr/solr-ref-guide/modules/upgrade-notes/pages/major-changes-in-solr-9.adoc
https://issues.apache.org/jira/browse/SOLR-17673
> SOLR-17673: Disable multithreaded search at the node level by default

- solr/core/src/java/org/apache/solr/search/SolrIndexSearcher.java
- solr/server/solr/solr.xml
- solr/solr-ref-guide/modules/configuration-guide/pages/configuring-solr-xml.adoc
- solr/solr-ref-guide/modules/upgrade-notes/pages/major-changes-in-solr-9.adoc
https://issues.apache.org/jira/browse/SOLR-17673
An addition to https://github.com/apache/solr/pull/3183
Spun off from @risdenk 's comment here : https://github.com/apache/solr/pull/3183#issuecomment-2659988149
> SOLR-17673: Add back in option to use max CPU threads for searching

- solr/core/src/java/org/apache/solr/cloud/ZkCollectionTerms.java
- solr/core/src/java/org/apache/solr/cloud/ZkController.java
- solr/core/src/java/org/apache/solr/cloud/ZkShardTerms.java
- solr/solrj-zookeeper/src/java/org/apache/solr/common/cloud/ZkStateReader.java
https://issues.apache.org/jira/browse/SOLR-17645
The main one I see in our tests are threads submitted by ZkStateReader.waitForState(), and ZkShardTerms having issues while a cluster is shutting down. I'll be looking for more and trying to address in this one PR.
> SOLR-17645: Gracefully handle exceptions in executor threads

- solr/solr-ref-guide/modules/deployment-guide/pages/enabling-ssl.adoc
The example to update the Zookeeper properties has a typo as it uses urlSchema instead of urlScheme.
Rename property in examples.
None.
> Update enabling-ssl.adoc - fix minor typo in example

- solr/solr-ref-guide/modules/deployment-guide/pages/solr-control-script-reference.adoc
Use "SolrCLI" on the main page for the SolrCLI.
this is a small fix, someday we need to rewrite/reorg the Solr Control Script page.    At least now the search bar finds "Solrcli"...
> Address that the word solrcli doesnt find this main page in Ref Guide

- solr/modules/hdfs/src/java/org/apache/solr/hdfs/HdfsDirectoryFactory.java
- solr/solr-ref-guide/modules/deployment-guide/pages/solr-on-hdfs.adoc
https://issues.apache.org/jira/browse/SOLR-17609
This PR updates `branch_9x` to flag that we are deprecating HDFS and removing it in Solr 10.
Pairs with https://github.com/apache/solr/pull/2923 that goes on `main`.
Only apply to branch_9x.  We should try and get the current "latest" ref guide updated with this PR to give folks a chance to know in case 9.9 never happens.
> SOLR-17609:  mark deprecation of HDFS module in 9x and removal in 10

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/core/CachingDirectoryFactory.java
- solr/core/src/java/org/apache/solr/core/DirectoryFactory.java
- solr/core/src/java/org/apache/solr/handler/IncrementalShardBackup.java
- solr/core/src/java/org/apache/solr/handler/admin/api/ReplicationAPIBase.java
Currently Replication and Backup copy files using a Directory created with the configured DirectoryFactory. This Directory may be a FilterDirectory that adds additional logic (e.g. encryption) that should not run when copying files (e.g. do not decrypt).
The proposal is to add a new REPLICATE value in the DirectoryFactory.DirContext that would be used by replication, and a new BACKUP for backup to get the Directory to use. The DirectoryFactory would unwrap the Directory in this case.
One could expect that only one REPLICATE could be enough, but backup requires more inner checksum verifications that may need to differentiate the logic between the two (this is the case for encryption).
Example:
In the solr-sandbox encryption module, we would need a way to unwrap the Directory used to copy …
> SOLR-17671 Replication and Backup use an unwrapped Directory.

- solr/CHANGES.txt
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/LBHttp2SolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/LBHttpSolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/LBSolrClient.java
- solr/solrj/src/test/org/apache/solr/client/solrj/TestLBHttp2SolrClient.java
https://issues.apache.org/jira/browse/SOLR-17667
I made a patch for branch_9x first, since that's where the failures are occurring for TestLBHttp2SolrClient
The changes are:
- No alive map, just allServers map for the servers given to the client (not passed via a request)
- The aliveness is determined by if the zombieMap contains the server
- All modifications to allServers and zombieServers go through the same methods. These methods are synchronized, so the list and both maps will not be updated independently.
- Since all modifications go through the same methods, we don't need to worry about dropping servers as the previous logic did.
> SOLR-17667: Simplify zombie logic in LBSolrClient

- dev-tools/scripts/releaseWizard.yaml
As discussed in slack https://the-asf.slack.com/archives/CEKUCUNE9/p1738760259166169
I opted to keep the instructions in the wizard but clearly mark it as optional, skipping the S/MIME email client stuff and focusing only on gpg command line clearsign option.
Not ran the wizard after this change so may be formatting bugs...
> Make PGP signing the release announcement optional

- solr/solr-ref-guide/modules/configuration-guide/pages/solr-plugins.adoc
- solr/solr-ref-guide/modules/deployment-guide/pages/cluster-node-management.adoc
- solr/solr-ref-guide/modules/getting-started/pages/solr-admin-ui.adoc
- solr/solr-ref-guide/modules/indexing-guide/pages/language-analysis.adoc
- solr/solr-ref-guide/modules/query-guide/pages/query-syntax-and-parsers.adoc
- solr/solr-ref-guide/modules/query-guide/pages/text-to-vector.adoc
The build outputs are reporting a few issues with tables cells that are not rendered and duplicate IDs.
This PR fixes these issues by updating the duplicate IDs and adding additional cells so that the last row / cell is displayed again.
Affected pages can be reviewed in current ref guide for the missing cells / page references.
> Fix asciidoc errors and warnings

- solr/solrj/src/java/org/apache/solr/common/util/IOUtils.java
To retain compatibility within 9x.
Not bringing this to main/10x.
This issue was introduced by [SOLR-17593: New home for default http2 client apache/solr#2689](https://github.com/apache/solr/pull/2689) and was seen to be a compatibility issue in the DIH for one: https://github.com/SearchScale/dataimporthandler/issues/91
> IOUtils: add back closeQuietly(Closeable)

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/core/ByteBuffersDirectoryFactory.java
- solr/core/src/java/org/apache/solr/core/CachingDirectoryFactory.java
- solr/core/src/java/org/apache/solr/core/DirectoryFactory.java
- solr/core/src/java/org/apache/solr/core/MMapDirectoryFactory.java
- solr/core/src/java/org/apache/solr/core/NIOFSDirectoryFactory.java
- solr/core/src/java/org/apache/solr/core/NRTCachingDirectoryFactory.java
- solr/core/src/java/org/apache/solr/core/RAMDirectoryFactory.java
- solr/core/src/java/org/apache/solr/core/StandardDirectoryFactory.java
- solr/core/src/test/org/apache/solr/core/AlternateDirectoryTest.java
- solr/core/src/test/org/apache/solr/core/ByteBuffersDirectoryFactoryTest.java
- solr/core/src/test/org/apache/solr/core/RAMDirectoryFactoryTest.java
- solr/core/src/test/org/apache/solr/handler/admin/CoreMergeIndexesAdminHandlerTest.java
- solr/test-framework/src/java/org/apache/solr/core/MockDirectoryFactory.java
- solr/test-framework/src/java/org/apache/solr/core/MockFSDirectoryFactory.java
https://issues.apache.org/jira/browse/SOLR-17675
In a previous [PR](https://github.com/apache/solr/pull/3185), we noted that the DirContext of the DirectoryFactory.create method should be removed. It was used only by the HdfsDirectoryFactory (now removed), and there was a bug in CachingDirectoryFactory which would create a Directory with this param, and cache it without this param in the cache key.
We already added a todo in DirectoryFactory, and the proposal is to apply this todo: remove the DirContext param from the DirectoryFactory.create method.
> @SOLR-17675 Remove DirContext param from DirectoryFactory create method.

- solr/core/src/test/org/apache/solr/search/ThinCache.java
Basically `onRemoval()` has a much weaker guarantee than it is assuming right now.
This method can be called asynchronously, after the key is already gone locally.
Or even after the new cache is created, and it doesn't have the value that is being removed in it's local cache.
This is a way to solve most of the issues, but one race condition still remains. (Not sure it's possible to solve)
If the cache evicts a key, then the user puts that key with its original value right afterwards, this code will still assume it should be removed. Since we don't have access to timings for removal and addition, there is no way to fix this. (I think).
But for the sake of our small test failures, this should be sufficient.
> Fix race condition in TestThinCache

- solr/test-framework/src/java/org/apache/solr/util/LogListener.java
- solr/test-framework/src/test/org/apache/solr/util/TestErrorLogMuter.java
These are hazardous/sloppy.  Tests should listen to a specific class/package.
Motivated by: https://issues.apache.org/jira/browse/SOLR-17667?focusedCommentId=17928175&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17928175
> LogListener: remove no-arg convenience methods

- solr/core/src/test/org/apache/solr/BasicFunctionalityTest.java
- solr/core/src/test/org/apache/solr/handler/tagger/TaggerTestCase.java
- solr/core/src/test/org/apache/solr/legacy/TestNumericRangeQuery32.java
- solr/core/src/test/org/apache/solr/legacy/TestNumericRangeQuery64.java
- solr/core/src/test/org/apache/solr/search/LargeFieldTest.java
- solr/core/src/test/org/apache/solr/uninverting/TestFieldCacheSort.java
- solr/core/src/test/org/apache/solr/uninverting/TestNumericTerms32.java
- solr/core/src/test/org/apache/solr/uninverting/TestNumericTerms64.java
- solr/core/src/test/org/apache/solr/update/AddBlockUpdateTest.java
- solr/core/src/test/org/apache/solr/update/processor/ClassificationUpdateProcessorIntegrationTest.java
- solr/modules/ltr/src/test/org/apache/solr/ltr/TestLTRReRankingPipeline.java
- solr/modules/ltr/src/test/org/apache/solr/ltr/TestLTRScoringQuery.java
- solr/modules/ltr/src/test/org/apache/solr/ltr/TestSelectiveWeightCreation.java
The API is deprecated since Lucene 9.5 - https://github.com/apache/lucene/blob/releases/lucene/9.5.0/lucene/core/src/java/org/apache/lucene/search/IndexSearcher.java#L382-L391 -- and remove in Lucene 10.
So the replacement here can go to both `main` and `branch_9x` branches with no JIRA or solr/CHANGES.txt entry needed in my opinion.
> in tests replace deprecated IndexSearcher.doc() calls

- solr/core/src/java/org/apache/solr/search/join/HashRangeQuery.java
- solr/core/src/test/org/apache/solr/cloud/TestCloudDeleteByQuery.java
- solr/core/src/test/org/apache/solr/search/SolrSearcherRequirementDetectorTest.java
https://issues.apache.org/jira/browse/SOLR-17677
> SOLR-17677: HashRangeQuery doesn't NEED SolrIndexSearcher

- solr/core/src/test/org/apache/solr/search/TestCoordinatorRole.java
`TestCoordinatorRole.testNRTRestart()` has been flaky for a long time, and for various reasons. I believe this is the last one.
Basically in the last part, it's supposed to turn off the NRT replica and the PULL replica alternating, and keep trying requests that have `shards.preference=NRT`, until a PULL replica is forced to be used to serve the request.
The issue was that the pull node is started right before this. So if a very low (< 300 ms) random value is chosen for `serveTogetherTime`, then the Pull replica will fail to recover from the NRT replica leader. Pull replicas do not become active unless they recover on startup. So when the NRT replica is offline, requests will fail because there are no replicas serving the requested shard.
The `getHostCoreName` call can handle up to 500 ms …
> Finally fix TestCoordinatorRole for good.

- solr/core/src/test/org/apache/solr/search/TestRecovery.java
- solr/test-framework/src/java/org/apache/solr/SolrTestCaseJ4.java
- solr/test-framework/src/java/org/apache/solr/util/SolrMatchers.java
https://issues.apache.org/jira/browse/SOLR-17650
According to the discussion in the JIRA, the behavior here is fine. We just need to update the tests now that buffered updates can be done in parallel.
The new testing stuff is heavy handed, but mostly needed to 1) test this at all and 2) give us a good error message that we can actually use.
> SOLR-17650: Fix tests for unordered buffered updates

- solr/CHANGES.txt
- solr/solrj/src/java/org/apache/solr/client/solrj/beans/DocumentObjectBinder.java
- solr/solrj/src/test/org/apache/solr/client/solrj/beans/TestDocumentObjectBinder.java
https://issues.apache.org/jira/browse/SOLR-17669
Flame Graph in our Production System showed a siginificant high memory consumption of Pattern.matcher
Wildcard can only be at beginning or end of Field Name, we replaced Pattern Regex with startsWith and endsWith
No new tests needed, old tests are working fine with new code
> SOLR-17669: Reduce Memory Consumption by 80-90% when using Dynamic fields (DocumentObjectBinder)

- solr/CHANGES.txt
- solr/core/src/test/org/apache/solr/update/processor/TestPartialUpdateDeduplication.java
- solr/solrj/src/java/org/apache/solr/client/solrj/request/UpdateRequest.java
https://issues.apache.org/jira/browse/SOLR-17518
This is a follow-up of #3200.
Deprecated methods are now removed in Solr 10.
> SOLR-17518: Remove deprecated XML methods from UpdateRequest

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cloud/ZkController.java
- solr/core/src/java/org/apache/solr/core/CoreContainer.java
- solr/core/src/test/org/apache/solr/security/BasicAuthIntegrationTest.java
https://issues.apache.org/jira/browse/SOLR-17644
- [] I have added tests for my changes.
> SOLR-17644: Fix missing auth listener

- solr/solr-ref-guide/modules/configuration-guide/pages/coreadmin-api.adoc
- Remove extra '&' character in the URL query parameter example in the CoreAdmin API documentation to ensure accuracy.
- The typo was located in `solr/solr-ref-guide/modules/configuration-guide/pages/coreadmin-api.adoc` at line 123.
- This improves clarity and prevents confusion for users following the documentation.
The typo issue can be seen in the Solr documentation at: [Documentation Link](https://solr.apache.org/guide/solr/latest/configuration-guide/coreadmin-api.html#coreadmin-create)
This pull request fixes a typo in the CoreAdmin API documentation by removing an extra `&` character in a URL query parameter example. The change ensures the documentation accurately reflects the correct syntax for creating a Solr core, improving clarity for users.
The solution involves a simple edit …
> [FIX] -- Correct typo in CoreAdmin create api documentation.

- solr/core/src/java/org/apache/solr/handler/component/SearchHandler.java
https://issues.apache.org/jira/browse/SOLR-17686
> SOLR-17686: Rename stageInEnglish to stageToString and make it protected and non-static

- solr/solr-ref-guide/modules/deployment-guide/examples/UsingPingRefGuideExamplesTest.java
- solr/solr-ref-guide/modules/deployment-guide/pages/ping.adoc
- Update ping.adoc with references from unit test.
- Add unit test to illustrate the usage of the ping response.
https://issues.apache.org/jira/browse/SOLR-17684
The SolrJ Reference Guide provides incorrect examples for retrieving the ping status of a collection.
https://solr.apache.org/guide/solr/9_8/deployment-guide/ping.html 
pingResponse.getStatus() returns the status of the ping request itself (status=0), not the collection's ping status ("OK").
Since getResponse() returns a NamedList<Object>, the value must be explicitly cast to a String or converted using .toString().
Created a new test class named: UsingPingRefGuideExamplesTest
- [  ] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to- …
> SOLR-17684: SolrJ Reference Guide (Ping) - Incorrect Status Retrieval

- dev-tools/scripts/releaseWizard.py
- dev-tools/scripts/requirements.txt
- dev-tools/scripts/scriptutil.py
https://issues.apache.org/jira/browse/SOLR-17438
> SOLR-17438 Resolve committer GPG key from other source

- solr/core/src/java/org/apache/solr/cli/RunExampleTool.java
The user didn't supply this url, so don't warn them about the formatting.  Bit of polish to the `bin/solr start -e techproducts` example command.
https://issues.apache.org/jira/browse/SOLR-17695
> SOLR-17695: Don't warn user about solrUrl format when they do not supply it

- solr/core/src/java/org/apache/solr/handler/ReplicationHandler.java
- solr/core/src/test/org/apache/solr/search/TestMinHashQParser.java
- solr/core/src/test/org/apache/solr/update/processor/RegexBoostProcessorTest.java
- solr/modules/langid/src/test/org/apache/solr/update/processor/OpenNLPLangDetectUpdateProcessorFactoryTest.java
- solr/solrj/src/java/org/apache/solr/common/params/SolrParams.java
- solr/solrj/src/java/org/apache/solr/common/util/SimpleOrderedMap.java
* new SimpleOrderedMap(MapWriter)   ex: a SolrParams
* deprecate SolrParams.toNamedList
* optimize SolrParams.writeMap
Bigger picture is avoiding NamedList.
Can go to 9x
> SimpleOrderedMap MapWriter constructor

- solr/core/src/test/org/apache/solr/cloud/TestRandomFlRTGCloud.java
- solr/core/src/test/org/apache/solr/handler/admin/ShowFileRequestHandlerTest.java
- solr/core/src/test/org/apache/solr/response/TestRawTransformer.java
- solr/core/src/test/org/apache/solr/search/TestSmileRequest.java
- solr/solrj/src/java/org/apache/solr/client/solrj/ResponseParser.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/BinaryResponseParser.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/HttpSolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/HttpSolrClientBase.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/InputStreamResponseParser.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/JsonMapResponseParser.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/NoOpResponseParser.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/StreamingBinaryResponseParser.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/XMLResponseParser.java
- solr/solrj/src/java/org/apache/solr/client/solrj/request/DelegationTokenRequest.java
- solr/solrj/src/test/org/apache/solr/client/solrj/SolrExampleCborTest.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/HttpSolrClientBuilderTest.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/LBHttpSolrClientBuilderTest.java
- solr/solrj/src/test/org/apache/solr/client/solrj/response/NoOpResponseParserTest.java
* processResponse should declare to throw IOException since it reads data
* processResponse(Reader) -- remove
* getContentType() -- remove (deprecated)
* getContentTypes() -- make abstract
NoOpResponseParser: must specify writer type; do not default to XML
10.0 only
> SolrJ ResponseParser API improvements, minor

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/core/CoreContainer.java
https://issues.apache.org/jira/browse/SOLR-17700
The tests seem to be happy with this change. `DeleteInactiveReplicaTest` failed before I added the non-locked private `unloadWithoutCoreOp()` method, so that's a good sign.
This should fix the issues we are seeing with the `SchemaDesignerApiTest` that #3213 was attempting to fix, in which there was a race condition between concurrent collection deletion and reload operations.
> SOLR-17700: Use core operation lock when unloading core

- solr/core/src/java/org/apache/solr/cloud/ZkController.java
- solr/core/src/java/org/apache/solr/core/ZkContainer.java
- solr/core/src/java/org/apache/solr/handler/admin/ZookeeperInfoHandler.java
- solr/core/src/java/org/apache/solr/schema/ZkIndexSchemaReader.java
- solr/core/src/test/org/apache/solr/cloud/LeaderElectionTest.java
- solr/solrj-zookeeper/src/java/org/apache/solr/common/cloud/OnDisconnect.java
- solr/solrj-zookeeper/src/java/org/apache/solr/common/cloud/OnReconnect.java
- solr/solrj-zookeeper/src/java/org/apache/solr/common/cloud/SolrZkClient.java
- solr/solrj-zookeeper/src/java/org/apache/solr/common/cloud/ZkStateReader.java
https://issues.apache.org/jira/browse/SOLR-17702
This will fix the flaky `org.apache.solr.cloud.BasicDistributedZk2Test` (class method) failures.
But in general this is a better way of taking down Solr. There's no reason for SolrZkClient to own this logic anymore. The classes that want to watch on connection state can decide if they want to be async or sync, and how to handle closing the executor themselves.
> SOLR-17702: Move ZK ConnectionListener logic out of SolrZkClient

- gradle/hacks/dummy-outputs.gradle
- gradle/hacks/turbocharge-jvm-opts.gradle
- gradle/testing/alternative-jdk-support.gradle
One of the current build issues we are facing is a NPE when `optimizeTask` is called on an undefined task during project configuration. This and similar issues are caused in various configurations that make use of the `TaskCollection.all` method. 
The actual root cause of these errors seems to be caused by our customization for the javadoc tasks in `render-javadoc.gradle`. I am not sure why this is happening and if similar errors could occur elsewhere.
This PR changes the method from `all` to `configureEach` for the problematic locations. They are somewhat equivalent:
_org.gradle.api.DomainObjectCollection<T>.all_
> Executes the given closure against all objects in this collection, and any objects subsequently added to this collection. The object is passed to the closure as the closure …
> Replace all with configureEach to solve configuration issues

- dev-tools/scripts/refguide/refguide-download-js-css.py
- dev-tools/scripts/requirements.txt
https://issues.apache.org/jira/browse/SOLR-17342
This script updates the old refguides by getting rid of links to external JS and CSS resources. 
It reads all HTML sources of each guide, and when encountering an external JS/CSS, it downloads it and changes the href to a local one.
> SOLR-17342 script to update old ref-guides

- solr/solr-ref-guide/modules/deployment-guide/pages/collection-management.adoc
The PR fixes a minor documentation error in the Solr Collection Management guide. The cURL command example for reloading collections was missing a closing apostrophe, which could confuse users.
The solution involved updating the example command on the [collection management page](https://solr.apache.org/guide/solr/latest/deployment-guide/collection-management.html#reload) by adding the missing closing apostrophe to the JSON payload in the cURL command.
Since this is a documentation-only change, no additional tests were necessary.
> Fix missing closing apostrophe in collection reload command example

- solr/solr-ref-guide/modules/deployment-guide/pages/taking-solr-to-production.adoc
Solr 9.8 start script `bin/solr` reads `SOLR_INCLUDE` environment variable not `SOLR_ENV`.
> Update taking-solr-to-production.adoc environment variable SOLR_ENV to SOLR_INCLUDE

- solr/core/src/test/org/apache/solr/update/processor/UpdateRequestProcessorFactoryTest.java
- solr/modules/s3-repository/src/test/org/apache/solr/s3/AbstractS3ClientTest.java
- solr/modules/s3-repository/src/test/org/apache/solr/s3/S3BackupRepositoryTest.java
- solr/modules/s3-repository/src/test/org/apache/solr/s3/S3IncrementalBackupTest.java
- solr/modules/s3-repository/src/test/org/apache/solr/s3/S3InstallShardTest.java
- solr/modules/s3-repository/src/test/org/apache/solr/s3/S3OutputStreamTest.java
_(already reviewed by a colleague & contributor @pmcarthur-apache )_
I'm nearly sure that `S3MockRule.builder().silent()` will change the root logger to WARN.  Maybe for JUL; not sure if such a change federates to Log4j2.  Maybe we should remove silent() but I didn't check how bad/verbose it is.
> Test: UpdateRequestProcessorFactoryTest, can be flaky

- solr/CHANGES.txt
- solr/core/src/test/org/apache/solr/cloud/DistribJoinFromCollectionTest.java
- solr/core/src/test/org/apache/solr/cloud/TestRandomFlRTGCloud.java
- solr/core/src/test/org/apache/solr/response/transform/TestSubQueryTransformerDistrib.java
- solr/core/src/test/org/apache/solr/search/join/ShardToShardJoinAbstract.java
- solr/solrj/src/java/org/apache/solr/client/solrj/SolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/beans/DocumentObjectBinder.java
- solr/solrj/src/java/org/apache/solr/client/solrj/request/QueryRequest.java
- solr/solrj/src/java/org/apache/solr/client/solrj/response/QueryResponse.java
- solr/solrj/src/test/org/apache/solr/client/solrj/beans/TestDocumentObjectBinder.java
- solr/solrj/src/test/org/apache/solr/client/solrj/response/QueryResponseTest.java
- solr/solrj/src/test/org/apache/solr/client/solrj/response/TestClusteringResponse.java
https://issues.apache.org/jira/browse/SOLR-17706
Remove from SolrClient, and thus update QueryResponse to not get it from there.
Use Java SPI/ServiceLoader to allow someone to customize.
Use ConcurrentHashMap.computeIfAbsent internally.
> SOLR-17706 SolrJ DocumentObjectBinder, make a singleton

- solr/prometheus-exporter/src/java/org/apache/solr/prometheus/exporter/SolrExporter.java
- solr/prometheus-exporter/src/test/org/apache/solr/prometheus/exporter/SolrExporterTestBase.java
This test flaps because the port is given up briefly and another process might take it.
It'd be nice if the exporter could accept a '0' and then have a getter for the port... but this retry should be fine too.
(I already reviewed this with my colleague @pmcarthur-apache)
> Test fix: SolrExporterTestBase, port bind

- solr/solrj/src/java/org/apache/solr/client/solrj/request/JavaBinUpdateRequestCodec.java
- solr/solrj/src/test/org/apache/solr/client/solrj/request/TestUpdateRequestCodec.java
This PR removes some dead code in JavaBinUpdateRequestCodec (no test exercises it), and simplifies related logic.  
*Disclaimer*  It's possible and maybe likely that an old SolrJ might have sent data encoded with these types.  It's also possible a user is using JavaBinCodec directly to do the same.  Henceforth, they will get an error.  As we have very little / inadequate backwards compatibility tests, I can't know for sure.  The disclaimer is so vague and frankly kind of expected for a major version (that this targets) that I'm not sure anything meaningful could be said in upgrade notes.
I plan to merge for 10.
Context:
----
While working on something nearby, I noticed that `JavaBinUpdateRequestCodec.readOuterMostDocIterator` (server side, processes an update request that's JavaBin …
> JavaBinUpdateRequestCodec: Dead code removal

- gradle/testing/randomization.gradle
This is basically a cherry-pick of Chris Hegarty's commit on Lucene ([faec0f823817ca95f1f103d6b9482d26ee75cc7b](https://github.com/apache/lucene/commit/faec0f823817ca95f1f103d6b9482d26ee75cc7b), PR https://github.com/apache/lucene/pull/14179). This will run all Solr tests without security manager enabled, once the runtime JVM for testing is 24 or later.
Original issue description: "This commit avoids setting the security manager on JDK 24+ - since it is not longer possible to enable it in JDK 24+ This is the minimum required to start testing with JDK 24 EA."
This will make Policeman Jenkins builds work again with Java 24+
Thanks to @ChrisHegarty.
> Do not enable security manager on JDK 24+ (#14179)

- solr/core/src/java/org/apache/solr/core/CoreContainer.java
- solr/core/src/java/org/apache/solr/core/SolrCores.java
https://issues.apache.org/jira/browse/SOLR-17716
SolrCores.waitAddPendingCoreOps is the main locking mechanism for operations on cores like creation/loading/removal.
In the current code, if an InterruptedException is caught while waiting for the lock, the method returns null. However returning null means basically that the waiting is complete and the caller got the lock. So the caller code proceeds normally with its critical operation on the core.
We should handle differently an InterruptedException to prevent the caller from taking the lock while another pending op is on the core. The proposal is to throw a SolrException.
> SOLR-17716: Handle interrupted exception in SolrCores.waitAddPendingCoreOps.

- gradle/testing/defaults-tests.gradle
- gradle/testing/failed-tests-at-end.gradle
This error has been seen on some of the Jenkins runs:
```
Caused by: groovy.lang.MissingPropertyException: Could not get unknown property 'testOutputsDir' for task ':solr:ui:desktopTest' of type org.jetbrains.kotlin.gradle.targets.jvm.tasks.KotlinJvmTest.
```
There's no reason to (currently) add the output for fucit or develocity for these tests, so let's just keep the logic to the JavaProject modules.
> Only apply test failure output logic for Java tests

- solr/core/src/test/org/apache/solr/cli/ZkSubcommandsTest.java
- solr/core/src/test/org/apache/solr/cloud/MissingSegmentRecoveryTest.java
- solr/core/src/test/org/apache/solr/handler/TestReplicationHandler.java
- solr/core/src/test/org/apache/solr/handler/TestStressThreadBackup.java
- solr/core/src/test/org/apache/solr/update/CustomTLogDirTest.java
- solr/test-framework/src/java/org/apache/solr/BaseDistributedSearchTestCase.java
https://issues.apache.org/jira/browse/SOLR-16903
Tests on nightly failing.
- `TestReplicationHandler` needs to check fileName from string
- `TestStressThreadBackup.java` `toList()` is immutable. Collect with `.collect(Collectors.toList())`
- `BaseDistributedSearchTestCase.java` seems with a nightly test, the file/directory already exists. Use `StandardCopyOption.REPLACE_EXISTING` to overwrite as `FileUtils.copyDirectory` does
- CustomTLogDirTest.java When using `LuceneTestCase.createTempDir()`, certain seeds generate a [WindowsFS](https://github.com/apache/lucene/blob/main/lucene/test-framework/src/java/org/apache/lucene/tests/mockfile/WindowsFS.java#L34) and this causes try-with-resources failing to [close the file stream](https://github.com/apache/solr/blob/470ae762b883b259da6f1278448553 …
> SOLR-16903: Nightly test failures from Path migration

- solr/core/src/java/org/apache/solr/schema/ExternalFileField.java
- solr/solr-ref-guide/modules/indexing-guide/pages/external-files-processes.adoc
- solr/solr-ref-guide/modules/indexing-guide/pages/field-types-included-with-solr.adoc
https://issues.apache.org/jira/browse/SOLR-17655
Mark ExternalFileField as deprecated.
This pairs with https://github.com/apache/solr/pull/3244, and is meant to go on `branch_9x` to mark this as deprecated.  Then #3244 can be committed to `main`.
no change.
> SOLR-17655: Mark ExternalFileField as deprecated

- gradle/validation/forbidden-apis/defaults.all.txt
- solr/core/src/java/org/apache/solr/update/UpdateLog.java
Very error-prone; confused with String.startsWith.
CC @mlbiscoc
> Forbidden-API: Path.startsWith(String)

- solr/core/src/test/org/apache/solr/cluster/events/ClusterEventProducerTest.java
I think the `ClusterEventProducerTest` failures on Windows could be related to https://bugs.openjdk.org/browse/JDK-8180466, since the errors are:
```
timestamp of the event is in the future
```
So an easy fix is to allow the timestamp to be >= for windows runs.
> Fix instant resolution issue for ClusterEventProducerTest on Windows

- solr/core/src/java/org/apache/solr/core/CancellableQueryTracker.java
- solr/core/src/java/org/apache/solr/handler/component/HttpShardHandler.java
- solr/core/src/java/org/apache/solr/request/SolrRequestInfo.java
- solr/core/src/java/org/apache/solr/servlet/HttpSolrCall.java
- solr/core/src/java/org/apache/solr/servlet/SolrRequestParsers.java
- solr/core/src/java/org/apache/solr/update/SolrCmdDistributor.java
https://issues.apache.org/jira/browse/SOLR-17069
[Justification](https://github.com/apache/solr/pull/2876#issuecomment-2782169134)
This was split out from #2876.
A related item https://issues.apache.org/jira/browse/SOLR-17741 "Remove addHttpRequestToContext option" but that's more about removing needless option than actually addressing a hazard/bug.
> SOLR-17069 HttpServletRequest; use eagerly to avoid inaccessibility

- solr/core/src/java/org/apache/solr/cloud/SolrZkServer.java
https://issues.apache.org/jira/browse/SOLR-17496
At smaller scale setups, running Solr in Solr Cloud mode with embedded ZooKeeper is just fine.   1 node, 2 node, it's just fine.   
For 10.0 I plan on completing #2783 which would provide more concrte details.
> SOLR-17496: Remove a warning that is no longer applicable.

- solr/core/src/java/org/apache/solr/core/SolrConfig.java
- solr/core/src/java/org/apache/solr/servlet/SolrRequestParsers.java
- solr/core/src/resources/EditableSolrConfigAttributes.json
- solr/core/src/test/org/apache/solr/core/TestConfigOverlay.java
- solr/core/src/test/org/apache/solr/core/TestSolrConfigHandler.java
- solr/core/src/test/org/apache/solr/servlet/SolrRequestParserTest.java
- solr/server/solr/configsets/_default/conf/solrconfig.xml
- solr/server/solr/configsets/sample_techproducts_configs/conf/solrconfig.xml
- solr/solr-ref-guide/modules/configuration-guide/pages/config-api.adoc
- solr/solr-ref-guide/modules/configuration-guide/pages/requestdispatcher.adoc
- solr/solr-ref-guide/modules/upgrade-notes/pages/major-changes-in-solr-10.adoc
in solrconfig.xml/requestDispatcher/requestParsers. Why: Obsolete/redundant with SolrQueryRequest.getHttpSolrCall().getReq()
https://issues.apache.org/jira/browse/SOLR-17741
> SOLR-17741: Remove addHttpRequestToContext option

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/core/SolrConfig.java
https://issues.apache.org/jira/browse/SOLR-17741
Just the deprecation, and CHANGES.txt reference.
I don't care to create yet another JIRA to make the 9x & main distinction for merely a deprecation.
> SOLR-17741: Deprecate 'addHttpRequestToContext' (9x)

- solr/CHANGES.txt
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/ConcurrentUpdateHttp2SolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/ConcurrentUpdateSolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/StallDetection.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/TimeSource.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/FakeTimeSource.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/StallDetectionTest.java
The current stall detection mechanism in the ConcurrentUpdateSolrClients is prone to generating false positives, especially under load. As pointed out by Jason, the existing approach simply intermittently monitors the queue size over time to detect stalls. However, this method is insufficient because the queue can report being full for extended periods when the system is under load, even if no actual stall has occurred.
> SOLR-17294: The stall detection in the ConcurrentUpdateSolrClients easily detects false positives.

- solr/CHANGES.txt
- solr/packaging/test/bats_helper.bash
- solr/packaging/test/test_prometheus.bats
- solr/prometheus-exporter/src/java/org/apache/solr/prometheus/exporter/SolrExporter.java
https://issues.apache.org/jira/browse/SOLR-17638
Fixing the error logging by only using the message. it seems including the entire stacktrace will crash the output completely. I am using SolrCLI as an example which seems to have a similar approach.
I am also fixing the fallback to the default value which was not happening.
> SOLR-17638 Some CLI errors not logged when starting prometheus exporter

- solr/solrj/src/java/org/apache/solr/client/solrj/JacksonContentWriter.java
- solr/solrj/src/resources/java-template/api.mustache
https://issues.apache.org/jira/browse/SOLR-17743
I welcome input on testing (if needed).
> SOLR-17743: V2 API: use correct content-type

- solr/core/src/java/org/apache/solr/servlet/ServletUtils.java
- solr/solrj/src/java/org/apache/solr/common/util/Utils.java
Do not read a single byte in a loop -- a performance anti-pattern.
I just happened to notice this during a debugging session that had me looking closely at single-byte reads.
> Optimize consumeInputFully, don't loop read single byte

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/search/RankQParserPlugin.java
- solr/core/src/test/org/apache/solr/search/RankQParserPluginTest.java
* Solr 8.6 added RankField support: https://issues.apache.org/jira/browse/SOLR-14590
* Lucene/Solr 8.8 added linear function support on the Lucene level only: https://issues.apache.org/jira/browse/LUCENE-9594
https://issues.apache.org/jira/browse/SOLR-17749
> SOLR-17749: linear function support for RankQParserPlugin

- solr/benchmark/src/java/org/apache/solr/bench/BaseBenchState.java
https://issues.apache.org/jira/browse/SOLR-17361
Removed dependency on `HotSpotDiagnosticMXBean`.
> SOLR-17361 OpenJ9 can't compile solr: No method HotSpotDiagnosticMXBean.dumpHeap

- build.gradle
- gradle/template.gradle.properties
- settings.gradle
- solr/webapp/build.gradle
The new UI module has shown some compatibilty challenges when it comes to building the project with less common operating systems like s390x or when running with alterantive JDKs (`RUNTIME_JAVA_HOME`).
This PR adds a gradle property called `disableNewUiModule` that can be used to disable the new UI module during builds. 
This is only a termporary workaround until we properly fix the compatibility issues or decide to remove the new UI module.
This PR can be tested by adding the following flag to the `gradle.properties`:
```properties
disableNewUiModule=true
```
> Allow disabling new UI module during builds

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/core/CoreContainer.java
- solr/core/src/java/org/apache/solr/core/SolrCore.java
- solr/core/src/java/org/apache/solr/search/SolrIndexSearcher.java
- solr/core/src/java/org/apache/solr/update/IndexFingerprint.java
- solr/core/src/test/org/apache/solr/update/SolrIndexFingerprintTest.java
https://issues.apache.org/jira/browse/SOLR-17756
The index fingerprint is currently being calculated on each segment sequentially. While this works fine, the index fingerprint calculation was noticed to be a very slow process and on leader election is blocking.
This proposes to have this calculation parallelized across segments instead. Since the fingerprint is just a cumulative sum of a hash on versions, the order in which it is added to the running sum should not matter.
Create a dedicated threadpool (`IndexFingerprintPool`) to calculate the indexfingerprint. Created a separate theadpool instead of the common `ForkJoinPool` as this can be an expensive operation calculating across a large index
Created `testSequentialVsParallelFingerprint` test to confirm the fingerprint is the same. …
> SOLR-17756: Parallelize calculation of index fingerprint across segments

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/response/transform/ValueSourceAugmenter.java
https://issues.apache.org/jira/browse/SOLR-17775
Optimize ValueSourceAugmenter performance by pre-calculating function values during setContext() instead of calculating them on-demand for each document.
Collect all document IDs from DocList during setContext(), sort them, and calculate function values sequentially by reader segment. Store results in a map for fast lookup during transform(). Include fallback for documents not in the pre-calculated set.
Existing test suite covers ValueSourceAugmenter functionality and all tests pass. Tested in Solr Cloud setup with function queries as pseudo-fields (e.g., &fl=sum(x,y),id,score) and verified performance improvement 
> SOLR-17775: optimize ValueSourceAugmenter

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/response/DocsStreamer.java
- solr/core/src/java/org/apache/solr/response/transform/OriginalScoreAugmenter.java
- solr/core/src/java/org/apache/solr/search/DocIterationInfo.java
- solr/core/src/java/org/apache/solr/search/ReRankCollector.java
- solr/core/src/java/org/apache/solr/search/SolrReturnFields.java
- solr/core/src/java/org/apache/solr/search/TopDocsSlice.java
- solr/core/src/test/org/apache/solr/search/DistributedReRankExplainTest.java
- solr/core/src/test/org/apache/solr/search/TestReRankQParserPlugin.java
- solr/solr-ref-guide/modules/query-guide/pages/query-re-ranking.adoc
https://issues.apache.org/jira/browse/SOLR-17678
The functionality was already added in https://github.com/apache/solr/pull/3222, but this is making the following changes before any release has been made:
- Rename from `matchScore` to `originalScore`, since that is the name that LTR queries already use for this feature. And eventually, the two implementations can hopefully be merged.
- Make the return field `originalScore()` to resemble a function. It is not currently a function, but in the future we want to use a real ValueSource function instead of hardcoding this option in Solr. The ticket that covers this is [SOLR-17784](https://issues.apache.org/jira/browse/SOLR-17784).
> SOLR-17678: Change matchScore to originalScore, make it a fake-function

- solr/core/src/java/org/apache/solr/api/V2HttpCall.java
https://issues.apache.org/jira/browse/SOLR-16391
We might be able to move this else if statement entirely, if all cores APIs are handled by JaxRS, but I may be wrong about that. It's just a guess.
> SOLR-16391: Fix CoresAPI integration in V2HttpCall

- solr/CHANGES.txt
- solr/solrj/src/java/org/apache/solr/client/solrj/request/CoreAdminRequest.java
- solr/solrj/src/java/org/apache/solr/common/params/CoreAdminParams.java
https://issues.apache.org/jira/browse/SOLR-17778
Trivial removal of dead code.
This removes a core admin operation that does nothing, but was still visible in SolrJ.
> SOLR-17778: Remove unused FORCEPREPAREFORLEADERSHIP operation

- solr/core/src/java/org/apache/solr/servlet/HttpSolrCall.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/ClusterStateProviderTest.java
https://issues.apache.org/jira/browse/SOLR-17582
User Agent versions < 9.9.0 work, but not the old 1.0 or 2.0 agent versions used by Solr. We should catch these versions and just change them to be semVer compliant.
> SOLR-17582: Fix ClusterState serializing for older SolrJ versions

- solr/core/src/java/org/apache/solr/core/CoreContainer.java
- solr/core/src/test/org/apache/solr/handler/admin/MetricsHandlerTest.java
It's only used for one silly thing:
It's needless to create an executor just to asynchronously wait for another executor (coreLoadExecutor) to close.  We can instead call shutdownAndAwaitTermination on coreLoadExecutor when the container shuts down.
> Refactor: remove coreContainerWorkExecutor

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/core/CoreContainer.java
- solr/core/src/java/org/apache/solr/handler/RequestHandlerBase.java
- solr/core/src/java/org/apache/solr/jersey/CatchAllExceptionMapper.java
- solr/core/src/java/org/apache/solr/update/DirectUpdateHandler2.java
- solr/core/src/java/org/apache/solr/update/TransactionLog.java
- solr/core/src/java/org/apache/solr/update/UpdateLog.java
- solr/core/src/test/org/apache/solr/handler/RequestHandlerBaseTest.java
- solr/core/src/test/org/apache/solr/update/UpdateLogTest.java
https://issues.apache.org/jira/browse/SOLR-17805
TransactionLog constructor can either open an existing log, or create a new log. When it is required to create a new log, it first creates a new empty log file and then opens an output stream on it.
After the new empty log file is created, if an exception occurs when creating the output stream (e.g. disk full, encryption key not available), the TransactionLog object is not created, but the empty file is left. The problem is that UpdateLog does not update its "id" field which should point to the next (non-existing) transaction log id, instead it continues to point to the empty log file. This completely blocks the logic in UpdateLog.ensureLog() and TransactionLog constructor will always refuse to create a new transaction log, throwing "New …
> SOLR-17805: Exception in TransactionLog constructor deletes the file and does not block subsequent updates.

- solr/cross-dc-manager/build.gradle
- solr/cross-dc-manager/src/java/org/apache/solr/crossdc/manager/consumer/KafkaCrossDcConsumer.java
- solr/cross-dc-manager/src/java/org/apache/solr/crossdc/manager/messageprocessor/SolrMessageProcessor.java
- solr/cross-dc-manager/src/test/org/apache/solr/crossdc/manager/DeleteByQueryToIdTest.java
- solr/cross-dc-manager/src/test/org/apache/solr/crossdc/manager/SimpleSolrIntegrationTest.java
- solr/cross-dc-manager/src/test/org/apache/solr/crossdc/manager/consumer/KafkaCrossDcConsumerTest.java
- solr/cross-dc-manager/src/test/org/apache/solr/crossdc/manager/messageprocessor/SolrMessageProcessorTest.java
- solr/cross-dc-manager/src/test/org/apache/solr/crossdc/manager/messageprocessor/TestMessageProcessor.java
https://issues.apache.org/jira/browse/SOLR-17804
Use a `Supplier<CloudSolrClient>` that automatically re-creates the client if its `ClusterStateProvider` is closed. Unfortunately SolrClient doesn't implement `SolrCloseable`.
> SOLR-17804: re-create SolrClient if closed.

- solr/core/src/java/org/apache/solr/handler/component/HttpShardHandler.java
- solr/core/src/java/org/apache/solr/handler/component/SearchHandler.java
https://issues.apache.org/jira/browse/SOLR-17792
https://github.com/apache/solr/pull/3398 accidentally broke the error handling in HttpShardHandler, by accepting already received requests after cancelling. So instead of throwing those responses away, the HttpShardHandler will find a response with an error after cancelling, since that is the contract that `take()` has. And even then, for tolerant requests, the `SearchHandler` needs to find any responses that have errors to know if the results are partial or not. (because tolerant requests don't guarantee that the response returned is the one with the error)
> SOLR-17792: Fix error handling for shard requests

- solr/core/src/java/org/apache/solr/cli/PackageTool.java
This is mostly to fix following tests that run in the same JVM and check logger events.
This should make smoke tests pass more easily. That's not a blocker for 9.9, so opening a PR against main first.
> Restore logging level after package tool.

- solr/core/src/java/org/apache/solr/update/PeerSync.java
- solr/core/src/java/org/apache/solr/update/PeerSyncWithLeader.java
- solr/core/src/test/org/apache/solr/cloud/PeerSyncReplicationTest.java
- solr/core/src/test/org/apache/solr/cloud/TestCloudRecovery.java
- solr/core/src/test/org/apache/solr/metrics/SolrMetricTestUtils.java
Migrate PeerSync and PeerSycWithLeader metrics and remove Dropwizard initializations.
```
solr_core_leader_sync_errors_total{category="REPLICATION",collection="gettingstarted",core="gettingstarted_shard1_replica_n2",otel_scope_name="org.apache.solr",replica="replica_n2",shard="shard1"} 2.0
solr_core_leader_sync_errors_total{category="REPLICATION",collection="gettingstarted",core="gettingstarted_shard2_replica_n1",otel_scope_name="org.apache.solr",replica="replica_n1",shard="shard2"} 2.0
solr_core_leader_sync_skipped_total{category="REPLICATION",collection="gettingstarted",core="gettingstarted_shard1_replica_n2",otel_scope_name="org.apache.solr",replica="replica_n2",shard="shard1"} 1.0 …
```
> SOLR-17806: Migrate PeerSync and PeerSyncWithLeader metrics to OTEL

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/update/processor/AtomicUpdateDocumentMerger.java
- solr/core/src/test/org/apache/solr/update/processor/AtomicUpdatesTest.java
https://issues.apache.org/jira/browse/SOLR-17721
This issue is very intermittent and depending on a number of factors.Fixed a NullPointerException in Solr's atomic update functionality when performing add-distinct operations on fields that exist in the document but have null values. The error "Cannot invoke 'java.util.Collection.size()' because 'original' is null" was occurring in the doAddDistinct method of AtomicUpdateDocumentMerger when getValues() returned null for fields with null values.
Added a null check in the doAddDistinct method to handle the case where existingField.getValues() returns null. When a field exists in the document but has a null value, getValues() returns null, but the code was trying to call size() on this null collection. The fix initializes an empty ArrayList …
> SOLR-17721 - null pointer fix in the doAddDistinct method

- solr/core/src/java/org/apache/solr/core/CoreContainer.java
- solr/core/src/java/org/apache/solr/handler/RequestHandlerBase.java
- solr/core/src/java/org/apache/solr/handler/component/SearchHandler.java
- solr/core/src/java/org/apache/solr/jersey/RequestMetricHandling.java
- solr/core/src/java/org/apache/solr/metrics/SolrCoreMetricManager.java
- solr/core/src/java/org/apache/solr/metrics/SolrMetricProducer.java
- solr/core/src/test/org/apache/solr/cloud/TestRandomRequestDistribution.java
- solr/core/src/test/org/apache/solr/core/RequestHandlersTest.java
- solr/core/src/test/org/apache/solr/handler/RequestHandlerBaseTest.java
- solr/core/src/test/org/apache/solr/handler/RequestHandlerMetricsTest.java
- solr/core/src/test/org/apache/solr/handler/admin/MBeansHandlerTest.java
- solr/core/src/test/org/apache/solr/handler/admin/MetricsHandlerTest.java
- solr/core/src/test/org/apache/solr/metrics/SolrMetricTestUtils.java
- solr/core/src/test/org/apache/solr/response/TestPrometheusResponseWriterCloud.java
- solr/solrj/src/test/org/apache/solr/client/solrj/SolrJMetricTestUtils.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/CloudHttp2SolrClientRetryTest.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/CloudHttp2SolrClientTest.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/CloudSolrClientRetryTest.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/CloudSolrClientTest.java
- solr/solrj/src/test/org/apache/solr/client/solrj/request/TestCoreAdmin.java
Migrate node registry ADMIN metrics and remove Dropwizard initializations from `RequestHandlerBase`.
This does not include `aggregateNodeLevelMetricsEnabled`
```
solr_node_requests_total{category="ADMIN",handler="/admin/authorization",otel_scope_name="org.apache.solr"} 0.0
solr_node_requests_total{category="ADMIN",handler="/admin/collections",otel_scope_name="org.apache.solr"} 0.0
solr_node_requests_total{category="ADMIN",handler="/admin/configs",otel_scope_name="org.apache.solr"} 0.0
solr_node_requests_total{category="ADMIN",handler="/admin/cores",otel_scope_name="org.apache.solr"} 0.0
solr_node_requests_total{category="ADMIN",handler="/admin/info",otel_scope_name="org.apache.solr"} 0.0 …
```
> SOLR-17806: Migrate ADMIN node registry metrics to OTEL

- solr/core/src/java/org/apache/solr/core/SolrCore.java
- solr/core/src/java/org/apache/solr/handler/admin/MetricsHandler.java
- solr/core/src/java/org/apache/solr/metrics/SolrMetricManager.java
- solr/core/src/java/org/apache/solr/response/PrometheusResponseWriter.java
- solr/core/src/test/org/apache/solr/response/TestPrometheusResponseWriter.java
- solr/modules/opentelemetry/src/test/org/apache/solr/opentelemetry/TestDistributedTracing.java
- solr/modules/opentelemetry/src/test/org/apache/solr/opentelemetry/TestMetricExemplars.java
https://issues.apache.org/jira/browse/SOLR-17818
Adding in metrics with exemplars from distributed trace. If you have Solr distributed trace on and push with OTLP to something like the OTEL collector or pull directly from the `/admin/metrics` endpoint, you can get exemplars on the metrics honored across the pipeline like so:
```
solr_metrics_core_requests_times_milliseconds_bucket{collection="demo",core="demo_shard1_replica_n1",handler="/update",job="unknown_service:java",replica="replica_n1",shard="shard1",le="50.0"} 26 1.751574499605e+09 # {trace_id="4438406367ea8ea60f53e3f6e26a409d",span_id="d797ab840ed14e6d"} 30.0 1.75157449662e+09
```
But this is directly pinned to your traces sampling rate.
Users need to specify the format with a `format=openmetrics` from the endpoint otherwise it …
> SOLR-17818: Expose Open Metrics 1.0 format from /admin/metrics and exemplar support

- solr/core/src/test/org/apache/solr/uninverting/TestFieldCacheSortRandom.java
https://issues.apache.org/jira/browse/SOLR-17631
After the merge of https://github.com/apache/solr/pull/3053 we got some formatting issues in a file.
Run tidy and apply correct spacings.
> SOLR-17631: Fix formatting issues (tidy)

- solr/core/src/java/org/apache/solr/core/CoreContainer.java
- solr/core/src/java/org/apache/solr/core/ZkContainer.java
- solr/core/src/java/org/apache/solr/handler/RequestHandlerBase.java
- solr/core/src/java/org/apache/solr/metrics/MetricsMap.java
- solr/core/src/test/org/apache/solr/cloud/PeerSyncReplicationTest.java
- solr/core/src/test/org/apache/solr/cloud/TestRandomRequestDistribution.java
- solr/modules/opentelemetry/src/test/org/apache/solr/opentelemetry/TestMetricExemplars.java
- solr/solrj-zookeeper/src/java/org/apache/solr/common/cloud/SolrZKMetricsListener.java
- solr/solrj-zookeeper/src/java/org/apache/solr/common/cloud/SolrZkClient.java
Migrate ZkContainer metrics and remove Dropwizard initializations.
```
solr_zk_child_fetches_total{otel_scope_name="org.apache.solr"} 16.0
solr_zk_cumulative_children_fetched_total{otel_scope_name="org.apache.solr"} 7.0
solr_zk_cumulative_multi_ops_total{otel_scope_name="org.apache.solr"} 8.0
solr_zk_ops_total{category="CONTAINER",ops="delete",otel_scope_name="org.apache.solr"} 0.0
solr_zk_ops_total{category="CONTAINER",ops="exists",otel_scope_name="org.apache.solr"} 218.0
solr_zk_ops_total{category="CONTAINER",ops="multi",otel_scope_name="org.apache.solr"} 3.0
solr_zk_ops_total{category="CONTAINER",ops="read",otel_scope_name="org.apache.solr"} 148.0
solr_zk_ops_total{category="CONTAINER",ops="write",otel_scope_name="org.apache.solr"} 5.0 …
```
> SOLR-17806: Migrate ZkContainer metrics to OTEL

- solr/core/src/java/org/apache/solr/core/NodeConfig.java
- solr/solrj/src/java/org/apache/solr/common/util/EnvUtils.java
- solr/solrj/src/resources/DeprecatedSystemPropertyMappings.properties
Tricky one because I didn't want to change the solr.xml name AS well, so now in solr.xml we have solr.hideStackTrace, but system is solr.responses.stacktrace.enabled.
Why is this in solr.xml?
https://issues.apache.org/jira/browse/SOLR-17864
I am going to leave this one  for just this one, unless I find other solr.xml that are also system variable equivalents..    Then maybe this grows into a whole "why do we define these in solr.xml and in system variables?" disucssion!
> SOLR-17864: Flip solr.hideStackTrace to .enabled equivalent.

- .github/renovate.json
Making renovate PRs stale after 60 days just creates message noise with not much value. This is because it does not serve to nag an author to tend to her PR, and some of us tend to periodically list all open renovate PRs some time before a release to do a batch of upgrades.
This PR adds the `exempt-stale` label to all renovate PRs.
> Exclude renovate PRs from being marked as 'stale'

- solr/core/src/test/org/apache/solr/cloud/ZkControllerTest.java
https://issues.apache.org/jira/browse/SOLR-17620
Turns out the backport to 9x, although compiling, caused test failure due to difference in `CloudConfig` between 9x and main. In 9x it needs a `hostContext` specified. 
This could have been avoided by running tests before committing the backport (by e.g. using the PR flow).
> SOLR-17620 Fix test failure for 9x by supplying hostContext

- solr/solrj-zookeeper/src/java/org/apache/solr/client/solrj/cloud/DelegatingCloudManager.java
- solr/solrj-zookeeper/src/java/org/apache/solr/client/solrj/cloud/SolrCloudManager.java
- solr/solrj-zookeeper/src/java/org/apache/solr/client/solrj/impl/SolrClientCloudManager.java
This removes `SolrCloudManager.request()` and implementations in Solr 10.
@dsmiley tagging you as reviewer since you removed callers in SOLR-17630 and marked the method deprecated.
> Remove unused method SolrCloudManager.request() and cleanup DelegatingCloudManager

- .github/workflows/dependency-graph-submission.yml
Inspired by: [Lucene issue #15114](https://github.com/apache/lucene/issues/15114)
This adds GitHub’s dependency graph setup so it’s easier for us to keep an eye on dependencies.
- Submits a full dependency graph (including transitives) that shows up under Insights → Dependency graph, so we can quickly check what we’re pulling in.
- [Future PR] Runs dependency review on each PR, comparing against main and flagging any unexpected changes.
- Hooks in Dependabot alerts so we get notified about High/Critical CVEs right away.
Overall, this makes troubleshooting, checking vulnerability status, and acting on alerts a lot smoother within the GitHub ecosystem. There’s plenty more potential here as we explore the feature further and as GitHub keeps expanding its toolkit.
> Adding dependency graph submission workflow

- solr/solrj/src/java/org/apache/solr/client/solrj/SolrQuery.java
and getRequestHandler.
Use QueryRequest.setPath instead.
https://issues.apache.org/jira/browse/SOLR-17715
> SOLR-17715: Deprecate SolrQuery.setRequestHandler

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/core/SchemaCodecFactory.java
- solr/core/src/java/org/apache/solr/schema/DenseVectorField.java
- solr/core/src/java/org/apache/solr/schema/ScalarQuantizedDenseVectorField.java
- solr/core/src/test-files/solr/collection1/conf/bad-schema-densevector-quantized-bits.xml
- solr/core/src/test-files/solr/collection1/conf/bad-schema-densevector-quantized-compress.xml
- solr/core/src/test-files/solr/collection1/conf/bad-schema-densevector-quantized-confidence-interval-high.xml
- solr/core/src/test-files/solr/collection1/conf/bad-schema-densevector-quantized-confidence-interval-low.xml
- solr/core/src/test-files/solr/collection1/conf/schema-densevector-quantized.xml
- solr/core/src/test-files/solr/collection1/conf/schema-densevector.xml
- solr/core/src/test/org/apache/solr/core/TestSchemaCodecFactoryDefaults.java
- solr/core/src/test/org/apache/solr/schema/ScalarQuantizedDenseVectorFieldTest.java
- solr/solr-ref-guide/modules/query-guide/pages/dense-vector-search.adoc
https://issues.apache.org/jira/browse/SOLR-17780
Lucene 9.9 codec includes an implementation of scalar quantized dense vectors. This is not yet supported in Solr.
* Add a new schema type ScalarQuantizedDenseVectorField
* Add usage of Lucene99ScalarQuantizedVectorsFormat / Lucene99HnswScalarQuantizedVectorsFormat in SchemaCodecFactory. This incorporates the respective index reader/writers
* Test for bad schema where a non valid `bits` value is provided
* Test for bad schema where a non valid `confidenceInterval` is provided
* Test for bad schema where `compress`=true but bit is not 4 byte alignment
* Test for default ScalarQuantizedDenseVectorField
* Test for 4 bit aligned ScalarQuantizedDenseVectorField
* Test for 4 bit compressed ScalarQuantizedDenseVectorField
* Test for custom …
> SOLR-17780: Add support for scalar quantized dense vectors

- solr/core/src/java/org/apache/solr/handler/ReplicationHandler.java
- solr/core/src/java/org/apache/solr/metrics/SolrMetricManager.java
- solr/core/src/java/org/apache/solr/metrics/SolrMetricsContext.java
https://issues.apache.org/jira/browse/SOLR-17458
Added OTEL metrics to ReplicationHandler. This is what they look like:
```
solr_replication_download_speed{category="REPLICATION",collection="gettingstarted",core="gettingstarted_shard1_replica_n9",handler="/replication",otel_scope_name="org.apache.solr",replica="replica_n9",shard="shard1"} 3.7073146E7
solr_replication_downloaded_size_bytes{category="REPLICATION",collection="gettingstarted",core="gettingstarted_shard1_replica_n9",handler="/replication",otel_scope_name="org.apache.solr",replica="replica_n9",shard="shard1"} 1.408779582E9
solr_replication_index_generation{category="REPLICATION",collection="gettingstarted",core="gettingstarted_shard1_replica_n9",handler="/replication",otel_scope_name="org.apache.solr",replica="replica_n9",shard= …
```
> SOLR-17806: switch ReplicationHandler metrics to OTEL

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/servlet/HttpSolrCall.java
- solr/solrj-zookeeper/src/java/org/apache/solr/common/cloud/ZkStateReader.java
https://issues.apache.org/jira/browse/SOLR-17893
- Both `clusterState.getCollectionOrNull()` calls in HttpSolrCall should allow for cached values. There's no reason to fetch live versions every time here.
- The `lastUpdateTime` needs to be updated after getting the stats. If there is no change, that is an "update". We don't want to check every call after 2 seconds, if the ClusterState hasn't changed. We want to check once every 2 seconds.
> SOLR-17893: Use caching to remove Remote Proxy bottleneck

- solr/core/src/java/org/apache/solr/update/SolrIndexWriter.java
- solr/core/src/test-files/solr/collection1/conf/solrconfig-indexmetrics.xml
- solr/core/src/test/org/apache/solr/update/SolrIndexMetricsTest.java
Migrate SolrIndexWriter metrics from Dropwizard to OTEL.
```text
solr_indexwriter_flush_total{category="INDEX",collection="test",core="test_shard1_replica_n1",otel_scope_name="org.apache.solr",replica="replica_n1",shard="shard1"} 67.0
solr_indexwriter_major_merge_milliseconds_bucket{category="INDEX",collection="test",core="test_shard1_replica_n1",otel_scope_name="org.apache.solr",replica="replica_n1",shard="shard1",le="0.0"} 0
solr_indexwriter_major_merge_milliseconds_bucket{category="INDEX",collection="test",core="test_shard1_replica_n1",otel_scope_name="org.apache.solr",replica="replica_n1",shard="shard1",le="5.0"} 0
solr_indexwriter_major_merge_milliseconds_bucket{category="INDEX",collection="test",core="test_shard1_replica_n1",otel_scope …
```
> SOLR-17806: Migrate SolrIndexWriter metrics to OTEL

- solr/core/src/test/org/apache/solr/search/TestCollapseQParserPlugin.java
Relying on index order is unreliable.
http://fucit.org/solr-jenkins-reports/history-trend-of-recent-failures.html#series/org.apache.solr.search.TestCollapseQParserPlugin.testMultiSort
```
TestCollapseQParserPlugin > testMultiSort FAILED
java.lang.AssertionError: REQUEST FAILED: xpath=//result/doc[1]/str[@name='id'][.='6']
xml response was: <?xml version="1.0" encoding="UTF-8"?>
<response>
<lst name="responseHeader"><int name="status">0</int><int name="QTime">0</int></lst><result name="response" numFound="2" start="0" numFoundExact="true"><doc><str name="id">7</str><int name="id_i">7</int><str name="group_s">group2</str><int name="test_i">5</int><long name="test_l">1000</long><str name="term_s">XXXX</str><long name="_version_">1842211920030990336</long></doc><doc><str name="id">2</str><int …
```
> Fix flaky test TestCollapseQParserPlugin.testMultiSort

- solr/core/src/java/org/apache/solr/handler/component/DebugComponent.java
- solr/core/src/java/org/apache/solr/handler/component/ExpandComponent.java
- solr/core/src/java/org/apache/solr/handler/component/FacetComponent.java
- solr/core/src/java/org/apache/solr/handler/component/HighlightComponent.java
- solr/core/src/java/org/apache/solr/handler/component/MoreLikeThisComponent.java
- solr/core/src/java/org/apache/solr/handler/component/PhrasesIdentificationComponent.java
- solr/core/src/java/org/apache/solr/handler/component/QueryComponent.java
- solr/core/src/java/org/apache/solr/handler/component/RealTimeGetComponent.java
- solr/core/src/java/org/apache/solr/handler/component/ResponseBuilder.java
- solr/core/src/java/org/apache/solr/handler/component/SearchHandler.java
- solr/core/src/java/org/apache/solr/handler/component/SpellCheckComponent.java
- solr/core/src/java/org/apache/solr/handler/component/StatsComponent.java
- solr/core/src/java/org/apache/solr/handler/component/SuggestComponent.java
- solr/core/src/java/org/apache/solr/handler/component/TermVectorComponent.java
- solr/core/src/java/org/apache/solr/handler/component/TermsComponent.java
- solr/core/src/java/org/apache/solr/search/facet/FacetModule.java
- solr/modules/clustering/src/java/org/apache/solr/handler/clustering/ClusteringComponent.java
this could:
* facilitate deriving `ResponseBuilder` classes e.g. see #3648
* make it (perhaps) clearer that and how (typically) search components get i.e. read the stage but that only the search handler sets i.e. updates the stage
* deprecate-and-retain `ResponseBuilder.stage` i.e. it becomes private only in (say) Solr 11 or a higher 10.x future version
> NO JIRA: provide ResponseBuilder.(get,set)Stage accessors, deprecate direct access

- solr/CHANGES.txt
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/BaseHttpClusterStateProvider.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/CloudSolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/Http2ClusterStateProvider.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/HttpClusterStateProvider.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/ClusterStateProviderTest.java
https://issues.apache.org/jira/browse/SOLR-17921
The fix here isn't too crazy. I added a scheduledExecutor service to re-fetch liveNodes every 1/2 of the cache validity duration. I also removed the synchronization on `getLiveNodes()` as that can really limit performance when used at high QPS. (the synchronization is now on `fetchLiveNodes()`)
> SOLR-17921: Prefetch liveNodes in BaseHttpClusterStateProvider

- solr/core/src/java/org/apache/solr/metrics/SolrMetricManager.java
- solr/core/src/java/org/apache/solr/metrics/SolrMetricProducer.java
- solr/core/src/java/org/apache/solr/security/AuditLoggerPlugin.java
- solr/core/src/java/org/apache/solr/security/AuthenticationPlugin.java
- solr/core/src/java/org/apache/solr/security/MultiDestinationAuditLogger.java
- solr/core/src/test/org/apache/solr/security/AuditLoggerIntegrationTest.java
- solr/core/src/test/org/apache/solr/security/AuditLoggerPluginTest.java
- solr/core/src/test/org/apache/solr/security/MockSolrMetricsContextFactory.java
- solr/core/src/test/org/apache/solr/security/MultiDestinationAuditLoggerTest.java
- solr/core/src/test/org/apache/solr/security/SolrLogAuditLoggerPluginTest.java
- solr/solr-ref-guide/modules/deployment-guide/pages/audit-logging.adoc
- solr/test-framework/src/java/org/apache/solr/cloud/SolrCloudAuthTestCase.java
Migrates DropWizard metrics for AuditLoggerPlugin to OpenTelemetry.
See: https://solr.apache.org/guide/solr/latest/deployment-guide/audit-logging.html
- Migrates AuditLoggerPlugin metrics to Open Telemetry format
- Supports both async and non-async mode
- Updates Solr docs with new metric names
The following output was tested manually with the following steps:
1. Start Solr 
e.g. ` ./solr/packaging/build/dev/bin/solr start -f`
2. Upload a `security.json` config to Zookeeper to enable the AuditLoggerPlugin 
e.g. `./solr/packaging/build/dev/bin/solr zk cp ./security.json zk:/security.json`
3. Create a core
e.g. `./solr/packaging/build/dev/bin/solr create -c test_core`
Example Async config:
```json
// security.json
{
"auditlogging": {
"class": …
```
> SOLR-17806: Migrate AuditLoggerPlugin to OTEL

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/component/QueryComponent.java
- solr/core/src/java/org/apache/solr/handler/component/ResponseBuilder.java
- solr/core/src/java/org/apache/solr/handler/component/SearchHandler.java
- solr/core/src/java/org/apache/solr/search/QueryLimit.java
- solr/core/src/java/org/apache/solr/search/QueryLimits.java
- solr/core/src/java/org/apache/solr/search/TimeAllowedLimit.java
- solr/core/src/java/org/apache/solr/search/grouping/distributed/requestfactory/TopGroupsShardRequestFactory.java
- solr/core/src/test/org/apache/solr/search/TestQueryLimits.java
- solr/solr-ref-guide/modules/query-guide/pages/common-query-parameters.adoc
This implementation is inspired by the idea described by @gus-asf:
* parent request sends an additional parameter to the sub-requests to indicate the time already spent processing the parent req.
* sub-requests deduct this time from `timeAllowed`, and further decrease it by an approximate flight time (configurable)
* additional hook was added to the QueryLimit api to skip sending shard requests if the limit is likely to be reached when they arrive at the target replica. This api should be generic enough to allow us to discount other "used up" limits (cpu, mem) if we decide to do so for consistency.
> SOLR-17926: Add tracking of time already spent to discount the limit for sub-requests

- solr/ui/src/commonMain/composeResources/values/strings.xml
- solr/ui/src/commonMain/kotlin/org/apache/solr/ui/components/auth/BasicAuthComponent.kt
- solr/ui/src/commonMain/kotlin/org/apache/solr/ui/components/auth/integration/DefaultAuthenticationComponent.kt
- solr/ui/src/commonMain/kotlin/org/apache/solr/ui/components/start/integration/HttpStartStoreClient.kt
- solr/ui/src/commonMain/kotlin/org/apache/solr/ui/domain/AuthMethod.kt
- solr/ui/src/commonMain/kotlin/org/apache/solr/ui/domain/AuthOption.kt
- solr/ui/src/commonMain/kotlin/org/apache/solr/ui/utils/HttpClientUtils.kt
- solr/ui/src/commonMain/kotlin/org/apache/solr/ui/views/auth/BasicAuthContent.kt
- solr/webapp/web/WEB-INF/web.xml
https://issues.apache.org/jira/browse/SOLR-17885
This PR depends on #3703.
> SOLR-17885: Fix authentication for new UI in browser

- solr/core/src/test/org/apache/solr/search/facet/TestJsonFacetErrors.java
- solr/core/src/test/org/apache/solr/search/facet/TestJsonFacetRefinement.java
- solr/core/src/test/org/apache/solr/search/facet/TestJsonFacets.java
- solr/core/src/test/org/apache/solr/search/facet/TestJsonFacetsWithNestedObjects.java
- solr/core/src/test/org/apache/solr/search/facet/TestJsonRangeFacets.java
- solr/core/src/test/org/apache/solr/search/json/TestJsonRequest.java
- solr/test-framework/src/java/org/apache/solr/SolrTestCaseHS.java
While migrating the use of NoOpResponseParser I noticed that quite a few methods in SolrTestCaseHS are NOT used.    
In fact, there may be an opportunity to collapse it back into SolrTestCaseJ4 or maybe take the best of both, but that would be more ambitious.
Removed unused methods and polished up a few variables.   I didn't do the whole deprecation thing since I don't think we recommend folks use SolrTestCaseHS in any type of external testing, it's pretty much only used by the Json faceting tests, and shouldn't be used.
Just rerunning existing tests that extend SolrTestCaseHS.
> Small cleanups SolrTestCaseHS
