apache/solr

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/security/JWTAuthPlugin.java
- solr/core/src/java/org/apache/solr/security/JWTIssuerConfig.java
- solr/core/src/test/org/apache/solr/security/JWTAuthPluginTest.java
- solr/solr-ref-guide/src/jwt-authentication-plugin.adoc
- solr/solr-ref-guide/src/major-changes-in-solr-9.adoc
Removing deprecated parameter.
Just some clean up, documented in the upgrade notes.
n/a
- [ X] I have developed this patch against the `main` branch.
- [ X] I have run `./gradlew check`.
- [X ] I have added documentation for the [Reference …
> SOLR-15203: remove deprecated jwk url

- solr/solr-ref-guide/src/basic-authentication-plugin.adoc
Documentation for the client changes introduced in SOLR-15154
Moved from https://github.com/apache/lucene-solr/pull/2468
> SOLR-15154: Document new options for credentials

- dev-tools/scripts/releaseWizard.py
Not sure if there's a better place to do this, or if you have other plans for modularizing checking for available binaries.
> Check For SVN in release wizard

- solr/core/src/java/org/apache/solr/cloud/api/collections/AddReplicaCmd.java
- solr/core/src/java/org/apache/solr/cloud/api/collections/BackupCmd.java
- solr/core/src/java/org/apache/solr/cloud/api/collections/CollApiCmds.java
- solr/core/src/java/org/apache/solr/cloud/api/collections/CollectionCommandContext.java
- solr/core/src/java/org/apache/solr/cloud/api/collections/CollectionHandlingUtils.java
- solr/core/src/java/org/apache/solr/cloud/api/collections/CreateCollectionCmd.java
- solr/core/src/java/org/apache/solr/cloud/api/collections/CreateSnapshotCmd.java
- solr/core/src/java/org/apache/solr/cloud/api/collections/DeleteReplicaCmd.java
- solr/core/src/java/org/apache/solr/cloud/api/collections/DeleteSnapshotCmd.java
- solr/core/src/java/org/apache/solr/cloud/api/collections/MigrateCmd.java
- solr/core/src/java/org/apache/solr/cloud/api/collections/OcmhCollectionCommandContext.java
- solr/core/src/java/org/apache/solr/cloud/api/collections/RestoreCmd.java
- solr/core/src/java/org/apache/solr/cloud/api/collections/SplitShardCmd.java
Not expecting any comments on this PR. Trivial change that I'm going to merge right away.
> SOLR-15157: rename getShardHandler into newShardHandler

- solr/core/src/java/org/apache/solr/cloud/DistributedClusterStateUpdater.java
This fixes the test failure of PerReplicaStatesIntegrationTest.testRestart()
> SOLR-15288: fix DOWNNODE issue for PRS collections when cluster state updates are distributed

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/admin/CollectionsHandler.java
Collection selector drop down does not sort collections
call Collections.sort() on the list coming from ZK
Manual tests. 
> SOLR-15153 - Collection selector drop down does not sort collections

- solr/core/src/java/org/apache/solr/cloud/RecoveryStrategy.java
https://issues.apache.org/jira/browse/SOLR-15328
> SOLR-15328: include time-taken in finished-recovery-process logging

- solr/solr-ref-guide/src/basic-authentication-plugin.adoc
Ref guide documentation for the changes introduced by https://github.com/apache/solr/pull/15
> SOLR-15155: Document how to set credentials in CloudHttp2SolrClient

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/admin/LukeRequestHandler.java
- solr/webapp/web/partials/core_overview.html
https://issues.apache.org/jira/browse/SOLR-15341
This time, completely removing it.
> SOLR-15341: remove indexHeapUsageBytes

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/core/CoreContainer.java
- solr/core/src/java/org/apache/solr/pkg/PackageAPI.java
- solr/core/src/test/org/apache/solr/pkg/TestPackages.java
https://issues.apache.org/jira/browse/SOLR-15369
> SOLR-15369: Only load PackageStoreAPI with SolrCloud

- solr/core/src/java/org/apache/solr/core/ConfigOverlay.java
- solr/core/src/java/org/apache/solr/search/CacheConfig.java
- solr/core/src/test/org/apache/solr/core/TestConfigOverlay.java
- solr/core/src/test/org/apache/solr/handler/admin/PropertiesRequestHandlerTest.java
- solr/solrj/src/test/org/apache/solr/client/solrj/io/stream/StreamingTest.java
IntelliJ inspection for incompatible types passed to assert*
> Fix bad unchecked casts for generic types

- solr/core/src/test/org/apache/solr/search/TestMaxScoreQueryParser.java
Precommit was broken by a recent Lucene change.
This updates Solr to address an underlying change that widened the
return type of DisjunctionMaxQuery from List to Collection.
See TestMaxScoreQueryParser
> Update type assumptions in TestMaxScoreQueryParser

- gradle/ide/intellij-idea.gradle
I'm not sure if this change has other unintended side effects, but I needed it for my Structure101 plugin to work.
> Update IntelliJ paths

- solr/CHANGES.txt
- solr/solrj/src/java/org/apache/solr/common/params/CommonParams.java
See https://issues.apache.org/jira/browse/SOLR-15384
> SOLR-15384 Zookeeper admin handlers not queryable from SolrJ

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/core/CoreContainer.java
https://issues.apache.org/jira/browse/SOLR-15222
> SOLR-15222: userfiles dir will only be created in SolrCloud mode

- solr/core/src/java/org/apache/solr/handler/admin/MetricsHistoryHandler.java
https://issues.apache.org/jira/browse/SOLR-15348
> SOLR-15348: reduce 'could not obtain overseer' WARNings in MetricsHistoryHandler

- solr/CHANGES.txt
- solr/webapp/web/css/angular/replication.css
See https://issues.apache.org/jira/browse/SOLR-15424
> SOLR-15424: Solr replication UI wraps ETA time

- solr/CHANGES.txt
- solr/webapp/web/js/angular/controllers/collections.js
- solr/webapp/web/js/angular/services.js
https://issues.apache.org/jira/browse/SOLR-15414
> SOLR-15414 Use ConfigSetAPI to list configs on AdminUI

- solr/core/src/java/org/apache/solr/util/CryptoKeys.java
https://issues.apache.org/jira/browse/SOLR-15426
> SOLR-15426 Remove unused decrypt AES methods

- README.md
https://issues.apache.org/jira/browse/SOLR-15241
> SOLR-15241: Add Docker & Kubernetes info to the README

- solr/contrib/prometheus-exporter/conf/grafana-solr-dashboard.json
https://issues.apache.org/jira/browse/SOLR-15397
> SOLR-15397 Remove "exemplar" setting for the new zookeeper grafana graph

- solr/solr-ref-guide/src/collection-management.adoc
https://issues.apache.org/jira/browse/SOLR-15311
> SOLR-15311: document 'async' as MODIFYCOLLECTION parameter instead of collection attribute/property

- solr/CHANGES.txt
- solr/server/etc/jetty.xml
https://issues.apache.org/jira/browse/SOLR-15453
Fixes security errors in browser.
Add `data:` directive
Integration test only. 
> SOLR-15453: permit local  binary image requests

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/core/HdfsDirectoryFactory.java
Misleading error message in HdfsDirectoryFactory
Fixing the error message.
Unit tests
> SOLR-15280 Misleading error message in HdfsDirectoryFactory

- solr/solr-ref-guide/src/major-changes-in-solr-9.adoc
Rename reference to VelocityResponseWriter plugin repo.
Edited URL in upgrade notes doc.
Double checked that the URL is accurate, by clicking through.
> renamed solritas repo

- solr/CHANGES.txt
- solr/contrib/langid/src/java/org/apache/solr/update/processor/LangIdParams.java
- solr/contrib/langid/src/java/org/apache/solr/update/processor/LanguageIdentifierUpdateProcessor.java
- solr/solr-ref-guide/src/detecting-languages-during-indexing.adoc
- solr/solr-ref-guide/src/major-changes-in-solr-9.adoc
https://issues.apache.org/jira/browse/SOLR-15471
> SOLR-15471 Rename parameter to langid.allowlist

- .git-blame-ignore-revs
https://issues.apache.org/jira/browse/SOLR-15454
> SOLR-15454: retain and explain Lucene commits in .git-blame-ignore-revs

- solr/core/src/java/org/apache/solr/util/CryptoKeys.java
- solr/core/src/test/org/apache/solr/security/JWTAuthPluginIntegrationTest.java
- solr/core/src/test/org/apache/solr/security/JWTAuthPluginTest.java
https://issues.apache.org/jira/browse/SOLR-15484
> SOLR-15484 Redesign integration test, with cluster in local scope variable per test

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/sql/CalciteSolrDriver.java
- solr/core/src/java/org/apache/solr/handler/sql/SolrEnumerator.java
- solr/core/src/java/org/apache/solr/handler/sql/SolrFilter.java
- solr/core/src/java/org/apache/solr/handler/sql/SolrSchema.java
- solr/core/src/test-files/solr/configsets/sql/conf/schema.xml
- solr/core/src/test/org/apache/solr/handler/TestSQLHandler.java
https://issues.apache.org/jira/browse/SOLR-15456
See JIRA
Added additional request to get schema info from luke for custom field types.
Added unit test to verify the type information for custom fields resolves correctly.
> SOLR-15456: Get field type info from luke for custom fields instead of defaulting to String

- solr/core/src/java/org/apache/solr/search/HashQParserPlugin.java
https://issues.apache.org/jira/browse/SOLR-15185
> SOLR-15185: fix hashCode

- solr/solr-ref-guide/src/spatial-search.adoc
https://issues.apache.org/jira/browse/SOLR-15491
Adding example to return distance field.
Updated documentation.
N/A
> SOLR-15491: Adding example to return distance field.

- gradle/validation/validate-source-patterns.gradle
- solr/core/src/java/org/apache/solr/core/CoreContainer.java
- solr/test-framework/src/java/org/apache/solr/BaseDistributedSearchTestCase.java
- solr/test-framework/src/java/org/apache/solr/cloud/AbstractFullDistribZkTestBase.java
https://issues.apache.org/jira/browse/SOLR-15485
> SOLR-15485: discourage Collections.singleton.forEach use

- solr/solr-ref-guide/build.gradle
See issue: https://issues.apache.org/jira/browse/SOLR-15520
> SOLR-15520: Fix build on windows by downgrading jekyll

- solr/core/src/java/org/apache/solr/handler/component/SearchHandler.java
https://issues.apache.org/jira/browse/SOLR-15519
> SOLR-15519: reduce SolrCore.getCircuitBreakerManager() calls in SearchHandler.handleRequestBody()

- gradle/validation/validate-source-patterns.gradle
- solr/core/src/java/org/apache/solr/core/CoreContainer.java
- solr/core/src/test/org/apache/solr/cloud/OverseerTest.java
https://issues.apache.org/jira/browse/SOLR-15485
> SOLR-15485: action post-commit review feedback

- solr/docker/scripts/solr-create
- solr/docker/scripts/solr-demo
- solr/docker/scripts/solr-foreground
- solr/docker/scripts/solr-precreate
- solr/docker/tests/cases/initdb/test.sh
https://issues.apache.org/jira/browse/SOLR-15545
> SOLR-15545: Properly source run-initdb in docker commands

- solr/CHANGES.txt
- solr/solr-ref-guide/src/major-changes-in-solr-9.adoc
- solr/solrj/src/java/org/apache/solr/common/cloud/ZkStateReader.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/CloudHttp2SolrClientTest.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/CloudSolrClientTest.java
https://issues.apache.org/jira/browse/SOLR-15549
> SOLR-15549: Better error message for missing ZK nodes in ZkStateReader.

- solr/contrib/ltr/src/java/org/apache/solr/ltr/LTRRescorer.java
- solr/contrib/ltr/src/java/org/apache/solr/ltr/interleaving/LTRInterleavingRescorer.java
https://issues.apache.org/jira/browse/SOLR-15537
> SOLR-15537: split 10-args LTRRescorer.scoreSingleHit method

- solr/solr-ref-guide/build.gradle
- solr/solr-ref-guide/src/configuring-logging.adoc
- solr/solr-ref-guide/src/enabling-ssl.adoc
- solr/solr-ref-guide/src/filters.adoc
- solr/solr-ref-guide/src/language-analysis.adoc
- solr/solr-ref-guide/src/solr-upgrade-notes.adoc
https://issues.apache.org/jira/browse/SOLR-15497
Same as PR #232 but doesn't have random extra commits in it.
Since @cpoerschke already approved the old PR, I'll merge this as soon as the checks pass.
> SOLR-15497: Fix broken links

- solr/CHANGES.txt
- solr/bin/solr
- solr/core/src/java/org/apache/solr/util/SolrCLI.java
- solr/solr-ref-guide/src/basic-authentication-plugin.adoc
- solr/solr-ref-guide/src/security-ui.adoc
- solr/webapp/web/js/angular/app.js
- solr/webapp/web/js/angular/controllers/schema-designer.js
- solr/webapp/web/js/angular/controllers/security.js
- solr/webapp/web/partials/security.html
https://issues.apache.org/jira/browse/SOLR-15573
See JIRA for details ...
_NOTE: I intend to backport this to 8x for inclusion in 8.10. While I can see the need for `blockUnknown=false`, I don't think people would want anonymous users to be able edit configs or read security info, so I believe these changes are safe from a back-compat perspective._
Adding `security-read` and `config-edit` to initial `security.json` created by the SolrCLI `auth` tool so that when `blockUnknown=false` these endpoints are still protected (anonymous should *NOT* be allowed to read security config).
Now when a user visits the Admin UI and has not logged in, when they view the Security screen, they will be re-directed to login first; this happens b/c `security-read` now requires the `admin` role by default.
The …
> SOLR-15573: bin/solr auth tool should provide role bindings for security-read and config-edit by default

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/search/grouping/distributed/command/SearchGroupsFieldCommand.java
- solr/core/src/java/org/apache/solr/search/grouping/distributed/command/TopGroupsFieldCommand.java
- solr/core/src/java/org/apache/solr/search/grouping/distributed/responseprocessor/SearchGroupShardResponseProcessor.java
- solr/core/src/java/org/apache/solr/search/grouping/distributed/responseprocessor/TopGroupsShardResponseProcessor.java
- solr/core/src/java/org/apache/solr/search/grouping/distributed/shardresultserializer/SearchGroupsResultTransformer.java
https://issues.apache.org/jira/browse/SOLR-15535
> SOLR-15535: remove rawtypes warnings in 'grouping' code

- solr/solr-ref-guide/src/json-query-dsl.adoc
https://issues.apache.org/jira/browse/SOLR-14540
This updates Mikhail's PR apache/lucene-solr#1805 to `main` and fixes various typos and issues on the page in general.
> SOLR-14540: add example for query DSL blockJoin facet

- solr/solr-ref-guide/src/solr-in-docker.adoc
* Add sub-headers to "Creating cores" section
* Add custom configset example to solr-precreate section
Transcribed from https://github.com/docker-solr/docker-solr/pull/383
Co-authored-by: Kirill Roskolii <roskoliy.kirill@gmail.com>
> Ref Guide: Docker, add headings

- solr/webapp/web/js/angular/controllers/security.js
https://issues.apache.org/jira/browse/SOLR-15637
Trivial UI fix. Tested manually, see screenshot
> SOLR-15637: Set scope.tls for security UI based on data.security.tls in response from server

- solr/core/src/java/org/apache/solr/update/PeerSync.java
- solr/core/src/test/org/apache/solr/update/PeerSyncTest.java
https://issues.apache.org/jira/browse/SOLR-15667
> SOLR-15667: add PeerSyncTest.handleVersionsWithRangesTests()

- solr/core/src/java/org/apache/solr/update/PeerSync.java
- solr/core/src/java/org/apache/solr/update/PeerSyncWithLeader.java
https://issues.apache.org/jira/browse/SOLR-15655
> SOLR-15655: PeerSync[WithLeader] 'sorted versions from' debug logging tweak

- build.gradle
> Bump owasp-dependencycheck to 6.4.1.1

- solr/CHANGES.txt
- solr/server/solr/configsets/sample_techproducts_configs/conf/solrconfig.xml
- solr/webapp/web/js/angular/controllers/core-overview.js
- solr/webapp/web/js/angular/services.js
- solr/webapp/web/partials/core_overview.html
https://issues.apache.org/jira/browse/SOLR-10529
Closes https://github.com/apache/lucene-solr/pull/193
> SOLR-10529: Solr UI Health Check enable/disable ping Button doesn't work

- solr/solrj/src/java/org/apache/solr/common/util/ByteArrayUtf8CharSequence.java
> fixed jdk9 equals method link

- solr/core/src/java/org/apache/solr/legacy/BBoxStrategy.java
> LUCENE-9229 fixed esri link

- solr/core/src/java/org/apache/solr/util/hll/HLL.java
> LUCENE-9229 fixed 3 javadoc links 1) google guave, 2&3) Two links relocated away from "aggregateknowledge"

- solr/contrib/gcs-repository/src/java/org/apache/solr/gcs/GCSBackupRepository.java
https://issues.apache.org/jira/browse/SOLR-15711
Not adding a changelog entry, since I don't think there were any actual errors seen from this.
> SOLR-15711: Fix GCSRepository to follow createDirectory API contract

- solr/CHANGES.txt
- solr/webapp/web/js/angular/controllers/schema-designer.js
- solr/webapp/web/js/angular/controllers/security.js
- solr/webapp/web/partials/schema-designer.html
- solr/webapp/web/partials/security.html
https://issues.apache.org/jira/browse/SOLR-15774
> SOLR-15774: Avoid weird off-by-one errors with Angular's 'chosen' select box directive for the security and schema-designer screens in Admin UI

- solr/CHANGES.txt
> SOLR-15635: move to 8.11.1 in CHANGES.txt

- solr/core/src/test/org/apache/solr/handler/component/UpdateLogCloudTest.java
https://issues.apache.org/jira/browse/SOLR-15806
> SOLR-15806: expand UpdateLogCloudTest coverage w.r.t. Ephemeral vs. Standard DirectoryFactory use

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/admin/ShowFileRequestHandler.java
- solr/core/src/test/org/apache/solr/handler/admin/ShowFileRequestHandlerTest.java
- solr/webapp/web/js/angular/controllers/files.js
https://issues.apache.org/jira/browse/SOLR-15804
> SOLR-15804 Allow content-types with ;charset in ShowFileRequestHandler

- solr/core/src/java/org/apache/solr/schema/AbstractEnumField.java
Fixed a typo in comment line inside AbstractEnumField.java. There is no need to add unit test and documentation because of typo fixing.
> Fixed a typo in comment line inside AbstractEnumField.java 

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/designer/SchemaDesignerSettings.java
- solr/core/src/java/org/apache/solr/handler/designer/SchemaDesignerSettingsDAO.java
- solr/core/src/test/org/apache/solr/handler/designer/TestSchemaDesignerSettingsDAO.java
- solr/webapp/web/js/angular/controllers/schema-designer.js
https://issues.apache.org/jira/browse/SOLR-15813
Also includes fix to improve how backend errors are reported in the UI.
> SOLR-15813: Schema designer not handling  stored as a string (vs. boolean) in the config overlay

- solr/CHANGES.txt
- solr/bin/solr
- solr/bin/solr.cmd
- solr/core/src/java/org/apache/solr/util/SolrCLI.java
- solr/core/src/test/org/apache/solr/util/AuthToolTest.java
- solr/test-framework/src/java/org/apache/solr/cloud/AbstractDistribZkTestBase.java
https://issues.apache.org/jira/browse/SOLR-15199
> SOLR-15199: Pass thru all command actions not explicitly handled by the bin/solr script, such as 'api', to the SolrCLI Java app

- dev-docs/cloud-script.adoc
- dev-docs/working-between-major-versions.adoc
https://issues.apache.org/jira/browse/SOLR-15818
> SOLR-15818 Fix branch_8x mention

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/core/SolrResourceLoader.java
- solr/core/src/java/org/apache/solr/schema/ManagedIndexSchemaFactory.java
- solr/core/src/test/org/apache/solr/core/ResourceLoaderTest.java
- solr/core/src/test/org/apache/solr/schema/PrimitiveFieldTypeTest.java
- solr/core/src/test/org/apache/solr/util/TestSystemIdResolver.java
https://issues.apache.org/jira/browse/SOLR-15826
> SOLR-15826: ResourceLoader should better respect allowed paths

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/schema/AbstractSpatialFieldType.java
- solr/core/src/test/org/apache/solr/schema/ExternalFileFieldSortTest.java
- solr/core/src/test/org/apache/solr/search/TestSolr4Spatial.java
- solr/core/src/test/org/apache/solr/search/TestSolrQueryParser.java
https://issues.apache.org/jira/browse/SOLR-15833
> SOLR-15833

- solr/solr-ref-guide/src/spatial-search.adoc
Fix Schema Configuration for RPT documentation so it's easier to understand.
N/A
> Fix RPT documentation

- solr/solr-ref-guide/src/commits-transaction-logs.adoc
If my understanding of the UpdateLog code is right (I'm looking at this bit in particular: https://github.com/apache/solr/blob/main/solr/core/src/java/org/apache/solr/update/UpdateLog.java#L506-L519), then:
- new transaction logs (files) are added for each [hard] commit
- old transaction logs are removed if there are more than maxNumLogsToKeep of them OR if we have more than numRecordsToKeep records in total
This means numRecordsToKeep is not per file, but across all the files.
Please describe the tests you've developed or run to confirm this patch implements the feature …
> Update transaction log options descriptions

- solr/core/src/test/org/apache/solr/cloud/OverseerCollectionConfigSetProcessorTest.java
https://issues.apache.org/jira/browse/SOLR-15868
> SOLR-15868: Fix test broken by new sorting of nodeList

- dev-tools/scripts/releaseWizard.yaml
https://issues.apache.org/jira/browse/SOLR-15817
> SOLR-15817 Ensure refGuide upgrade notes are completed

- dev-tools/scripts/README.md
- dev-tools/scripts/create_line_file_docs.py
- dev-tools/scripts/githubPRs.py
- dev-tools/scripts/releasedJirasRegex.py
https://issues.apache.org/jira/browse/SOLR-15852
For some of the simple scripts and README
> SOLR-15852 Update dev-tools/scripts for 9.0

- gradle/solr/packaging.gradle
https://issues.apache.org/jira/browse/SOLR-15756
Merging the chang I found during work with SOLR-15867
> SOLR-15756 Add back contrib readmes in distribution

- solr/solr-ref-guide/src/common-query-parameters.adoc
https://issues.apache.org/jira/browse/SOLR-15798
document fl=nam* wildcard pattern.
docs
n/a
- [x ] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms to the standards described there to the best of my ability.
- [ x] I have created a Jira issue and added the issue ID to my pull request title.
- [ x] I have given Solr maintainers [access](https://help.github.com/en/articles/allowing-changes-to-a-pull-request-branch-created-from-a-fork) to contribute to my PR branch. (optional but recommended)
- [ x] I have developed this patch against the `main` branch.
- [ x] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref- …
> SOLR-15798: add example of using wildcard on fl parameter

- gradle/testing/alternative-jdk-support.gradle
- gradle/validation/error-prone.gradle
see https://issues.apache.org/jira/browse/SOLR-15876
> SOLR-15876: Only disable error-prone, if it is running as an alternate runtime JVM

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/component/RealTimeGetComponent.java
- solr/core/src/test/org/apache/solr/search/TestRealTimeGet.java
Added a test that fails in the current code and a possible fix. 
I'll add CHANGES entry after this is reviewed and before committing.
> SOLR-15854: Let RealtimeGet component support negative filters

- .lift.toml
@TomMD is there anything else besides the file rename and the property change that we should be aware of moving from muse to lift?
> update muse to lift

- gradle/validation/error-prone.gradle
- solr/core/src/java/org/apache/solr/servlet/RateLimitManager.java
- solr/solrj/src/java/org/apache/solr/common/cloud/SolrZooKeeper.java
Regression introduced by apache/lucene-solr#2264
> SOLR-15903 Fix incompatible types used with java collections

- gradle/solr/packaging.gradle
- solr/CHANGES.txt
- solr/contrib/analysis-extras/README.md
- solr/solr-ref-guide/src/major-changes-in-solr-9.adoc
https://issues.apache.org/jira/browse/SOLR-15924
Surprisingly no mentions in the ref guide...
> SOLR-15924: Remove lucene-libs from contrib module packaging

- solr/solr-ref-guide/src/language-analysis.adoc
This PR fixes a couple of typos in a OpenNLP filter factory class name that is presented in the Language Analysis documentation page.
Replace filter class with the correct one.
N/A
> Fix OpenNLP Phrase Chunker filter name typo in Language Analysis docs

- solr/solr-ref-guide/src/tutorial-films.adoc
Hello,
This is just a tiny pull request to fix two typos found reading the Solr tutorial.
(Sorry, I had already created the Jira ticket before reading the "How to contribute")
Have a nice day.
> SOLR-15930 - Fix typos in the Solr tutorial

- solr/core/src/java/org/apache/solr/update/SolrIndexConfig.java
- solr/core/src/java/org/apache/solr/util/DataConfigNode.java
- solr/solrj/src/java/org/apache/solr/common/ConfigNode.java
@madrob 
I opened a new PR here to address your review comments
> SOLR-15337: Avoid XPath in solrconfig.xml parsing (take 2)

- solr/CHANGES.txt
- solr/contrib/ltr/src/java/org/apache/solr/ltr/LTRThreadModule.java
- solr/core/src/java/org/apache/solr/cloud/ZkController.java
- solr/core/src/java/org/apache/solr/core/CloseHook.java
- solr/core/src/java/org/apache/solr/core/SolrCore.java
- solr/core/src/java/org/apache/solr/handler/ReplicationHandler.java
- solr/core/src/java/org/apache/solr/handler/component/SearchHandler.java
- solr/core/src/java/org/apache/solr/spelling/suggest/SolrSuggester.java
- solr/core/src/java/org/apache/solr/spelling/suggest/Suggester.java
- solr/core/src/test/org/apache/solr/core/SolrCoreTest.java
https://issues.apache.org/jira/browse/SOLR-15934
@cpoerschke tagging you specifically for the comment I made in the LTR module. If you feel that it can be dismissed or spun out into a separate issue, then I'm happy to do either.
> SOLR-15934 CloseHook is now an interface

- solr/core/src/test/org/apache/solr/core/TestBadConfig.java
https://issues.apache.org/jira/browse/SOLR-15939
> SOLR-15939 Fix test failure in TestBadConfig

- solr/core/src/test/org/apache/solr/cloud/api/collections/TestCollectionAPI.java
https://issues.apache.org/jira/browse/SOLR-15870
> SOLR-15870 Test TestCollectionAPI fails frequently

- solr/core/src/java/org/apache/solr/core/CoreContainer.java
- solr/core/src/java/org/apache/solr/servlet/CoreContainerProvider.java
- solr/core/src/java/org/apache/solr/util/StartupLoggingUtils.java
- solr/server/etc/jetty-requestlog.xml
https://issues.apache.org/jira/browse/SOLR-14142
> SOLR-14142 Log in Solr's log whether request logging is enabled

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cloud/api/collections/BackupCmd.java
- solr/core/src/java/org/apache/solr/handler/IncrementalShardBackup.java
- solr/core/src/java/org/apache/solr/handler/SnapShooter.java
- solr/core/src/java/org/apache/solr/handler/admin/BackupCoreOp.java
- solr/solr-ref-guide/src/major-changes-in-solr-9.adoc
https://issues.apache.org/jira/browse/SOLR-15884
This changes for all types of backup responses (incremental, non-incremental, snapshot)
> SOLR-15884: Use a map for backup responses

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/tagger/TaggerRequestHandler.java
- solr/solr-ref-guide/src/major-changes-in-solr-9.adoc
- solr/solr-ref-guide/src/tagger-handler.adoc
(for each tag)
https://issues.apache.org/jira/browse/SOLR-15944
I didn't try it for real yet, I admit, but it's trivial
> SOLR-15944: Tagger: JSON response should use map not array

- dev-tools/scripts/smokeTestRelease.py
- help/workflow.txt
- solr/bin/install_solr_service.sh
- solr/packaging/build.gradle
- solr/solr-ref-guide/src/installing-solr.adoc
- solr/solr-ref-guide/src/solr-tutorial.adoc
https://issues.apache.org/jira/browse/SOLR-15952
> SOLR-15952: Stop releasing Solr binary ZIP artifact from v9.0

- solr/solrj/src/java/org/apache/solr/common/cloud/SolrZkClient.java
- solr/solrj/src/java/org/apache/solr/common/cloud/ZkMaintenanceUtils.java
https://issues.apache.org/jira/browse/SOLR-15918
> SOLR-15918 Fix test failures

- solr/CHANGES.txt
- solr/webapp/web/css/angular/query.css
- solr/webapp/web/partials/query.html
https://issues.apache.org/jira/browse/SOLR-11905
I did not bother updating any screenshots in RefGuide, since the existing images did not cover these parts anyway.
> SOLR-11905 New Admin UI input boxes for JSON query and facet DSL

- solr/CHANGES.txt
- solr/server/resources/log4j2-console.xml
change zk logging to ERROR level for SolrCLI
https://issues.apache.org/jira/browse/SOLR-15968
> SOLR-15968 bin/solr zk always throws exception

- solr/core/src/test/org/apache/solr/handler/component/DistributedQueryComponentCustomSortTest.java
- solr/modules/hdfs/src/test/org/apache/solr/handler/TestHdfsBackupRestoreCore.java
- solr/test-framework/src/java/org/apache/solr/cloud/AbstractBasicDistributedZk2TestBase.java
- solr/test-framework/src/java/org/apache/solr/handler/BackupRestoreUtils.java
https://issues.apache.org/jira/browse/SOLR-15969
Co-authored-by: Kevin Risden <krisden@apache.org>
> SOLR-15969 Supress SimpleTextCodec on Backup Operations

- solr/core/src/test/org/apache/solr/handler/admin/ThreadDumpHandlerTest.java
https://issues.apache.org/jira/browse/SOLR-15124
> SOLR-15124: Fix ThreadDumpHandlerTest

- solr/core/src/java/org/apache/solr/security/JWTAuthPlugin.java
- solr/core/src/java/org/apache/solr/security/JWTIssuerConfig.java
- solr/core/src/java/org/apache/solr/security/JWTPrincipal.java
- solr/core/src/java/org/apache/solr/security/JWTPrincipalWithUserRoles.java
- solr/core/src/java/org/apache/solr/security/JWTVerificationkeyResolver.java
- solr/core/src/test/org/apache/solr/security/JWTAuthPluginIntegrationTest.java
- solr/core/src/test/org/apache/solr/security/JWTAuthPluginTest.java
- solr/core/src/test/org/apache/solr/security/JWTIssuerConfigTest.java
- solr/core/src/test/org/apache/solr/security/JWTVerificationkeyResolverTest.java
https://issues.apache.org/jira/browse/SOLR-15907
This is step one of moving to module - to isolate code formatting changes in one commit
> SOLR-15907 Apply spotless only on JWT classes

- solr/CHANGES.txt
- solr/modules/analysis-extras/build.gradle
- solr/modules/analysis-extras/src/test/org/apache/solr/schema/TestICUCollationFieldUDVAS.java
https://issues.apache.org/jira/browse/SOLR-15991
> SOLR-15991: analysis-extras module tests shouldn't rely on log4j dependency

- solr/core/src/java/org/apache/solr/search/DisMaxQParserPlugin.java
- solr/core/src/test/org/apache/solr/response/JSONWriterTest.java
- solr/modules/s3-repository/src/test/org/apache/solr/s3/S3ReadWriteTest.java
- solr/solr-ref-guide/modules/query-guide/pages/result-clustering.adoc
- solr/solrj/src/java/org/apache/solr/common/params/FacetParams.java
- solr/test-framework/src/java/org/apache/solr/cloud/MiniSolrCloudCluster.java
https://issues.apache.org/jira/browse/SOLR-15913
Spelling error has crept in.
Fix spelling.
Ran tests.
- [ X] I have developed this patch against the `main` branch.
- [ X] I have run `./gradlew check`.
> SOLR-15913: fix typo for word overridden

- README.md
- solr/README.md
https://issues.apache.org/jira/browse/SOLR-13737
lead with SOLR Cloud in the README
n/a
> SOLR-13737 Moving SolrCloud up on the README 

- solr/core/build.gradle
https://issues.apache.org/jira/browse/SOLR-16007
> SOLR-16007: javax.servlet-api.jar shoud not be in WEB-INF/lib

- solr/core/src/test/org/apache/solr/handler/TestSQLHandler.java
- solr/core/src/test/org/apache/solr/handler/TestSQLHandlerNonCloud.java
- solr/core/src/test/org/apache/solr/handler/admin/DaemonStreamApiTest.java
- solr/solrj/src/test/org/apache/solr/client/solrj/io/graph/GraphTest.java
- solr/solrj/src/test/org/apache/solr/client/solrj/io/stream/StreamDecoratorTest.java
- solr/solrj/src/test/org/apache/solr/client/solrj/io/stream/StreamExpressionTest.java
- solr/solrj/src/test/org/apache/solr/client/solrj/io/stream/StreamingTest.java
https://issues.apache.org/jira/browse/SOLR-16012
> SOLR-16012: Remove mapParams from StreamingTest and TestSQLHandler

- solr/bin/install_solr_service.sh
https://issues.apache.org/jira/browse/SOLR-9575
> SOLR-9575: Use default solr.xml in install_solr_service

- gradle/validation/spotless.gradle
- solr/prometheus-exporter/src/java/org/apache/solr/prometheus/collector/CollectionsCollector.java
- solr/prometheus-exporter/src/java/org/apache/solr/prometheus/collector/MetricSamples.java
- solr/prometheus-exporter/src/java/org/apache/solr/prometheus/collector/MetricsCollector.java
- solr/prometheus-exporter/src/java/org/apache/solr/prometheus/collector/MetricsCollectorFactory.java
- solr/prometheus-exporter/src/java/org/apache/solr/prometheus/collector/PingCollector.java
- solr/prometheus-exporter/src/java/org/apache/solr/prometheus/collector/SchedulerMetricsCollector.java
- solr/prometheus-exporter/src/java/org/apache/solr/prometheus/collector/SearchCollector.java
- solr/prometheus-exporter/src/java/org/apache/solr/prometheus/collector/package-info.java
- solr/prometheus-exporter/src/java/org/apache/solr/prometheus/exporter/CachedPrometheusCollector.java
- solr/prometheus-exporter/src/java/org/apache/solr/prometheus/exporter/MetricsConfiguration.java
- solr/prometheus-exporter/src/java/org/apache/solr/prometheus/exporter/MetricsQuery.java
- solr/prometheus-exporter/src/java/org/apache/solr/prometheus/exporter/MetricsQueryTemplate.java
- solr/prometheus-exporter/src/java/org/apache/solr/prometheus/exporter/PrometheusExporterSettings.java
- solr/prometheus-exporter/src/java/org/apache/solr/prometheus/exporter/SolrClientFactory.java
- solr/prometheus-exporter/src/java/org/apache/solr/prometheus/exporter/SolrExporter.java
- solr/prometheus-exporter/src/java/org/apache/solr/prometheus/exporter/SolrScrapeConfiguration.java
- solr/prometheus-exporter/src/java/org/apache/solr/prometheus/exporter/package-info.java
- solr/prometheus-exporter/src/java/org/apache/solr/prometheus/scraper/SolrCloudScraper.java
- solr/prometheus-exporter/src/java/org/apache/solr/prometheus/scraper/SolrScraper.java
- solr/prometheus-exporter/src/java/org/apache/solr/prometheus/scraper/SolrStandaloneScraper.java
- solr/prometheus-exporter/src/java/org/apache/solr/prometheus/scraper/package-info.java
- solr/prometheus-exporter/src/test/org/apache/solr/prometheus/PrometheusExporterTestBase.java
- solr/prometheus-exporter/src/test/org/apache/solr/prometheus/collector/MetricSamplesTest.java
- solr/prometheus-exporter/src/test/org/apache/solr/prometheus/exporter/MetricsQueryTemplateTest.java
- solr/prometheus-exporter/src/test/org/apache/solr/prometheus/exporter/SolrExporterIntegrationTest.java
- solr/prometheus-exporter/src/test/org/apache/solr/prometheus/exporter/SolrExporterTestBase.java
- solr/prometheus-exporter/src/test/org/apache/solr/prometheus/scraper/SolrCloudScraperTest.java
- solr/prometheus-exporter/src/test/org/apache/solr/prometheus/scraper/SolrStandaloneScraperTest.java
- solr/prometheus-exporter/src/test/org/apache/solr/prometheus/utils/Helpers.java
https://issues.apache.org/jira/browse/SOLR-16035
> SOLR-16035: Enable spotless for prometheus-exporter

- .github/workflows/docker-test.yml
- .github/workflows/gradle-precommit.yml
- .github/workflows/solrj-test.yml
Implements the same change as https://github.com/apache/lucene/pull/674
> Upgrade to github java action v2

- gradle/validation/spotless.gradle
- solr/modules/analysis-extras/src/java/org/apache/solr/schema/ICUCollationField.java
- solr/modules/analysis-extras/src/java/org/apache/solr/update/processor/OpenNLPExtractNamedEntitiesUpdateProcessorFactory.java
- solr/modules/analysis-extras/src/test/org/apache/solr/analysis/TestFoldingMultitermExtrasQuery.java
- solr/modules/analysis-extras/src/test/org/apache/solr/schema/TestICUCollationField.java
- solr/modules/analysis-extras/src/test/org/apache/solr/schema/TestICUCollationFieldDocValues.java
- solr/modules/analysis-extras/src/test/org/apache/solr/schema/TestICUCollationFieldOptions.java
- solr/modules/analysis-extras/src/test/org/apache/solr/schema/TestICUCollationFieldUDVAS.java
- solr/modules/analysis-extras/src/test/org/apache/solr/update/processor/TestOpenNLPExtractNamedEntitiesUpdateProcessorFactory.java
https://issues.apache.org/jira/browse/SOLR-16033
> SOLR-16033: Enable spotless on analysis-extras module

- gradle/validation/spotless.gradle
- solr/modules/clustering/src/java/org/apache/solr/handler/clustering/ClusteringComponent.java
- solr/modules/clustering/src/java/org/apache/solr/handler/clustering/Engine.java
- solr/modules/clustering/src/java/org/apache/solr/handler/clustering/EngineContext.java
- solr/modules/clustering/src/java/org/apache/solr/handler/clustering/EngineEntry.java
- solr/modules/clustering/src/java/org/apache/solr/handler/clustering/EngineParameters.java
- solr/modules/clustering/src/java/org/apache/solr/handler/clustering/FlatKeysAttrVisitor.java
- solr/modules/clustering/src/java/org/apache/solr/handler/clustering/InputDocument.java
- solr/modules/clustering/src/java/org/apache/solr/handler/clustering/PathResourceLookup.java
- solr/modules/clustering/src/java/org/apache/solr/handler/clustering/package-info.java
- solr/modules/clustering/src/test/org/apache/solr/handler/clustering/ClusteringComponentDistributedTest.java
- solr/modules/clustering/src/test/org/apache/solr/handler/clustering/ClusteringComponentTest.java
- solr/modules/clustering/src/test/org/apache/solr/handler/clustering/EchoClusteringAlgorithm.java
- solr/modules/clustering/src/test/org/apache/solr/handler/clustering/EchoClusteringAlgorithmProvider.java
- solr/modules/clustering/src/test/org/apache/solr/handler/clustering/MockClusteringAlgorithm.java
- solr/modules/clustering/src/test/org/apache/solr/handler/clustering/ResourceCheckAlgorithm.java
- solr/modules/clustering/src/test/org/apache/solr/handler/clustering/SampleData.java
https://issues.apache.org/jira/browse/SOLR-16034
> SOLR-16034: Enable spotless on clustering module

- gradle/validation/spotless.gradle
- solr/modules/extraction/src/java/org/apache/solr/handler/extraction/ExtractingDocumentLoader.java
- solr/modules/extraction/src/java/org/apache/solr/handler/extraction/ExtractingMetadataConstants.java
- solr/modules/extraction/src/java/org/apache/solr/handler/extraction/ExtractingParams.java
- solr/modules/extraction/src/java/org/apache/solr/handler/extraction/ExtractingRequestHandler.java
- solr/modules/extraction/src/java/org/apache/solr/handler/extraction/ParseContextConfig.java
- solr/modules/extraction/src/java/org/apache/solr/handler/extraction/RegexRulesPasswordProvider.java
- solr/modules/extraction/src/java/org/apache/solr/handler/extraction/SolrContentHandler.java
- solr/modules/extraction/src/java/org/apache/solr/handler/extraction/SolrContentHandlerFactory.java
- solr/modules/extraction/src/java/org/apache/solr/handler/extraction/XLSXResponseWriter.java
- solr/modules/extraction/src/java/org/apache/solr/handler/extraction/package-info.java
- solr/modules/extraction/src/test/org/apache/solr/handler/extraction/ExtractingRequestHandlerTest.java
- solr/modules/extraction/src/test/org/apache/solr/handler/extraction/ParseContextConfigTest.java
- solr/modules/extraction/src/test/org/apache/solr/handler/extraction/TestXLSXResponseWriter.java
https://issues.apache.org/jira/browse/SOLR-16027
> SOLR-16027: Enable spotless on extraction module

- gradle/validation/spotless.gradle
- solr/modules/scripting/src/java/org/apache/solr/scripting/package-info.java
- solr/modules/scripting/src/java/org/apache/solr/scripting/update/ScriptEngineCustomizer.java
- solr/modules/scripting/src/java/org/apache/solr/scripting/update/ScriptUpdateProcessorFactory.java
- solr/modules/scripting/src/java/org/apache/solr/scripting/update/package-info.java
- solr/modules/scripting/src/java/org/apache/solr/scripting/xslt/TransformerProvider.java
- solr/modules/scripting/src/java/org/apache/solr/scripting/xslt/XSLTConstants.java
- solr/modules/scripting/src/java/org/apache/solr/scripting/xslt/XSLTResponseWriter.java
- solr/modules/scripting/src/java/org/apache/solr/scripting/xslt/XSLTUpdateRequestHandler.java
- solr/modules/scripting/src/java/org/apache/solr/scripting/xslt/package-info.java
- solr/modules/scripting/src/test/org/apache/solr/scripting/update/ScriptEngineTest.java
- solr/modules/scripting/src/test/org/apache/solr/scripting/update/ScriptUpdateProcessorFactoryTest.java
- solr/modules/scripting/src/test/org/apache/solr/scripting/update/TestBadScriptingUpdateProcessorConfig.java
- solr/modules/scripting/src/test/org/apache/solr/scripting/xslt/XSLTOutputWriterTest.java
- solr/modules/scripting/src/test/org/apache/solr/scripting/xslt/XSLTUpdateRequestHandlerTest.java
https://issues.apache.org/jira/browse/SOLR-16030
> SOLR-16030: Enable spotless on scripting module

- gradle/validation/spotless.gradle
- solr/modules/gcs-repository/src/java/org/apache/solr/gcs/GCSBackupRepository.java
- solr/modules/gcs-repository/src/java/org/apache/solr/gcs/GCSConfigParser.java
- solr/modules/gcs-repository/src/java/org/apache/solr/gcs/package-info.java
- solr/modules/gcs-repository/src/test/org/apache/solr/gcs/ConcurrentDelegatingStorage.java
- solr/modules/gcs-repository/src/test/org/apache/solr/gcs/GCSBackupRepositoryTest.java
- solr/modules/gcs-repository/src/test/org/apache/solr/gcs/GCSIncrementalBackupTest.java
- solr/modules/gcs-repository/src/test/org/apache/solr/gcs/LocalStorageGCSBackupRepository.java
https://issues.apache.org/jira/browse/SOLR-16026
> SOLR-16026: Enable spotless on gcs-repository module

- gradle/validation/spotless.gradle
https://issues.apache.org/jira/browse/SOLR-14920
> SOLR-14920: Remove solr-ref-guide from spotless exclusion

- solr/solr-ref-guide/modules/upgrade-notes/pages/major-changes-in-solr-9.adoc
https://issues.apache.org/jira/browse/SOLR-15904
> SOLR-15904: Add SQL module to major-change-in-solr-9.adoc

- solr/solr-ref-guide/modules/deployment-guide/pages/backup-restore.adoc
- solr/solr-ref-guide/modules/deployment-guide/pages/collection-management.adoc
https://issues.apache.org/jira/browse/SOLR-16021
> SOLR-16021: Improve docs for S3 location option

- solr/core/src/test/org/apache/solr/core/TestLazyCores.java
https://issues.apache.org/jira/browse/SOLR-15964
> SOLR-15964: Fix test; use latch instead of a sleep

- solr/distribution/build.gradle
https://issues.apache.org/jira/browse/SOLR-15952
I factored this out into a separate commit on its original JIRA
> SOLR-15952: Remove some remnants of the distZipTask, which was dead code

- solr/core/src/test/org/apache/solr/metrics/reporters/SolrJmxReporterTest.java
https://issues.apache.org/jira/browse/SOLR-16036
> SOLR-16036 Race condition in SolrJmxReporterTest

- solr/CHANGES.txt
- solr/modules/sql/src/java/org/apache/solr/handler/sql/CalciteSolrDriver.java
- solr/modules/sql/src/java/org/apache/solr/handler/sql/SolrFilter.java
- solr/modules/sql/src/java/org/apache/solr/handler/sql/functions/ArrayContains.java
- solr/modules/sql/src/java/org/apache/solr/handler/sql/functions/ArrayContainsAll.java
- solr/modules/sql/src/java/org/apache/solr/handler/sql/functions/ArrayContainsAny.java
- solr/modules/sql/src/java/org/apache/solr/handler/sql/functions/package-info.java
- solr/modules/sql/src/test/org/apache/solr/handler/sql/TestSQLHandler.java
Co-authored-by: Kiran Chitturi
https://issues.apache.org/jira/browse/SOLR-16009
Backport of #715
> SOLR-16009: Disable Calcite simplify config setting

- solr/solr-ref-guide/modules/deployment-guide/pages/taking-solr-to-production.adoc
https://issues.apache.org/jira/browse/SOLR-16054
> SOLR-16054: Better documentation of solr.environment property

- dev-tools/scripts/smokeTestRelease.py
https://issues.apache.org/jira/browse/SOLR-16076
> SOLR-16076 Update smoke test for moved bin-test

- solr/core/build.gradle
- solr/server/build.gradle
https://issues.apache.org/jira/browse/SOLR-16072
> SOLR-16072: make solr.jetty metrics reappear again

- dev-tools/scripts/releaseWizard.yaml
https://issues.apache.org/jira/browse/SOLR-15852
> SOLR-15852: Delete docker folder from staging repo before release

- solr/test-framework/src/java/org/apache/solr/SolrTestCaseJ4.java
https://issues.apache.org/jira/browse/SOLR-14290
Tested via picking an external plugin at random on solr.cool: https://github.com/solr-cool/solr-bmax-queryparser 
Did a little hacking to upgrade to 10.0.  Boom.  The fix looked obvious and the problem went away.  Still, there are other problems over there and I don't want to go doing a full upgrade of that plugin :-).
> SOLR-14290: Fix NPE by external users of SolrTestCaseJ4

- solr/CHANGES.txt
- solr/webapp/web/css/angular/common.css
- solr/webapp/web/index.html
https://issues.apache.org/jira/browse/SOLR-15652
Admin footer links have aged and need some love.
Update links where it makes sense, introduce a link to the community Slack channel as I suspect the split between IRC and Slack is 99% slack to 1% IRC ;-)
I wanted to add a "Slack" icon, but wasn't sure how to procure one, and what licensing ramifications might be, so I bailed on that.
Manual UI testing
- [ X] I have given Solr maintainers …
> SOLR-15652: Update Admin UI Footer Links

- solr/CHANGES.txt
- solr/webapp/web/js/angular/controllers/security.js
Backport of https://github.com/apache/solr/pull/741
> SOLR-16022: Enforce special character requirements on passwords with length less than 15

- solr/solr-ref-guide/modules/deployment-guide/pages/jwt-authentication-plugin.adoc
https://issues.apache.org/jira/browse/SOLR-16085
Trying to update my JWT settings, and ran into bug in ref guide
fix ref guide
> SOLR-16085: fix curl command, reformatting for easier reading

- solr/CHANGES.txt
- solr/solrj/src/java/org/apache/solr/common/SolrInputDocument.java
https://issues.apache.org/jira/browse/SOLR-16101
> SOLR-16101: Add empty constructor for SolrInputDocument

- solr/CHANGES.txt
- solr/solrj/src/java/org/apache/solr/common/SolrInputDocument.java
https://issues.apache.org/jira/browse/SOLR-16101
> SOLR-16101: Add empty constructor for SolrInputDocument (#746)

- solr/CHANGES.txt
- solr/solrj/src/java/org/apache/solr/common/SolrInputDocument.java
https://issues.apache.org/jira/browse/SOLR-16101
> SOLR-16101: Add empty constructor for SolrInputDocument (#746) (#751)

- solr/CHANGES.txt
https://issues.apache.org/jira/browse/SOLR-15590
Just the changes entry, then the JIRA can be closed
> SOLR-15590: Changes entry for 9.0

- build.gradle
- gradle/validation/forbidden-apis/com.google.guava.guava.all.txt
- gradle/validation/forbidden-apis/commons-codec.commons-codec.all.txt
- gradle/validation/forbidden-apis/commons-io.commons-io.all.txt
- gradle/validation/forbidden-apis/defaults.all.txt
- gradle/validation/forbidden-apis/defaults.tests.txt
- gradle/validation/forbidden-apis/javax.servlet.javax.servlet-api.solr.txt
- solr/CHANGES.txt
This also cleans up signatures files to make use of new wildcard method signatures feature.
I did not open an issue as this is trivial and is more build maintenance. I will commit this to 9x and main branch. I can also backport to 9.0, opinions?
> Upgrade forbiddenapis to version 3.3

- solr/docker/tests/cases/prometheus-exporter/test.sh
https://issues.apache.org/jira/browse/SOLR-14401
Changes the test to look for another metric line, now passes
> SOLR-14401 Fix docker test for prometheus-exporter

- dev-tools/scripts/releaseWizard.yaml
- solr/docker/templates/Dockerfile.official.header.template
From what I can tell looking at the releaseWizard steps, these should be the eventual artifact locations for Solr, but please check it for me!
Also if you can check the releaseWizard @janhoy , that part is kind of hard for me to check.
> Fix official dockerfile sources and add build steps to RC message

- solr/solr-ref-guide/modules/getting-started/pages/solr-tutorial.adoc
- solr/solr-ref-guide/modules/getting-started/pages/tutorial-diy.adoc
- solr/solr-ref-guide/modules/getting-started/pages/tutorial-films.adoc
- solr/solr-ref-guide/modules/getting-started/pages/tutorial-techproducts.adoc
https://issues.apache.org/jira/browse/SOLR-16125
> SOLR-16125 Make tutorial commands copyable

- solr/prometheus-exporter/conf/solr-exporter-config.xml
- solr/prometheus-exporter/src/test-files/conf/prometheus-solr-exporter-integration-test-config.xml
…ication_master as solr_metrics_core_replication_leader
https://issues.apache.org/jira/browse/SOLR-14702
https://issues.apache.org/jira/browse/SOLR-16128
> SOLR-14702 / SOLR-16128: Rename prometheus key *_master -> *_leader

- solr/core/src/java/org/apache/solr/core/ConfigSetService.java
- solr/packaging/build.gradle
- solr/packaging/test/bats_helper.bash
- solr/packaging/test/test_auth.bats
- solr/packaging/test/test_bats.bats
- solr/packaging/test/test_create_collection.bats
- solr/packaging/test/test_delete_collection.bats
- solr/packaging/test/test_help.bats
- solr/packaging/test/test_modules.bats
- solr/packaging/test/test_start_solr.bats
Also fix logging for configSet, noticed that the directories specified were wrong when I was getting test failures.
> SOLR-16143: Fix integration test cleanup & bats tmp directory

- solr/CHANGES.txt
- solr/bin/solr
- solr/core/src/java/org/apache/solr/core/ConfigSetService.java
- solr/core/src/java/org/apache/solr/core/SolrConfig.java
- solr/core/src/test-files/solr/configsets/_default/conf/managed-schema.xml
- solr/core/src/test-files/solr/configsets/_default/conf/solrconfig.xml
- solr/core/src/test/org/apache/solr/util/MultipleManagedSchemasTest.java
- solr/packaging/build.gradle
- solr/packaging/test/README.md
- solr/packaging/test/bats_helper.bash
- solr/packaging/test/test_auth.bats
- solr/packaging/test/test_bats.bats
- solr/packaging/test/test_create_collection.bats
- solr/packaging/test/test_delete_collection.bats
- solr/packaging/test/test_help.bats
- solr/packaging/test/test_modules.bats
- solr/packaging/test/test_start_solr.bats
https://issues.apache.org/jira/browse/SOLR-16143
Also includes integration test fixes that led to finding this bug.
> SOLR-16143 SolrConfig ResourceProvider can miss updates from ZooKeeper

- solr/solr-ref-guide/README.adoc
- solr/solr-ref-guide/antora.template.yml
- solr/solr-ref-guide/antora.yml
- solr/solr-ref-guide/build.gradle
https://issues.apache.org/jira/browse/SOLR-16159
> SOLR-16159: Add prerelease suffixes to non-released ref-guide versions.

- dev-tools/scripts/smokeTestRelease.py
https://issues.apache.org/jira/browse/SOLR-16133
> SOLR-16133 Use tempfile module in smoketester

- solr/core/src/test/org/apache/solr/schema/TestBulkSchemaConcurrent.java
https://issues.apache.org/jira/browse/SOLR-16174
> SOLR-16174: Modernize TestBulkSchemaConcurrent

- solr/core/src/java/org/apache/solr/search/facet/FacetFieldProcessorByEnumTermsStream.java
See: [SOLR-16176](https://issues.apache.org/jira/browse/SOLR-16176)
> SOLR-16176: Never apply facet overrequest in the case where limit:-1

- NOTICE.txt
- gradle/validation/rat-sources.gradle
- solr/benchmark/README.md
- solr/modules/analysis-extras/README.md
- solr/modules/clustering/README.md
- solr/modules/clustering/src/test-files/clustering/solr/collection1/conf/schema.xml
- solr/modules/extraction/README.md
- solr/modules/gcs-repository/README.md
- solr/modules/hadoop-auth/README.md
- solr/modules/hdfs/README.md
- solr/modules/jaegertracer-configurator/README.md
- solr/modules/jwt-auth/README.md
- solr/modules/langid/README.md
- solr/modules/ltr/README.md
- solr/modules/ltr/example/README.md
- solr/modules/s3-repository/README.md
- solr/modules/scripting/README.md
- solr/modules/sql/README.md
- solr/prometheus-exporter/README.md
- solr/solr-ref-guide/antora.template.yml
- solr/solr-ref-guide/antora.yml
- solr/solr-ref-guide/modules/configuration-guide/config-nav.adoc
- solr/solr-ref-guide/modules/deployment-guide/deployment-nav.adoc
- solr/solr-ref-guide/modules/getting-started/getting-started-nav.adoc
- solr/solr-ref-guide/modules/indexing-guide/indexing-nav.adoc
- solr/solr-ref-guide/modules/query-guide/querying-nav.adoc
- solr/solr-ref-guide/modules/upgrade-notes/upgrade-nav.adoc
- solr/solr-ref-guide/playbook.template.yml
- solr/test-framework/README.md
https://issues.apache.org/jira/browse/SOLR-16177
> SOLR-16177 Fix License Headers and Rat Check

- solr/modules/jwt-auth/src/java/org/apache/solr/security/jwt/JWTVerificationkeyResolver.java
> Fix typo in JWTVerificationkeyResolver exception message

- solr/solr-ref-guide/modules/query-guide/pages/terms-component.adoc
https://issues.apache.org/jira/browse/SOLR-16179
terms.fl can be specified in the query multiple times, which is not clear from the documentation.
Added the respective documentation with examples in JSON and XML
Reviewed the created doc with asciidoctor and verified the changes.
- [x ] I have added documentation for the [Reference Guide](https://github.com/apache/solr/tree/main/solr/solr-ref-guide)
> SOLR-16179 : Updated the documentation as reported in the ticket , along with the examples

- solr/solrj/src/java/org/apache/solr/client/solrj/impl/CloudSolrClient.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/CloudSolrClientCacheTest.java
https://issues.apache.org/jira/browse/SOLR-16185
> SOLR-16185: CloudSolrClientCacheTest leaks threads

- solr/solr-ref-guide/modules/upgrade-notes/pages/major-changes-in-solr-9.adoc
Revert of change from https://github.com/apache/solr/pull/851#discussion_r870212878
May add other commits to this PR as well...
> Further polish for "Major changes in 9" page

- solr/CHANGES.txt
- solr/modules/sql/src/java/org/apache/solr/handler/sql/SolrFilter.java
- solr/modules/sql/src/test/org/apache/solr/handler/sql/TestSQLHandler.java
backport of https://github.com/apache/solr/pull/870
> SOLR-16199: Improve handling of LIKE queries with wildcard (#870)

- solr/solr-ref-guide/modules/query-guide/pages/json-facet-api.adoc
- solr/solr-ref-guide/modules/query-guide/pages/stream-decorator-reference.adoc
- solr/solr-ref-guide/modules/query-guide/pages/stream-evaluator-reference.adoc
No JIRA ticket as yet, and perhaps not needed either?
> solr-ref-guide: expand 'eval' streaming expression example; fix a few typos;

- solr/core/src/test/org/apache/solr/core/TestCoreDiscovery.java
https://issues.apache.org/jira/browse/SOLR-16104
> SOLR-16104: TestCoreDiscovery.testTooManyTransientCores() to use retryUntil logic

- solr/core/src/java/org/apache/solr/core/CoreContainer.java
https://issues.apache.org/jira/browse/SOLR-13858
@sigram FYI - can you confirm that this was done? I looked through the code and got the impression that it was, but wanted to double check before removing the TODO
> SOLR-13858: Remove obsolete comment

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/update/processor/DistributedUpdateProcessor.java
- solr/core/src/test/org/apache/solr/update/TestInPlaceUpdatesStandalone.java
Co-authored-by: Lamine Idjeraoui <lidjeraoui@apple.com>
https://issues.apache.org/jira/browse/SOLR-16218
> SOLR-16218: Fix bug in in-place update when failOnVersionConflicts=false (#898)

- solr/core/src/java/org/apache/solr/api/ApiBag.java
- solr/core/src/java/org/apache/solr/api/V2HttpCall.java
- solr/core/src/java/org/apache/solr/cloud/OverseerTaskProcessor.java
- solr/core/src/java/org/apache/solr/cloud/overseer/SliceMutator.java
- solr/core/src/java/org/apache/solr/core/InitParams.java
- solr/core/src/java/org/apache/solr/core/SolrResourceLoader.java
- solr/core/src/java/org/apache/solr/core/TransientSolrCoreCacheFactory.java
- solr/core/src/java/org/apache/solr/handler/RequestHandlerBase.java
- solr/core/src/java/org/apache/solr/handler/admin/CollectionsHandler.java
- solr/core/src/java/org/apache/solr/schema/IndexSchema.java
- solr/core/src/java/org/apache/solr/security/BasicAuthPlugin.java
- solr/core/src/java/org/apache/solr/security/Permission.java
- solr/core/src/java/org/apache/solr/security/Sha256AuthenticationProvider.java
- solr/core/src/java/org/apache/solr/util/ExportTool.java
- solr/core/src/java/org/apache/solr/util/configuration/providers/AbstractSSLCredentialProvider.java
- solr/core/src/java/org/apache/solr/util/configuration/providers/EnvSSLCredentialProvider.java
- solr/core/src/test/org/apache/solr/TestCrossCoreJoin.java
- solr/core/src/test/org/apache/solr/cloud/TestConfigSetsAPI.java
- solr/core/src/test/org/apache/solr/cloud/TestLockTree.java
- solr/core/src/test/org/apache/solr/util/configuration/providers/EnvSSLCredentialProviderTest.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/CloudSolrClientCacheTest.java
- solr/solrj/src/test/org/apache/solr/common/cloud/TestPerReplicaStates.java
- solr/solrj/src/test/org/apache/solr/common/util/TestPathTrie.java
- solr/solrj/src/test/org/apache/solr/common/util/TestValidatingJsonMap.java
https://issues.apache.org/jira/browse/SOLR-15528
> SOLR-15528: guava collections replaced with JDK equiv

- solr/solr-ref-guide/modules/deployment-guide/pages/installing-solr.adoc
> Spelling correction

- solr/solr-ref-guide/modules/deployment-guide/pages/backup-restore.adoc
Fix typo as per jira/SOLR-16261
> SOLR-16261: fix typo in backup-restore.adoc in solr-ref-guide

- solr/core/src/test/org/apache/solr/TestRandomDVFaceting.java
- solr/core/src/test/org/apache/solr/cloud/DistributedVersionInfoTest.java
- solr/core/src/test/org/apache/solr/cloud/OverseerCollectionConfigSetProcessorTest.java
- solr/core/src/test/org/apache/solr/cloud/SegmentTerminateEarlyTestState.java
- solr/core/src/test/org/apache/solr/cloud/TestCloudPhrasesIdentificationComponent.java
- solr/core/src/test/org/apache/solr/cloud/TestCloudPseudoReturnFields.java
- solr/core/src/test/org/apache/solr/cloud/TestRandomFlRTGCloud.java
- solr/core/src/test/org/apache/solr/cloud/TestStressCloudBlindAtomicUpdates.java
- solr/core/src/test/org/apache/solr/cloud/TestStressInPlaceUpdates.java
- solr/core/src/test/org/apache/solr/cloud/TestTolerantUpdateProcessorRandomCloud.java
- solr/core/src/test/org/apache/solr/handler/DocumentAnalysisRequestHandlerTest.java
- solr/core/src/test/org/apache/solr/handler/component/TestDistributedStatsComponentCardinality.java
- solr/core/src/test/org/apache/solr/handler/component/TestPivotHelperCode.java
- solr/core/src/test/org/apache/solr/index/WrapperMergePolicyFactoryTest.java
- solr/core/src/test/org/apache/solr/response/JSONWriterTest.java
- solr/core/src/test/org/apache/solr/response/SmileWriterTest.java
- solr/core/src/test/org/apache/solr/schema/TestPointFields.java
- solr/core/src/test/org/apache/solr/search/AnalyticsMergeStrategyTest.java
- solr/core/src/test/org/apache/solr/search/AnalyticsTestQParserPlugin.java
- solr/core/src/test/org/apache/solr/search/SolrIndexSearcherTest.java
- solr/core/src/test/org/apache/solr/search/TestBlockCollapse.java
- solr/core/src/test/org/apache/solr/search/TestFilteredDocIdSet.java
- solr/core/src/test/org/apache/solr/search/TestRecovery.java
- solr/core/src/test/org/apache/solr/update/SolrIndexConfigTest.java
- solr/core/src/test/org/apache/solr/update/VersionInfoTest.java
- solr/core/src/test/org/apache/solr/update/processor/CategoryRoutedAliasUpdateProcessorTest.java
- solr/core/src/test/org/apache/solr/update/processor/IgnoreCommitOptimizeUpdateProcessorFactoryTest.java
- solr/core/src/test/org/apache/solr/update/processor/RoutedAliasUpdateProcessorTest.java
- solr/core/src/test/org/apache/solr/util/SolrPluginUtilsTest.java
https://issues.apache.org/jira/browse/SOLR-16281
boxing/unboxing has been improved since Java 5!
Apply suggestiosn!
> SOLR-16281: review boxing unboxing

- help/formatting.txt
https://issues.apache.org/jira/browse/SOLR-16294
update to current state of solr.
text change
> SOLR-16294: update formatting.txt

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/core/QuerySenderListener.java
- solr/core/src/test/org/apache/solr/core/QuerySenderListenerTest.java
- solr/core/src/test/org/apache/solr/core/TestSolrConfigHandler.java
- solr/solr-ref-guide/modules/configuration-guide/pages/caches-warming.adoc
https://issues.apache.org/jira/browse/SOLR-9359
Enable the Config API to be used to manage warming queries.
This update makes the class inspect the configuration it receives and decide between two ways to handle it.
(See also https://github.com/apache/lucene-solr/pull/2643.)
Unit test included for the new `convertQueriesToList` method, and an integration test for config upload.
> SOLR-9359: Make Config API work for warming queries

- solr/solrj/src/test/org/apache/solr/client/solrj/io/stream/StreamDecoratorTest.java
Noticed as part of https://issues.apache.org/jira/browse/SOLR-16286 -- please see code comments for details.
> SOLR-16286: simplify StreamDecoratorTest.test[Parallel]PriorityStream

- solr/solr-ref-guide/modules/indexing-guide/pages/reindexing.adoc
Added a mention of it under the Index to Another Collection strategy.
> Mention REINDEXCOLLECTION in Reindexing docs

- solr/core/src/java/org/apache/solr/core/SolrXmlConfig.java
- solr/core/src/test/org/apache/solr/core/TestSolrXml.java
[SOLR-16366](https://issues.apache.org/jira/browse/SOLR-16366)
> SOLR-16366: Avoid using XPath in SolrXmlConfig

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/search/CaffeineCache.java
- solr/core/src/test/org/apache/solr/search/TestCaffeineCache.java
SOLR-16357 CaffeineCache ramBytes incorrect accounting on updates and deletes
2 problematic scenarios:
* updates over existing value will double-add the key
* deletes will double-delete: once due to manual bookkeeping in the remove method and second due to the onRemoval callback
I also removed metricNames variable because it looked unused. Can rollback this change if needed.
https://issues.apache.org/jira/browse/SOLR-16357
CaffeineCache ramBytes accounting is incorrect on deletes and updates over exiting values.
Updated ramBytes tracking code.
Added basic tests for tracking changes to ramBytes value
> SOLR-16357 CaffeineCache ramBytes incorrect accounting on updates and deletes

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/MoreLikeThisHandler.java
- solr/core/src/test/org/apache/solr/handler/MoreLikeThisHandlerTest.java
Just a no brainer fix with a shallow test coverage. I'm not sure who need this standalone handler still.
> SOLR-7883: /mlt handler to support facets

- solr/solr-ref-guide/modules/upgrade-notes/pages/solr-upgrade-notes.adoc
https://issues.apache.org/jira/browse/SOLR-16192
> SOLR-16192: Upgrade notes for ZK Injectors

- solr/core/src/java/org/apache/solr/search/Grouping.java
https://issues.apache.org/jira/browse/SOLR-16413
> SOLR-16413: shorten long Grouping.searchWithTimeLimiter warnings

- build.gradle
- solr/CHANGES.txt
> Upgrade forbiddenapis to 3.4

- solr/solr-ref-guide/modules/deployment-guide/pages/taking-solr-to-production.adoc
NO ISSUE
I've found a [typo](https://github.com/apache/solr/blame/main/solr/solr-ref-guide/modules/deployment-guide/pages/taking-solr-to-production.adoc#L368) on the docs at the [Ulimit Settings section on the Taking Solr to Production page](https://solr.apache.org/guide/solr/latest/deployment-guide/taking-solr-to-production.html#ulimit-settings-nix-operating-systems).
Fix a typo and change the order of a sentence to make it more comfortable visually.
> Fix typo in the the Ulimit Settings section

- solr/CHANGES.txt
- solr/modules/sql/src/java/org/apache/solr/handler/sql/CalciteSolrDriver.java
- solr/modules/sql/src/resources/saffron.properties
- solr/solrj/src/java/org/apache/solr/client/solrj/io/sql/DriverImpl.java
https://issues.apache.org/jira/browse/SOLR-16433
> SOLR-16433: Security Manager prevents Solr SQL from working

- solr/CHANGES.txt
- solr/solrj/src/java/org/apache/solr/common/util/ContentStream.java
https://issues.apache.org/jira/browse/SOLR-11657
Deprecate ContentStream out of SolrJ
Annotated the class with @Deprecated annotation
Not required.
> SOLR-11657: Added @Deprecated annotation

- solr/solr-ref-guide/modules/indexing-guide/pages/reindexing.adoc
Fixed a few typos on the guid. as changes are very small I did not create a jira ticket.
> Fixed typos on reindexing guide page

- solr/solr-ref-guide/modules/deployment-guide/pages/taking-solr-to-production.adoc
NO ISSUE
> Because of the potential garbage collection issues and the particular issues that happen at 32GB, if a single instance would require a 64GB heap, performance is likely to improve greatly if the machine is set up with two nodes that each have a 31GB heap.
changed to
Because of the potential garbage collection issues and the particular issues that happen at 32GB, if a single instance would require a 64GB heap, performance is likely to improve greatly if the machine is set up with two nodes that each have a **32GB** heap.
Minor fix for the calculation mistake
No
> Fix wording in taking-solr-to-production.adoc

- solr/licenses/semver4j-LICENSE-MIT.txt
#515 follow-up:
```
wget https://raw.githubusercontent.com/semver4j/semver4j/v2.1.1/LICENSE
mv LICENSE solr/licenses/semver4j-LICENSE-MIT.txt
```
> SOLR-15854: (java-semver-->semver4j)-LICENSE-MIT.txt rename follow-up

- solr/CHANGES.txt
- solr/packaging/build.gradle
- solr/packaging/test/bats_helper.bash
https://issues.apache.org/jira/browse/SOLR-16481
> SOLR-16481: Upgrade Bats to 1.8.0

- solr/solr-ref-guide/modules/deployment-guide/pages/solr-in-docker.adoc
Found a typo in the Solr in Docker page
Fix the typo from "do no" to "do not" in the Solr in docker page
> Fix typo from "do no" to "do not" in the solr in docker page

- solr/CHANGES.txt
- solr/docker/build.gradle
https://issues.apache.org/jira/browse/SOLR-16486
More discussion can be found in https://github.com/apache/solr-docker/pull/13
Also fixed header for CHANGES
> SOLR-16486: Pin OS Variant for Docker image

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/component/HttpShardHandlerFactory.java
https://issues.apache.org/jira/browse/SOLR-16485
> SOLR-16485: Fix NPE in ShardHandlerFactory for standalone

- solr/CHANGES.txt
- solr/core/build.gradle
- solr/core/src/java/org/apache/solr/servlet/LoadAdminUiServlet.java
https://issues.apache.org/jira/browse/SOLR-16476
> SOLR-16476: Remove commons-text dependency from solr-core

- solr/core/src/java/org/apache/solr/update/DirectUpdateHandler2.java
https://issues.apache.org/jira/browse/SOLR-16363
Follow on to https://github.com/apache/solr/pull/1121 that I merged too soon by mistake.
> SOLR-16363: DirectUpdateHandler2 remove String.format from error logging

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cloud/ZkController.java
https://issues.apache.org/jira/browse/SOLR-14679
> SOLR-14679: Fix evergrowing tlogs on TLOG replicas

- solr/solr-ref-guide/modules/deployment-guide/pages/cluster-types.adoc
Typo
Fix it with better grammar
> Fix typo in the user-managed mode explanation

- solr/core/src/test/org/apache/solr/metrics/JvmMetricsTest.java
https://issues.apache.org/jira/browse/SOLR-16501
> SOLR-16501: Fix JvmMetricsTest NPE

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/admin/LukeRequestHandler.java
- solr/core/src/test-files/solr/collection1/conf/schema12.xml
- solr/core/src/test/org/apache/solr/handler/admin/LukeRequestHandlerTest.java
https://issues.apache.org/jira/browse/SOLR-16293
> SOLR-16293: Luke request fails for document with a binary field

- dev-tools/scripts/releaseWizard.py
- dev-tools/scripts/releaseWizard.yaml
- gradle/maven/defaults-maven.gradle
Also make the release wizard work. It is currently broken with respect to GPG signing.
> Fix useGpg signing without password

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/component/SortedNumericStatsValues.java
- solr/core/src/test/org/apache/solr/handler/component/TestDistributedStatsComponentCardinality.java
https://issues.apache.org/jira/browse/SOLR-10918
> SOLR-10918: Fix IntPointField hashing for HLL

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/core/SolrCore.java
- solr/core/src/java/org/apache/solr/rest/RestManager.java
- solr/core/src/test/org/apache/solr/rest/TestRestManager.java
- solr/test-framework/src/java/org/apache/solr/util/RestTestBase.java
- solr/test-framework/src/java/org/apache/solr/util/RestTestHarness.java
https://issues.apache.org/jira/browse/SOLR-16274
> SOLR-16274: HEAD request for managed resource returns 500 Server Error

- solr/solr-ref-guide/modules/getting-started/pages/introduction.adoc
https://issues.apache.org/jira/browse/SOLR-16495
> SOLR-16495 - new text for introduction to solr page.

- solr/solr-ref-guide/modules/getting-started/pages/introduction.adoc
> SOLR-16495 - new text for introduction to solr page. (#1130)

- solr/test-framework/src/java/org/apache/solr/cloud/api/collections/AbstractIncrementalBackupTest.java
https://issues.apache.org/jira/browse/SOLR-16511
> SOLR-16511: Fix key in AbstractIncrementalBackupTest.corruptIndexFiles

- solr/CHANGES.txt
- solr/solr-ref-guide/modules/configuration-guide/pages/implicit-requesthandlers.adoc
- solr/solr-ref-guide/modules/configuration-guide/pages/system-info-handler.adoc
https://issues.apache.org/jira/browse/SOLR-13626
This is work that was done in the old shared lucene-solr repo https://github.com/apache/lucene-solr/pull/802 by @tonycoz.
Add missing documentation for /admin/info/system which implicit-requesthandlers currently links to a 404
Provide some basic documentation.
built ref guide
> SOLR-13626: document the SystemInfoHandler

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/security/RuleBasedAuthorizationPluginBase.java
- solr/core/src/test/org/apache/solr/security/BaseTestRuleBasedAuthorizationPlugin.java
https://issues.apache.org/jira/browse/SOLR-16527
Intra-node communication will have no roles attached, a null 'roles' set will trigger a NPE in the RuleBasedAuthorizationPluginBase#getPermissionNamesForRoles method.
Added a null guard.
Added test for null set
> SOLR-16527 RuleBasedAuthorizationPluginBase NPE

- dev-tools/scripts/smokeTestRelease.py
https://issues.apache.org/jira/browse/SOLR-16132
> SOLR-16132: Stop gpg-agent after use

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/search/QParserPlugin.java
- solr/core/src/java/org/apache/solr/search/mlt/AbstractMLTQParser.java
- solr/core/src/java/org/apache/solr/search/mlt/CloudMLTQParser.java
- solr/core/src/java/org/apache/solr/search/mlt/MLTContentQParserPlugin.java
- solr/core/src/java/org/apache/solr/search/mlt/SimpleMLTQParser.java
- solr/core/src/test/org/apache/solr/search/QueryEqualityTest.java
- solr/core/src/test/org/apache/solr/search/mlt/CloudMLTQContentParserTest.java
- solr/core/src/test/org/apache/solr/search/mlt/CloudMLTQParserTest.java
- solr/core/src/test/org/apache/solr/search/mlt/SimpleMLTContentQParserTest.java
- solr/core/src/test/org/apache/solr/search/mlt/SimpleMLTQParserTest.java
- solr/solr-ref-guide/modules/query-guide/pages/morelikethis.adoc
https://issues.apache.org/jira/browse/SOLR-16420
~TODO: add cloud test and equality test, if necessary and indent the code~  **Done**.
One question: `mindf` default for cloud test is 0 in code now that contradicts to the ref guide - 5. This PR sets default mindf to 5. It is a good idea to fix it by the PR?
> SOLR-16420: {!mlt_content}

- solr/solr-ref-guide/modules/query-guide/pages/stream-source-reference.adoc
> SOLR-16420: update stream ref guide about mindf=5 default

- dev-docs/lucene-upgrade.md
https://issues.apache.org/jira/browse/SOLR-16442
> SOLR-16442: git mechanics for 'gradlew updateLicenses' in lucene-upgrade.md

- gradle/validation/error-prone.gradle
This ports https://github.com/apache/lucene/pull/11971 to Solr and builds on https://github.com/apache/solr/pull/1200
> Disable useless errorprone checks

- .github/workflows/bin-solr-test.yml
- solr/packaging/test/test_start_solr.bats
https://issues.apache.org/jira/browse/SOLR-16584
> SOLR-16584 BATS test fails stopping two instances

- solr/CHANGES.txt
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/LBHttp2SolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/LBHttpSolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/LBSolrClient.java
https://issues.apache.org/jira/browse/SOLR-10461
I believe I found the reason tests are failing, looks to be https://github.com/apache/solr/pull/1217. the builder will always set the value to 0 (https://github.com/apache/solr/pull/1217/files#diff-d5404e29026104a2965fb5d5d1a9857d406b7ade5165ec4c2dc7b16e32fdabccR185), instead of the default value being picked up as before (https://github.com/apache/solr/pull/1217/files#diff-8a5ab47986f979f1134864e1352f6617e8d425f756018da7e0c1fa191fcc8fafR81) so it's basically overriding the default. Solution is to move the default value to the builder so it would set to the correct default if this is not already set by the client.
Set correct defaults on builder.
Please describe the tests you've developed or run to confirm this patch implements the feature …
> SOLR-10461: move setAliveCheckInterval from clients into Builder

- solr/CHANGES.txt
- solr/modules/jaegertracer-configurator/README.md
- solr/modules/jaegertracer-configurator/src/java/org/apache/solr/jaeger/JaegerTracerConfigurator.java
- solr/solr-ref-guide/modules/deployment-guide/pages/distributed-tracing.adoc
- solr/solr-ref-guide/modules/upgrade-notes/pages/major-changes-in-solr-9.adoc
https://issues.apache.org/jira/browse/SOLR-16534
> SOLR-16534 Deprecate Jaegertracer-Configurator

- NOTICE.txt
> Update copyright year in NOTICE.txt file.

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/search/CollapsingQParserPlugin.java
- solr/core/src/test/org/apache/solr/search/TestCollapseQParserPlugin.java
https://issues.apache.org/jira/browse/SOLR-16611 
Changed uninvertingReader#getSorted so that it does not return null.  
Added unit test for no docs.
The test now succeeds, but the code before the change fails.
> SOLR-16611: fix collapse hint=top_fc bug

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/search/CollapsingQParserPlugin.java
- solr/core/src/test/org/apache/solr/search/TestCollapseQParserPlugin.java
* fixed collapse top_fc getSorted
Co-authored-by: Mikhail Khludnev <mkhl@apache.org>
https://issues.apache.org/jira/browse/SOLR-16611
cc @metapox , fyi
> SOLR-16611: fix collapse hint=top_fc bug (#1274)

- solr/core/src/test/org/apache/solr/cloud/TestRandomFlRTGCloud.java
Followup on a2f3f7f33efd765cc6c608c78745d8b9c108b8df
See: #1276
> Add a trivial validator for the new CoreAugmenter transformer

- solr/bin/solr
- solr/docker/templates/Dockerfile.body.template
https://issues.apache.org/jira/browse/SOLR-16457
> SOLR-16457: Use pwd -P

- solr/core/src/java/org/apache/solr/search/DocSetBuilder.java
- solr/core/src/java/org/apache/solr/search/DocSetUtil.java
https://issues.apache.org/jira/browse/SOLR-16617
> SOLR-16617: DocSetBuilder should use DocSetUtil#smallSetSize

- build.gradle
- solr/CHANGES.txt
https://issues.apache.org/jira/browse/SOLR-16624
> SOLR-16624: Remove Gradle Groovy version override

- solr/modules/opentelemetry/src/java/org/apache/solr/opentelemetry/ClosableTracerShim.java
- solr/modules/opentelemetry/src/java/org/apache/solr/opentelemetry/OtelTracerConfigurator.java
- solr/modules/opentelemetry/src/test/org/apache/solr/opentelemetry/OtelTracerConfiguratorTest.java
https://issues.apache.org/jira/browse/SOLR-16532
I created a new PR where we can gather all followup cleanups that may arrive after the initial merge in #1168
> SOLR-16532 Further improvements to opentelemetry module

- solr/CHANGES.txt
- solr/webapp/web/js/angular/app.js
- solr/webapp/web/partials/index.html
https://issues.apache.org/jira/browse/SOLR-15772
I know I should have chosen some other class to get `text-align: left` and not put the style on the div tag, but I was too lazy to investigate what class might do that for me...
> SOLR-15772 More visible security warnings in Admin UI

- solr/core/src/java/org/apache/solr/handler/component/FacetComponent.java
Debugging FacetComponent I noticed two little things which can be improved
> Small code improvements in FacetComponent

- dev-tools/solr-missing-doclet/build.gradle
- gradle/documentation/documentation.gradle
- gradle/documentation/render-javadoc.gradle
- gradle/lucene-dev/lucene-dev-repo-composite.gradle
- gradle/validation/jar-checks.gradle
- gradle/validation/rat-sources.gradle
- gradle/validation/validate-source-patterns.gradle
- solr/solr-ref-guide/build.gradle
This is a followup to SOLR-15455 / #304
I'm happy to open a Jira issue for this if that would be helpful, or push to a branch that allows collaborative work.
In the course of exercising the joint Lucene/Solr local development workflow, a few opportunities for improvement presented themselves. I've separated these into logical commits. Some of these commits are more important than others; I think they're all good, but 87d041e9719b14d7b6a184d976fb88168fe4b8f2 and 64846a40af386b745e172b95577c260fbfcad8d7 in particular I'd say are just "nice to have" -- happy to revert them from this PR if anyone has a problem with them.
> Improvements to joint Lucene/Solr dev workflow

- solr/CHANGES.txt
- solr/solr-ref-guide/modules/upgrade-notes/pages/major-changes-in-solr-9.adoc
https://issues.apache.org/jira/browse/SOLR-15955
> SOLR-15955: Jetty 10.x upgrade notes

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/security/AllowListUrlChecker.java
- solr/core/src/test/org/apache/solr/security/AllowListUrlCheckerTest.java
https://issues.apache.org/jira/browse/SOLR-16631
Given that hostnames should be case insensitive (see [rfc3986;section-6.2.2.1](https://www.rfc-editor.org/rfc/rfc3986#section-6.2.2.1)), the check for should also consider hostnames in urls in a case insentive way.
hostPort checking is now ignoring the case
Changed existing tests with mixed cases in the host name
> SOLR-16631: solr.allowUrls - hostnames should be treated in case insensitive way

- solr/solr-ref-guide/modules/getting-started/pages/tutorial-five-minutes.adoc
Adds basic search example in tutorial-five-minutes file.
Added an example on how to search a document.
Output comes like:
```
curl 'http://localhost:8983/solr/techproducts/select?q=name%3Alightning'
{
"responseHeader":{
"zkConnected":true,
"status":0,
"QTime":0,
"params":{
"q":"name:lightning"}},
"response":{"numFound":1,"start":0,"numFoundExact":true,"docs":[
{
"id":"978-0641723445",
"cat":["book",
"hardcover"],
"name":"The Lightning Thief",
"author":["Rick Riordan"],
"series_t":"Percy Jackson and the Olympians",
"sequence_i":1,
"genre_s":"fantasy",
"inStock":true,
"price":12.5,
"pages_i":384,
"_version_":1757019285952135168}]
}}
```
Not needed
> Solve FIXME in tutorial-five-minutes

- solr/server/solr/configsets/_default/conf/solrconfig.xml
Co-authored-by: Renato Haeberli <>
> fix typo in comment (#1305)

- gradle/testing/defaults-tests.gradle
- gradle/testing/randomization.gradle
Updated inputs defined in `CommandLineArgumentProvider`s to use lazy file types. While usage of "eager" file types is not currently causing issues, it is generally preferred to use lazy file types where possible to defer file evaluation to execution time.
Replaced `File`s with their lazy counterparts: `Directory` and `RegularFile`
Build scan for these changes: https://scans.gradle.com/s/2rtoy5kx6cipa
N/A - this PR only updates build logic
> Gradle: Use lazy file types

- solr/CHANGES.txt
- solr/docker/build.gradle
- solr/docker/gradle-help.txt
- solr/solr-ref-guide/modules/upgrade-notes/pages/major-changes-in-solr-9.adoc
https://issues.apache.org/jira/browse/SOLR-16665
> SOLR-16665: Upgrade the base docker image to Ubuntu 22 (Jammy)

- solr/CHANGES.txt
- solr/solr-ref-guide/modules/upgrade-notes/pages/major-changes-in-solr-9.adoc
https://issues.apache.org/jira/browse/SOLR-15733
> SOLR-15733: Update CHANGES.txt and upgrade notes

- solr/CHANGES.txt
- solr/solr-ref-guide/modules/upgrade-notes/pages/major-changes-in-solr-9.adoc
* SOLR-15733: Update CHANGES.txt and upgrade notes
https://issues.apache.org/jira/browse/SOLR-15733
> SOLR-15733: Update CHANGES.txt and upgrade notes (#1368)

- solr/solr-ref-guide/modules/deployment-guide/pages/rule-based-authorization-plugin.adoc
https://issues.apache.org/jira/browse/SOLR-16671
Please feel free to suggest better wording.
> SOLR-16671: Explicitly call out library permissions for config-edit

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/core/CoreContainer.java
- solr/core/src/java/org/apache/solr/handler/admin/CoreAdminHandler.java
- solr/core/src/java/org/apache/solr/handler/admin/CoreAdminOperation.java
- solr/core/src/java/org/apache/solr/handler/admin/CreateSnapshotOp.java
- solr/core/src/java/org/apache/solr/handler/admin/DeleteSnapshotOp.java
- solr/core/src/java/org/apache/solr/handler/admin/api/CoreAdminAPIBase.java
- solr/core/src/java/org/apache/solr/handler/admin/api/CoreSnapshotAPI.java
- solr/core/src/java/org/apache/solr/handler/admin/api/SnapshotAPI.java
- solr/core/src/test/org/apache/solr/core/snapshots/TestSolrCoreSnapshots.java
- solr/core/src/test/org/apache/solr/handler/admin/StatsReloadRaceTest.java
- solr/core/src/test/org/apache/solr/handler/admin/api/CoreSnapshotAPITest.java
- solr/solr-ref-guide/modules/deployment-guide/pages/backup-restore.adoc
- solr/solrj/src/java/org/apache/solr/common/params/CoreAdminParams.java
https://issues.apache.org/jira/browse/SOLR-16462
This pull request implements V2 equivalent endpoints for the Snapshot API (Create, List, and Delete).
I created a SnapshotAPI class that houses new v2 implementations of the CreateSnapshot, ListSnapshot, and DeleteSnapshot operations. The SnapshotAPI endpoints were implemented using the Jersey JAX-RS reference implementation. The original CoreAdminOperation implementations were modified to call the new SnapshotAPI methods. The backup/restore reference documentation has been updated to show both V1 and V2 Snapshot API examples.
No new tests were added, but I would be willing to add some if needed. There are existing tests that check that both the coreName and commitName were passed into a given Snapshot operation. Since those values are now …
> SOLR-16462: Create v2 equivalent of v1 'CREATESNAPSHOT', 'LISTSNAPSHOT' and 'DELETESNAPSHOT' (core level)

- solr/CHANGES.txt
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/Http2SolrClient.java
https://issues.apache.org/jira/browse/SOLR-16668
Also added a bit of cleanup in the code.
> SOLR-16668: Default to Java SSL for Http2SolrClient

- solr/CHANGES.txt
- solr/modules/analytics/src/java/org/apache/solr/handler/component/AnalyticsComponent.java
- solr/solr-ref-guide/modules/configuration-guide/pages/requesthandlers-searchcomponents.adoc
- solr/solr-ref-guide/modules/query-guide/pages/analytics-expression-sources.adoc
- solr/solr-ref-guide/modules/query-guide/pages/analytics-mapping-functions.adoc
- solr/solr-ref-guide/modules/query-guide/pages/analytics-reduction-functions.adoc
- solr/solr-ref-guide/modules/query-guide/pages/analytics.adoc
- solr/solr-ref-guide/modules/upgrade-notes/pages/major-changes-in-solr-9.adoc
https://issues.apache.org/jira/browse/SOLR-16660
> SOLR-16660 Deprecate analytics component

- solr/core/src/test/org/apache/solr/search/TestCoordinatorRole.java
https://issues.apache.org/jira/browse/SOLR-16664
I started to look at `TestCoordinatorRole` and besides just adding the assertion to make sure docs is not null there are other confusing things in this test.
> SOLR-16664: TestCoordinatorRole fails docs is null

- solr/CHANGES.txt
- solr/bin/solr
- solr/bin/solr.cmd
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/Http2SolrClient.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/Http2SolrClientTest.java
https://issues.apache.org/jira/browse/SOLR-16679
> SOLR-16679: Fix solr.jetty.ssl.verifyClientHostName logging

- solr/solrj/src/test/org/apache/solr/client/solrj/SolrExampleTests.java
https://issues.apache.org/jira/browse/SOLR-16585
> SOLR-16585: examples test for match all paging

- solr/solrj/src/test/org/apache/solr/client/solrj/SolrExampleTests.java
https://issues.apache.org/jira/browse/SOLR-16585
> SOLR-16585: examples test for match all paging (#1378)

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/component/QueryComponent.java
- solr/core/src/test/org/apache/solr/cloud/TestCloudPseudoReturnFields.java
- solr/core/src/test/org/apache/solr/search/ReturnFieldsTest.java
- solr/core/src/test/org/apache/solr/search/TestPseudoReturnFields.java
https://issues.apache.org/jira/browse/SOLR-16681
https://lists.apache.org/thread/vrbsm8wy14t0xgfk0og3pkvj8s0123rd
> SOLR-16681: Throw exception when attempting to replace uniqueKey via fl in distributed request

- solr/solrj/src/test/org/apache/solr/client/solrj/SolrExampleTests.java
https://issues.apache.org/jira/browse/SOLR-16585
> SOLR-16585: bypass empty update

- solr/solrj/src/java/org/apache/solr/client/solrj/impl/Http2SolrClient.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/Http2SolrClientTest.java
https://issues.apache.org/jira/browse/SOLR-16638
Fixing Http2SolrClient's exception message when serverBaseUrl is null
Instead of using the nullable serverBaseUrl, I am using the request data, this should reflect the actual request that caused the exception in the message.
Before change:
```
org.apache.solr.client.solrj.impl.BaseHttpSolrClient$RemoteSolrException: Error from server at null: Expected mime type in [application/octet-stream, application/vnd.apache.solr.javabin] but got text/html.
```
After change
```
org.apache.solr.client.solrj.impl.BaseHttpSolrClient$RemoteSolrException: Error from server at http://127.0.0.1:57676/solr/debug/foo/admin/ping?wt=javabin&version=2: Expected mime type in [application/octet-stream, application/vnd.apache.solr.javabin] but got text/html.
```
This …
> SOLR-16638 Fix Http2SolrClient's exception message when serverBaseUrl is null

- .inferconfig
- .lift.toml
- solr/solrj/src/java/org/apache/solr/common/util/ObjectReleaseTracker.java
- solr/solrj/src/java/org/noggit/CharArr.java
- solr/solrj/src/java/org/noggit/JSONParser.java
Experimenting with ways to suppress false-positive errors reported by Lift, especially THREAD_SAFETY_VIOLATION implemented by Infer/RacerD
Reference:
* https://github.com/facebook/infer/issues/1732
* https://help.sonatype.com/lift/configuring-lift/infer-specifics
> Inferconfig

- build.gradle
- solr/CHANGES.txt
See https://github.com/policeman-tools/forbidden-apis/wiki/Changes#version-35-released-2023-03-27
> Upgrade forbiddenapis to 3.5

- solr/CHANGES.txt
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/Http2SolrClient.java
https://issues.apache.org/jira/browse/SOLR-16723
> SOLR-16723: Http2SolrClient should not use Apache Http client classes

- gradle/validation/forbidden-apis/org.apache.commons.collections4.all.txt
- solr/core/build.gradle
- solr/core/src/java/org/apache/solr/core/PluginBag.java
- solr/core/src/java/org/apache/solr/handler/CollectionsAPI.java
- solr/core/src/java/org/apache/solr/handler/admin/api/AddReplicaAPI.java
- solr/core/src/java/org/apache/solr/handler/admin/api/CreateShardAPI.java
- solr/core/src/java/org/apache/solr/handler/admin/api/MergeIndexesAPI.java
- solr/core/src/java/org/apache/solr/handler/admin/api/RenameCollectionAPI.java
- solr/core/src/java/org/apache/solr/handler/admin/api/SplitCoreAPI.java
- solr/core/src/java/org/apache/solr/handler/admin/api/SplitShardAPI.java
- solr/core/src/java/org/apache/solr/handler/configsets/CreateConfigSetAPI.java
- solr/core/src/java/org/apache/solr/packagemanager/PackageManager.java
- solr/core/src/java/org/apache/solr/search/Grouping.java
- solr/core/src/java/org/apache/solr/search/SolrDocumentFetcher.java
- solr/core/src/java/org/apache/solr/search/grouping/endresulttransformer/GroupedEndResultTransformer.java
- solr/core/src/test/org/apache/solr/cloud/RollingRestartTest.java
- solr/core/src/test/org/apache/solr/util/tracing/TestHttpServletCarrier.java
https://issues.apache.org/jira/browse/SOLR-16724
> SOLR-16724: Remove unneeded commons-collections4 dependency

- solr/CHANGES.txt
- solr/core/src/test/org/apache/solr/cloud/TestRandomFlRTGCloud.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/CloudSolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/ConcurrentUpdateHttp2SolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/ConcurrentUpdateSolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/DelegationTokenHttpSolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/HttpSolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/LBHttp2SolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/LBHttpSolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/LBSolrClient.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/BasicHttpSolrClientTest.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/LBHttp2SolrClientTest.java
https://issues.apache.org/jira/browse/SOLR-16601
> SOLR-16601: Remove Deprecated Methods from SolrClients

- solr/core/src/java/org/apache/solr/util/DateMathParser.java
- solr/solr-ref-guide/modules/indexing-guide/pages/date-formatting-math.adoc
https://issues.apache.org/jira/browse/SOLR-16726
Adding the Date Math expression units to the Solr Ref Guide.
Just a documenation update and a simple comment in the code.
N/A
> SOLR-16726: Adding Date Math expression units to docs

- gradle/validation/forbidden-apis/java.solr.txt
- solr/CHANGES.txt
- solr/solrj/src/java/org/apache/solr/common/SolrException.java
https://issues.apache.org/jira/browse/SOLR-15703
> SOLR-15703: Remove SolrException#log methods

- solr/CHANGES.txt
- solr/bin/solr
https://issues.apache.org/jira/browse/SOLR-16734
> SOLR-16734: SOLR_DATA_HOME is only honored in verbode mode

- solr/CHANGES.txt
- solr/server/etc/jetty-ssl.xml
This PR doesn't change any defaults, just adds a way to configure via system properties
> SOLR-16735: Allow custom configuration of Jetty's SecureRequestCustomizer

- solr/solrj/src/java/org/apache/solr/client/solrj/impl/CloudHttp2SolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/Http2SolrClient.java
https://issues.apache.org/jira/browse/SOLR-16601
Found more deprecated code that should be removed from `main`
Remove
ran
> SOLR-16601: remove deprecated code in Solr Clients

- solr/solr-ref-guide/modules/indexing-guide/pages/external-files-processes.adoc
I don't think these were supposed to have an underscore at the end - it appears to be a typo. (external_fieldname_ should be external_fieldname)
> Fix filename in external-files-processes.adoc

- solr/core/src/java/org/apache/solr/cli/ApiTool.java
- solr/core/src/java/org/apache/solr/cli/SolrCLI.java
- solr/core/src/test/org/apache/solr/cli/ApiToolTest.java
Also some small cleanups on SolrCLI
https://issues.apache.org/jira/browse/SOLR-16767
> SOLR-16767: migrate some methods into ApiTool that are only used by it

- solr/modules/analytics/src/test/org/apache/solr/analytics/NoFacetTest.java
- solr/modules/analytics/src/test/org/apache/solr/analytics/OverallAnalyticsTest.java
- solr/modules/analytics/src/test/org/apache/solr/analytics/SolrAnalyticsTestCase.java
- solr/modules/analytics/src/test/org/apache/solr/analytics/facet/PivotFacetTest.java
- solr/modules/analytics/src/test/org/apache/solr/analytics/facet/QueryFacetTest.java
- solr/modules/analytics/src/test/org/apache/solr/analytics/facet/RangeFacetTest.java
- solr/modules/analytics/src/test/org/apache/solr/analytics/facet/ValueFacetTest.java
Just some hygiene - I know the analytics module is going away, but this was a low hanging fruit :)
> Remove duplicate code analytics tests

- solr/CHANGES.txt
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/CloudHttp2SolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/Http2SolrClient.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/Http2SolrClientTest.java
https://issues.apache.org/jira/browse/SOLR-16737
Copy more properties from the seed client inside the builder itself, at the same time leaving the option to overwrite properties (both before and after the seed is set to avoid any regressions).
This also fixed a regression I identified on https://github.com/apache/solr/pull/1564
> SOLR-16737 Http2SolrClient needs to inherit all properties when initialized with another http2 client

- solr/CHANGES.txt
- solr/prometheus-exporter/conf/grafana-solr-dashboard.json
- solr/prometheus-exporter/conf/solr-exporter-config.xml
- solr/solr-ref-guide/modules/deployment-guide/pages/metrics-reporting.adoc
- solr/solr-ref-guide/modules/deployment-guide/pages/performance-statistics-reference.adoc
https://issues.apache.org/jira/browse/SOLR-15083
"solr_metrics_jvm_os_cpu_time_seconds", "solr_metrics_node_time_seconds_total", "solr_metrics_core_time_seconds_total" metric has seconds in its name but the metric is incorrectly converting the metric to microseconds. (Nanoseconds / 1000)
Change the math conversion in the prometheus_exporter default config to export the metric into seconds (nanoseconds / 10^9 = seconds)
Manual testing with prometheus and grafana
> SOLR-15083: prometheus-exporter incorrect metric namings

- solr/packaging/test/test_export.bats
- solr/solr-ref-guide/modules/deployment-guide/pages/solr-control-script-reference.adoc
https://issues.apache.org/jira/browse/SOLR-16763
Docs and a test 
Document that export is cloud mode only...
> SOLR-16763: some docs and a test that export requires cloud mode

- solr/packaging/test/test_zk.bats
https://issues.apache.org/jira/browse/SOLR-12226
Start testing ZK interaction as we get into cli changes..
basic bats test to see if it works
literally wrote a test ;-)
> SOLR-12226: Basic zk test framework in BATS

- solr/solr-ref-guide/modules/upgrade-notes/pages/major-changes-in-solr-9.adoc
https://issues.apache.org/jira/browse/SOLR-16774
> SOLR-16774: Docker version requirement documented

- solr/solrj/src/java/org/apache/solr/client/solrj/impl/ConcurrentUpdateSolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/DelegationTokenHttpSolrClient.java
https://issues.apache.org/jira/browse/SOLR-13605
Backporting issues
Removed deprecated code references, and updated property names.
rerunning
> SOLR-13605: Fix backport issues

- solr/CHANGES.txt
- solr/webapp/web/js/angular/controllers/index.js
I'm not sure this is the right fix, I don't trust my UI skills. I believe this was introduced in https://github.com/apache/solr/pull/1296
> SOLR-16789: Admin UI Dashboard shows "unauthenticated" warning on authenticated servers

- gradle/testing/randomization/policies/solr-tests.policy
(cherry picked from commit 29fa8d2a0150ddbdf7c965269d9d69a1b2763a99)
https://issues.apache.org/jira/browse/SOLR-16804 backport
> SOLR-16804 Simplify testing modified dependencies. (#1648)

- solr/core/src/java/org/apache/solr/update/DocumentBuilder.java
- solr/core/src/test-files/solr/collection1/conf/schema-densevector.xml
- solr/core/src/test-files/solr/collection1/conf/schema-vector-catchall.xml
- solr/core/src/test/org/apache/solr/update/DocumentBuilderVectorCatchAllCopyTest.java
SOLR-16807: DenseVectorField breaks '*' copyFields
> SOLR-16807: DenseVectorField breaks '*' copyFields (#1651)

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/loader/JsonLoader.java
- solr/core/src/test/org/apache/solr/handler/JsonLoaderTest.java
https://issues.apache.org/jira/browse/SOLR-16811
> SOLR-16811: fix echo and mapUniqueKeyOnly params at /update/json/docs.

- solr/documentation/src/markdown/index.template.md
Hyper link , mentioned in url "https://solr.apache.org/docs/9_2_1/index.html" to Tutorial section is broken.
We are getting "The requested URL was not found on this server." error.
URL for tutorial mentioned : https://solr.apache.org/guide/solr/latest/solr-tutorial.html
Actual URL for tutorial should be : +https://solr.apache.org/guide/solr/latest/getting-started/solr-tutorial.html+
https://issues.apache.org/jira/browse/SOLR-16817
Actual URL for tutorial should be : +https://solr.apache.org/guide/solr/latest/getting-started/solr-tutorial.html+
It is is trivial doc change and hence tested with developer mode
- [ yes] I have reviewed the guidelines for [How to Contribute](https://wiki.apache.org/solr/HowToContribute) and my code conforms …
> SOLR-16817: Fixing broken link of Solr Tutorial section

- solr/core/src/java/org/apache/solr/security/PKIAuthenticationPlugin.java
https://issues.apache.org/jira/browse/SOLR-16720
Attempting to fix failures on SOLR-16720 @gerlowskija's PR https://github.com/apache/solr/pull/1495, so contribution is heavily inspired by that PR. I think I found the reason it was failing, opening another PR for validation.
I think failures were due to extra fallback to getUser() on the onBegin -> generateToken. this should not happen as everything was already setup when the `onQueued` method was called.
I used the failure seed as a starting point, and now it passes
```
./gradlew test --tests JWTAuthPluginIntegrationTest.testMetrics -Dtests.seed=8938961115F4C519 -Dtests.multiplier=3 -Dtests.locale=tr-TR -Dtests.timezone=Pacific/Niue -Dtests.asserts=true -Dtests.file.encoding=UTF-8
```
Please provide a short description of the approach …
> SOLR-16720: Defer PKI header creation to send-time

- solr/core/src/java/org/apache/solr/core/backup/repository/BackupRepository.java
> Remove deprecated BackupRepository delete with ignoreNoSuchFileException API

- solr/core/src/java/org/apache/solr/handler/component/ResponseBuilder.java
- solr/core/src/java/org/apache/solr/search/AbstractReRankQuery.java
- solr/core/src/java/org/apache/solr/search/ReRankCollector.java
- solr/core/src/java/org/apache/solr/search/ReRankQParserPlugin.java
- solr/core/src/java/org/apache/solr/search/ReRankScaler.java
- solr/core/src/java/org/apache/solr/search/ReRankWeight.java
- solr/core/src/test/org/apache/solr/search/TestReRankQParserPlugin.java
- solr/solr-ref-guide/modules/query-guide/pages/query-re-ranking.adoc
https://issues.apache.org/jira/browse/SOLR-16827
When combining an unbounded Lucene / Solr score with a vector score its difficult or impossible to balance the two components by simply adjusting the weight of the rerank score. 
This ticket will add Min/Max scaling of both the main query scores and ReRank scores to the ReRanker to support the hybrid ranking function.
> SOLR-16827: Add min/max scaling to the reranker

- solr/CHANGES.txt
- solr/benchmark/src/java/org/apache/solr/bench/MiniClusterState.java
- solr/benchmark/src/java/org/apache/solr/bench/search/JsonFaceting.java
- solr/benchmark/src/java/org/apache/solr/bench/search/NumericSearch.java
- solr/benchmark/src/resources/configs/cloud-minimal/conf/schema.xml
- solr/core/src/java/org/apache/solr/schema/DatePointField.java
- solr/core/src/java/org/apache/solr/schema/DoublePointField.java
- solr/core/src/java/org/apache/solr/schema/FloatPointField.java
- solr/core/src/java/org/apache/solr/schema/IntPointField.java
- solr/core/src/java/org/apache/solr/schema/LongPointField.java
- solr/core/src/test/org/apache/solr/schema/TestPointFields.java
- solr/core/src/test/org/apache/solr/search/TestSolrQueryParser.java
Similar to Lucene's https://github.com/apache/lucene/pull/12087
> SOLR-16846: Use IndexOrDocValuesQuery for PointFields on Set queries

- solr/CHANGES.txt
- solr/benchmark/log4j2-bench.xml
- solr/benchmark/src/java/org/apache/solr/bench/search/QueryResponseWriters.java
- solr/benchmark/src/resources/configs/cloud-minimal/conf/schema.xml
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/NoOpResponseParser.java
https://issues.apache.org/jira/browse/SOLR-16841
Proposing some benchmarks for the various QueryResponseWriter options
Running benchmark
```
./jmh.sh QueryResponseWriters
```
Running benchmark for a specific type
```
./jmh.sh QueryResponseWriters -p wt=javabin
```
Some numbers
```
Benchmark                      (wt)   Mode  Cnt     Score    Error  Units
QueryResponseWriters.query  javabin  thrpt    4  3102.964 ± 40.186  ops/s
QueryResponseWriters.query     json  thrpt    4   450.379 ± 27.369  ops/s
QueryResponseWriters.query    smile  thrpt    4  3572.251 ± 17.695  ops/s
QueryResponseWriters.query      xml  thrpt    4   369.158 ± 17.062  ops/s
QueryResponseWriters.query   python  thrpt    4   370.970 ± 17.421  ops/s
QueryResponseWriters.query     phps  thrpt    4   455.651 ± 21.930  ops/s …
```
> SOLR-16841 QueryResponseWriter benchmarks

- solr/CHANGES.txt
- solr/core/src/test/org/apache/solr/cloud/DeleteReplicaTest.java
https://issues.apache.org/jira/browse/SOLR-16848
Test fails due to a timing issue in jetty restart. please see analysis on jira ticket. https://issues.apache.org/jira/browse/SOLR-16848?focusedCommentId=17735796&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-17735796
Added a wait loop with timeout to allow correct init.
> SOLR-16848 Flaky DeleteReplicaTest.raceConditionOnDeleteAndRegisterReplica

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cluster/placement/plugins/AffinityPlacementConfig.java
- solr/core/src/java/org/apache/solr/cluster/placement/plugins/AffinityPlacementFactory.java
- solr/core/src/java/org/apache/solr/cluster/placement/plugins/OrderedNodePlacementPlugin.java
- solr/core/src/test/org/apache/solr/cluster/placement/plugins/AffinityPlacementFactoryTest.java
- solr/solr-ref-guide/modules/configuration-guide/pages/replica-placement-plugins.adoc
- solr/test-framework/src/java/org/apache/solr/cluster/placement/ClusterAbstractionsForTest.java
https://issues.apache.org/jira/browse/SOLR-16837
> SOLR-16837: introducing AffinityPlacementFactory.withCollectionShards

- solr/core/src/test/org/apache/solr/handler/tagger/RandomizedTaggerTest.java
https://issues.apache.org/jira/browse/SOLR-16744
Fix RandomizedTaggerTest that fails for some rare seeds.
Don't test tagger with too long name.
Truncate names at 1000 chars.
n/a
> SOLR-16744: fix flaky RandomizedTaggerTest

- solr/benchmark/src/java/org/apache/solr/bench/search/SimpleSearch.java
https://issues.apache.org/jira/browse/SOLR-16702
Not a fix for this issue, but proposing some minor updates to the SimpleSearch benchmark to collect number of failures (which are very low compared to the overall number of runs) AND compare http1 with http2.
```
Benchmark           (strict)  (useHttp1)   Mode  Cnt      Score      Error  Units
SimpleSearch.query     false       false  thrpt    9  66644.499 ± 1679.914  ops/s
SimpleSearch.query     false        true  thrpt    9  48148.312 ± 1141.006  ops/s
```
numbers of failures
```
Iteration   6: --> Completed Iteration with 325567 queries and 1 errors
```
Please describe the tests you've developed or run to confirm this patch implements the feature or …
> SOLR-16702 JMH benchmarks can fail with http2 when using many threads

- solr/core/src/java/org/apache/solr/servlet/CoordinatorHttpSolrCall.java
- solr/core/src/test/org/apache/solr/common/cloud/ZkStateReaderAccessor.java
- solr/core/src/test/org/apache/solr/search/TestCoordinatorRole.java
- solr/solrj-zookeeper/src/java/org/apache/solr/common/cloud/ZkStateReader.java
https://issues.apache.org/jira/browse/SOLR-16860
It's found that DocCollection watch is not removed from `ZkStateReader` of Coordinator node if such collection is deleted.
Core registration in CoordinatorHttpCall correctly registers watch in ZkStateReader as in https://github.com/apache/solr/blob/f774922ecf44b18b78435cef8735618bb793ac30/solr/core/src/java/org/apache/solr/servlet/CoordinatorHttpSolrCall.java#L99, however there’s no code to remove such watch on collection deletion (state update).
For non coordinator node, it’s done at UnloadCoreOnDeleteWatcher at https://github.com/apache/solr/blob/main/solr/core/src/java/org/apache/solr/cloud/ZkController.java#L2869
Use `ZkStateReader#registerDocCollectionWatcher` instead of `ZkStateReader#registerCore`, the `stateWatcher` should return …
> SOLR-16860: Remove watch from ZkStateReader of Coordinator Node when collection is deleted

- solr/solr-ref-guide/modules/deployment-guide/pages/configuring-logging.adoc
https://issues.apache.org/jira/browse/SOLR-16582
Added documentation to #1229 
> SOLR-16582 : Documentation for logging filter on SolrCore

- solr/core/src/test/org/apache/solr/util/TestCircuitBreaker.java
https://issues.apache.org/jira/browse/SOLR-15819
As proposed on the dev list (https://lists.apache.org/thread/xhsrr6ksc5y11t29zz60oglw8ymkrwtf), PR to remove this problematic test.
> SOLR-15819 spurious failures from TestCircuitBreaker.testResponseWithCBTiming

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cluster/placement/plugins/AffinityPlacementFactory.java
- solr/core/src/java/org/apache/solr/search/JoinQParserPlugin.java
- solr/core/src/java/org/apache/solr/search/join/ScoreJoinQParserPlugin.java
- solr/core/src/test/org/apache/solr/cluster/placement/plugins/StubShardAffinityPlacementFactory.java
- solr/core/src/test/org/apache/solr/search/join/ShardJoinCompositeTest.java
- solr/core/src/test/org/apache/solr/search/join/ShardJoinImplicitTest.java
- solr/core/src/test/org/apache/solr/search/join/ShardJoinRouterTest.java
- solr/core/src/test/org/apache/solr/search/join/ShardToShardJoinAbstract.java
- solr/solr-ref-guide/modules/query-guide/pages/join-query-parser.adoc
- solr/test-framework/src/java/org/apache/solr/cluster/placement/AttributeFetcherForTest.java
> SOLR-16717: join multiple shards on both sides. rebase of (#1691)

- solr/core/src/java/org/apache/solr/cli/RunExampleTool.java
TestSolrCLIRunExample has been failing thread leak in nightly since the Http2SolrClient has not been closed in `RunExampleTool`
> Fix TestSolrCLIRunExample Nightly Thread Leak

- solr/CHANGES.txt
- solr/bin/solr
- solr/bin/solr.cmd
https://issues.apache.org/jira/browse/SOLR-16869
> SOLR-16869: Use Panama Vector apis for Java 20/21

- solr/core/src/java/org/apache/solr/cli/HealthcheckTool.java
https://issues.apache.org/jira/browse/SOLR-16882
Missing requires parameter on command
add requrie!
Thanks @gerlowskija for spotting this!
> missing required parameter on the builder

- solr/core/src/java/org/apache/solr/cli/RunExampleTool.java
Small ticket so no JIRA needed.
> Pass verbose flag to solr start when using example

- dev-tools/scripts/checkJavadocLinks.py
- gradle/documentation/render-javadoc.gradle
- solr/CHANGES.txt
https://issues.apache.org/jira/browse/SOLR-16884
> SOLR-16884: Enable javadocs search for the site build

- solr/CHANGES.txt
- solr/bin/solr
- solr/bin/solr.cmd
- solr/core/src/java/org/apache/solr/cli/SolrCLI.java
- solr/core/src/java/org/apache/solr/cli/VersionTool.java
https://issues.apache.org/jira/browse/SOLR-16842
Eliminate special case code in solrCLI by introducing VersionTool
refactoring
bats test and manual.   Pinging @Willdotwhite and @mkhludnev to verify the `solr.cmd` changes!
> SOLR-16842: Make "version" just another Tool.

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/servlet/RateLimitManager.java
- solr/core/src/java/org/apache/solr/servlet/ServletUtils.java
- solr/core/src/java/org/apache/solr/servlet/SolrDispatchFilter.java
- solr/core/src/test/org/apache/solr/servlet/TestRequestRateLimiter.java
https://issues.apache.org/jira/browse/SOLR-16889
PR for short cutting the request if Rate Limiter decides against processing. also takes care of cleaning up the request.
> SOLR-16889 Rate Limiter should stop processing on 429

- solr/CHANGES.txt
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/Http2SolrClient.java
https://issues.apache.org/jira/browse/SOLR-16265
Initially started with addressing the TODO to remove extra buffer from the code (https://github.com/apache/solr/pull/1789/files#diff-db379c74efc9ff28acfd7571b07e16dbcdaa510783f2bee835b4a288927b5b3dR694). Ended up with removing all deprecated code to refresh implementation and bring it up to latest guidance.
It looks a bit more involved because some of the writers now need to push content after being setup, opposed to before style that was upfront setup of content.
To evaluate some performance aspect I ran exiting indexing benchmark. Numbers were equivalent, but heap footprint on benchmark client side saw a drop. posted screenshots below. if there are other tests I could run please let me know.
Please provide a short description of the …
> SOLR-16265 reduce memory usage of ContentWriter based requests in Http2SolrClient

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cli/AuthTool.java
- solr/core/src/java/org/apache/solr/cli/ConfigSetDownloadTool.java
- solr/core/src/java/org/apache/solr/cli/ConfigSetUploadTool.java
- solr/core/src/java/org/apache/solr/cli/ZkCpTool.java
- solr/core/src/java/org/apache/solr/cli/ZkLsTool.java
- solr/core/src/java/org/apache/solr/cli/ZkMkrootTool.java
- solr/core/src/java/org/apache/solr/cli/ZkMvTool.java
- solr/core/src/java/org/apache/solr/cli/ZkRmTool.java
- solr/core/src/java/org/apache/solr/cloud/ZkCLI.java
- solr/core/src/java/org/apache/solr/cloud/ZkController.java
- solr/core/src/java/org/apache/solr/core/CloudConfig.java
- solr/core/src/java/org/apache/solr/core/ZkContainer.java
- solr/core/src/java/org/apache/solr/packagemanager/PackageManager.java
- solr/core/src/java/org/apache/solr/schema/ManagedIndexSchemaFactory.java
- solr/solrj-zookeeper/src/java/org/apache/solr/client/solrj/impl/ZkClientClusterStateProvider.java
- solr/solrj-zookeeper/src/java/org/apache/solr/common/cloud/SolrZkClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/CloudHttp2SolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/CloudLegacySolrClient.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/SolrZkClientTimeout.java
- solr/test-framework/src/java/org/apache/solr/util/TestHarness.java
https://issues.apache.org/jira/browse/SOLR-14667
Pulling together all zk client timeout values that I could find in a single class `SolrZkClientTimeout`. not the best name, open to suggestions. location of this class is in solrj module, also open to suggestions. values are based on system properties with a default of 30s.
A bit of extra work went into providing setters for these values via the CloudHttp2SolrClient and CloudLegacySolrClient builders. this will make things a bit simpler client side, if anyone does not want to rely purely on system properties.
I have also started a discussion on the dev list for the [ZkCmdExecutor class](https://lists.apache.org/thread/g42bg5v6twps2y5pwdyqtzhm2rnx943k). there were no changes to this class in this PR. I ended up not needing to touch it. if …
> SOLR-14667 Make zkClientTimeout consistent and based on a system property

- solr/core/src/java/org/apache/solr/cloud/DistributedMap.java
- solr/core/src/java/org/apache/solr/cloud/LeaderElector.java
- solr/core/src/java/org/apache/solr/cloud/OverseerElectionContext.java
- solr/core/src/java/org/apache/solr/cloud/ShardLeaderElectionContextBase.java
- solr/core/src/java/org/apache/solr/cloud/ZkController.java
- solr/core/src/java/org/apache/solr/cloud/ZkDistributedQueue.java
- solr/core/src/java/org/apache/solr/handler/admin/api/CreateCollectionAPI.java
- solr/core/src/java/org/apache/solr/schema/ManagedIndexSchemaFactory.java
- solr/core/src/test/org/apache/solr/cloud/ZkSolrClientTest.java
- solr/solrj-zookeeper/src/java/org/apache/solr/common/cloud/ZkCmdExecutor.java
- solr/solrj-zookeeper/src/java/org/apache/solr/common/cloud/ZkMaintenanceUtils.java
Trivial refactoring, does not need a Sol Jira ticket.
Proposed it in this thread https://lists.apache.org/thread/g42bg5v6twps2y5pwdyqtzhm2rnx943k
> Refactor ZkCmdExecutor, move all ensureExists methods to ZkMaintenanceUtils

- solr/CHANGES.txt
CHANGES.txt update for https://github.com/apache/solr/pull/1846
> CHANGES.txt update for io.opentelemetry update

- solr/CHANGES.txt
- solr/bin/solr
- solr/core/src/java/org/apache/solr/cli/CreateTool.java
- solr/core/src/java/org/apache/solr/cli/SolrCLI.java
- solr/packaging/test/test_ssl.bats
https://issues.apache.org/jira/browse/SOLR-16941
I've also updated one of the SSL tests to show that this works (defaulting the scheme at least)
> SOLR-16941: Use smarter default Solr URL in CLI

- solr/core/src/java/org/apache/solr/util/circuitbreaker/CircuitBreakerManager.java
- solr/core/src/java/org/apache/solr/util/circuitbreaker/CircuitBreakerRegistry.java
- solr/core/src/test-files/solr/collection1/conf/solrconfig-pluggable-circuitbreaker.xml
- solr/core/src/test/org/apache/solr/util/BaseTestCircuitBreaker.java
https://issues.apache.org/jira/browse/SOLR-15474
Follow-up due to race condition on #1725 merge: https://github.com/apache/solr/pull/1725#discussion_r1308640769
> SOLR-15474: three more code review tweaks

- solr/solr-ref-guide/modules/configuration-guide/pages/configuring-solr-xml.adoc
(cherry picked from commit [`4d656c5`](https://github.com/apache/solr/commit/4d656c5ef845912f54eb7b0f7936491e680cac55))
> Fix configuration parameter stateCompressor in solr-xml doc (#1872)

- solr/core/src/java/org/apache/solr/handler/component/SearchHandler.java
No change in existing behaviour, but the factored out method would be supportive of customisation or future changes to (say) consider the `rb.isDistrib` flag value.
> NO JIRA: factor out protected SearchHandler.checkCircuitBreakers method

- solr/modules/ltr/src/test/org/apache/solr/ltr/feature/TestFieldValueFeature.java
Could be considered follow-up to #123 for https://issues.apache.org/jira/browse/SOLR-12697 and/or preparation for https://issues.apache.org/jira/browse/SOLR-15440 or just well, independent with "NO JIRA" since it's a small test change.
> NO JIRA: add TestFieldValueFeature.testBooleanValue_docValues() case

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/servlet/LoadAdminUiServlet.java
- solr/core/src/test/org/apache/solr/servlet/LoadAdminUiServletTest.java
- solr/modules/jwt-auth/src/java/org/apache/solr/security/jwt/JWTAuthPlugin.java
- solr/modules/jwt-auth/src/java/org/apache/solr/security/jwt/JWTIssuerConfig.java
- solr/modules/jwt-auth/src/test-files/solr/security/jwt_plugin_jwk_security.json
- solr/modules/jwt-auth/src/test-files/solr/security/jwt_plugin_jwk_security_blockUnknownFalse.json
- solr/modules/jwt-auth/src/test/org/apache/solr/security/jwt/JWTAuthPluginIntegrationTest.java
- solr/modules/jwt-auth/src/test/org/apache/solr/security/jwt/JWTAuthPluginTest.java
- solr/modules/jwt-auth/src/test/org/apache/solr/security/jwt/JWTIssuerConfigTest.java
- solr/solr-ref-guide/modules/deployment-guide/pages/jwt-authentication-plugin.adoc
Backport PR for `branch_9x`.
Co-authored-by: Lamine Idjeraoui <lidjeraoui@apple.com>
Co-authored-by: Jan Høydahl <janhoy@apache.org>
(cherry picked from commit 931de5157226655ec18b2530b4ac27905f0b5818)
> SOLR-16897: Add support of OAuth 2.0/OIDC 'code with PKCE' flow (#1792)

- solr/CHANGES.txt
- solr/bin/solr
- solr/bin/solr.cmd
https://issues.apache.org/jira/browse/SOLR-16970
Same with SOLR_TOOL_OPTS
> SOLR-16970: SOLR_OPTS should override most options

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/component/SearchHandler.java
- solr/core/src/java/org/apache/solr/logging/MDCLoggingContext.java
- solr/core/src/java/org/apache/solr/util/tracing/SimplePropagator.java
- solr/solr-ref-guide/modules/deployment-guide/pages/distributed-tracing.adoc
- solr/solr-ref-guide/modules/upgrade-notes/pages/major-changes-in-solr-9.adoc
- solr/solrj/src/java/org/apache/solr/common/params/CommonParams.java
https://issues.apache.org/jira/browse/SOLR-15367
This PR is for deprecating the rid generation, sourcing it from the trace id if that exists.
Params have been marked as deprecated with 9.4.
I have moved the changes.txt entry to 9.4 features.
This step is setup for the 9.x backport mainly. There will be a followup for main branch to remove rid completely.
> SOLR-15367 Convert "rid" functionality into a default Tracer

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/component/RealTimeGetComponent.java
- solr/core/src/test/org/apache/solr/cloud/FullSolrCloudDistribCmdsTest.java
https://issues.apache.org/jira/browse/SOLR-16971
RealTimeGet with Composite router throws NPE at slice resolution time making it unusable.
The route field needs to be separated out because the`CompositeIdRouter#getTargetSlice` will never allow a null route to pass by because of the fix did for delete-by-id. 
I have added a test based on existing example with router field but this is misleading in the sense that Solr will shortcut the execution and bypass the code that I fixed by setting distrib=false on the query. not sure how to do better than this.
Please review the following and check …
> SOLR-16971 RealTimeGet with Composite router throws NPE

- solr/bin/solr
> Revert "SOLR-16981: bin/solr stop improvements"

- solr/core/src/test-files/solr/configsets/cache-control/conf/schema.xml
- solr/core/src/test-files/solr/configsets/cache-control/conf/solrconfig.xml
- solr/core/src/test/org/apache/solr/search/TestCoordinatorRole.java
https://issues.apache.org/jira/browse/SOLR-16890
Adding more test cases to verify the Coordinator node role introduced in Solr 9
> SOLR-16890: More test cases for Coordinator node role

- solr/solr-ref-guide/modules/indexing-guide/pages/filters.adoc
Fix a copy-paste error in the docs for Protected Term Filter.
> Fix example for Protected Term Filter

- solr/solr-ref-guide/modules/indexing-guide/pages/filters.adoc
fix protected term filter example
> fix protected term filter example (#1894)

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/util/tracing/TraceUtils.java
- solr/test-framework/build.gradle
- solr/test-framework/src/java/org/apache/solr/cloud/MiniSolrCloudCluster.java
https://issues.apache.org/jira/browse/SOLR-16960
Took a stab at randomizing the isRecording flag during tests so we get better coverage.
> SOLR-16960 Tests should sometimes run with a Tracer (not no-op)

- solr/core/src/java/org/apache/solr/servlet/CoordinatorHttpSolrCall.java
- solr/core/src/java/org/apache/solr/servlet/HttpSolrCall.java
HttpSolrCall#populateTracingSpan probably has incorrect replica/collection info tagged.
> Coordinator node does not have correct collection tagged for TracingSpan

- solr/modules/ltr/src/java/org/apache/solr/ltr/feature/FieldValueFeature.java
- solr/modules/ltr/src/test/org/apache/solr/ltr/feature/TestFieldValueFeature.java
https://issues.apache.org/jira/browse/SOLR-16994
> SOLR-16994: facilitate date-related FieldValueFeature extensions (docValues=True only)

- solr/bin/solr.cmd
https://issues.apache.org/jira/browse/SOLR-16970
> SOLR-16970: Fix windows script

- solr/core/src/java/org/apache/solr/response/JacksonJsonWriter.java
https://issues.apache.org/jira/browse/SOLR-17009
Set withObjectIndenter to have consistent line endings for objects
> SOLR-17009 json.wrf parameter ignored in JacksonJsonWriter

- solr/test-framework/src/java/org/apache/solr/cloud/MiniSolrCloudCluster.java
https://issues.apache.org/jira/browse/SOLR-17014
> SOLR-17014: Ensure that injecting random recording flag only happens under randomized context SOLR-16960

- solr/solr-ref-guide/modules/upgrade-notes/pages/major-changes-in-solr-9.adoc
solr 9 upgrade only suggest re-indexing, but for collection create in Solr 7 or lower this is mandatory.
Changed the sentence to show if collection sis created in Solr 8 a re-index is suggested, but if it was created in Solr 7 or lower re-index is mandatory.
just single line document change
> fix upgrade notes Solr 9

- solr/benchmark/src/java/org/apache/solr/bench/BaseBenchState.java
- solr/benchmark/src/java/org/apache/solr/bench/CircularIterator.java
- solr/benchmark/src/java/org/apache/solr/bench/Docs.java
- solr/benchmark/src/java/org/apache/solr/bench/MiniClusterState.java
- solr/benchmark/src/java/org/apache/solr/bench/index/CloudIndexing.java
- solr/benchmark/src/java/org/apache/solr/bench/search/NumericSearch.java
Some cleanup of the benchmark console output.
Moved the circular iterator to its own class so other benchmarks can use it (currently the CloudIndexing bench will exhaust the iterator under load and simply crash).
Cleanup of CloudIndexing params that were not used anywhere, made the 2 benches into a single one based on a param with 2 values so it is a bit clearer (this still runs 2 benchmarks).
Default seed was hardcoded, made it random (for passing a specific seed, use the params).
> No Jira: Solr benchmark cleanup

- dev-tools/scripts/addVersion.py
- dev-tools/scripts/releaseWizard.yaml
Some tweaks based on working on the Solr release.
I ended up creating a new build page for Solr, looking for some feedback on this (including if this is needed or not) https://cwiki.apache.org/confluence/display/SOLR/JenkinsReleaseBuilds+-+Solr
> No Jira: some release script tweaks

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cloud/api/collections/AddReplicaCmd.java
- solr/core/src/java/org/apache/solr/cloud/overseer/ClusterStateMutator.java
- solr/core/src/java/org/apache/solr/cloud/overseer/SliceMutator.java
- solr/core/src/test/org/apache/solr/cloud/AddReplicaTest.java
- solr/core/src/test/org/apache/solr/cloud/CreateCollectionTest.java
- solr/core/src/test/org/apache/solr/cloud/CreateCollectionWithPropertiesTest.java
- solr/solr-ref-guide/modules/deployment-guide/pages/collection-management.adoc
https://issues.apache.org/jira/browse/SOLR-17006
CREATE collection and ADDREPLICA commands both accept core properties (as property.* parameters) that are then added to the core.properties file. However, those additional properties are not persisted anywhere in the cluster state.
Consequently, cores that are added later to a collection (e.g., by adding a new replica) do not contain those properties, which seems inconsistent. I would like to be able to specify a core property when creating a collection, and not repeat myself when adding a new replica later on.
This PR stores core properties in the cluster state for collections and replicas (which also allows them to be queried by plugins, if required). It also apply collection-level core properties to cores created when adding a new …
> SOLR-17006: Persist user-defined core properties

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/component/HttpShardHandler.java
- solr/core/src/java/org/apache/solr/update/SolrCmdDistributor.java
- solr/core/src/java/org/apache/solr/util/stats/InstrumentedHttpListenerFactory.java
- solr/core/src/java/org/apache/solr/util/stats/InstrumentedHttpRequestExecutor.java
- solr/core/src/java/org/apache/solr/util/tracing/SolrApacheHttpRequestCarrier.java
- solr/core/src/java/org/apache/solr/util/tracing/SolrHttpRequestCarrier.java
- solr/core/src/java/org/apache/solr/util/tracing/SolrJettyRequestCarrier.java
- solr/core/src/java/org/apache/solr/util/tracing/TraceUtils.java
- solr/core/src/test/org/apache/solr/util/tracing/TestDistributedTracing.java
https://issues.apache.org/jira/browse/SOLR-16943
This is the 9.x equivalent of https://github.com/apache/solr/pull/1856
> [9.x] SOLR-16943 Move Jetty HttpClient tracing into InstrumentedHttpListenerFactory

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cloud/api/collections/CollApiCmds.java
- solr/core/src/java/org/apache/solr/handler/IndexFetcher.java
- solr/core/src/java/org/apache/solr/update/UpdateShardHandler.java
- solr/core/src/java/org/apache/solr/util/tracing/SimplePropagator.java
- solr/core/src/java/org/apache/solr/util/tracing/TraceUtils.java
- solr/core/src/test/org/apache/solr/util/tracing/TestDistributedTracing.java
- solr/core/src/test/org/apache/solr/util/tracing/TestSimplePropagatorDistributedTracing.java
https://issues.apache.org/jira/browse/SOLR-17011
This is the 9.x backport of https://github.com/apache/solr/pull/1979
> [9.x] SOLR-17011 Add tracing spans to internal collection commands (#1979)

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/servlet/ServletUtils.java
… via stack traces
https://issues.apache.org/jira/browse/SOLR-17035
Updating the thread name to include the trace id if present.
* Current format:
```
qtp1175371136-23 (23)
org.apache.lucene.codecs.lucene90.blocktree.SegmentTermsEnum.getFrame​(SegmentTermsEnum.java:213)
org.apache.lucene.codecs.lucene90.blocktree.SegmentTermsEnum.pushFrame​(SegmentTermsEnum.java:241)
org.apache.lucene.codecs.lucene90.blocktree.SegmentTermsEnum.seekExact​(SegmentTermsEnum.java:494)
org.apache.lucene.index.TermStates.loadTermsEnum​(TermStates.java:111)
org.apache.lucene.index.TermStates.build​(TermStates.java:96)
```
* Proposed:
```
qtp2090991873-68-localhost-2786 (68)
org.apache.lucene.analysis.CharArrayMap.containsKey​(CharArrayMap.java:99)
org.apache.lucene.analysis.CharArraySet.contains​(CharArraySet.jav …
```
> SOLR-17035 Add trace id to jetty thread names to improve debuggability

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/api/ContainerPluginsRegistry.java
- solr/core/src/java/org/apache/solr/cloud/api/collections/Assign.java
- solr/core/src/java/org/apache/solr/cluster/placement/PlacementPluginFactory.java
- solr/core/src/java/org/apache/solr/cluster/placement/impl/DelegatingPlacementPluginFactory.java
- solr/core/src/java/org/apache/solr/cluster/placement/impl/PlacementPluginFactoryLoader.java
- solr/core/src/java/org/apache/solr/cluster/placement/plugins/AffinityPlacementFactory.java
- solr/core/src/java/org/apache/solr/core/CoreContainer.java
- solr/core/src/java/org/apache/solr/core/NodeConfig.java
- solr/core/src/java/org/apache/solr/core/SolrXmlConfig.java
- solr/core/src/test-files/solr/solr-50-all.xml
- solr/core/src/test/org/apache/solr/cluster/placement/impl/PlacementPluginIntegrationTest.java
- solr/core/src/test/org/apache/solr/core/TestSolrXml.java
- solr/solr-ref-guide/modules/configuration-guide/pages/configuring-solr-xml.adoc
- solr/solr-ref-guide/modules/configuration-guide/pages/replica-placement-plugins.adoc
https://issues.apache.org/jira/browse/SOLR-17079
Currently, container-level plugins can only be declared installed via calls to /cluster/plugin APIs. In some situations (especially corporate ones having tight security requirements), it is not possible to mutate the configuration of a cluster at runtime. Cluster should rather be configured fully at startup, and any change in config requires a re-deployment.
While there are several affected plugins, this PR makes it possible to configure replica placement (only) plugins in solr.xml. This default plugin will be installed by default, and can still be overridden by cluster plugins.
Enriched existing integration tests.
> SOLR-17079: Allow to declare replica placement plugins in solr.xml

- solr/core/src/test/org/apache/solr/cloud/OverseerCollectionConfigSetProcessorTest.java
https://issues.apache.org/jira/browse/SOLR-17079
Fixing tests broken after #2071.
> SOLR-17079: Fix OverseerCollectionConfigSetProcessorTest

- solr/core/src/java/org/apache/solr/util/circuitbreaker/LoadAverageCircuitBreaker.java
- solr/core/src/test/org/apache/solr/util/TestGlobalCircuitBreaker.java
- solr/solr-ref-guide/modules/deployment-guide/pages/circuit-breakers.adoc
https://issues.apache.org/jira/browse/SOLR-17082
> SOLR-17082 Disable TestGlobalCircuitBreaker on windows

- solr/core/src/test/org/apache/solr/core/BlobRepositoryMockingTest.java
> GH-2086: errorprone fix #2086

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/packagemanager/PackageManager.java
- solr/core/src/test/org/apache/solr/packagemanager/TestPackageManager.java
(#2074)
(cherry picked from commit 3cf2fb809d5214db82e7b99fb85035c7b336590a)
https://issues.apache.org/jira/browse/SOLR-17072
> SOLR-17072: CLI package to print problem JSON Path (#2074)

- solr/bin/solr
- solr/core/src/java/org/apache/solr/core/SolrCore.java
- solr/core/src/java/org/apache/solr/core/SolrResourceLoader.java
- solr/core/src/java/org/apache/solr/util/circuitbreaker/CPUCircuitBreaker.java
- solr/core/src/java/org/apache/solr/util/circuitbreaker/CircuitBreakerRegistry.java
- solr/core/src/java/org/apache/solr/util/circuitbreaker/LoadAverageCircuitBreaker.java
- solr/core/src/java/org/apache/solr/util/circuitbreaker/MemoryCircuitBreaker.java
- solr/core/src/test/org/apache/solr/util/BaseTestCircuitBreaker.java
- solr/core/src/test/org/apache/solr/util/TestGlobalCircuitBreaker.java
Co-authored-by: Christine Poerschke <cpoerschke@apache.org>
(cherry picked from commit e740123546c7f20c6728df42d493e11f93dc8c79)
> SOLR-16974: Global Circuit Breakers (backport 9x)

- solr/CHANGES.txt
- solr/bin/solr
- solr/solr-ref-guide/modules/deployment-guide/pages/circuit-breakers.adoc
- solr/solr-ref-guide/modules/upgrade-notes/pages/major-changes-in-solr-9.adoc
(cherry picked from commit 2bbb06aac63ec2ec94aab73874f09959b39f881f)
https://issues.apache.org/jira/browse/SOLR-16974
> SOLR-16974: Documentation and changes entry for global CB (9x)

- dev-tools/scripts/cloud.sh
- solr/CHANGES.txt
https://issues.apache.org/jira/browse/SOLR-17091
> SOLR-17091 Update cloud.sh to ignore -slim.tgz.

- dev-tools/scripts/cloud.sh
https://issues.apache.org/jira/browse/SOLR-17091
> SOLR-17091 fix edit that got missed in last commit

- dev-tools/scripts/cloud.sh
- solr/CHANGES.txt
https://issues.apache.org/jira/browse/SOLR-17091
> Backport SOLR-17091

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/core/CoreContainer.java
- solr/core/src/java/org/apache/solr/core/CoreSorter.java
- solr/core/src/java/org/apache/solr/core/NodeConfig.java
- solr/core/src/java/org/apache/solr/core/SolrXmlConfig.java
- solr/core/src/test-files/solr/solr-50-all.xml
- solr/core/src/test/org/apache/solr/core/CoreSorterTest.java
- solr/core/src/test/org/apache/solr/core/TestCoreContainer.java
- solr/core/src/test/org/apache/solr/core/TestSolrXml.java
- solr/solr-ref-guide/modules/configuration-guide/pages/configuring-solr-xml.adoc
https://issues.apache.org/jira/browse/SOLR-17083
I would like to be able to configure how cores are sorted before being loaded to accommodate more specific needs.
This PR makes the CoreSorter instance configurable in solr.xml.
Added new tests.
> SOLR-17083: Make CoreSorter class configurable

- solr/core/src/test/org/apache/solr/response/DocsStreamerTest.java
Test capturing the existing behaviour -- #2103 proposes to change it.
https://issues.apache.org/jira/browse/SOLR-16952
> SOLR-16952: add DocsStreamerTest.testDenseVectorField test

- solr/CHANGES.txt
- solr/solrj/src/java/org/apache/solr/common/util/ObjectCache.java
- solr/solrj/src/test/org/apache/solr/common/util/ObjectCacheTest.java
https://issues.apache.org/jira/browse/SOLR-17094
As a plugin author, I often need a place where to store an object which should be a singleton, e.g., at CoreContainer-level. To do so, in spite of a better place, I use the ObjectCache as a holder of my singleton. This makes it easy to store and retrieve my singleton, but it is quite complex to clean it up when CoreContainer is shutting down.
This PR modifies ObjectCache to automatically close any Closeable object that is stored within it, in order to serve this use case for plugin authors.
Added tests for ObjectCache (new and existing features).
> SOLR-17094: Close objects contained inside an ObjectCache

- solr/solr-ref-guide/modules/deployment-guide/pages/cluster-node-management.adoc
Documentation incorrectly stated that sourceNodes had a default value, while in fact [it must be defined to a non-empty value](https://github.com/apache/solr/blob/main/solr/core/src/java/org/apache/solr/cloud/api/collections/MigrateReplicasCmd.java#L57): 
```java
if (sourceNodes.isEmpty()) {
throw new SolrException(
SolrException.ErrorCode.BAD_REQUEST, "sourceNodes is a required param");
}
```
I don't believe it would mean anything to migrate all replicas.
Documentation fixed.
N/A
> Fix documentation of Migrate Replicas

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/search/BoolQParserPlugin.java
- solr/core/src/java/org/apache/solr/search/join/FiltersQParser.java
- solr/core/src/test/org/apache/solr/search/QueryEqualityTest.java
- solr/core/src/test/org/apache/solr/search/TestMmBoolQParserPlugin.java
- solr/solr-ref-guide/modules/query-guide/pages/other-parsers.adoc
https://issues.apache.org/jira/browse/SOLR-13748
> SOLR-13748: Add support for mm parameter to bool query parser (#2025)

- solr/CHANGES.txt
https://issues.apache.org/jira/browse/SOLR-14496
At the time of the original CHANGES.txt entry, the intention was that this would be backported and make it into a 9.x release.  But that idea has been shelved (for now).
This commit adjusts the CHANGES.txt entry accordingly.
N/A - doc change only.
> SOLR-14496: Update the version in CHANGES.txt

- solr/solr-ref-guide/modules/configuration-guide/pages/package-manager-internals.adoc
> Update package-manager-internals.adoc follow up #2147

- solr/solr-ref-guide/modules/configuration-guide/pages/package-manager-internals.adoc
> Update package-manager-internals.adoc follow up #2147 (#2151)

- solr/solr-ref-guide/modules/configuration-guide/pages/replica-placement-plugins.adoc
> Update replica-placement-plugins.adoc (#2155)

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/core/SolrCore.java
- solr/core/src/test/org/apache/solr/core/SolrCoreTest.java
- solr/core/src/test/org/apache/solr/handler/admin/MetricsHandlerTest.java
https://issues.apache.org/jira/browse/SOLR-17060
Posting a proposal for SOLR-17060, I am not entirely sure this will work correctly.
The approach is to identify the problematic window (core still in init phase) and avoid enabling the metrics. based on this idea I extended the existing `isClosed()` (`refCount.get() <= 0`) check to verify that the core is opened instead (`refCount.get() <= 1`).
The test provided is a best-effort, I could not capture the deadlock, but I did get some exception which may indicate some error in opening the searcher but I am not familiar enough with this code to tell for sure.
Open to feedback on both fix and test - even if to say that this approach is not good in identifying and fixing the deadlock.
Please provide a short description of the approach taken to …
> SOLR-17060 CoreContainer#create may deadlock with concurrent requests for metrics

- solr/solr-ref-guide/modules/deployment-guide/pages/docker-networking.adoc
Link is 404
Seems to have been moved without a redirect
Updated the link
I clicked the link
> Update outdated link in docker-networking.adoc

- solr/prometheus-exporter/src/java/org/apache/solr/prometheus/scraper/SolrScraper.java
A minor improvement to avoid throwing an NPE and instead more clearly log an error.
I've seen NPEs when trying to use "queryResponse" if we can't reach Solr, and I've noticed the same NPE reported elsewhere like the dev list.
> SOLR-17108: Prometheus Exporter: do not throw NullPointerException.

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/schema/IndexSchema.java
- solr/core/src/java/org/apache/solr/schema/ManagedIndexSchema.java
- solr/core/src/test/org/apache/solr/schema/ResolveAnalyzerByNameTest.java
https://issues.apache.org/jira/browse/SOLR-16203
(cherry picked from commit 8201bf81d79b638f281c3d075ba7c5e240ee9e08)
> SOLR-16203: Properly initialize schema plugins loaded by SPI name (9.4.1)

- gradle/globals.gradle
- gradle/validation/git-status.gradle
As discussed: https://lists.apache.org/thread/08bf2772cmh9pnvk667v6995qnh4m2v4
Inlined failOrWarn so I could use a dynamic default depending on isCIBuild
I tested this with setting the env var and not, and with the property both ways.
I also slightly optimized isCIBuild .
> Build: validation.git.failOnModified default to isCIBuild

- .asf.yaml
`branch_9_5` has recently been created and should be treated as 'protected'.
Branch protection is governed by `.asf.yaml` on `main`, so this PR makes the required change there.
None 😦 
> Update protected-branches to include branch_9_5

- solr/CHANGES.txt
- solr/modules/extraction/src/test/org/apache/solr/handler/extraction/ExtractingRequestHandlerTest.java
- solr/modules/hadoop-auth/src/java/org/apache/solr/security/hadoop/HadoopAuthPlugin.java
- solr/modules/hadoop-auth/src/java/org/apache/solr/security/hadoop/KerberosPlugin.java
- solr/modules/hadoop-auth/src/java/org/apache/solr/util/configuration/providers/hadoop/HadoopSSLCredentialProvider.java
- solr/modules/hadoop-auth/src/test/org/apache/solr/client/solrj/impl/Krb5HttpClientUtils.java
- solr/modules/hadoop-auth/src/test/org/apache/solr/security/hadoop/HadoopTestUtil.java
- solr/modules/hadoop-auth/src/test/org/apache/solr/security/hadoop/ImpersonationUtil.java
- solr/modules/hadoop-auth/src/test/org/apache/solr/security/hadoop/KerberosTestServices.java
- solr/modules/hadoop-auth/src/test/org/apache/solr/security/hadoop/TestImpersonationWithHadoopAuth.java
- solr/modules/hadoop-auth/src/test/org/apache/solr/security/hadoop/TestSolrCloudWithSecureImpersonation.java
- solr/modules/hadoop-auth/src/test/org/apache/solr/util/configuration/HadoopSSLConfigurationsTest.java
- solr/modules/hdfs/src/java/org/apache/solr/hdfs/HdfsDirectoryFactory.java
- solr/modules/hdfs/src/java/org/apache/solr/hdfs/index/CheckHdfsIndex.java
- solr/modules/hdfs/src/test/org/apache/hadoop/fs/RawLocalFileSystem.java
- solr/modules/hdfs/src/test/org/apache/hadoop/util/PlatformName.java
- solr/modules/hdfs/src/test/org/apache/solr/hdfs/HdfsDirectoryFactoryTest.java
- solr/modules/hdfs/src/test/org/apache/solr/hdfs/cloud/HdfsTestUtil.java
- solr/modules/jwt-auth/src/java/org/apache/solr/security/jwt/JWTIssuerConfig.java
- solr/modules/jwt-auth/src/test/org/apache/solr/security/jwt/JWTAuthPluginTest.java
- solr/modules/ltr/src/java/org/apache/solr/ltr/interleaving/algorithms/TeamDraftInterleaving.java
- solr/modules/opentelemetry/src/java/org/apache/solr/opentelemetry/OtelTracerConfigurator.java
- solr/modules/opentelemetry/src/test/org/apache/solr/opentelemetry/OtelTracerConfiguratorTest.java
- solr/modules/s3-repository/src/java/org/apache/solr/s3/S3BackupRepositoryConfig.java
https://issues.apache.org/jira/browse/SOLR-17126
This is a backport of #2193. Some differences in modules like OpenTelemetry caused some manual steps.
*edit* Gave it a new JIRA issue number, targeting 9.6
> SOLR-17126 Cut over System.getProperty() to EnvUtils for modules (backport-9x)

- .github/workflows/tests-via-crave.yml
With the recent change to the cloning mechanism in Crave, the sources are cloned in a slightly different location: Instead of it being inside a solr subdirectory, it will be in the parent.
Fix the GHA yaml to account for this.
The solr subdirectory is no longer required in the scripts. Remove it
This GHA should only be merged after the Solr GHA runners are restarted post upgrade to latest Crave version
> Update the GHA script to account for the new clone location

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/core/SolrCore.java
- solr/solrj/src/java/org/apache/solr/common/util/ExecutorUtil.java
https://issues.apache.org/jira/browse/SOLR-17144
Each core in Solr spawns a thread when the core is opened. If we have thousands of unused cores, it means we have thousands of waiting threads, wasting some resources (fd, memory).
Instead of keeping this thread always active, span it on-demand with a TTL of 60 seconds.
No new tests added for this. Just checked basic non-regression.
> SOLR-17144: Do not keep an active thread per core

- solr/solr-ref-guide/modules/indexing-guide/pages/date-formatting-math.adoc
- solr/solr-ref-guide/modules/indexing-guide/pages/documents-screen.adoc
- solr/solr-ref-guide/modules/indexing-guide/pages/field-types-included-with-solr.adoc
- solr/solr-ref-guide/modules/indexing-guide/pages/indexing-nested-documents.adoc
- solr/solr-ref-guide/modules/indexing-guide/pages/indexing-with-cbor.adoc
- solr/solr-ref-guide/modules/indexing-guide/pages/partial-document-updates.adoc
Fixed a couple of typos in the Ref Guide.
> Fix a few typos in the Indexing Guide

- solr/bin/solr
- solr/packaging/test/test_modules.bats
https://issues.apache.org/jira/browse/SOLR-15960
`compgen -e` only provides names of exported env vars. Since we are trying to explicitly export all Solr related env vars, we need to find all the unexported env vars too. 
`compgen -v` provides all vars, unexported or exported.
I changed a modules test to use a `SOLR_INCLUDE` file instead of exporting an env var. This fails without the bin/solr change.
> SOLR-15960: Find unexported variables with compgen

- solr/CHANGES.txt
- solr/webapp/web/js/angular/controllers/cloud.js
https://issues.apache.org/jira/browse/SOLR-17152
> SOLR-17152: Better alignment of Admin UI graph

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/search/CacheConfig.java
- solr/core/src/test/org/apache/solr/core/CacheConfigTest.java
- solr/core/src/test/org/apache/solr/core/TestSolrConfigHandler.java
https://issues.apache.org/jira/browse/SOLR-17148
Config API is not able to enable or disable the cache. 
Please refer to the ticket https://issues.apache.org/jira/browse/SOLR-17148
Five test cases added
1. Cache enabled in SolrConfig.XML returns valid CacheConfig
2. Cache disable in SolrConfigXML returns null CacheConfig
3. Cache enabled in SolrConfig but disable in ConfigOverlay returns null CacheConfig
4. Cache disabled in SolrConfig but enabled in ConfigOverlay returns Valid CacheConfig.
> SOLR-17148: Fixing Config API overlay property enabling or disabling cache

- solr/core/src/java/org/apache/solr/search/SolrIndexSearcher.java
@chatman included a few as part of #2248 and looking further there's a few more, so separating them out here. No JIRA ticket or CHANGES.txt entry needed I think.
> NO JIRA: remove duplicate '(cmd.getFlags() & GET_SCORES) != 0' calls

- gradle/ge.gradle
Add more Gradle Enterprise build metadata.
(replacing previous #2256 )
> Build: ge.gradle add tags & projectId=solr

- solr/solrj/src/java/org/apache/solr/client/solrj/request/UpdateRequest.java
The `ReqSupplier` interface isn't actually needed, we only have one implementation, and it lends some more indirection for the reader to wade through.
This is not end user facing so no JIRA needed.
Remove it.
There are no `ReqSupplier` specific tests, so removing it and relying on existing tests to confirm it works!
> ReqSupplier interface not actually needed, so simplify code

- dev-tools/scripts/cloud.sh
https://issues.apache.org/jira/browse/SOLR-17166
> SOLR-17166 cloud.sh can't put solr.xml in zk anymore

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/component/QueryComponent.java
- solr/core/src/java/org/apache/solr/handler/component/ResponseBuilder.java
- solr/core/src/java/org/apache/solr/search/QueryCommand.java
- solr/core/src/java/org/apache/solr/search/QueryResultKey.java
- solr/core/src/java/org/apache/solr/search/SolrIndexSearcher.java
- solr/core/src/test/org/apache/solr/cli/PostToolTest.java
- solr/core/src/test/org/apache/solr/core/QueryResultKeyTest.java
- solr/core/src/test/org/apache/solr/search/stats/TestDistribIDF.java
- solr/solr-ref-guide/modules/deployment-guide/pages/solrcloud-distributed-requests.adoc
- solr/solrj/src/java/org/apache/solr/common/params/CommonParams.java
…ry time (#2046)
* add param to disable distrib stats at query time
---------
> SOLR-17058: 9x backport 

- solr/solr-ref-guide/modules/deployment-guide/pages/docker-faq.adoc
Spinoff from #1114 which will clean up One sub chapter, while this cleans up the rest of the file.
> Clean up docker-faq.adoc

- README.md
I have added in README.md a section "Developer Documentation" with a few useful hits to build solr and run it locally. 
Modified README.md, as discussed in solr mailing list in thread "Run solr in cloud mode and debug from intellij" with @cpoerschke and @mkhludnev.
> added a few useful hits to build solr and run it locally

- .github/workflows/gradle-precommit.yml
To make it clearer what the same command for running locally is.
> clarify .github/workflows display name: gradle precommit--->check w/ Java 11

- solr/core/src/test/org/apache/solr/request/macro/TestMacroExpander.java
- solr/solr-ref-guide/modules/indexing-guide/pages/date-formatting-math.adoc
- solr/solr-ref-guide/modules/query-guide/pages/learning-to-rank.adoc
- solr/solr-ref-guide/modules/query-guide/pages/streaming-expressions.adoc
As discussed with @epugh in https://github.com/apache/solr/pull/2245#discussion_r1479109367, I'm opening a PR to add the DateRangeField example from cwiki.apache.org to the Ref Guide.
The example was originally contributed to the community wiki (https://cwiki.apache.org/confluence/display/solr/DateRangeField) by Gediminas Zalys.
> Add DateRangeField example to Ref Guide

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/spelling/FileBasedSpellChecker.java
- solr/core/src/test-files/solr/collection1/conf/schema-spellchecker.xml
- solr/core/src/test/org/apache/solr/spelling/FileBasedSpellCheckerTest.java
https://issues.apache.org/jira/browse/SOLR-17197
Fix logic in FileBasedSpellChecker that uses wrong method to retrieve fieldType by its name
There are a few existing tests in FileBasedSpellCheckerTest - but those tests refer to `schema.xml` which defines the field `teststop` and fieldType by the same name `teststop` (so the bug stays hidden).
I changed the tests to refer to `schema-spellchecker.xml` instead (to avoid changes to other unrelated tests that may depend on `schema.xml`), and made sure that the `teststop` field and its type do not have exactly the same name.
> SOLR-17197: Fix getting fieldType by its name in FileBasedSpellChecker

- solr/core/src/java/org/apache/solr/handler/component/QueryComponent.java
- solr/core/src/java/org/apache/solr/handler/component/ResponseBuilder.java
- solr/core/src/java/org/apache/solr/search/QueryCommand.java
- solr/core/src/java/org/apache/solr/search/QueryResultKey.java
- solr/core/src/java/org/apache/solr/search/SolrIndexSearcher.java
- solr/core/src/test/org/apache/solr/core/QueryResultKeyTest.java
- solr/core/src/test/org/apache/solr/search/stats/TestBaseStatsCache.java
- solr/core/src/test/org/apache/solr/search/stats/TestDefaultStatsCache.java
https://issues.apache.org/jira/browse/SOLR-17173
also invert properties
> fail distrib.statsCache=true when LocalStatsCache

- solr/core/src/java/org/apache/solr/handler/component/QueryComponent.java
- solr/core/src/java/org/apache/solr/handler/component/ResponseBuilder.java
- solr/core/src/java/org/apache/solr/search/QueryCommand.java
- solr/core/src/java/org/apache/solr/search/QueryResultKey.java
- solr/core/src/java/org/apache/solr/search/SolrIndexSearcher.java
- solr/core/src/test/org/apache/solr/core/QueryResultKeyTest.java
- solr/core/src/test/org/apache/solr/search/stats/TestBaseStatsCache.java
- solr/core/src/test/org/apache/solr/search/stats/TestDefaultStatsCache.java
> SOLR-17173: throw exception on attempting enable distrib IDF with LocalStatsCache (#2332)

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cluster/placement/impl/CollectionMetricsBuilder.java
- solr/core/src/test/org/apache/solr/cluster/placement/impl/CollectionMetricsBuilderTest.java
https://issues.apache.org/jira/browse/SOLR-17198
Collection Handler operations that use the Affinity placement plugin (Create Collection, Split Shard, Delete Replica) may fail if the AttributeFetcher finds that multiple replicas claim to be the leader for a shard. This scenario may occur if shard leadership changes while the AttributeFetcher is requesting metrics from each node.
For the use case it is fulfilling (fetching replica metrics like index size, query rate or update rate, the AttributeFetcher should not care if multiple replicas claim to be the leader. Each one is capable of supplying the required metric values. This PR replaces the exception with a log message, and accepts one of the replicas as shard leader, which will supply the metrics.
Added CollectionMetricsBuilderTest to …
> SOLR-17198: AttributeFetcher no longer fails when it observes multiple shard leaders

- solr/core/src/java/org/apache/solr/handler/RequestHandlerBase.java
- solr/core/src/java/org/apache/solr/search/CpuAllowedLimit.java
- solr/core/src/java/org/apache/solr/util/ThreadCpuTimer.java
- solr/core/src/test/org/apache/solr/search/TestCpuAllowedLimit.java
https://issues.apache.org/jira/browse/SOLR-17203
> SOLR-17203 fix calculation for CpuAllowedLimit

- solr/solr-ref-guide/modules/deployment-guide/pages/circuit-breakers.adoc
https://issues.apache.org/jira/browse/SOLR-16982
In the original PR we changed code but did not update reference guide.
> SOLR-16982 Reference guide change for sharded request and circuit breaker

- solr/solr-ref-guide/modules/configuration-guide/pages/configuration-files.adoc
- solr/solr-ref-guide/modules/deployment-guide/pages/solr-control-script-reference.adoc
- solr/solr-ref-guide/modules/getting-started/pages/introduction.adoc
- solr/solr-ref-guide/modules/getting-started/pages/searching-in-solr.adoc
- solr/solr-ref-guide/modules/getting-started/pages/solr-tutorial.adoc
- solr/solr-ref-guide/modules/getting-started/pages/tutorial-aws.adoc
- solr/solr-ref-guide/modules/getting-started/pages/tutorial-diy.adoc
- solr/solr-ref-guide/modules/getting-started/pages/tutorial-solrcloud.adoc
Made a few updates to the tutorial docs - mostly, to the "SolrCloud on AWS EC2" tutorial.
> Update tutorial docs in the Ref Guide

- build.gradle
- gradle/globals.gradle
- gradle/ide/eclipse.gradle
- gradle/java/javac.gradle
- solr/CHANGES.txt
https://issues.apache.org/jira/browse/SOLR-17205
This PR only adds the plumbing, does not bump main
> SOLR-17205 De-couple SolrJ Java version from server Java version

- solr/solr-ref-guide/modules/upgrade-notes/pages/major-changes-in-solr-9.adoc
https://issues.apache.org/jira/browse/SOLR-17254
This section doesn't seem to have been maintained by feature authors very well (myself included), so I've added most of the items from the release announcement. @epugh and I chatted and he agreed that the post tool note however is too small for this list. 
Feedback/suggestions very welcome. I left in the references to the Jira issues, but that's different from prior releases, so I wonder how people feel about it. Personally when I have read this section for prior releases I would always have been interested to have an easy way to find more info these sorts of things. It is a departure from prior style, though, so I could be talked into either removing them or enhancing them with hyperlinks...
> SOLR-17254 - Major Changes in 9.6

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cli/AuthTool.java
- solr/core/src/java/org/apache/solr/cli/ConfigSetDownloadTool.java
- solr/core/src/java/org/apache/solr/cli/ConfigSetUploadTool.java
- solr/core/src/java/org/apache/solr/cli/DeleteTool.java
- solr/core/src/java/org/apache/solr/cli/HealthcheckTool.java
- solr/core/src/java/org/apache/solr/cli/SolrCLI.java
- solr/core/src/java/org/apache/solr/cli/ZkCpTool.java
- solr/core/src/java/org/apache/solr/cli/ZkLsTool.java
- solr/core/src/java/org/apache/solr/cli/ZkMkrootTool.java
- solr/core/src/java/org/apache/solr/cli/ZkMvTool.java
- solr/core/src/java/org/apache/solr/cli/ZkRmTool.java
- solr/core/src/test/org/apache/solr/cloud/SolrCLIZkUtilsTest.java
- solr/packaging/test/test_zk.bats
https://issues.apache.org/jira/browse/SOLR-17248
I've broken the build on 9x while backporting, and this is to fix it.  I am opening a PR targeting `branch_9x` to make sure everything passes the tests before merging.
> Backporting SOLR-17248 to branch_9x

- solr/core/src/test/org/apache/solr/util/TimeZoneUtilsTest.java
Fixing the build by a bug introduced in https://issues.apache.org/jira/browse/SOLR-17278.
> fix errorprone build error by grouping operators together

- dev-docs/releasing.adoc
https://issues.apache.org/jira/browse/SOLR-17244
> SOLR-17244 - initial cut at an orientation for prospective release managers

- solr/core/src/java/org/apache/solr/core/CachingDirectoryFactory.java
https://issues.apache.org/jira/browse/SOLR-17323
> SOLR-17323: Fix potential ConcurrentModificationException on CachingDirectoryFactory.close()

- solr/solr-ref-guide/modules/deployment-guide/pages/enabling-ssl.adoc
- solr/solr-ref-guide/modules/getting-started/pages/tutorial-films.adoc
- solr/solr-ref-guide/modules/getting-started/pages/tutorial-techproducts.adoc
https://issues.apache.org/jira/browse/SOLR-17332
This is focused on updating the Ref Guide, and will go to both `main` and `branch_9x`.
> SOLR-17332: Removing lingering references to post.jar from ref guide

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cluster/placement/plugins/OrderedNodePlacementPlugin.java
- solr/core/src/test/org/apache/solr/cloud/MigrateReplicasTest.java
- solr/core/src/test/org/apache/solr/cluster/placement/plugins/SimplePlacementFactoryTest.java
https://issues.apache.org/jira/browse/SOLR-17331
I've also added and re-arranged tests as-per the Jira comments.
> SOLR-17331: More optimal placements with OrderedNodePlacementPlugin

- solr/example/films/README.md
- solr/example/films/vectors/create_model.py
- solr/example/films/vectors/films.py
- solr/solr-ref-guide/modules/getting-started/pages/tutorial-vectors.adoc
minor #1988 follow-up and optional support for dimensions other than 10
> example/films: README.md and vectors tweaks

- solr/CHANGES.txt
https://issues.apache.org/jira/browse/SOLR-15582
> SOLR-15582: remove changelog, this is just a small refactoring that was in the related PR.

- solr/core/src/test/org/apache/solr/update/CustomTLogDirTest.java
> Fix failing test for SOLR-16962; update log must be enabled

- .github/workflows/docker-test.yml
* https://github.com/actions/checkout/releases
* https://github.com/actions/setup-java/releases
* https://github.com/actions/cache/releases
> docker-test.yml: Upgrade GitHub Actions

- solr/solr-ref-guide/modules/deployment-guide/pages/collection-management.adoc
Based on https://github.com/apache/solr/blob/main/solr/core/src/java/org/apache/solr/cloud/api/collections/BackupCmd.java#L201  and 
https://github.com/apache/solr/blob/main/solr/core/src/java/org/apache/solr/cloud/api/collections/BackupCmd.java#L209
and testing incremental backups using different backup names
the previous description of backupName is not correct. Backup name should be the same if using incremental backups
Update description of backupName 
> [ref guide] Fix description of field backupName for backup

- .github/workflows/bin-solr-test.yml
Spinoff from https://github.com/apache/solr/pull/2573#pullrequestreview-2188208038
> Run bats tests for all cli code changes

- solr/solrj-zookeeper/src/java/org/apache/solr/common/cloud/CollectionPropertiesZkStateReader.java
- solr/solrj-zookeeper/src/java/org/apache/solr/common/cloud/ZkStateReader.java
**Summary**
This PR introduces `CollectionPropertiesZkStateReader` to manage collection property methods, shifting these responsibilities from ZkStateReader.
**Purpose**
`ZkStateReader` is currently overloaded with tasks, including refreshing and maintaining state for live nodes, collections, cluster state, collection properties, replica properties, aliases, and more. By distributing these responsibilities into specialized classes, we can ensure that each class has a single, well-defined responsibility, thereby reducing complexity.
This PR aims to transfer collection property management to `CollectionPropertiesZkStateReader`.
- Separation of Concerns: Enhances modularity by isolating logic specific to collection properties.
- Improved Maintainability: Simplifies `ZkStateReader`, making …
> Delegate Collection Property Management to CollectionPropertiesZkStateReader

- solr/core/src/test/org/apache/solr/response/TestPrometheusResponseWriter.java
https://issues.apache.org/jira/browse/SOLR-17368
`TestPrometheusResponseWriter` was failing ~25% of tests due to dummy metric `dummyMetrics.2xx-responses` not unique enough for exporting compared to `org.eclipse.jetty.server.handler.DefaultHandler.2xx-responses` which could leak between tests creating a duplicate metric.
Change the dummy jetty metric with `999xx` that exports a unique enough label that `2xx` cannot clash with it, even with real leaking jetty metrics.
> [SOLR-17368] Change prometheus dummy metric to a more unique label

- solr/core/src/java/org/apache/solr/response/PrometheusResponseWriter.java
https://issues.apache.org/jira/browse/SOLR-10654
The Prometheus Response Writer response content type was JSON which is incorrect.
Based on [Prometheus](https://github.com/prometheus/docs/blob/main/content/docs/instrumenting/exposition_formats.md) docs, override content-type to `text/plain; version=0.0.4`
> SOLR-10654: Override PrometheusResponseWriter Content Type

- solr/CHANGES.txt
- solr/solrj-zookeeper/src/java/org/apache/solr/common/cloud/CollectionPropertiesZkStateReader.java
https://issues.apache.org/jira/browse/SOLR-17396
Building on <https://github.com/apache/solr/pull/2585|PR> which delegated Collection Properties Management to `CollectionPropertiesZkStateReader`, this PR seeks to minimize thread contention within `CollectionPropertiesZkStateReader`.
- Use collection level locking where relevant instead of synchronizing on "watchedCollectionProperties"
- With the double checked locking implemented in CollectionPropertiesZkStateReader, the scope of the synchronized (this) will be reduced to collection property operations, and no longer be in contention with the synchronization of unrelated operations on ZkStateReader.
Please describe the tests you've developed or run to …
> SOLR-17396: Reduce thread contention in ZkStateReader.getCollectionProperties()

- README.md
Inspired by @stefanvodita's https://github.com/apache/lucene/pull/13476 change.
> add build badges to README.md

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/admin/ClusterStatus.java
- solr/core/src/java/org/apache/solr/handler/admin/CollectionsHandler.java
- solr/solr-ref-guide/modules/deployment-guide/pages/cluster-node-management.adoc
- solr/solrj-zookeeper/src/java/org/apache/solr/common/cloud/ZkStateReader.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/BaseHttpClusterStateProvider.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/ClusterStateProvider.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/CloudHttp2SolrClientTest.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/HttpClusterStateSSLTest.java
https://issues.apache.org/jira/browse/SOLR-17381
Modify the requests to retrieve only the necessary information, such as the cluster status for a specific collection, live nodes, or cluster properties. Ensure these changes maintain backward compatibility. Additionally, update the HTTP CSP to reflect these optimizations.
Introduce additional params to fetch CLUSTERSTATUS. Also added a INCLUDE_ALL param which would return all info by default to maintain backwards compatibility.
Additionally, made changes in BaseHttpClusterStateProvider to request minimal info for every use case.
Please describe the tests you've developed …
> SOLR-17381: Make CLUSTERSTATUS configurable

- solr/solrj/src/java/org/apache/solr/client/solrj/impl/BaseHttpClusterStateProvider.java
The cache timeout to refresh aliases and live nodes in Http ClusterStateProvider is currently hardcoded to 5 seconds. This is pretty frequent.
Introducing an override to set the timeout  via EnvUtils that is backwards compatible
Ensured existing tests pass
> Use EnvUtils to override cache timeout in HTTP ClusterStateProvider

- gradle/documentation/render-javadoc.gradle
> SOLR-17223 Remove hardcoded java version in renderJavadoc task

- .github/workflows/bin-solr-test.yml
- .github/workflows/docker-test.yml
- .github/workflows/gradle-precommit.yml
- .github/workflows/solrj-test.yml
- gradle/develocity.gradle
- settings.gradle
This change migrates Solr to use the Develocity Gradle Plugin. The existing Gradle Enterprise Gradle Plugin will no longer be supported when ge.apache.org is updated to 2024.3.
These changes will not functionally change how build scans are published to ge.apache.org.
This change also introduces the [setup-gradle](https://github.com/gradle/actions/tree/main/setup-gradle) action to GitHub Actions workflows to support Develocity functionality. In particular, this will allow the usage of short-lived access tokens to publish build scans as well as build scan links to ge.apache.org in GitHub Actions workflows. Optionally, the action can post job summaries as [pull request comments](https://github.com/gradle/actions/blob/main/docs/setup-gradle.md#adding-job-summary-as-a-pull-request-comment), …
> Migrate from Gradle Enterprise Gradle Plugin to Develocity Gradle Plugin

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cloud/Overseer.java
https://issues.apache.org/jira/browse/SOLR-17421
Overseer might be stop after a failure of the `QUIT` operation if we don't give up on leadership (see Jira).
At least, this happens if we get a timeout error when closing the thread pool for cluster state updater (there might be other scenarios).
Catch the exception to make sure we don't stop with a half finished `QUIT` command.
Unfortunately, I can't easily reproduce with a test.
> SOLR-17421: Make sure overseer drops leadership after QUIT failure

- solr/solr-ref-guide/modules/deployment-guide/pages/solr-in-docker.adoc
Ref guide fix, not planning JIRA.
> Don't reference the old post.sh script in docs, use the bin/solr post command.

- solr/bin/solr.cmd
https://issues.apache.org/jira/browse/SOLR-17423
Follow to original PR that fixes for windows.
> SOLR-17423: use long form, -h now means --help, not --host in solr.cmd

- solr/core/src/java/org/apache/solr/cli/ApiTool.java
- solr/core/src/java/org/apache/solr/cli/PostTool.java
- solr/core/src/java/org/apache/solr/cli/SolrCLI.java
- solr/core/src/test/org/apache/solr/cli/ApiToolTest.java
- solr/core/src/test/org/apache/solr/cli/PostToolTest.java
https://issues.apache.org/jira/browse/SOLR-17427
> SOLR-17427: Fix url building in cli

- solr/core/src/java/org/apache/solr/core/SolrCore.java
> Comment: SolrCore.getRealtimeSearcher

- solr/core/src/test/org/apache/solr/cli/PostToolTest.java
https://issues.apache.org/jira/browse/SOLR-11640
Originally this was to make sure we obey the fileTypes setting!  However, this has been resolved at some point.  So this is now some formatting fixes.
This is some lint cleanups.   No jira needed.
> Lint cleanups in PostToolTest

- dev-docs/FAQ.adoc
> help the next person when it comes to building the docs..

- solr/core/src/java/org/apache/solr/cli/StatusTool.java
https://issues.apache.org/jira/browse/SOLR-17457
This is a big one!   I committed to branch_9_7, and then branch_9x, and wanted to get this one improvement into main.
> SOLR-17457: Scavange one change from the SOLR-17457 bug fix for main

- dev-tools/scripts/releaseWizard.yaml
Not tested but I think it should do the trick.
> SOLR-17249 Edit .asf.yaml on main branch

- solr/core/src/java/org/apache/solr/core/CoreContainer.java
- solr/core/src/java/org/apache/solr/core/HttpSolrClientProvider.java
- solr/core/src/java/org/apache/solr/update/UpdateShardHandler.java
- solr/core/src/java/org/apache/solr/util/stats/InstrumentedHttpListenerFactory.java
- solr/core/src/test/org/apache/solr/core/TestHttpSolrClientProvider.java
- solr/solrj/src/java/org/apache/solr/common/util/IOUtils.java
> SOLR-16503: New home for default http2 client (#2689)

- solr/solr-ref-guide/modules/deployment-guide/pages/enabling-ssl.adoc
Ref Guide update, no JIRA needed.
> Update to mention bin/solr instead of zkcli.sh in Ref Guide

- solr/bin/solr.cmd
- solr/core/src/java/org/apache/solr/cli/SolrCLI.java
- solr/core/src/java/org/apache/solr/cli/ZkCpTool.java
- solr/core/src/java/org/apache/solr/cli/ZkLsTool.java
- solr/core/src/java/org/apache/solr/cli/ZkRmTool.java
- solr/core/src/test/org/apache/solr/cli/SolrCLIZkToolsTest.java
- solr/packaging/test/test_zk.bats
- solr/solr-ref-guide/modules/deployment-guide/pages/solr-control-script-reference.adoc
- solr/solrj-zookeeper/src/java/org/apache/solr/common/cloud/ZkMaintenanceUtils.java
- solr/solrj-zookeeper/src/test/org/apache/solr/common/cloud/TestZkMaintenanceUtils.java
Deprecate --recurse
https://issues.apache.org/jira/browse/SOLR-17482
See JIRA
See JIRA
> SOLR-17482: Change long form of -r to --recursive

- solr/solr-ref-guide/modules/deployment-guide/pages/collection-management.adoc
https://lists.apache.org/thread/f9obf8jb2w5wddl6n4yny9rjjknk9tz1
Remove policy reference, outdated
> ref guide: remove policy reference

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/handler/RequestHandlerBase.java
- solr/core/src/java/org/apache/solr/handler/component/HttpShardHandler.java
- solr/core/src/java/org/apache/solr/handler/component/ParallelHttpShardHandler.java
- solr/core/src/java/org/apache/solr/handler/component/QueryComponent.java
- solr/core/src/java/org/apache/solr/handler/component/ResponseBuilder.java
- solr/core/src/java/org/apache/solr/handler/component/SearchHandler.java
- solr/core/src/java/org/apache/solr/handler/component/ShardHandler.java
- solr/core/src/java/org/apache/solr/handler/component/ShardResponse.java
- solr/core/src/java/org/apache/solr/request/SolrQueryRequest.java
- solr/core/src/java/org/apache/solr/request/SolrRequestInfo.java
- solr/core/src/java/org/apache/solr/response/SolrQueryResponse.java
- solr/core/src/java/org/apache/solr/search/QueryLimits.java
- solr/core/src/java/org/apache/solr/search/QueryResult.java
- solr/core/src/java/org/apache/solr/search/facet/FacetModule.java
- solr/core/src/java/org/apache/solr/search/grouping/CommandHandler.java
- solr/core/src/java/org/apache/solr/search/grouping/distributed/responseprocessor/SearchGroupShardResponseProcessor.java
- solr/core/src/java/org/apache/solr/search/grouping/distributed/responseprocessor/TopGroupsShardResponseProcessor.java
- solr/core/src/java/org/apache/solr/search/stats/ExactStatsCache.java
- solr/core/src/java/org/apache/solr/util/SolrResponseUtil.java
- solr/core/src/test/org/apache/solr/search/TestCpuAllowedLimit.java
- solr/solr-ref-guide/modules/query-guide/pages/common-query-parameters.adoc
- solr/solr-ref-guide/modules/upgrade-notes/pages/major-changes-in-solr-9.adoc
- solr/solrj/src/java/org/apache/solr/common/params/ShardParams.java
- solr/solrj/src/test/org/apache/solr/common/params/ShardParamsTest.java
> SOLR-17158 Terminate distributed processing faster when query limits reached and partial results are not needed (#2666)

- README.md
- solr/solr-ref-guide/modules/deployment-guide/pages/enabling-ssl.adoc
- solr/solr-ref-guide/modules/deployment-guide/pages/installing-solr.adoc
- solr/solr-ref-guide/modules/deployment-guide/pages/solr-control-script-reference.adoc
- solr/solr-ref-guide/modules/deployment-guide/pages/solr-on-hdfs.adoc
- solr/solr-ref-guide/modules/getting-started/pages/tutorial-solrcloud.adoc
- solr/solr-ref-guide/modules/getting-started/pages/tutorial-techproducts.adoc
https://issues.apache.org/jira/browse/SOLR-17467
> SOLR-17467: Update docs to reflect SolrCloud is now default mode.

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/cloud/ZkController.java
- solr/core/src/test/org/apache/solr/cloud/OverseerTest.java
- solr/core/src/test/org/apache/solr/cloud/ZkControllerTest.java
- solr/solrj-zookeeper/build.gradle
- solr/solrj-zookeeper/src/java/org/apache/solr/client/solrj/cloud/DelegatingCloudManager.java
- solr/solrj-zookeeper/src/java/org/apache/solr/client/solrj/cloud/SolrCloudManager.java
- solr/solrj-zookeeper/src/java/org/apache/solr/client/solrj/impl/SolrClientCloudManager.java
- solr/solrj-zookeeper/src/java/org/apache/solr/client/solrj/impl/SolrClientNodeStateProvider.java
- solr/solrj-zookeeper/src/test/org/apache/solr/client/solrj/impl/NodeValueFetcherTest.java
[SOLR-16503](https://issues.apache.org/jira/browse/SOLR-16503)
> [branch_9x] Backport Switched from HTTP1 to HTTP2 in SolrClientCloudManager

- dev-docs/asf-jenkins.adoc
Hopefully these docs will answer a lot of questions I had when troubleshooting a recent outage of our ASF Jenkins agents.
> Add docs detailing our ASF Jenkins usage

- solr/bin/solr
- solr/bin/solr.cmd
https://issues.apache.org/jira/browse/SOLR-17321
With the min JDK 21 requirement some code snippets in `bin/solr.cmd` and `bin/solr` can be cleaned up.
Cleanup obsolete code in `bin/solr.cmd` and `bin/solr`.
**To the reviewers**: Please review carefully the GC-related changes, as I am not sure what is supported and what not in the newer versions. I tried to remove only obsolete cases, but I am not sure how to test the configurations.
No tests modified. Some of the tests currently fail when running `./gradlew check` (currently inspecting).
> SOLR-17321: Cleanup JDK version related logic in scripts

- dev-tools/scripts/releaseWizard.yaml
* Fix release wizard to stop attempting to remove old artifacts from the Lucene space
> Fix release wizard to remove from Solr space before attempting Lucene space

- crave.yaml
Remove crave.yaml
https://github.com/apache/solr/pull/2498#pullrequestreview-2400349037
> Remove crave.yaml

- solr/solr-ref-guide/modules/upgrade-notes/pages/major-changes-in-solr-10.adoc
https://issues.apache.org/jira/browse/SOLR-17524
We need to let folks know the CLI has changed, but I don't want to do an exhaustive list..   especially because we have bin/solr tool --help command to remind folks.  
I did call out a few big changes that folks might see to illustrate the changes.
Some ref guide docs.  This get's committed to `main` only.
> SOLR-17524: Call out a few changes in 10.

- solr/solr-ref-guide/modules/deployment-guide/pages/jwt-authentication-plugin.adoc
This PR fixes the claim name mismatch for the config example in the JWT Authentication Plugin docs.
```
"claimsMatch": { "foo" : "A|B", "dept" : "IT" }, <4>
```
```
<4> Require that the `roles` claim is one of "A" or "B" and that the `dept` claim is "IT"
```
The claim in the example is `foo`, not `roles`.
N/A
> Fix claim name in JWT Authentication Plugin docs

- solr/core/src/java/org/apache/solr/handler/ReplicationHandler.java
https://issues.apache.org/jira/browse/SOLR-17579
A trailing fix after the original merge!
> Reformat comment better

- solr/CHANGES.txt
File to Path work only going into 10x. Moved it under CHANGES.txt.
> SOLR-17548: Move to under 10x under CHANGES.txt

- solr/solrj/src/java/org/apache/solr/common/util/JavaBinCodec.java
- solr/solrj/src/test/org/apache/solr/common/util/TestJavaBinCodec.java
> SOLR-17588 : javabin must support primitive arrays

- solr/core/src/java/org/apache/solr/handler/designer/DefaultSampleDocumentsLoader.java
- solr/core/src/java/org/apache/solr/handler/designer/DefaultSchemaSuggester.java
- solr/core/src/java/org/apache/solr/handler/designer/SampleDocuments.java
- solr/core/src/java/org/apache/solr/handler/designer/SchemaDesignerAPI.java
- solr/core/src/java/org/apache/solr/handler/designer/SchemaDesignerConfigSetHelper.java
- solr/core/src/test/org/apache/solr/handler/designer/TestSchemaDesignerAPI.java
- solr/core/src/test/org/apache/solr/handler/designer/TestSchemaDesignerConfigSetHelper.java
> IDE suggested cleanups

- solr/CHANGES.txt
Unfortunately this also made it into the 9.8.0 release :(
> Remove unused 9.7.1 section in CHANGES.txt

- solr/webapp/build.gradle
These exclusions don't match anything.
> build solr/webapp/build.gradle: remove needless excludes

- solr/core/src/java/org/apache/solr/cli/SolrCLI.java
https://issues.apache.org/jira/browse/SOLR-17668
Add the cluster command to tool help output, and rearrange lines a bit to format nicer.
> SOLR-17668: Add in cluster command to tool help.

- solr/CHANGES.txt
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/BaseHttpClusterStateProvider.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/Http2ClusterStateProvider.java
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/HttpClusterStateProvider.java
- solr/solrj/src/test/org/apache/solr/client/solrj/impl/CloudHttp2SolrClientTest.java
i.e. stop eagerly connecting when CloudSolrClient is created.
https://issues.apache.org/jira/browse/SOLR-17607
> SOLR-17607: Http ClusterStateProvider, lazy connect

- solr/CHANGES.txt
https://issues.apache.org/jira/browse/SOLR-17685
Change to 10x
Backporting looked tough, and I don't want to inject new bugs into 9x...
> SOLR-17685: Change fix version to 10x

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/client/solrj/embedded/EmbeddedSolrServer.java
- solr/core/src/java/org/apache/solr/core/SolrCore.java
- solr/core/src/java/org/apache/solr/handler/admin/SolrInfoMBeanHandler.java
- solr/core/src/java/org/apache/solr/handler/export/ExportWriter.java
- solr/core/src/java/org/apache/solr/jersey/MessageBodyWriters.java
- solr/core/src/java/org/apache/solr/response/DocsStreamer.java
- solr/core/src/java/org/apache/solr/response/JavaBinResponseWriter.java
- solr/core/src/java/org/apache/solr/response/QueryResponseWriter.java
- solr/core/src/test/org/apache/solr/TestGroupingSearch.java
- solr/core/src/test/org/apache/solr/TestTolerantSearch.java
- solr/core/src/test/org/apache/solr/response/TestJavaBinResponseWriter.java
https://issues.apache.org/jira/browse/SOLR-17682
2nd PR for this JIRA; I wanted to do this separately.
> SOLR-17682: Rename BinaryResponseWriter to JavaBinResponseWriter

- solr/CHANGES.txt
- solr/core/src/java/org/apache/solr/parser/SolrQueryParserBase.java
- solr/core/src/java/org/apache/solr/search/FuzzyQParserPlugin.java
- solr/core/src/java/org/apache/solr/search/QParserPlugin.java
- solr/core/src/test/org/apache/solr/search/QueryEqualityTest.java
- solr/solr-ref-guide/modules/query-guide/pages/other-parsers.adoc
- solr/solr-ref-guide/modules/query-guide/pages/standard-query-parser.adoc
https://issues.apache.org/jira/browse/SOLR-17714
Still need to add some tests
> SOLR-17714: Add a FuzzyQParser for all FuzzyQuery customizations

- solr/CHANGES.txt
- solr/solr-ref-guide/modules/deployment-guide/pages/solrj.adoc
- solr/solr-ref-guide/modules/upgrade-notes/pages/major-changes-in-solr-10.adoc
- solr/solrj/src/java/org/apache/solr/client/solrj/impl/CloudSolrClient.java
https://issues.apache.org/jira/browse/SOLR-14070
This PR will target to deprecate the CloudSolrClient's ZKHost constructor.
This involves marking constructor `public Builder(List<String> zkHosts, Optional<String> zkChroot)` deprecated.
> SOLR-14070 : Deprecate CloudSolrClient's ZKHost constructor

- solr/core/src/test-files/solr/collection1/conf/schema.xml
- solr/core/src/test/org/apache/solr/schema/CurrencyFieldTypeTest.java
- solr/core/src/test/org/apache/solr/search/CurrencyRangeFacetCloudTest.java
- solr/test-framework/src/test-files/solr/collection1/conf/schema.xml
https://issues.apache.org/jira/browse/SOLR-17683
Found and fixed a reproducible seed that was failing in nightly.
> SOLR-17683: Update test to reflect only one type of Currency Field in Solr.

- solr/solr-ref-guide/modules/deployment-guide/pages/basic-authentication-plugin.adoc
https://issues.apache.org/jira/browse/SOLR-17724
10x only
> SOLR-17724: clarify basic auth credential docs

- solr/CHANGES.txt
- solr/packaging/test/bats_helper.bash
- solr/packaging/test/test_prometheus.bats
- solr/prometheus-exporter/src/java/org/apache/solr/prometheus/exporter/SolrExporter.java
(cherry picked from commit 75289fa19237acafb34916548def8677b964d172)
https://issues.apache.org/jira/browse/SOLR-17638
> SOLR-17638 backport to branch_9x

- solr/solr-ref-guide/build.gradle
- solr/solr-ref-guide/ui-src/partials/head-icons.hbs
- solr/solr-ref-guide/ui-src/partials/head-scripts.hbs
https://issues.apache.org/jira/browse/SOLR-17633
Adds matomo tracking to ref guide.
> SOLR-17633 Add matomo script to ref-guide

- solr/solr-ref-guide/modules/query-guide/pages/other-parsers.adoc
* https://github.com/apache/solr/blob/main/solr/solr-ref-guide/modules/query-guide/pages/other-parsers.adoc#payload-score-parser
* https://github.com/apache/solr/blob/main/solr/solr-ref-guide/modules/query-guide/pages/other-parsers.adoc#payload-check-parser
> Solr Ref Guide: fix bullet point format for Payload (Check,Score) Parser

- solr/core/src/test/org/apache/solr/schema/TestUseDocValuesAsStored.java
- solr/test-framework/src/java/org/apache/solr/SolrTestCaseJ4.java
https://issues.apache.org/jira/browse/SOLR-17698
Fixes test broken by https://github.com/apache/solr/pull/3256
> SOLR-17698: Fix TestUseDocValuesAsStored for enums

- solr/core/src/java/org/apache/solr/response/transform/ValueSourceAugmenter.java
https://issues.apache.org/jira/browse/SOLR-17775
additional minor optimization
@yurkor
> SOLR-17775: avoid over-calling ReaderUtil.subIndex

- solr/ui/src/commonMain/kotlin/org/apache/solr/ui/views/navigation/Footer.kt
https://issues.apache.org/jira/browse/SOLR-14414
Andrey challenged the table to "can you vibe code some kotlin" so I tried it.   Yeah, thanks to Zed, we got clicakable links.
Would love some review!
> SOLR-14414: adding clickable links to footer

- solr/cross-dc-manager/src/java/org/apache/solr/crossdc/manager/consumer/KafkaCrossDcConsumer.java
- solr/cross-dc-manager/src/java/org/apache/solr/crossdc/manager/messageprocessor/SolrMessageProcessor.java
- solr/cross-dc-manager/src/test/org/apache/solr/crossdc/manager/DeleteByQueryToIdTest.java
- solr/cross-dc-manager/src/test/org/apache/solr/crossdc/manager/SimpleSolrIntegrationTest.java
- solr/cross-dc-manager/src/test/org/apache/solr/crossdc/manager/consumer/KafkaCrossDcConsumerTest.java
- solr/cross-dc-manager/src/test/org/apache/solr/crossdc/manager/messageprocessor/SolrMessageProcessorTest.java
- solr/cross-dc-manager/src/test/org/apache/solr/crossdc/manager/messageprocessor/TestMessageProcessor.java
https://issues.apache.org/jira/browse/SOLR-17804. Cherry-pick from PR 3411.
> SOLR-17804: re-create SolrClient if closed (cherry-pick to 9x)

- solr/cross-dc-manager/src/java/org/apache/solr/crossdc/manager/consumer/KafkaCrossDcConsumer.java
- solr/cross-dc-manager/src/java/org/apache/solr/crossdc/manager/messageprocessor/SolrMessageProcessor.java
- solr/cross-dc-manager/src/test/org/apache/solr/crossdc/manager/DeleteByQueryToIdTest.java
- solr/cross-dc-manager/src/test/org/apache/solr/crossdc/manager/SimpleSolrIntegrationTest.java
- solr/cross-dc-manager/src/test/org/apache/solr/crossdc/manager/consumer/KafkaCrossDcConsumerTest.java
- solr/cross-dc-manager/src/test/org/apache/solr/crossdc/manager/messageprocessor/SolrMessageProcessorTest.java
- solr/cross-dc-manager/src/test/org/apache/solr/crossdc/manager/messageprocessor/TestMessageProcessor.java
https://issues.apache.org/jira/browse/SOLR-17804. Cherry-pick from PR-3411
> SOLR-17804: re-create SolrClient if closed (cherry-pick to 9.9)

- gradle/develocity.gradle
Adding debug statements and checking if token still valid.
>  Develocity Access check

- solr/core/src/test/org/apache/solr/handler/TestSnapshotCoreBackup.java
- solr/core/src/test/org/apache/solr/handler/TestStressThreadBackup.java
#3053 follow-up as per https://github.com/apache/solr/pull/3053#discussion_r2288536568
https://issues.apache.org/jira/browse/SOLR-17631
> SOLR-17631: fix TestStressThreadBackup w.r.t. CheckIndex.Level

- solr/core/src/java/org/apache/solr/servlet/HttpSolrCall.java
- solr/core/src/test/org/apache/solr/cloud/FullSolrCloudDistribCmdsTest.java
- solr/core/src/test/org/apache/solr/update/processor/RoutedAliasUpdateProcessorTest.java
- solr/solrj/src/java/org/apache/solr/common/cloud/DocCollection.java
https://issues.apache.org/jira/browse/SOLR-17560
This PR simplifies the DocCollection class by removing the getLeaderReplicas(nodeName) method. This specialized method is redundant, as its functionality can be achieved by combining other existing, more generic methods.
The code that uses the getLeaderReplicas method was updated in both the application and its tests. The method was then removed from the DocCollection class.
The changes were verified by running all relevant tests. This included the full test suite and targeted tests for the affected code paths. All tests passed successfully.
> SOLR-17560: Remove redundant getLeaderReplicas method

- solr/bin/solr
- solr/bin/solr.cmd
- solr/core/src/java/org/apache/solr/cloud/api/collections/CreateCollectionCmd.java
- solr/core/src/java/org/apache/solr/core/ConfigSetService.java
- solr/packaging/test/test_start_solr.bats
- solr/solrj-zookeeper/src/test/org/apache/solr/common/cloud/TestZkConfigSetService.java
- solr/solrj/src/resources/DeprecatedSystemPropertyMappings.properties
SOLR-17875: Rationalize bootstrap_conf, bootstrap_confdir, and -Dcollection.configName in start up scripts (#3512)"
This reverts commit c3ed5a80
> Revert SOLR-17875 #3512

- dev-tools/scripts/cloud.sh
Just a couple updates to track the most current bin/solr command line options.
> Fix a tiny bitrot in cloud.sh with command script params

- solr/modules/extraction/src/java/org/apache/solr/handler/extraction/ExtractingDocumentLoader.java
- solr/modules/extraction/src/java/org/apache/solr/handler/extraction/ExtractingRequestHandler.java
https://issues.apache.org/jira/browse/SOLR-13973
Introduce deprecation warning so we have freedom to change things up in Solr 10.
Add Deprecation tags.
I have a separate PR to add to the major changes in solr 10 ref guide page a mention of this.
> SOLR-13973: Deprecate existing Tika integration to open door to new ways

- .github/workflows/tests-via-crave.yml
There are two things addressed in this PR:
1. Add the pull request information into the crave command as a "message" - so that it is available in the dashboard. This should make it simple to understand what pull request is this action for
2. Make explicit - the command being run as part of the action. Functionally this has no impact other than to allow the Solr community see what the test command is AND in the future change it themselves as needed.
1. Use the `--message` flag to add the PR number
2. Add the test command to the `crave run` invocation
Not applicable
> Add the PR info and make the test command explicit, and not dependent on default commands from Crave
